[WIP] Adds support for BigFloat
dgraph-io/dgraph pull request #3981
Opened 2019-09-13 12:32 UTC by harshil-goel

This PR adds BigFloat as another scalar type in schema. 
For now, it supports storing and retrieving 200 precision float, which isn't possible with just a float64.

Work Remaining:
- [ ] Precision is hardcoded to 200
- [ ] No support for aggregate functions

2021-01-13 05:49 UTC, pawanrawal commented
This change would have to be reworked as the master has significantly diverged.

2023-02-09 11:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dgraph-io/dgraph?pullRequest=3981) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/dgraph-io/dgraph?pullRequest=3981) before we can accept your contribution.<br/>**8** out of **9** committers have signed the CLA.<br/><br/>:white_check_mark: mangalaman93<br/>:white_check_mark: anurags92<br/>:white_check_mark: skrdgraph<br/>:white_check_mark: MichelDiz<br/>:white_check_mark: harshil-goel<br/>:white_check_mark: shivaji-dgraph<br/>:white_check_mark: joshua-goldstein<br/>:white_check_mark: rderbier<br/>:x: shivaji-kumowiz<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dgraph-io/dgraph?pullRequest=3981) it.</sub>

2023-02-09 11:32 UTC, mangalaman93 requested changes

2023-02-09 11:32 UTC, mangalaman93 commented on query/aggregator.go
>  	"bytes"
I think we should return explicit errors when an operation is not supported

2023-02-09 11:32 UTC, mangalaman93 commented on query/aggregator.go
> +		f, _ := value.Float64()
this doesn't seem like a good idea.

2024-08-19 14:57 UTC, mangalaman93 requested changes
Looks pretty good to me, just one comment.!

2024-08-19 14:57 UTC, mangalaman93 commented on types/conversion.go
> +		{
why is this in a block?

2024-08-20 10:24 UTC, mangalaman93 approved these changes

2024-08-20 10:24 UTC, merged