fix(GraphQL): This PR adds out of range check for Int type.
dgraph-io/dgraph pull request #6275
Opened 2020-08-26 10:14 UTC by JatinDevDG

This PR adds out of range Input validation check for Int type.
If the integer input value represents a value less than -2^31 or greater than or equal to 2^31, validation error is raised.

2020-08-26 10:40 UTC, pawanrawal requested changes
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6275)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @JatinDevDG, @MichaelJCompton, and @pawanrawal)

___
*[graphql/schema/validation_rules.go, line 69 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MFeLPsj-uscBNlCpHF-:-MFeLPsj-uscBNlCpHF0:bvsj0f9) ([raw file](https://github.com/dgraph-io/dgraph/blob/31d12accf30ee9c9983494837ab074ba0e28f125/graphql/schema/validation_rules.go#L69)):*
> ```Go
> }
> 
> func intRangeCheck(observers *validator.Events, addError validator.AddErrFunc) {
> ```

Do we need another check for the Int64 type that we introduced recently?
___
*[graphql/schema/validation_rules.go, line 79 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MFeKw_C64hJKNe4Gp0V:-MFeKw_C64hJKNe4Gp0W:b-ggqun0) ([raw file](https://github.com/dgraph-io/dgraph/blob/31d12accf30ee9c9983494837ab074ba0e28f125/graphql/schema/validation_rules.go#L79)):*
> ```Go
> 		}
> 
> 		intVal, err := strconv.ParseInt(value.Raw, 10, 64)
> ```

Shouldn't this be parsed with bit size 32? That already gives an out of bound error.

From  https://golang.org/pkg/strconv/#ParseInt

```
if the value corresponding to s cannot be represented by a signed integer of the given size, err.Err = ErrRange
```

So maybe you can check for the error if its ErrRange, then you can throw the Out of range error otherwise whatever error is returned.
___
*[graphql/schema/validation_rules.go, line 88 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MFeLYot0r3Tnxa_UADZ:-MFeLYot0r3Tnxa_UAD_:bz84n7s) ([raw file](https://github.com/dgraph-io/dgraph/blob/31d12accf30ee9c9983494837ab074ba0e28f125/graphql/schema/validation_rules.go#L88)):*
> ```Go
> 		}
> 
> 		addError(validator.Message("Out of range value '%s', for Variable type `%s`",
> ```

The value.Definition.Name is always going to be `Int` so no need to substitute it


<!-- Sent from Reviewable.io -->

2020-08-26 13:21 UTC, abhimanyusinghgaur requested changes
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6275)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @JatinDevDG and @MichaelJCompton)

___
*[graphql/e2e/common/error_test.yaml, line 120 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MFeuWAr84qs2K4uFQoy:-MFeuWAr84qs2K4uFQoz:b-rwijl0) ([raw file](https://github.com/dgraph-io/dgraph/blob/31d12accf30ee9c9983494837ab074ba0e28f125/graphql/e2e/common/error_test.yaml#L120)):*
> ```
> "Out of range value '2147483648', for Variable type `Int`"
> ```
Is it possible to change it to:

```
"Out of range value '2147483648', for field `numLikes` of type `Int`"
```
or, if it is not possible to get `numLikes`, then:
```
"Out of range value '2147483648', for type `Int`"
```
`Variable` doesn't feel right in this context.


<!-- Sent from Reviewable.io -->

2020-08-27 08:07 UTC, JatinDevDG reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6275)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @abhimanyusinghgaur, @MichaelJCompton, and @pawanrawal)

___
*[graphql/e2e/common/error_test.yaml, line 120 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MFeuWAr84qs2K4uFQoy:-MFiwm9y69q3r-IWSS2r:b-i0nlzd) ([raw file](https://github.com/dgraph-io/dgraph/blob/31d12accf30ee9c9983494837ab074ba0e28f125/graphql/e2e/common/error_test.yaml#L120)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> "Out of range value '2147483648', for Variable type `Int`"
> ```
Is it possible to change it to:

```
"Out of range value '2147483648', for field `numLikes` of type `Int`"
```
or, if it is not possible to get `numLikes`, then:
```
"Out of range value '2147483648', for type `Int`"
```
`Variable` doesn't feel right in this context.
</blockquote></details>

field name is not there , changed it to Out of range value '2147483648', for type `Int` or 'int64'.
___
*[graphql/schema/validation_rules.go, line 69 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MFeLPsj-uscBNlCpHF-:-MFix6nD0EeQM50_P1xo:b-qy3qbu) ([raw file](https://github.com/dgraph-io/dgraph/blob/31d12accf30ee9c9983494837ab074ba0e28f125/graphql/schema/validation_rules.go#L69)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Do we need another check for the Int64 type that we introduced recently?
</blockquote></details>

yes, done.
___
*[graphql/schema/validation_rules.go, line 79 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MFeKw_C64hJKNe4Gp0V:-MFix9jF0xmhd0heA26l:b-b5c35t) ([raw file](https://github.com/dgraph-io/dgraph/blob/31d12accf30ee9c9983494837ab074ba0e28f125/graphql/schema/validation_rules.go#L79)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Shouldn't this be parsed with bit size 32? That already gives an out of bound error.

From  https://golang.org/pkg/strconv/#ParseInt

```
if the value corresponding to s cannot be represented by a signed integer of the given size, err.Err = ErrRange
```

So maybe you can check for the error if its ErrRange, then you can throw the Out of range error otherwise whatever error is returned.
</blockquote></details>

changed.
___
*[graphql/schema/validation_rules.go, line 88 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MFeLYot0r3Tnxa_UADZ:-MFixBiDE_SFQzYbLq__:b4v88dk) ([raw file](https://github.com/dgraph-io/dgraph/blob/31d12accf30ee9c9983494837ab074ba0e28f125/graphql/schema/validation_rules.go#L88)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

The value.Definition.Name is always going to be `Int` so no need to substitute it
</blockquote></details>

didn't changed it because,Now we also have int64. 


<!-- Sent from Reviewable.io -->

2020-08-27 13:03 UTC, abhimanyusinghgaur requested changes
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6275)* status: 0 of 9 files reviewed, 7 unresolved discussions (waiting on @JatinDevDG, @MichaelJCompton, and @pawanrawal)

___
*[graphql/e2e/common/error_test.yaml, line 176 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MFjxve32PoZV1uPiC9-:-MFjxve32PoZV1uPiC90:bb0kkhe) ([raw file](https://github.com/dgraph-io/dgraph/blob/23bffbd7ec3b078c80029d10c2d540b49c31ab39/graphql/e2e/common/error_test.yaml#L176)):*
> ```
> 9007199300000000
> ```
It was supposed to be negative, but there is no negative sign here.
And `2^53` is `9007199254740992` not `9007199300000000`. I suspect the calculator being used is itself not precise.
___
*[graphql/e2e/common/mutation.go, line 3654 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MFjyynw2Sdvjwe9Yho3:-MFjyynw2Sdvjwe9Yho4:b-2rrc1v) ([raw file](https://github.com/dgraph-io/dgraph/blob/23bffbd7ec3b078c80029d10c2d540b49c31ab39/graphql/e2e/common/mutation.go#L3654)):*
> ```
> 9223372036854775000
> ```
It looks something close to `2^63` but is not `2^63`, because powers of 2 don't end with `0`s.
`2^63 = 9,223,372,036,854,775,808`
Also, if we are giving errors for it being greater than `(2^53)-1` than how can this test pass?
___
*[graphql/schema/validation_rules.go, line 99 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MFk-cLt4SVsRJtOYUug:-MFk-cLt4SVsRJtOYUuh:b-xa2foj) ([raw file](https://github.com/dgraph-io/dgraph/blob/23bffbd7ec3b078c80029d10c2d540b49c31ab39/graphql/schema/validation_rules.go#L99)):*
> ```Go
> func intRangeCheck(observers *validator.Events, addError validator.AddErrFunc) {
> 	observers.OnValue(func(walker *validator.Walker, value *ast.Value) {
> 		if value.Definition == nil || value.ExpectedType == nil || value.Kind != ast.IntValue{
> ```

what if we receive value in a GraphQL variable instead of directly in the query?
___
*[graphql/schema/validation_rules.go, line 116 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MFk--gr0cNztriZ1xYp:-MFk--gr0cNztriZ1xYq:b-3zbtbi) ([raw file](https://github.com/dgraph-io/dgraph/blob/23bffbd7ec3b078c80029d10c2d540b49c31ab39/graphql/schema/validation_rules.go#L116)):*
> ```
> float64(val) == (-1)*math.Pow(2, 53)
> ```
we shouldn't be converting to float and then compare, because that is exactly where we lose the precision. We should just keep the comparison between int64 values. Also, since we know the RHS in this equation, we can keep it as a constant.


<!-- Sent from Reviewable.io -->

2020-09-01 10:56 UTC, pawanrawal requested changes
> Reviewed 5 of 9 files at r2, 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6275)* status: all files reviewed, 8 unresolved discussions (waiting on @JatinDevDG and @MichaelJCompton)

___
*[graphql/e2e/common/error_test.yaml, line 171 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MG8HKab6pLdmjHCFFq0:-MG8HKab6pLdmjHCFFq1:bp9mug2) ([raw file](https://github.com/dgraph-io/dgraph/blob/c324d28b11fce7081b2f9e46595fedb8e31fab5e/graphql/e2e/common/error_test.yaml#L171)):*
> ```YAML
>     { }
>   errors:
>     [ { "message": "Given input type mismatch, Expected Int64",
> ```

Can we have the field name or the value as part of the error message.
___
*[graphql/e2e/directives/schema.graphql, line 178 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MG8HvZ76SY3F6pnnJ7Q:-MG8HvZ76SY3F6pnnJ7R:bcis94o) ([raw file](https://github.com/dgraph-io/dgraph/blob/c324d28b11fce7081b2f9e46595fedb8e31fab5e/graphql/e2e/directives/schema.graphql#L178)):*
> ```GraphQL
> type post1{
>     id:ID
>     title:String!  @id @search(by: [regexp])
> ```

Should be formatted properly.
___
*[graphql/e2e/directives/schema.graphql, line 181 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MG8I3lt5HuhbwZh9pqY:-MG8I3lt5HuhbwZh9pqZ:bav3s7r) ([raw file](https://github.com/dgraph-io/dgraph/blob/c324d28b11fce7081b2f9e46595fedb8e31fab5e/graphql/e2e/directives/schema.graphql#L181)):*
> ```GraphQL
>     numLikes:Int64
>     numViews:Int64
>     numComments:Int64
> ```

can be removed as its not being used. You only probably need one value here and you can create two posts.
___
*[graphql/schema/validation_rules.go, line 123 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MG8IaFe9dA-QnZ0_Pqf:-MG8IaFe9dA-QnZ0_Pqg:bpjkgiz) ([raw file](https://github.com/dgraph-io/dgraph/blob/c324d28b11fce7081b2f9e46595fedb8e31fab5e/graphql/schema/validation_rules.go#L123)):*
> ```Go
> }
> 
> func intRangeCheck1(observers *validator.Events, addError validator.AddErrFunc) {
> ```

should be removed


<!-- Sent from Reviewable.io -->

2020-09-01 18:52 UTC, JatinDevDG reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6275)* status: 2 of 47 files reviewed, 8 unresolved discussions (waiting on @abhimanyusinghgaur, @MichaelJCompton, and @pawanrawal)

___
*[graphql/e2e/common/error_test.yaml, line 176 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MFjxve32PoZV1uPiC9-:-MG9zqkk2Vb-QN-PZtT_:b-8buqp8) ([raw file](https://github.com/dgraph-io/dgraph/blob/23bffbd7ec3b078c80029d10c2d540b49c31ab39/graphql/e2e/common/error_test.yaml#L176)):*
>
modified.
___
*[graphql/e2e/common/error_test.yaml, line 171 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MG8HKab6pLdmjHCFFq0:-MG9zmkk6Ai4AEP-yXd0:bslg9ky) ([raw file](https://github.com/dgraph-io/dgraph/blob/c324d28b11fce7081b2f9e46595fedb8e31fab5e/graphql/e2e/common/error_test.yaml#L171)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Can we have the field name or the value as part of the error message.
</blockquote></details>

added value.
___
*[graphql/e2e/common/mutation.go, line 3654 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MFjyynw2Sdvjwe9Yho3:-MG9zw6K9edATVD1I0w1:b-i735fn) ([raw file](https://github.com/dgraph-io/dgraph/blob/23bffbd7ec3b078c80029d10c2d540b49c31ab39/graphql/e2e/common/mutation.go#L3654)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 9223372036854775000
> ```
It looks something close to `2^63` but is not `2^63`, because powers of 2 don't end with `0`s.
`2^63 = 9,223,372,036,854,775,808`
Also, if we are giving errors for it being greater than `(2^53)-1` than how can this test pass?
</blockquote></details>

modified the test to check rangefor  int64.
___
*[graphql/e2e/directives/schema.graphql, line 178 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MG8HvZ76SY3F6pnnJ7Q:-MGA-9nd6YleEaF6x04w:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/c324d28b11fce7081b2f9e46595fedb8e31fab5e/graphql/e2e/directives/schema.graphql#L178)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Should be formatted properly.
</blockquote></details>

done.
___
*[graphql/e2e/directives/schema.graphql, line 181 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MG8I3lt5HuhbwZh9pqY:-MGA-CCq8VdCepkCF3fR:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/c324d28b11fce7081b2f9e46595fedb8e31fab5e/graphql/e2e/directives/schema.graphql#L181)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

can be removed as its not being used. You only probably need one value here and you can create two posts.
</blockquote></details>

done.
___
*[graphql/schema/validation_rules.go, line 99 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MFk-cLt4SVsRJtOYUug:-MGA-HM80l8XOWzrpoE7:bf3z7ee) ([raw file](https://github.com/dgraph-io/dgraph/blob/23bffbd7ec3b078c80029d10c2d540b49c31ab39/graphql/schema/validation_rules.go#L99)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

what if we receive value in a GraphQL variable instead of directly in the query?
</blockquote></details>

Right now , we  get output coercing error for variables as we were getting previously. Input coercing for variables will be added in separate PR.
___
*[graphql/schema/validation_rules.go, line 116 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MFk--gr0cNztriZ1xYp:-MGA-iD42fNY5DjgjMU-:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/23bffbd7ec3b078c80029d10c2d540b49c31ab39/graphql/schema/validation_rules.go#L116)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> float64(val) == (-1)*math.Pow(2, 53)
> ```
we shouldn't be converting to float and then compare, because that is exactly where we lose the precision. We should just keep the comparison between int64 values. Also, since we know the RHS in this equation, we can keep it as a constant.
</blockquote></details>

done.
___
*[graphql/schema/validation_rules.go, line 123 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MG8IaFe9dA-QnZ0_Pqf:-MGA-kis5cwxGMij6AFm:brpmqc3) ([raw file](https://github.com/dgraph-io/dgraph/blob/c324d28b11fce7081b2f9e46595fedb8e31fab5e/graphql/schema/validation_rules.go#L123)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

should be removed
</blockquote></details>

removed.


<!-- Sent from Reviewable.io -->

2020-09-02 10:35 UTC, abhimanyusinghgaur requested changes
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6275)* status: 2 of 48 files reviewed, 18 unresolved discussions (waiting on @JatinDevDG, @MichaelJCompton, and @pawanrawal)

___
*[graphql/e2e/common/error_test.yaml, line 119 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MGD6SBD6hABe29a7U4W:-MGD6SBD6hABe29a7U4X:b-nfkjb8) ([raw file](https://github.com/dgraph-io/dgraph/blob/bf88eb37ad152dbbd0c6d9bedb535a05194c064b/graphql/e2e/common/error_test.yaml#L119)):*
> ```YAML
> 
> -
>   name: "Out of range error for int32 type"
> ```

also an out of range error case with 2^63 for Int64
___
*[graphql/e2e/common/mutation.go, line 3656 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MGD7QhQ7M1yWWavZaVu:-MGD7QhQ7M1yWWavZaVv:bn1vsoz) ([raw file](https://github.com/dgraph-io/dgraph/blob/bf88eb37ad152dbbd0c6d9bedb535a05194c064b/graphql/e2e/common/mutation.go#L3656)):*
> ```
> -9223372036854775807
> ```
should this be `-9223372036854775808`, i.e. the actual negative bound?
___
*[graphql/e2e/common/mutation.go, line 3672 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MGD7GE48-7pnU9GRiS_:-MGD7GE48-7pnU9GRiSa:bpevzqy) ([raw file](https://github.com/dgraph-io/dgraph/blob/bf88eb37ad152dbbd0c6d9bedb535a05194c064b/graphql/e2e/common/mutation.go#L3672)):*
> ```
> 9223372036854775808
> ```
shouldn't this be `9223372036854775807`?
___
*[graphql/resolve/resolver.go, line 1509 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MGDBTwa2phKhOTwhqiI:-MGDBTwa2phKhOTwhqiJ:bihyzkz) ([raw file](https://github.com/dgraph-io/dgraph/blob/bf88eb37ad152dbbd0c6d9bedb535a05194c064b/graphql/resolve/resolver.go#L1509)):*
> ```
> // numUids are added as int, so we need special handling for that.
> ```
a new line before this like comments in other cases. Also, we can just keep this `case int: ...` part after `case int64` part to minimize the git diff.
___
*[graphql/resolve/resolver.go, line 1532 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MGDClw0Ej0iAfZeWNFK:-MGDClw0Ej0iAfZeWNFL:bjv8uum) ([raw file](https://github.com/dgraph-io/dgraph/blob/bf88eb37ad152dbbd0c6d9bedb535a05194c064b/graphql/resolve/resolver.go#L1532)):*
<details><summary><i alt="summary">Quoted 13 lines of code…</i></summary>

> ```
> case float64:
> 			// The spec says that we can coerce a Float value to Int, if we don't lose information.
> 			// See: https: //spec.graphql.org/June2018/#sec-Float
> 			// Lets try to see if this number could be converted to int64 without losing
> 			// information, otherwise return error.
> 			// See: https://github.com/golang/go/issues/19405 to understand why the comparison
> 			// should be done after double conversion.
> 			i64Val := int64(v)
> 			if v == float64(i64Val) {
> 				val = i64Val
> 			} else {
> 				return nil, valueCoercionError(v)
> 			}
> ```
</details>

I guess , this part could also be removed now that we are using json Number to represent Int64 internally, so it will no longer be parsed to float.
___
*[graphql/resolve/resolver.go, line 1466 at r7](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MGDKeXK2FOq-dQ0r7_Z:-MGDKeXK2FOq-dQ0r7__:b-r9d3vi) ([raw file](https://github.com/dgraph-io/dgraph/blob/d32a70a8d104e62c8e1c9bcfa9284edefae6b00e/graphql/resolve/resolver.go#L1466)):*
> ```
> valFloat, _ := v.Float64()
> 			val = strconv.FormatFloat(valFloat, 'f', -1, 64)
> ```
for string, we can just do:
```
val = v.String()
```
no need to parse it to float and then parse it back to a string.
___
*[graphql/resolve/resolver.go, line 1474 at r7](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MGDKwfv8A7HWnnYSLMi:-MGDKwfv8A7HWnnYSLMj:b-qz94da) ([raw file](https://github.com/dgraph-io/dgraph/blob/d32a70a8d104e62c8e1c9bcfa9284edefae6b00e/graphql/resolve/resolver.go#L1474)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> case float64:
> 			val = v != 0
> 		case int64:
> 			val = v != 0
> ```
</details>

now maybe we can remove these cases.
___
*[graphql/resolve/resolver.go, line 1492 at r7](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MGDN4SH9sRPiEgVVrZ8:-MGDN4SH9sRPiEgVVrZ9:bjnmqvb) ([raw file](https://github.com/dgraph-io/dgraph/blob/d32a70a8d104e62c8e1c9bcfa9284edefae6b00e/graphql/resolve/resolver.go#L1492)):*
<details><summary><i alt="summary">Quoted 13 lines of code…</i></summary>

> ```
> case float64:
> 			// The spec says that we can coerce a Float value to Int, if we don't lose information.
> 			// See: https: //spec.graphql.org/June2018/#sec-Float
> 			// Lets try to see if this number could be converted to int32 without losing
> 			// information, otherwise return error.
> 			// See: https://github.com/golang/go/issues/19405 to understand why the comparison
> 			// should be done after double conversion.
> 			i32Val := int32(v)
> 			if v == float64(i32Val) {
> 				val = i32Val
> 			} else {
> 				return nil, valueCoercionError(v)
> 			}
> ```
</details>

I guess this case could be removed now.
___
*[graphql/resolve/resolver.go, line 1508 at r7](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MGDKArhB85iIUSai_nu:-MGDKArhB85iIUSai_nv:bqrhhcl) ([raw file](https://github.com/dgraph-io/dgraph/blob/d32a70a8d104e62c8e1c9bcfa9284edefae6b00e/graphql/resolve/resolver.go#L1508)):*
> ```
> 32
> ```
the reason for this being 64 was that a 32-bit float won't be able to represent the full range of 32-bit ints. So, we should change it back to 64.
___
*[graphql/resolve/resolver.go, line 1520 at r7](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MGDLs1_8YyXwl02NbH0:-MGDLs1_8YyXwl02NbH1:b-nsvllp) ([raw file](https://github.com/dgraph-io/dgraph/blob/d32a70a8d104e62c8e1c9bcfa9284edefae6b00e/graphql/resolve/resolver.go#L1520)):*
> ```
> val = i
> ```
execution flow won't reach this line, can be removed.
___
*[graphql/resolve/resolver.go, line 1532 at r7](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MGDM33V48VcJO2oO08L:-MGDM33V48VcJO2oO08M:b-9so18e) ([raw file](https://github.com/dgraph-io/dgraph/blob/d32a70a8d104e62c8e1c9bcfa9284edefae6b00e/graphql/resolve/resolver.go#L1532)):*
> ```
> 32
> ```
64
___
*[graphql/resolve/resolver.go, line 1542 at r7](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MGDM9ZO9PIfQ-KY3b1x:-MGDM9ZO9PIfQ-KY3b1y:bvzsakf) ([raw file](https://github.com/dgraph-io/dgraph/blob/d32a70a8d104e62c8e1c9bcfa9284edefae6b00e/graphql/resolve/resolver.go#L1542)):*
> ```
> val = i
> ```
stale line, should be removed
___
*[graphql/resolve/resolver.go, line 1620 at r7](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MGDMmY42D34_hfGhou8:-MGDMmY42D34_hfGhou9:bi3d0s4) ([raw file](https://github.com/dgraph-io/dgraph/blob/d32a70a8d104e62c8e1c9bcfa9284edefae6b00e/graphql/resolve/resolver.go#L1620)):*
<details><summary><i alt="summary">Quoted 12 lines of code…</i></summary>

> ```
> case float64:
> 			truncated := math.Trunc(v)
> 			if truncated == v {
> 				// Lets interpret int values as unix timestamp.
> 				t := time.Unix(int64(truncated), 0).UTC()
> 				val = t.Format(time.RFC3339)
> 			} else {
> 				return nil, valueCoercionError(v)
> 			}
> 		case int64:
> 			t := time.Unix(v, 0).UTC()
> 			val = t.Format(time.RFC3339)
> ```
</details>

so, both these cases could be removed now.
___
*[graphql/schema/gqlschema.go, line 66 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MGDFKpMDqwbQM3F9ZqS:-MGDFKpMDqwbQM3F9ZqT:b-z75ezc) ([raw file](https://github.com/dgraph-io/dgraph/blob/bf88eb37ad152dbbd0c6d9bedb535a05194c064b/graphql/schema/gqlschema.go#L66)):*
> ```Go
> 	schemaExtras = `
> """
> The Int64 scalar type represents a signed 64‐bit numeric non‐fractional value.
> ```

The docs for `Int` type say:
```
The Int scalar type represents non-fractional signed whole numeric values.
Int can represent values between -(2^31) and 2^31 - 1.
```

So, similarly, for `Int64` we can now say:
```
The Int64 scalar type represents a signed 64‐bit numeric non‐fractional value.
Int64 can represent values between -(2^63) and 2^63 - 1.
```
___
*[graphql [...]

2020-09-02 14:30 UTC, JatinDevDG reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6275)* status: 2 of 48 files reviewed, 18 unresolved discussions (waiting on @abhimanyusinghgaur, @MichaelJCompton, and @pawanrawal)

___
*[graphql/e2e/common/error_test.yaml, line 119 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MGD6SBD6hABe29a7U4W:-MGDxbA_1FCQKj5ici6j:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/bf88eb37ad152dbbd0c6d9bedb535a05194c064b/graphql/e2e/common/error_test.yaml#L119)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

also an out of range error case with 2^63 for Int64
</blockquote></details>

done.
___
*[graphql/e2e/common/mutation.go, line 3656 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MGD7QhQ7M1yWWavZaVu:-MGDyYDq8fnkAyrmP0jT:bed20xu) ([raw file](https://github.com/dgraph-io/dgraph/blob/bf88eb37ad152dbbd0c6d9bedb535a05194c064b/graphql/e2e/common/mutation.go#L3656)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> -9223372036854775807
> ```
should this be `-9223372036854775808`, i.e. the actual negative bound?
</blockquote></details>

changed, swapped values by mistake.
___
*[graphql/e2e/common/mutation.go, line 3672 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MGD7GE48-7pnU9GRiS_:-MGDyd1X5zAFCin6gO-2:b-b5c35t) ([raw file](https://github.com/dgraph-io/dgraph/blob/bf88eb37ad152dbbd0c6d9bedb535a05194c064b/graphql/e2e/common/mutation.go#L3672)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 9223372036854775808
> ```
shouldn't this be `9223372036854775807`?
</blockquote></details>

changed.
___
*[graphql/resolve/resolver.go, line 1509 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MGDBTwa2phKhOTwhqiI:-MGDYINS16OD7r5V3Ab5:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/bf88eb37ad152dbbd0c6d9bedb535a05194c064b/graphql/resolve/resolver.go#L1509)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> // numUids are added as int, so we need special handling for that.
> ```
a new line before this like comments in other cases. Also, we can just keep this `case int: ...` part after `case int64` part to minimize the git diff.
</blockquote></details>

done.
___
*[graphql/resolve/resolver.go, line 1532 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MGDClw0Ej0iAfZeWNFK:-MGDUulw6eC-iH6TQRd7:brpmqc3) ([raw file](https://github.com/dgraph-io/dgraph/blob/bf88eb37ad152dbbd0c6d9bedb535a05194c064b/graphql/resolve/resolver.go#L1532)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> case float64:
> 			// The spec says that we can coerce a Float value to Int, if we don't lose information.
> 			// See: https: //spec.graphql.org/June2018/#sec-Float
> 			// Lets try to see if this number could be converted to int64 without losing
> 			// information, otherwise return error.
> 			// See: https://github.com/golang/go/issues/19405 to understand why the comparison
> 			// should be done after double conversion.
> 			i64Val := int64(v)
> 			if v == float64(i64Val) {
> 				val = i64Val
> 			} else {
> 				return nil, valueCoercionError(v)
> 			}
> ```
I guess , this part could also be removed now that we are using json Number to represent Int64 internally, so it will no longer be parsed to float.
</blockquote></details>

removed.
___
*[graphql/resolve/resolver.go, line 1466 at r7](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MGDKeXK2FOq-dQ0r7_Z:-MGDS7qbCg1QCClFj2BU:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/d32a70a8d104e62c8e1c9bcfa9284edefae6b00e/graphql/resolve/resolver.go#L1466)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> valFloat, _ := v.Float64()
> 			val = strconv.FormatFloat(valFloat, 'f', -1, 64)
> ```
for string, we can just do:
```
val = v.String()
```
no need to parse it to float and then parse it back to a string.
</blockquote></details>

done.
___
*[graphql/resolve/resolver.go, line 1474 at r7](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MGDKwfv8A7HWnnYSLMi:-MGDSAwJ3aKfd4BhBqG3:brpmqc3) ([raw file](https://github.com/dgraph-io/dgraph/blob/d32a70a8d104e62c8e1c9bcfa9284edefae6b00e/graphql/resolve/resolver.go#L1474)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> case float64:
> 			val = v != 0
> 		case int64:
> 			val = v != 0
> ```
now maybe we can remove these cases.
</blockquote></details>

removed.
___
*[graphql/resolve/resolver.go, line 1492 at r7](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MGDN4SH9sRPiEgVVrZ8:-MGDTK4Y92-bcxW66tGj:b-7u8vxj) ([raw file](https://github.com/dgraph-io/dgraph/blob/d32a70a8d104e62c8e1c9bcfa9284edefae6b00e/graphql/resolve/resolver.go#L1492)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> case float64:
> 			// The spec says that we can coerce a Float value to Int, if we don't lose information.
> 			// See: https: //spec.graphql.org/June2018/#sec-Float
> 			// Lets try to see if this number could be converted to int32 without losing
> 			// information, otherwise return error.
> 			// See: https://github.com/golang/go/issues/19405 to understand why the comparison
> 			// should be done after double conversion.
> 			i32Val := int32(v)
> 			if v == float64(i32Val) {
> 				val = i32Val
> 			} else {
> 				return nil, valueCoercionError(v)
> 			}
> ```
I guess this case could be removed now.
</blockquote></details>

There are some admin e2e tests that require this case.
___
*[graphql/resolve/resolver.go, line 1508 at r7](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MGDKArhB85iIUSai_nu:-MGDTl1v0jHCL7ztSSvD:b-c4vgoh) ([raw file](https://github.com/dgraph-io/dgraph/blob/d32a70a8d104e62c8e1c9bcfa9284edefae6b00e/graphql/resolve/resolver.go#L1508)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 32
> ```
the reason for this being 64 was that a 32-bit float won't be able to represent the full range of 32-bit ints. So, we should change it back to 64.
</blockquote></details>

ok, changed.
___
*[graphql/resolve/resolver.go, line 1520 at r7](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MGDLs1_8YyXwl02NbH0:-MGDTuFo6hK3ExIHwZmE:brpmqc3) ([raw file](https://github.com/dgraph-io/dgraph/blob/d32a70a8d104e62c8e1c9bcfa9284edefae6b00e/graphql/resolve/resolver.go#L1520)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> val = i
> ```
execution flow won't reach this line, can be removed.
</blockquote></details>

removed.
___
*[graphql/resolve/resolver.go, line 1532 at r7](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MGDM33V48VcJO2oO08L:-MGDUSsxBBZyo0VoFd1Q:b-b5c35t) ([raw file](https://github.com/dgraph-io/dgraph/blob/d32a70a8d104e62c8e1c9bcfa9284edefae6b00e/graphql/resolve/resolver.go#L1532)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 32
> ```
64
</blockquote></details>

changed.
___
*[graphql/resolve/resolver.go, line 1542 at r7](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MGDM9ZO9PIfQ-KY3b1x:-MGDUpxl89yrvwy-hjHL:brpmqc3) ([raw file](https://github.com/dgraph-io/dgraph/blob/d32a70a8d104e62c8e1c9bcfa9284edefae6b00e/graphql/resolve/resolver.go#L1542)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> val = i
> ```
stale line, should be removed
</blockquote></details>

removed.
___
*[graphql/resolve/resolver.go, line 1620 at r7](https://reviewable.io/reviews/dgraph-io/ [...]

2020-09-02 16:16 UTC, abhimanyusinghgaur approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 
no major comments, just some minor things related to formatting.

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-:-MGEaTo96SzJvIAyiitl:b-yfl3pe)* status: 1 of 48 files reviewed, 8 unresolved discussions (waiting on @JatinDevDG, @MichaelJCompton, and @pawanrawal)

___
*[graphql/resolve/resolver.go, line 1505 at r8](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MGEZHlk3DsECm5CMhe7:-MGEZHllDQ6A5I___LdB:b-qqjnye) ([raw file](https://github.com/dgraph-io/dgraph/blob/9962657ff44254d04a2e8ef80c2fe237a2e585be/graphql/resolve/resolver.go#L1505)):*
> ```
> 32 bit int.
> ```
64 bit floating point number.
___
*[graphql/resolve/resolver.go, line 1506 at r8](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MGEZKDXEgvkcOhQsE2p:-MGEZKDXEgvkcOhQsE2q:bu08by4) ([raw file](https://github.com/dgraph-io/dgraph/blob/12b27160fa0c8bc3ad668a24ef557c6bdb6cd9c0/graphql/resolve/resolver.go#L1506)):*
> ```
> // Lets try to see if this number could be converted to int32 without losing
> 			// information, otherwise return error.
> ```
this comment can be put back now
___
*[graphql/schema/rules.go, line 52 at r8](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MGE__F1CE6IaatzkFH5:-MGE__F1CE6IaatzkFH6:b-800urs) ([raw file](https://github.com/dgraph-io/dgraph/blob/9962657ff44254d04a2e8ef80c2fe237a2e585be/graphql/schema/rules.go#L52)):*
> ```
> ValueKindToString
> ```
no need to export it:
```
valueKindToString
```
___
*[graphql/schema/rules.go, line 53 at r8](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MGE_hcLDfXsz4ucyqCt:-MGE_hcLDfXsz4ucyqCu:b8hq8ql) ([raw file](https://github.com/dgraph-io/dgraph/blob/9962657ff44254d04a2e8ef80c2fe237a2e585be/graphql/schema/rules.go#L53)):*
> ```
> var valueKind string
> ```
instead of keeping a var and assigning to it, we can just `return` from each case.


<!-- Sent from Reviewable.io -->

2020-09-02 18:04 UTC, JatinDevDG reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6275)* status: 1 of 48 files reviewed, 8 unresolved discussions (waiting on @abhimanyusinghgaur, @MichaelJCompton, and @pawanrawal)

___
*[graphql/resolve/resolver.go, line 1505 at r8](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MGEZHlk3DsECm5CMhe7:-MGEz8xt63e_cWrJY_7Z:b-b5c35t) ([raw file](https://github.com/dgraph-io/dgraph/blob/9962657ff44254d04a2e8ef80c2fe237a2e585be/graphql/resolve/resolver.go#L1505)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 32 bit int.
> ```
64 bit floating point number.
</blockquote></details>

changed.
___
*[graphql/resolve/resolver.go, line 1506 at r8](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MGEZKDXEgvkcOhQsE2p:-MGEzBL67FEmSUrA_m-p:b-t948zx) ([raw file](https://github.com/dgraph-io/dgraph/blob/12b27160fa0c8bc3ad668a24ef557c6bdb6cd9c0/graphql/resolve/resolver.go#L1506)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> // Lets try to see if this number could be converted to int32 without losing
> 			// information, otherwise return error.
> ```
this comment can be put back now
</blockquote></details>

added.
___
*[graphql/schema/rules.go, line 52 at r8](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MGE__F1CE6IaatzkFH5:-MGEzEUk4lTas9qzac5B:b-2mk5da) ([raw file](https://github.com/dgraph-io/dgraph/blob/9962657ff44254d04a2e8ef80c2fe237a2e585be/graphql/schema/rules.go#L52)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> ValueKindToString
> ```
no need to export it:
```
valueKindToString
```
</blockquote></details>

put in validation_rules.go file.
___
*[graphql/schema/rules.go, line 53 at r8](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MGE_hcLDfXsz4ucyqCt:-MGEzQPD5j4KyKkBmMWA:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/9962657ff44254d04a2e8ef80c2fe237a2e585be/graphql/schema/rules.go#L53)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> var valueKind string
> ```
instead of keeping a var and assigning to it, we can just `return` from each case.
</blockquote></details>

done.


<!-- Sent from Reviewable.io -->

2020-09-03 08:24 UTC, pawanrawal approved these changes
> Reviewed 4 of 45 files at r6, 1 of 2 files at r7, 38 of 42 files at r8, 6 of 6 files at r9.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6275)* status: all files reviewed, 5 unresolved discussions (waiting on @abhimanyusinghgaur, @JatinDevDG, and @MichaelJCompton)

___
*[graphql/e2e/schema/generatedSchema.graphql, line 16 at r9](https://reviewable.io/reviews/dgraph-io/dgraph/6275#-MGI1HEO0pi4h3s-HBA-:-MGI1HEO0pi4h3s-HBA0:biv08bi) ([raw file](https://github.com/dgraph-io/dgraph/blob/5de04f16823052edd243af9e0bcf07d54e8a4917/graphql/e2e/schema/generatedSchema.graphql#L16)):*
> ```GraphQL
> """
> The Int64 scalar type represents a signed 64‐bit numeric non‐fractional value.
> Int64 can represent values between -(2^63) and 2^63 - 1.
> ```

...values in the range [-(2^63),  2^63 - 1]. Values out of this range would give an out of range error.


To make it clear that it's inclusive of these values.


<!-- Sent from Reviewable.io -->

2020-09-03 10:31 UTC, merged