fix(encoder): Use EncoderAlloc for manual allocations
dgraph-io/dgraph pull request #6327
Opened 2020-08-31 11:01 UTC by jarifibrahim

The `codec.Encoder` type and `codec.Encode()` function is used at many places in dgraph and using manually allocated memory in these functions would require all the callers to call `FreePack`. This PR creates a new `EncoderAlloc` type and `EncodeAlloc()` function that can be used by bulk loader to manually allocate memory.

2020-09-01 14:37 UTC, jarifibrahim reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6327)* status: 4 of 7 files reviewed, 3 unresolved discussions (waiting on @manishrjain and @martinmr)

___
*[codec/codec.go, line 65 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6327#-MG8cWNs4J5TZ39407Op:-MG93Tf98HjNmVvCJ5EA:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/168f8dd865f223821e9c875f2ff78288e7c62842/codec/codec.go#L65)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Just add a bool here.
</blockquote></details>

Done.
___
*[codec/codec.go, line 105 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6327#-MG8ciBPBf2ABF9MfD-D:-MG93dNe871h8I0ZeIz3:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/168f8dd865f223821e9c875f2ff78288e7c62842/codec/codec.go#L105)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

pass the bool here.
</blockquote></details>

Done.
___
*[worker/restore.go, line 171 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6327#-MG8d_akCEil2OW5Rg6F:-MG94IzkCYRn3mDo0p-H:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/168f8dd865f223821e9c875f2ff78288e7c62842/worker/restore.go#L171)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

In all production code, try to use manual memory.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-03 11:46 UTC, jarifibrahim reviewed
@martinmr I also noticed that we don't free the pack in case `l.rollup()` returns an error. So if we return error from here https://github.com/dgraph-io/dgraph/blob/690d094f0850e8661840eacdad6f82ce01903c39/posting/list.go#L1022-L1025

The caller (that is Rollup function) will ignore the `l.plist` here https://github.com/dgraph-io/dgraph/blob/690d094f0850e8661840eacdad6f82ce01903c39/posting/list.go#L803-L806 and we will leak the `l.plist`.

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6327#-:-MGIlZOQA_pvh-UJAUZn:bafzn7r)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @manishrjain and @martinmr)

___
*[posting/list.go, line 1 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6327#-MG9FkBhAs7kJV1EaUIP:-MGIjYvEBqwoHweGbs7_:b-xtd833) ([raw file](https://github.com/dgraph-io/dgraph/blob/e79555f25e3f294a7154e2d351abd3b55d3c8b5f/posting/list.go#L1)):*
<details><summary><i>Previously, martinmr (Martin Martinez Rivera) wrote…</i></summary><blockquote>

Are we using manual allocs in the Rollup function?
</blockquote></details>

Nice catch. We weren't doing it. I've added it now.See https://github.com/dgraph-io/dgraph/pull/6327/commits/690d094f0850e8661840eacdad6f82ce01903c39 . Please confirm if this is correct.


<!-- Sent from Reviewable.io -->

2020-09-09 16:40 UTC, martinmr requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6327)* status: all files reviewed, 5 unresolved discussions (waiting on @jarifibrahim and @manishrjain)

___
*[posting/list.go, line 1 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6327#-MG9FkBhAs7kJV1EaUIP:-MGnjNwh02xYyWViZVdO:b197bme) ([raw file](https://github.com/dgraph-io/dgraph/blob/e79555f25e3f294a7154e2d351abd3b55d3c8b5f/posting/list.go#L1)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

Nice catch. We weren't doing it. I've added it now.See https://github.com/dgraph-io/dgraph/pull/6327/commits/690d094f0850e8661840eacdad6f82ce01903c39 . Please confirm if this is correct.
</blockquote></details>

I think there's one missing manual alloc. See the other comment.
___
*[posting/list.go, line 945 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6327#-MGnjEZNBbY1Vxc1Tk5O:-MGnjEZNBbY1Vxc1Tk5P:b6nea27) ([raw file](https://github.com/dgraph-io/dgraph/blob/690d094f0850e8661840eacdad6f82ce01903c39/posting/list.go#L945)):*
> ```Go
> 	var startUid, endUid uint64
> 	var splitIdx int
> 	enc := codec.Encoder{BlockSize: blockSize}
> ```

I think this also needs manual alloc.


<!-- Sent from Reviewable.io -->

2020-09-14 15:42 UTC, jarifibrahim commented
Closing this PR in favor of https://github.com/dgraph-io/dgraph/pull/6447

2020-09-14 15:42 UTC, closed without merging