fix(gqlgen): Update gqlgen in go.mod
dgraph-io/dgraph pull request #6594
Opened 2020-09-29 09:42 UTC by vmrajas

Motivation:
gqlgen is an external module used by Dgraph for parsing graphql queries. It had the following issue: https://github.com/99designs/gqlgen/issues/1299 .
The issue was fixed with https://github.com/99designs/gqlgen/pull/1341 .
Changing the gqlgen version in go.mod .
Also added a test to verify if the issue is solved in gqlgen.

Fixes GRAPHQL-637

2020-09-29 11:41 UTC, abhimanyusinghgaur requested changes
The indirect lib upgrade for `gqlparser` seems to cause a test failure. We will have to look into that.

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6594#-:-MIObjG_DibPev63ToN7:b-no7cha)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @abhimanyusinghgaur, @manishrjain, @MichaelJCompton, @pawanrawal, @vmrajas, and @vvbalaji-dgraph)

___
*[graphql/e2e/common/query.go, line 1346 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6594#-MIOcCBA3nHe6m9qQtPU:-MIOcCBA3nHe6m9qQtPV:bkkwhpu) ([raw file](https://github.com/dgraph-io/dgraph/blob/8b42c82688650daaddf1665079484057890f0508/graphql/e2e/common/query.go#L1346)):*
> ```Go
> }
> 
> func queryAliasAndAttrOnInterface(t *testing.T) {
> ```

we should move this to `fragment.go`, this being a fragment specific test.
Actually, we can merge this one with `fragmentInQueryOnInterface` in `fragment.go` by just appending to the query and expected output there.
___
*[graphql/e2e/common/query.go, line 1357 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6594#-MIOcKLnBNXvTPLqi58J:-MIOcKLnBNXvTPLqi58K:b4zkoee) ([raw file](https://github.com/dgraph-io/dgraph/blob/8b42c82688650daaddf1665079484057890f0508/graphql/e2e/common/query.go#L1357)):*
> ```
> name
> ```
let's keep the test at a minimum, and not add this line in the query here.


<!-- Sent from Reviewable.io -->

2020-09-29 13:31 UTC, vmrajas reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6594)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @abhimanyusinghgaur, @manishrjain, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

___
*[graphql/e2e/common/query.go, line 1346 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6594#-MIOcCBA3nHe6m9qQtPU:-MIP2pDv45oHVQUbkUUS:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8b42c82688650daaddf1665079484057890f0508/graphql/e2e/common/query.go#L1346)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

we should move this to `fragment.go`, this being a fragment specific test.
Actually, we can merge this one with `fragmentInQueryOnInterface` in `fragment.go` by just appending to the query and expected output there.
</blockquote></details>

Done.
___
*[graphql/e2e/common/query.go, line 1357 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6594#-MIOcKLnBNXvTPLqi58J:-MIP2pevBsC91EsrKBLz:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8b42c82688650daaddf1665079484057890f0508/graphql/e2e/common/query.go#L1357)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> name
> ```
let's keep the test at a minimum, and not add this line in the query here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-29 17:59 UTC, abhimanyusinghgaur approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>
Seems like you will need to merge master into your branch before merging, otherwise the CI won't pass. There was a failing test which has just been fixed in master.

> Reviewed 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6594#-:-MIQ-vuS6m1a1R1t3f6e:b-6sydkn)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @manishrjain, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)



<!-- Sent from Reviewable.io -->

2020-10-01 12:03 UTC, pawanrawal approved these changes

2020-10-01 13:24 UTC, merged