CL - 20.07.2, 20.03.6, 1.2.8
dgraph-io/dgraph pull request #6688
Opened 2020-10-08 20:33 UTC by parasssh

2020-10-08 20:55 UTC, lgalatin requested changes

2020-10-08 20:55 UTC, lgalatin commented on CHANGELOG.md
> +- docs: Update restore documentation. (#6653)
we normally don't include documentation and testing changes.

2020-10-08 20:55 UTC, lgalatin commented on CHANGELOG.md
> +- perf(raft): Use raft storage in managedmode (#6457) (#6547)
only one PR number should be included.

2020-10-08 20:55 UTC, lgalatin commented on CHANGELOG.md
> +- fix(GraphQL Query): Remove extra fields when querying interfaces (#6596) (#6647)
please put all GraphQL changes together so we can stay consistent from previous versions.

2020-10-08 20:55 UTC, lgalatin commented on CHANGELOG.md
> +
extra line here

2020-10-08 20:55 UTC, lgalatin commented on CHANGELOG.md
> +- feat(Dgraph): add utility to export backup data. (#6590)
It is better if we can remove this part: feat(Dgraph)

2020-10-08 20:55 UTC, lgalatin commented on CHANGELOG.md
> +- fix(GraphQL): don't generate orderable enum value for list fields (#6392) (#6413)
... at the end of sentence, can we fix this.

2020-10-12 22:55 UTC, lgalatin reviewed
Some sentences are not starting with capital letter and/or are not ending with a period.

2020-10-12 22:55 UTC, lgalatin commented on CHANGELOG.md
> +[20.07.2]: https://github.com/dgraph-io/dgraph/compare/v20.07.1...v20.03.2
change to: [20.07.2]: https://github.com/dgraph-io/dgraph/compare/v20.07.2...v20.07.1

2020-10-12 22:55 UTC, lgalatin commented on CHANGELOG.md
> +  - This PR adds documentation for Scalar DateTime type. (#6554)
don't need this one since it is documentation

2020-10-12 22:55 UTC, lgalatin commented on CHANGELOG.md
> +- fix Poor-man's auth for admin operations (#6686)
if this is ACL related it should go under Enterprise

2020-10-13 18:50 UTC, danielmai approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6688#-:-MJYI8c16XJ_jlfw6CWA:bg7igkv)* status: all files reviewed, 9 unresolved discussions (waiting on @parasssh)



<!-- Sent from Reviewable.io -->

2022-04-29 07:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dgraph-io/dgraph?pullRequest=6688) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dgraph-io/dgraph?pullRequest=6688) before we can accept your contribution.<br/><hr/>**parasssh** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dgraph-io/dgraph?pullRequest=6688) it.</sub>

2023-08-11 02:36 UTC, closed without merging