Feat(GraphQL): This PR adds auth switch in graphql authhorization header.
dgraph-io/dgraph pull request #6779
Opened 2020-10-22 10:54 UTC by JatinDevDG

This PR adds auth switch in graphql authorization header which can be turned on to apply jwt checking on types which don't have auth directive.

2020-10-22 13:09 UTC, abhimanyusinghgaur requested changes
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6779)* status: 0 of 11 files reviewed, 17 unresolved discussions (waiting on @JatinDevDG, @manishrjain, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

___
*[graphql/authorization/auth.go, line 136 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKFCW2C7MO55yDTOBdw:-MKFCW2C7MO55yDTOBdx:b-7j964s) ([raw file](https://github.com/dgraph-io/dgraph/blob/f152bad30eb1e0ad52e1c1fa6fe8a14676234f02/graphql/authorization/auth.go#L136)):*
> ```Go
> 
> 	idx := authMetaRegex.FindAllStringSubmatchIndex(authInfo, -1)
> 	glog.Infof("%s", idx)
> ```

stale
___
*[graphql/authorization/auth.go, line 145 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKFD0ET15GpK2u7k_GZ:-MKFD0ET15GpK2u7k_G_:b5rk128) ([raw file](https://github.com/dgraph-io/dgraph/blob/f152bad30eb1e0ad52e1c1fa6fe8a14676234f02/graphql/authorization/auth.go#L145)):*
> ```Go
> 	meta.Namespace = authInfo[idx[0][6]:idx[0][7]]
> 	meta.Algo = authInfo[idx[0][8]:idx[0][9]]
> 	meta.VerificationKey = authInfo[idx[0][10]:idx[0][11]]
> ```

so, we are not providing support for this in the old format. One way to get users to move to the new format :)
___
*[graphql/e2e/auth/auth_test.go, line 128 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKFMGAiASMrqnsv38ao:-MKFMGAiASMrqnsv38ap:b9385at) ([raw file](https://github.com/dgraph-io/dgraph/blob/f152bad30eb1e0ad52e1c1fa6fe8a14676234f02/graphql/e2e/auth/auth_test.go#L128)):*
> ```
> closedByDefault bool
> ```
don't see it used here, should be removed?
___
*[graphql/e2e/auth_ClosedByDefault/auth_test.go, line 44 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKFKAnWBSYJm7nZ9eeL:-MKFKAnWBSYJm7nZ9eeM:boxvape) ([raw file](https://github.com/dgraph-io/dgraph/blob/f152bad30eb1e0ad52e1c1fa6fe8a14676234f02/graphql/e2e/auth_ClosedByDefault/auth_test.go#L44)):*
<details><summary><i alt="summary">Quoted 199 lines of code…</i></summary>

> ```
> type Region struct {
> 	Id     string         `json:"id,omitempty"`
> 	Name   string         `json:"name,omitempty"`
> 	Users  []*common.User `json:"users,omitempty"`
> 	Global bool           `json:"global,omitempty"`
> }
> type Movie struct {
> 	Id               string    `json:"id,omitempty"`
> 	Content          string    `json:"content,omitempty"`
> 	Hidden           bool      `json:"hidden,omitempty"`
> 	RegionsAvailable []*Region `json:"regionsAvailable,omitempty"`
> }
> type Issue struct {
> 	Id    string       `json:"id,omitempty"`
> 	Msg   string       `json:"msg,omitempty"`
> 	Owner *common.User `json:"owner,omitempty"`
> }
> type Log struct {
> 	Id     string `json:"id,omitempty"`
> 	Logs   string `json:"logs,omitempty"`
> 	Random string `json:"random,omitempty"`
> }
> type ComplexLog struct {
> 	Id      string `json:"id,omitempty"`
> 	Logs    string `json:"logs,omitempty"`
> 	Visible bool   `json:"visible,omitempty"`
> }
> type Role struct {
> 	Id         string         `json:"id,omitempty"`
> 	Permission string         `json:"permission,omitempty"`
> 	AssignedTo []*common.User `json:"assignedTo,omitempty"`
> }
> type Ticket struct {
> 	Id         string         `json:"id,omitempty"`
> 	OnColumn   *Column        `json:"onColumn,omitempty"`
> 	Title      string         `json:"title,omitempty"`
> 	AssignedTo []*common.User `json:"assignedTo,omitempty"`
> }
> type Column struct {
> 	ColID     string    `json:"colID,omitempty"`
> 	InProject *Project  `json:"inProject,omitempty"`
> 	Name      string    `json:"name,omitempty"`
> 	Tickets   []*Ticket `json:"tickets,omitempty"`
> }
> type Project struct {
> 	ProjID  string    `json:"projID,omitempty"`
> 	Name    string    `json:"name,omitempty"`
> 	Roles   []*Role   `json:"roles,omitempty"`
> 	Columns []*Column `json:"columns,omitempty"`
> }
> type Student struct {
> 	Id    string `json:"id,omitempty"`
> 	Email string `json:"email,omitempty"`
> }
> type Task struct {
> 	Id          string            `json:"id,omitempty"`
> 	Name        string            `json:"name,omitempty"`
> 	Occurrences []*TaskOccurrence `json:"occurrences,omitempty"`
> }
> type TaskOccurrence struct {
> 	Id   string `json:"id,omitempty"`
> 	Due  string `json:"due,omitempty"`
> 	Comp string `json:"comp,omitempty"`
> }
> type TestCase struct {
> 	user            string
> 	role            string
> 	result          string
> 	name            string
> 	filter          map[string]interface{}
> 	variables       map[string]interface{}
> 	query           string
> 	closedByDefault bool
> }
> type uidResult struct {
> 	Query []struct {
> 		UID string
> 	}
> }
> type Tasks []Task
> func (tasks Tasks) add(t *testing.T) {
> 	getParams := &common.GraphQLParams{
> 		Query: `
> 		mutation AddTask($tasks : [AddTaskInput!]!) {
> 		  addTask(input: $tasks) {
> 			numUids
> 		  }
> 		}
> 		`,
> 		Variables: map[string]interface{}{"tasks": tasks},
> 	}
> 	gqlResponse := getParams.ExecuteAsPost(t, graphqlURL)
> 	require.Nil(t, gqlResponse.Errors)
> }
> func (r *Region) add(t *testing.T, user, role string) {
> 	getParams := &common.GraphQLParams{
> 		Headers: common.GetJWT(t, user, role, metaInfo),
> 		Query: `
> 		mutation addRegion($region: AddRegionInput!) {
> 		  addRegion(input: [$region]) {
> 			numUids
> 		  }
> 		}
> 		`,
> 		Variables: map[string]interface{}{"region": r},
> 	}
> 	gqlResponse := getParams.ExecuteAsPost(t, graphqlURL)
> 	require.Nil(t, gqlResponse.Errors)
> }
> func (r *Region) delete(t *testing.T, user, role string) {
> 	getParams := &common.GraphQLParams{
> 		Headers: common.GetJWT(t, user, role, metaInfo),
> 		Query: `
> 		mutation deleteRegion($name: String) {
> 		  deleteRegion(filter:{name: { eq: $name}}) {
> 			msg
> 		  }
> 		}
> 		`,
> 		Variables: map[string]interface{}{"name": r.Name},
> 	}
> 	gqlResponse := getParams.ExecuteAsPost(t, graphqlURL)
> 	require.Nil(t, gqlResponse.Errors)
> }
> func TestOptimizedNestedAuthQuery(t *testing.T) {
> 	query := `
> 	query {
> 	  queryMovie {
> 		content
> 		 regionsAvailable {
> 		  name
> 		  global
> 		}
> 	  }
> 	}
> 	`
> 	user := "user1"
> 	role := "ADMIN"
> 	getUserParams := &common.GraphQLParams{
> 		Headers: common.GetJWT(t, user, role, metaInfo),
> 		Query:   query,
> 	}
> 	gqlResponse := getUserParams.ExecuteAsPost(t, graphqlURL)
> 	require.Nil(t, gqlResponse.Errors)
> 	beforeTouchUids := gqlResponse.Extensions["touched_uids"]
> 	beforeResult := gqlResponse.Data
> 	// Previously, Auth queries would have touched all the new `Regions`. But after the optimization
> 	// we should only touch necessary `Regions` which are assigned to some `Movie`. Hence, adding
> 	// these extra `Regions` would not increase the `touched_uids`.
> 	var regions []Region
> 	for i := 0; i < 100; i++ {
> 		r := Region{
> 			Name:   fmt.Sprintf("Test_Region_%d", i),
> 			Global: true,
> 		}
> 		r.add(t, user, role)
> 		regions = append(regions, r)
> 	}
> 	gqlResponse = getUserParams.ExecuteAsPost(t, graphqlURL)
> 	require.Nil(t, gqlResponse.Errors)
> 	afterTouchUids := gqlResponse.Extensions["touched_uids"]
> 	require.Equal(t, beforeTouchUids, afterTouchUids)
> 	require.Equal(t, beforeResult, gqlResponse.Data)
> 	// Clean up
> 	for _, region := range regions {
> 		region.delete(t, user, role)
> 	}
> }
> func (s Student) deleteByEmail(t *testing.T) {
> 	getParams := &common.GraphQLParams{
> 		Query: `
> 			mutation delStudent ($filter : StudentFilter!){
> 			  	deleteStudent (filter: $filter) {
> 					numUids
> 			  	}
> 			}
> 		`,
> 		Variables: map[string]interface{}{"filter": map[string]interface{}{
> 			"email": map[string]interface{}{"eq": s.Email},
> 		}},
> 	}
> 	gqlResponse := getParams.ExecuteAsPost(t, graphqlURL)
> 	require.Nil(t, gqlResponse.Errors)
> }
> func (s Student) add(t *testing.T) {
> 	mutation := &common.GraphQLParams{
> 		Query: `
> 		mutation addStudent($student : AddStudentInput!) {
> 			addStudent(input: [$student]) {
> 				numUids
> 			}
> 		}`,
> 		Variables: map[string]interface{}{"student": s},
> 	}
> 	result := `{"addStudent":{"numUids": 1} [...]

2020-10-23 08:59 UTC, JatinDevDG reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6779)* status: 0 of 12 files reviewed, 17 unresolved discussions (waiting on @abhimanyusinghgaur, @manishrjain, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

___
*[graphql/authorization/auth.go, line 136 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKFCW2C7MO55yDTOBdw:-MKGn04n9qjSGIjKa4VL:brpmqc3) ([raw file](https://github.com/dgraph-io/dgraph/blob/f152bad30eb1e0ad52e1c1fa6fe8a14676234f02/graphql/authorization/auth.go#L136)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

stale
</blockquote></details>

removed.
___
*[graphql/authorization/auth.go, line 145 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKFD0ET15GpK2u7k_GZ:-MKGn54QARxi0nzQ0vDB:b4ujtwm) ([raw file](https://github.com/dgraph-io/dgraph/blob/f152bad30eb1e0ad52e1c1fa6fe8a14676234f02/graphql/authorization/auth.go#L145)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

so, we are not providing support for this in the old format. One way to get users to move to the new format :)
</blockquote></details>

yeah, audiance is also not there.
___
*[graphql/e2e/auth/auth_test.go, line 128 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKFMGAiASMrqnsv38ao:-MKH0Crx4afdKHek8gT4:brpmqc3) ([raw file](https://github.com/dgraph-io/dgraph/blob/f152bad30eb1e0ad52e1c1fa6fe8a14676234f02/graphql/e2e/auth/auth_test.go#L128)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> closedByDefault bool
> ```
don't see it used here, should be removed?
</blockquote></details>

removed.
___
*[graphql/e2e/auth_ClosedByDefault/auth_test.go, line 44 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKFKAnWBSYJm7nZ9eeL:-MKH1QTPErTN_82bpkfx:bs6lhz6) ([raw file](https://github.com/dgraph-io/dgraph/blob/f152bad30eb1e0ad52e1c1fa6fe8a14676234f02/graphql/e2e/auth_ClosedByDefault/auth_test.go#L44)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> type Region struct {
> 	Id     string         `json:"id,omitempty"`
> 	Name   string         `json:"name,omitempty"`
> 	Users  []*common.User `json:"users,omitempty"`
> 	Global bool           `json:"global,omitempty"`
> }
> type Movie struct {
> 	Id               string    `json:"id,omitempty"`
> 	Content          string    `json:"content,omitempty"`
> 	Hidden           bool      `json:"hidden,omitempty"`
> 	RegionsAvailable []*Region `json:"regionsAvailable,omitempty"`
> }
> type Issue struct {
> 	Id    string       `json:"id,omitempty"`
> 	Msg   string       `json:"msg,omitempty"`
> 	Owner *common.User `json:"owner,omitempty"`
> }
> type Log struct {
> 	Id     string `json:"id,omitempty"`
> 	Logs   string `json:"logs,omitempty"`
> 	Random string `json:"random,omitempty"`
> }
> type ComplexLog struct {
> 	Id      string `json:"id,omitempty"`
> 	Logs    string `json:"logs,omitempty"`
> 	Visible bool   `json:"visible,omitempty"`
> }
> type Role struct {
> 	Id         string         `json:"id,omitempty"`
> 	Permission string         `json:"permission,omitempty"`
> 	AssignedTo []*common.User `json:"assignedTo,omitempty"`
> }
> type Ticket struct {
> 	Id         string         `json:"id,omitempty"`
> 	OnColumn   *Column        `json:"onColumn,omitempty"`
> 	Title      string         `json:"title,omitempty"`
> 	AssignedTo []*common.User `json:"assignedTo,omitempty"`
> }
> type Column struct {
> 	ColID     string    `json:"colID,omitempty"`
> 	InProject *Project  `json:"inProject,omitempty"`
> 	Name      string    `json:"name,omitempty"`
> 	Tickets   []*Ticket `json:"tickets,omitempty"`
> }
> type Project struct {
> 	ProjID  string    `json:"projID,omitempty"`
> 	Name    string    `json:"name,omitempty"`
> 	Roles   []*Role   `json:"roles,omitempty"`
> 	Columns []*Column `json:"columns,omitempty"`
> }
> type Student struct {
> 	Id    string `json:"id,omitempty"`
> 	Email string `json:"email,omitempty"`
> }
> type Task struct {
> 	Id          string            `json:"id,omitempty"`
> 	Name        string            `json:"name,omitempty"`
> 	Occurrences []*TaskOccurrence `json:"occurrences,omitempty"`
> }
> type TaskOccurrence struct {
> 	Id   string `json:"id,omitempty"`
> 	Due  string `json:"due,omitempty"`
> 	Comp string `json:"comp,omitempty"`
> }
> type TestCase struct {
> 	user            string
> 	role            string
> 	result          string
> 	name            string
> 	filter          map[string]interface{}
> 	variables       map[string]interface{}
> 	query           string
> 	closedByDefault bool
> }
> type uidResult struct {
> 	Query []struct {
> 		UID string
> 	}
> }
> type Tasks []Task
> func (tasks Tasks) add(t *testing.T) {
> 	getParams := &common.GraphQLParams{
> 		Query: `
> 		mutation AddTask($tasks : [AddTaskInput!]!) {
> 		  addTask(input: $tasks) {
> 			numUids
> 		  }
> 		}
> 		`,
> 		Variables: map[string]interface{}{"tasks": tasks},
> 	}
> 	gqlResponse := getParams.ExecuteAsPost(t, graphqlURL)
> 	require.Nil(t, gqlResponse.Errors)
> }
> func (r *Region) add(t *testing.T, user, role string) {
> 	getParams := &common.GraphQLParams{
> 		Headers: common.GetJWT(t, user, role, metaInfo),
> 		Query: `
> 		mutation addRegion($region: AddRegionInput!) {
> 		  addRegion(input: [$region]) {
> 			numUids
> 		  }
> 		}
> 		`,
> 		Variables: map[string]interface{}{"region": r},
> 	}
> 	gqlResponse := getParams.ExecuteAsPost(t, graphqlURL)
> 	require.Nil(t, gqlResponse.Errors)
> }
> func (r *Region) delete(t *testing.T, user, role string) {
> 	getParams := &common.GraphQLParams{
> 		Headers: common.GetJWT(t, user, role, metaInfo),
> 		Query: `
> 		mutation deleteRegion($name: String) {
> 		  deleteRegion(filter:{name: { eq: $name}}) {
> 			msg
> 		  }
> 		}
> 		`,
> 		Variables: map[string]interface{}{"name": r.Name},
> 	}
> 	gqlResponse := getParams.ExecuteAsPost(t, graphqlURL)
> 	require.Nil(t, gqlResponse.Errors)
> }
> func TestOptimizedNestedAuthQuery(t *testing.T) {
> 	query := `
> 	query {
> 	  queryMovie {
> 		content
> 		 regionsAvailable {
> 		  name
> 		  global
> 		}
> 	  }
> 	}
> 	`
> 	user := "user1"
> 	role := "ADMIN"
> 	getUserParams := &common.GraphQLParams{
> 		Headers: common.GetJWT(t, user, role, metaInfo),
> 		Query:   query,
> 	}
> 	gqlResponse := getUserParams.ExecuteAsPost(t, graphqlURL)
> 	require.Nil(t, gqlResponse.Errors)
> 	beforeTouchUids := gqlResponse.Extensions["touched_uids"]
> 	beforeResult := gqlResponse.Data
> 	// Previously, Auth queries would have touched all the new `Regions`. But after the optimization
> 	// we should only touch necessary `Regions` which are assigned to some `Movie`. Hence, adding
> 	// these extra `Regions` would not increase the `touched_uids`.
> 	var regions []Region
> 	for i := 0; i < 100; i++ {
> 		r := Region{
> 			Name:   fmt.Sprintf("Test_Region_%d", i),
> 			Global: true,
> 		}
> 		r.add(t, user, role)
> 		regions = append(regions, r)
> 	}
> 	gqlResponse = getUserParams.ExecuteAsPost(t, graphqlURL)
> 	require.Nil(t, gqlResponse.Errors)
> 	afterTouchUids := gqlResponse.Extensions["touched_uids"]
> 	require.Equal(t, beforeTouchUids, afterTouchUids)
> 	require.Equal(t, beforeResult, gqlResponse.Data)
> 	// Clean up
> 	for _, region := range regions {
> 		region.delete(t, user, role)
> 	}
> }
> func (s Student) deleteByEmail(t *testing.T) {
> 	getParams := &common.GraphQLParams{
> 		Query: `
> 			mutation delStudent ($filter : StudentFilter!){
> 			  	deleteStudent (filter: $filter) {
> 					numUids
> 			  	}
> 			}
> 		`,
> 		Variables: map[string]interface{}{"filter": map[string]interface{}{
> 			"email": map[string]interface{}{"eq": s.Email},
> 		}},
> 	}
> 	gqlResponse := getParams.ExecuteAsPost(t, graphqlURL)
> 	require.Nil(t, gqlResponse.Errors)
> }
> func (s Student) add(t *testing.T) {
> 	mutation := &common.GraphQLParams{
> 		Query: `
> 	 [...]

2020-10-23 10:45 UTC, abhimanyusinghgaur requested changes
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6779)* status: 0 of 10 files reviewed, 17 unresolved discussions (waiting on @abhimanyusinghgaur, @JatinDevDG, @manishrjain, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

___
*[graphql/e2e/auth_ClosedByDefault/auth_test.go, line 41 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKJyABKCOkEzxu7dVQt:-MKJyABKCOkEzxu7dVQu:b-ruq2nz) ([raw file](https://github.com/dgraph-io/dgraph/blob/2ab68fb908d663c05fce900ade7ea1bcb7db48e7/graphql/e2e/auth_ClosedByDefault/auth_test.go#L41)):*
<details><summary><i alt="summary">Quoted 20 lines of code…</i></summary>

> ```
> type TestCase struct {
> 	user            string
> 	role            string
> 	result          string
> 	name            string
> 	filter          map[string]interface{}
> 	variables       map[string]interface{}
> 	query           string
> 	closedByDefault bool
> }
> type UserSecret struct {
> 	Id      string `json:"id,omitempty"`
> 	ASecret string `json:"aSecret,omitempty"`
> 	OwnedBy string `json:"ownedBy,omitempty"`
> }
> type Todo struct {
> 	Id    string `json:"id,omitempty"`
> 	Text  string `json:"text,omitempty"`
> 	Owner string `json:"owner,omitempty"`
> }
> ```
</details>

even these we should not duplicate here. We can just use the ones from `auth/auth_test.go` wherever needed in this file. For, `Todo` just declare it in the `auth/auth_test.go` because the schema we are using is also from the same package, so I think it would be better if we kept all the related things at the same place.
___
*[graphql/e2e/auth_ClosedByDefault/auth_test.go, line 73 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKK-8WsBaOWkPFdxCZ-:-MKK-8WsBaOWkPFdxCZ0:b-587rjk) ([raw file](https://github.com/dgraph-io/dgraph/blob/2ab68fb908d663c05fce900ade7ea1bcb7db48e7/graphql/e2e/auth_ClosedByDefault/auth_test.go#L73)):*
> ```
> user:   "user1",
> ```
not required
___
*[graphql/e2e/auth_ClosedByDefault/auth_test.go, line 74 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKJzKk93PezHxCBGcp4:-MKJzKk93PezHxCBGcp5:bu5lj3h) ([raw file](https://github.com/dgraph-io/dgraph/blob/2ab68fb908d663c05fce900ade7ea1bcb7db48e7/graphql/e2e/auth_ClosedByDefault/auth_test.go#L74)):*
> ```
> result: `{"addUserSecret":{"usersecret":[{"aSecret":"secret1"}]}}`,
> ```
result should be null?
also, should be moved after variables.
___
*[graphql/e2e/auth_ClosedByDefault/auth_test.go, line 81 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKJzRsb0GzWXLKNvuZR:-MKJzRscB36QpO592hOp:bz21agx) ([raw file](https://github.com/dgraph-io/dgraph/blob/2ab68fb908d663c05fce900ade7ea1bcb7db48e7/graphql/e2e/auth_ClosedByDefault/auth_test.go#L81)):*
> ```
> result: `{"addTodo":{"Todo":[]}}`,
> ```
should be moved after variables
___
*[graphql/e2e/auth_ClosedByDefault/auth_test.go, line 107 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKJzr9W44lFSoSleDD3:-MKJzr9W44lFSoSleDD4:bj2eedm) ([raw file](https://github.com/dgraph-io/dgraph/blob/2ab68fb908d663c05fce900ade7ea1bcb7db48e7/graphql/e2e/auth_ClosedByDefault/auth_test.go#L107)):*
> ```Go
> 		require.Equal(t, len(gqlResponse.Errors), 1)
> 		require.Contains(t, gqlResponse.Errors[0].Error(),
> 			"Jwt is required when ClosedByDefault flag is true")
> ```

we should also compare the result we receive in response, to the one given in the test case.
___
*[graphql/e2e/auth_ClosedByDefault/auth_test.go, line 121 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKK-LLu6i5RDOJmLM1M:-MKK-LLu6i5RDOJmLM1N:b-t56xb7) ([raw file](https://github.com/dgraph-io/dgraph/blob/2ab68fb908d663c05fce900ade7ea1bcb7db48e7/graphql/e2e/auth_ClosedByDefault/auth_test.go#L121)):*
> ```
> 			user:   "user1",
> 			role:   "ADMIN",
> ```
not required
___
*[graphql/e2e/auth_ClosedByDefault/auth_test.go, line 131 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKK-h-m-Xv-lJmgLoVu:-MKK-h-m-Xv-lJmgLoVv:b-t56xb7) ([raw file](https://github.com/dgraph-io/dgraph/blob/2ab68fb908d663c05fce900ade7ea1bcb7db48e7/graphql/e2e/auth_ClosedByDefault/auth_test.go#L131)):*
> ```
> 			user:   "user1",
> 			role:   "ADMIN",
> ```
not required
___
*[graphql/e2e/auth_ClosedByDefault/auth_test.go, line 143 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKK-sFF9HKc_f5PAvem:-MKK-sFF9HKc_f5PAven:bj2eedm) ([raw file](https://github.com/dgraph-io/dgraph/blob/2ab68fb908d663c05fce900ade7ea1bcb7db48e7/graphql/e2e/auth_ClosedByDefault/auth_test.go#L143)):*
> ```Go
> 		gqlResponse := queryParams.ExecuteAsPost(t, graphqlURL)
> 		require.Contains(t, gqlResponse.Errors[0].Error(),
> 			"Jwt is required when ClosedByDefault flag is true")
> ```

we should also compare the result we receive in response, to the one given in the test case.
___
*[graphql/e2e/auth_ClosedByDefault/docker-compose.yml, line 1 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKK0aYx1B_UooIdhRlr:-MKK0aYx1B_UooIdhRls:bu2uz69) ([raw file](https://github.com/dgraph-io/dgraph/blob/2ab68fb908d663c05fce900ade7ea1bcb7db48e7/graphql/e2e/auth_ClosedByDefault/docker-compose.yml#L1)):*
> ```YAML
> version: "3.5"
> ```

I believe we would also not require a separate docker-compose. Just the separate go test file should be enough. We should just move that file to the `e2e/auth` package, and name that `closed_by_default_test.go`
___
*[graphql/resolve/auth_test.go, line 345 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKK1zBdCLZ-rFDsk91G:-MKK1zBdCLZ-rFDsk91H:b-40p1fx) ([raw file](https://github.com/dgraph-io/dgraph/blob/2ab68fb908d663c05fce900ade7ea1bcb7db48e7/graphql/resolve/auth_test.go#L345)):*
> ```
> ClosedByDefault
> ```
closedByDefault
___
*[graphql/resolve/auth_test.go, line 652 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKK226i80i7H4uz7wTK:-MKK226i80i7H4uz7wTL:b-40p1fx) ([raw file](https://github.com/dgraph-io/dgraph/blob/2ab68fb908d663c05fce900ade7ea1bcb7db48e7/graphql/resolve/auth_test.go#L652)):*
> ```
> ClosedByDefault
> ```
closedByDefault
___
*[graphql/resolve/auth_test.go, line 703 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKK2j76BrjTcflS93VE:-MKK2j76BrjTcflS93VF:b-40p1fx) ([raw file](https://github.com/dgraph-io/dgraph/blob/2ab68fb908d663c05fce900ade7ea1bcb7db48e7/graphql/resolve/auth_test.go#L703)):*
> ```
> ClosedByDefault
> ```
closedByDefault
___
*[graphql/resolve/auth_test.go, line 726 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKK2a0S1i_v2N6Lf7ck:-MKK2a0S1i_v2N6Lf7cl:bl2o2p8) ([raw file](https://github.com/dgraph-io/dgraph/blob/2ab68fb908d663c05fce900ade7ea1bcb7db48e7/graphql/resolve/auth_test.go#L726)):*
> ```
> if !strings.HasPrefix(tcase.Name, "Query with missing jwt token") {
> ```
It should be:
```
if !closedByDefault {
```


<!-- Sent from Reviewable.io -->

2020-10-23 11:03 UTC, abhimanyusinghgaur reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6779)* status: 0 of 10 files reviewed, 16 unresolved discussions (waiting on @abhimanyusinghgaur, @JatinDevDG, @manishrjain, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

___
*[graphql/e2e/auth_ClosedByDefault/docker-compose.yml, line 1 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKK0aYx1B_UooIdhRlr:-MKK744vDpSJPuS0yIRa:b-u3cjne) ([raw file](https://github.com/dgraph-io/dgraph/blob/2ab68fb908d663c05fce900ade7ea1bcb7db48e7/graphql/e2e/auth_ClosedByDefault/docker-compose.yml#L1)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

I believe we would also not require a separate docker-compose. Just the separate go test file should be enough. We should just move that file to the `e2e/auth` package, and name that `closed_by_default_test.go`
</blockquote></details>

sorry, misunderstood this.


<!-- Sent from Reviewable.io -->

2020-10-23 12:08 UTC, JatinDevDG reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6779)* status: 0 of 11 files reviewed, 16 unresolved discussions (waiting on @abhimanyusinghgaur, @manishrjain, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

___
*[graphql/e2e/auth_ClosedByDefault/docker-compose.yml, line 1 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKK0aYx1B_UooIdhRlr:-MKKEPZ34KNu7G3zVLF6:b2aesx1) ([raw file](https://github.com/dgraph-io/dgraph/blob/2ab68fb908d663c05fce900ade7ea1bcb7db48e7/graphql/e2e/auth_ClosedByDefault/docker-compose.yml#L1)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

sorry, misunderstood this.
</blockquote></details>

no problem. i retained new directory for tests.
___
*[graphql/resolve/auth_test.go, line 345 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKK1zBdCLZ-rFDsk91G:-MKKFBIb3Z-GqligQHB1:b-b5c35t) ([raw file](https://github.com/dgraph-io/dgraph/blob/2ab68fb908d663c05fce900ade7ea1bcb7db48e7/graphql/resolve/auth_test.go#L345)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> ClosedByDefault
> ```
closedByDefault
</blockquote></details>

changed.
___
*[graphql/resolve/auth_test.go, line 652 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKK226i80i7H4uz7wTK:-MKKFHdAEjW3c7FQ6ys-:b-b5c35t) ([raw file](https://github.com/dgraph-io/dgraph/blob/2ab68fb908d663c05fce900ade7ea1bcb7db48e7/graphql/resolve/auth_test.go#L652)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> ClosedByDefault
> ```
closedByDefault
</blockquote></details>

changed.
___
*[graphql/resolve/auth_test.go, line 703 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKK2j76BrjTcflS93VE:-MKKFJya0MXVP8Gbf70E:bdfhyxl) ([raw file](https://github.com/dgraph-io/dgraph/blob/2ab68fb908d663c05fce900ade7ea1bcb7db48e7/graphql/resolve/auth_test.go#L703)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> ClosedByDefault
> ```
closedByDefault
</blockquote></details>

removed, don't need.
___
*[graphql/resolve/auth_test.go, line 726 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKK2a0S1i_v2N6Lf7ck:-MKKFXcg9O1PuaKFfH6g:b-q2gd1v) ([raw file](https://github.com/dgraph-io/dgraph/blob/2ab68fb908d663c05fce900ade7ea1bcb7db48e7/graphql/resolve/auth_test.go#L726)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> if !strings.HasPrefix(tcase.Name, "Query with missing jwt token") {
> ```
It should be:
```
if !closedByDefault {
```
</blockquote></details>

no, actually there are some old tests that require this.
___
*[graphql/e2e/auth_ClosedByDefault/auth_test.go, line 41 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKJyABKCOkEzxu7dVQt:-MKKLh6y2Z-E-pGPIYGz:b-q1a9mh) ([raw file](https://github.com/dgraph-io/dgraph/blob/2ab68fb908d663c05fce900ade7ea1bcb7db48e7/graphql/e2e/auth_ClosedByDefault/auth_test.go#L41)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> type TestCase struct {
> 	user            string
> 	role            string
> 	result          string
> 	name            string
> 	filter          map[string]interface{}
> 	variables       map[string]interface{}
> 	query           string
> 	closedByDefault bool
> }
> type UserSecret struct {
> 	Id      string `json:"id,omitempty"`
> 	ASecret string `json:"aSecret,omitempty"`
> 	OwnedBy string `json:"ownedBy,omitempty"`
> }
> type Todo struct {
> 	Id    string `json:"id,omitempty"`
> 	Text  string `json:"text,omitempty"`
> 	Owner string `json:"owner,omitempty"`
> }
> ```
even these we should not duplicate here. We can just use the ones from `auth/auth_test.go` wherever needed in this file. For, `Todo` just declare it in the `auth/auth_test.go` because the schema we are using is also from the same package, so I think it would be better if we kept all the related things at the same place.
</blockquote></details>

moved Todo and usersecret  to common.go and retained TestCase
___
*[graphql/e2e/auth_ClosedByDefault/auth_test.go, line 73 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKK-8WsBaOWkPFdxCZ-:-MKKBTV-BfsE6D67vXjz:brpmqc3) ([raw file](https://github.com/dgraph-io/dgraph/blob/2ab68fb908d663c05fce900ade7ea1bcb7db48e7/graphql/e2e/auth_ClosedByDefault/auth_test.go#L73)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> user:   "user1",
> ```
not required
</blockquote></details>

removed.
___
*[graphql/e2e/auth_ClosedByDefault/auth_test.go, line 74 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKJzKk93PezHxCBGcp4:-MKKBV7xDveLOfPLKH7i:b-aodbiq) ([raw file](https://github.com/dgraph-io/dgraph/blob/2ab68fb908d663c05fce900ade7ea1bcb7db48e7/graphql/e2e/auth_ClosedByDefault/auth_test.go#L74)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> result: `{"addUserSecret":{"usersecret":[{"aSecret":"secret1"}]}}`,
> ```
result should be null?
also, should be moved after variables.
</blockquote></details>

yeah,changed.
___
*[graphql/e2e/auth_ClosedByDefault/auth_test.go, line 81 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKJzRsb0GzWXLKNvuZR:-MKKBc0F-MyZKNtx3WdF:b-b5c35t) ([raw file](https://github.com/dgraph-io/dgraph/blob/2ab68fb908d663c05fce900ade7ea1bcb7db48e7/graphql/e2e/auth_ClosedByDefault/auth_test.go#L81)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> result: `{"addTodo":{"Todo":[]}}`,
> ```
should be moved after variables
</blockquote></details>

changed.
___
*[graphql/e2e/auth_ClosedByDefault/auth_test.go, line 107 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKJzr9W44lFSoSleDD3:-MKKEEpt15EP5MV3c6DF:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/2ab68fb908d663c05fce900ade7ea1bcb7db48e7/graphql/e2e/auth_ClosedByDefault/auth_test.go#L107)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

we should also compare the result we receive in response, to the one given in the test case.
</blockquote></details>

done.
___
*[graphql/e2e/auth_ClosedByDefault/auth_test.go, line 121 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKK-LLu6i5RDOJmLM1M:-MKKEJAeBo7MjuoegDFJ:brpmqc3) ([raw file](https://github.com/dgraph-io/dgraph/blob/2ab68fb908d663c05fce900ade7ea1bcb7db48e7/graphql/e2e/auth_ClosedByDefault/auth_test.go#L121)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 			user:   "user1",
> 			role:   "ADMIN",
> ```
not required
</blockquote></details>

removed.
___
*[graphql/e2e/auth_ClosedByDefault/auth_test.go, line 131 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKK-h-m-Xv-lJmgLoVu:-MKKEL4nBSAHa5JH5nXr:brpmqc3) ([raw file](https://github.com/dgraph-io/dgraph/blob/2ab68fb908d663c05fce900ade7ea1bcb7db48e7/graphql/e2e/auth_ClosedByDefault/auth_test.go#L131)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 			user:   "user1",
> 			role:   "ADMIN",
> ```
not required
</blockquote></details>

removed.
___
*[graphql/e2e/auth_ClosedByDefault/auth_test.go, line 143 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKK-sFF9HKc_f5PAvem:-MKKEN-j1-AZh0JIJ0rM:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/2ab68fb908d663c05fce900ade7ea1bcb7db48e7/graphql/e2e/auth_ClosedByDefault/auth_test.go#L143)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

we should also compare the result we receive in re [...]

2020-10-23 12:18 UTC, abhimanyusinghgaur approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 11 files at r1, 5 of 10 files at r2, 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-:-MKKOIdl-H1SQgTC2xNE:bnfp4nl)* status: 10 of 11 files reviewed, all discussions resolved (waiting on @manishrjain, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

___
*[graphql/resolve/auth_test.go, line 726 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKK2a0S1i_v2N6Lf7ck:-MKKNmS7ClkeDYQ5FOAm:b-h7b5pu) ([raw file](https://github.com/dgraph-io/dgraph/blob/2ab68fb908d663c05fce900ade7ea1bcb7db48e7/graphql/resolve/auth_test.go#L726)):*
<details><summary><i>Previously, JatinDevDG (Jatin Dev) wrote…</i></summary><blockquote>

no, actually there are some old tests that require this.
</blockquote></details>

but for the previous diff, it shows that `ctx` always contained claims, so seems only the new tests require this.


<!-- Sent from Reviewable.io -->

2020-10-27 08:29 UTC, pawanrawal requested changes
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6779)* status: 9 of 11 files reviewed, 12 unresolved discussions (waiting on @abhimanyusinghgaur, @JatinDevDG, @manishrjain, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

___
*[graphql/authorization/auth.go, line 316 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKd6WGj8dY0WygUjz08:-MKd6WGj8dY0WygUjz09:b9h20h0) ([raw file](https://github.com/dgraph-io/dgraph/blob/7be00a80725b0cd0d5d04fd568d6a4e3da979b1b/graphql/authorization/auth.go#L316)):*
> ```Go
> 	if !ok {
> 		if authMeta.ClosedByDefault {
> 			return &CustomClaims{}, fmt.Errorf("Jwt is required when ClosedByDefault flag is true")
> ```

Change error to the following, no need to mention anything about `ClosedByDefault`.
```
A valid JWT is required but was not provided.
```
___
*[graphql/e2e/auth/schema.graphql, line 588 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKd7LU5BqPzigAQbcCq:-MKd7LU5BqPzigAQbcCr:b-rkz5cu) ([raw file](https://github.com/dgraph-io/dgraph/blob/7be00a80725b0cd0d5d04fd568d6a4e3da979b1b/graphql/e2e/auth/schema.graphql#L588)):*
> ```GraphQL
> }
> 
> type Todo{
> ```

Space before {
```
type Todo {
```
___
*[graphql/e2e/auth/schema.graphql, line 589 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKd80y51zwc1YmL6i3a:-MKd80y62K1l9bh9OJCA:b-c1g2n1) ([raw file](https://github.com/dgraph-io/dgraph/blob/7be00a80725b0cd0d5d04fd568d6a4e3da979b1b/graphql/e2e/auth/schema.graphql#L589)):*
> ```GraphQL
> 
> type Todo{
>     id:ID
> ```

```
id: ID
```

please take care of formatting
___
*[graphql/resolve/auth_ClosedByDefault_add_test.yaml, line 1 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKd8MRJ7bojuML2O1Mm:-MKd8MRJ7bojuML2O1Mn:b-63yxso) ([raw file](https://github.com/dgraph-io/dgraph/blob/7be00a80725b0cd0d5d04fd568d6a4e3da979b1b/graphql/resolve/auth_ClosedByDefault_add_test.yaml#L1)):*
> ```YAML
> - name: "Query with missing jwt token - Type with Auth"
> ```

the filename should be like below. Please don't mix cases while naming files
```
auth_closed_by_default_...
```
___
*[graphql/resolve/auth_ClosedByDefault_add_test.yaml, line 27 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKd8XVoCdgiOA5VTcL6:-MKd8XVoCdgiOA5VTcL7:bbbfjz3) ([raw file](https://github.com/dgraph-io/dgraph/blob/7be00a80725b0cd0d5d04fd568d6a4e3da979b1b/graphql/resolve/auth_ClosedByDefault_add_test.yaml#L27)):*
> ```YAML
> - name: "Query with missing jwt token - Type without Auth"
>   gqlquery: |
>     mutation addTodo($todo: AddTodoInput!) {
> ```

add some update and delete tests as well?
___
*[graphql/resolve/auth_test.go, line 387 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKd9qIwDFuwBfJhjkvE:-MKd9qIx1M7VqUXXHo62:b-dxw5ga) ([raw file](https://github.com/dgraph-io/dgraph/blob/7be00a80725b0cd0d5d04fd568d6a4e3da979b1b/graphql/resolve/auth_test.go#L387)):*
> ```Go
> 
> 			if tcase.Error != nil {
> 				require.Equal(t, err.Error(), tcase.Error.Error())
> ```

Also check 

```
require.NotNil(t, err)
```
before comparing error values
___
*[graphql/resolve/auth_test.go, line 726 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKdA5FA3iKsvksCCxng:-MKdA5FA3iKsvksCCxnh:b-s6qgvy) ([raw file](https://github.com/dgraph-io/dgraph/blob/7be00a80725b0cd0d5d04fd568d6a4e3da979b1b/graphql/resolve/auth_test.go#L726)):*
> ```Go
> 
> 	ctx := context.Background()
> 	if !strings.HasPrefix(tcase.Name, "Query with missing jwt token") {
> ```

Don't like all this special behavior stuff where we decide the behavior of a test based on the value of a test case. Why are we doing this?
___
*[graphql/resolve/auth_test.go, line 826 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKd98TWEFXZjXkNQ8g0:-MKd98TWEFXZjXkNQ8g1:b-y8lhyn) ([raw file](https://github.com/dgraph-io/dgraph/blob/7be00a80725b0cd0d5d04fd568d6a4e3da979b1b/graphql/resolve/auth_test.go#L826)):*
> ```Go
> 
> 	t.Run("Query Rewriting "+algo, func(t *testing.T) {
> 		queryRewriting(t, strSchema, metaInfo, true)
> ```

instead of passing this last flag, just read the file and pass the contents of the file to this function.

closedByDefault is already part of the schema so no need to pass it again. You are anyway using it to decide the name of the file, so better read the file and pass the contents of the file to this and `mutationAdd` function below.
___
*[testutil/graphql.go, line 211 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKd73y8C66GpJw2CPkb:-MKd73y94cm80Kh4WZ9o:b-ezj8u6) ([raw file](https://github.com/dgraph-io/dgraph/blob/7be00a80725b0cd0d5d04fd568d6a4e3da979b1b/testutil/graphql.go#L211)):*
> ```Go
> 	if algo == "HS256" {
> 		if closedByDefault {
> 			authInfo = `# Dgraph.Authorization {"VerificationKey":"secretkey","Header":"X-Test-Auth","Namespace":"https://xyz.io/jwt/claims","Algo":"HS256","Audience":["aud1","63do0q16n6ebjgkumu05kkeian","aud5"],"ClosedByDefault":true}`
> ```

Why copy the whole thing twice. Just use `fmt.Sprintf(authInfo, closedByDefault)` to substitute the appropriate value. Same below.
___
*[graphql/e2e/auth_ClosedByDefault/auth_ClosedByDefault_test.go, line 1 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKd56EH8vq0TgONQYG7:-MKd56EH8vq0TgONQYG8:b-hdt9st) ([raw file](https://github.com/dgraph-io/dgraph/blob/7be00a80725b0cd0d5d04fd568d6a4e3da979b1b/graphql/e2e/auth_ClosedByDefault/auth_ClosedByDefault_test.go#L1)):*
> ```Go
> /*
> ```

rename file and folder to

```
auth_closed_by_default/auth_closed_by_default_test.go
```
___
*[graphql/e2e/auth_ClosedByDefault/auth_ClosedByDefault_test.go, line 90 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKd8AeE1XAmamfF3oIN:-MKd8AeE1XAmamfF3oIO:b-wpy324) ([raw file](https://github.com/dgraph-io/dgraph/blob/7be00a80725b0cd0d5d04fd568d6a4e3da979b1b/graphql/e2e/auth_ClosedByDefault/auth_ClosedByDefault_test.go#L90)):*
> ```Go
> }
> 
> func TestAuthRulesQueryWithClosedByDefaultAFlag(t *testing.T) {
> ```

```
...DefaultFlag
```
___
*[graphql/e2e/auth_ClosedByDefault/auth_ClosedByDefault_test.go, line 125 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKd7Ut0-2RWUK6pjP5p:-MKd7Ut0-2RWUK6pjP5q:b-wb8g73) ([raw file](https://github.com/dgraph-io/dgraph/blob/7be00a80725b0cd0d5d04fd568d6a4e3da979b1b/graphql/e2e/auth_ClosedByDefault/auth_ClosedByDefault_test.go#L125)):*
> ```Go
> 
> func TestMain(m *testing.M) {
> 	schemaFile := "../auth/schema.graphql"
> ```

I am seeing all this code across multiple files. Could you have this inside `common` and call it from different places.

The function can be called `BootstrapAuthData(closedByDefault bool)``


<!-- Sent from Reviewable.io -->

2020-10-28 11:03 UTC, JatinDevDG reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6779)* status: 1 of 14 files reviewed, 12 unresolved discussions (waiting on @abhimanyusinghgaur, @manishrjain, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

___
*[graphql/authorization/auth.go, line 316 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKd6WGj8dY0WygUjz08:-MKdClIJDKnv-5n3ZwUx:b-b5c35t) ([raw file](https://github.com/dgraph-io/dgraph/blob/7be00a80725b0cd0d5d04fd568d6a4e3da979b1b/graphql/authorization/auth.go#L316)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Change error to the following, no need to mention anything about `ClosedByDefault`.
```
A valid JWT is required but was not provided.
```
</blockquote></details>

changed.
___
*[graphql/e2e/auth/schema.graphql, line 588 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKd7LU5BqPzigAQbcCq:-MKdDULc-2ZrcwKd_Vol:b-n9tkhd) ([raw file](https://github.com/dgraph-io/dgraph/blob/7be00a80725b0cd0d5d04fd568d6a4e3da979b1b/graphql/e2e/auth/schema.graphql#L588)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Space before {
```
type Todo {
```
</blockquote></details>

changed
___
*[graphql/e2e/auth/schema.graphql, line 589 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKd80y51zwc1YmL6i3a:-MKdDVih4rFbysQBbfA2:b-b5c35t) ([raw file](https://github.com/dgraph-io/dgraph/blob/7be00a80725b0cd0d5d04fd568d6a4e3da979b1b/graphql/e2e/auth/schema.graphql#L589)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

```
id: ID
```

please take care of formatting
</blockquote></details>

changed.
___
*[graphql/resolve/auth_test.go, line 726 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKK2a0S1i_v2N6Lf7ck:-MKidAkxB0yGfgenKt6G:bw7u2h2) ([raw file](https://github.com/dgraph-io/dgraph/blob/2ab68fb908d663c05fce900ade7ea1bcb7db48e7/graphql/resolve/auth_test.go#L726)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

but for the previous diff, it shows that `ctx` always contained claims, so seems only the new tests require this.
</blockquote></details>

ohhh, yeah changed this. I thought it's the one inside queryRewriting.
___
*[graphql/resolve/auth_test.go, line 387 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKd9qIwDFuwBfJhjkvE:-MKinCP31MaAYmVjrto4:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/7be00a80725b0cd0d5d04fd568d6a4e3da979b1b/graphql/resolve/auth_test.go#L387)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Also check 

```
require.NotNil(t, err)
```
before comparing error values
</blockquote></details>

done.
___
*[graphql/resolve/auth_test.go, line 726 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKdA5FA3iKsvksCCxng:-MKidTTF4ALxg1EN90lk:b-6na7er) ([raw file](https://github.com/dgraph-io/dgraph/blob/7be00a80725b0cd0d5d04fd568d6a4e3da979b1b/graphql/resolve/auth_test.go#L726)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Don't like all this special behavior stuff where we decide the behavior of a test based on the value of a test case. Why are we doing this?
</blockquote></details>

changed this. Actually we don't generate JWT for cases for which closedByDefault flag is false. 
___
*[graphql/resolve/auth_test.go, line 826 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKd98TWEFXZjXkNQ8g0:-MKidkIo1bCc0_3DTiit:b-b5c35t) ([raw file](https://github.com/dgraph-io/dgraph/blob/7be00a80725b0cd0d5d04fd568d6a4e3da979b1b/graphql/resolve/auth_test.go#L826)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

instead of passing this last flag, just read the file and pass the contents of the file to this function.

closedByDefault is already part of the schema so no need to pass it again. You are anyway using it to decide the name of the file, so better read the file and pass the contents of the file to this and `mutationAdd` function below.
</blockquote></details>

changed.
___
*[testutil/graphql.go, line 211 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKd73y8C66GpJw2CPkb:-MKimgZ2ByuV4mQ1BeTo:b-1ghcq) ([raw file](https://github.com/dgraph-io/dgraph/blob/7be00a80725b0cd0d5d04fd568d6a4e3da979b1b/testutil/graphql.go#L211)):*
> ```
> authInfo = `# Dgraph.Authorization {"VerificationKey":"secretkey","Header":"X-Test-Auth","Namespace":"https://xyz.io/jwt/claims","Algo":"HS256","Audience":["aud1","63do0q16n6ebjgkumu05kkeian","aud5"],"ClosedByDefault":true}`
> ```
changed.
___
*[graphql/e2e/auth_ClosedByDefault/auth_ClosedByDefault_test.go, line 1 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKd56EH8vq0TgONQYG7:-MKdDyIR9kgj-JrqkcIb:b-b5c35t) ([raw file](https://github.com/dgraph-io/dgraph/blob/7be00a80725b0cd0d5d04fd568d6a4e3da979b1b/graphql/e2e/auth_ClosedByDefault/auth_ClosedByDefault_test.go#L1)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

rename file and folder to

```
auth_closed_by_default/auth_closed_by_default_test.go
```
</blockquote></details>

changed.
___
*[graphql/e2e/auth_ClosedByDefault/auth_ClosedByDefault_test.go, line 90 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKd8AeE1XAmamfF3oIN:-MKdE9VVA1ISONE105WW:b-b5c35t) ([raw file](https://github.com/dgraph-io/dgraph/blob/7be00a80725b0cd0d5d04fd568d6a4e3da979b1b/graphql/e2e/auth_ClosedByDefault/auth_ClosedByDefault_test.go#L90)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

```
...DefaultFlag
```
</blockquote></details>

changed.
___
*[graphql/e2e/auth_ClosedByDefault/auth_ClosedByDefault_test.go, line 125 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKd7Ut0-2RWUK6pjP5p:-MKdZW2m4zG90VLe96p6:bjrtten) ([raw file](https://github.com/dgraph-io/dgraph/blob/7be00a80725b0cd0d5d04fd568d6a4e3da979b1b/graphql/e2e/auth_ClosedByDefault/auth_ClosedByDefault_test.go#L125)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

I am seeing all this code across multiple files. Could you have this inside `common` and call it from different places.

The function can be called `BootstrapAuthData(closedByDefault bool)``
</blockquote></details>

This code only used inside auth/auth_test.go and auth_Closed_by_default_test.go . Moved starting part of the code inside common.go. The other part is a little difficult to move because it involves to set metainfo ,algo in different ways.
___
*[graphql/resolve/auth_ClosedByDefault_add_test.yaml, line 1 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKd8MRJ7bojuML2O1Mm:-MKdbF8W0metFxtrZLv9:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/7be00a80725b0cd0d5d04fd568d6a4e3da979b1b/graphql/resolve/auth_ClosedByDefault_add_test.yaml#L1)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

the filename should be like below. Please don't mix cases while naming files
```
auth_closed_by_default_...
```
</blockquote></details>

done.
___
*[graphql/resolve/auth_ClosedByDefault_add_test.yaml, line 27 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKd8XVoCdgiOA5VTcL6:-MKinEtm1xtHNLiSCA3s:b-3e7g0x) ([raw file](https://github.com/dgraph-io/dgraph/blob/7be00a80725b0cd0d5d04fd568d6a4e3da979b1b/graphql/resolve/auth_ClosedByDefault_add_test.yaml#L27)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

add some update and delete tests as well?
</blockquote></details>

added e2e and unit tests for update and delete.


<!-- Sent from Reviewable.io -->

2020-10-28 11:43 UTC, pawanrawal approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>  is there a doc ticket corresponding to this change? Otherwise please create one, link this issue and assign to Aaron with priority highest.

> Reviewed 10 of 13 files at r5.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-:-MKj01N455wcfauynnYT:b8ax7hw)* status: 11 of 14 files reviewed, 3 unresolved discussions (waiting on @abhimanyusinghgaur, @JatinDevDG, @manishrjain, @MichaelJCompton, and @vvbalaji-dgraph)

___
*[graphql/resolve/auth_test.go, line 181 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKj-LLiC9vWU7HcAH3B:-MKj-LLiC9vWU7HcAH3C:bntwm6) ([raw file](https://github.com/dgraph-io/dgraph/blob/9f60182a65c4b87b5130ed2903e1639095787c06/graphql/resolve/auth_test.go#L181)):*
> ```Go
> 	}
> 	require.Equal(t, authVar, result)
> 	//reset auth meta, so that it won't effect other tests
> ```

`// reset` 
Space after `//`
___
*[graphql/resolve/auth_test.go, line 845 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKj-l22ArohJYjgcrR1:-MKj-l22ArohJYjgcrR2:b-i9vrx7) ([raw file](https://github.com/dgraph-io/dgraph/blob/9f60182a65c4b87b5130ed2903e1639095787c06/graphql/resolve/auth_test.go#L845)):*
> ```Go
> 	var b []byte
> 	var err error
> 	b, err = ioutil.ReadFile(file)
> ```

b, err can be defined inline
```
b, err := 
```
___
*[graphql/e2e/auth_ClosedByDefault/auth_ClosedByDefault_test.go, line 23 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6779#-MKizhu368h0rz4uABT3:-MKizhu368h0rz4uABT4:b-9dxuf3) ([raw file](https://github.com/dgraph-io/dgraph/blob/7be00a80725b0cd0d5d04fd568d6a4e3da979b1b/graphql/e2e/auth_ClosedByDefault/auth_ClosedByDefault_test.go#L23)):*
> ```Go
> 	"github.com/dgraph-io/dgraph/graphql/e2e/common"
> 	"github.com/dgraph-io/dgraph/testutil"
> 	"github.com/pkg/errors"
> ```

rename file to `auth_closed...` , C shouldn't be capital


<!-- Sent from Reviewable.io -->

2020-10-29 19:58 UTC, merged