docs (new): Add Geolocation feature to GraphQL docs
dgraph-io/dgraph pull request #6782
Opened 2020-10-22 14:50 UTC by bucanero

Add Geolocation reference to GraphQL

This PR adds a new article for the Geolocation feature in GraphQL

Fixes GRAPHQL-726

2020-10-23 00:03 UTC, aaroncarey reviewed
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6782)* status: all files reviewed, 5 unresolved discussions (waiting on @bucanero, @danielmai, and @MichaelJCompton)

___
*[wiki/content/graphql/queries/geolocation.md, line 16 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6782#-MKHjPek3CpuTAJ_nPw9:-MKHjPelDGbjKjHk-cyb:bwjunnb) ([raw file](https://github.com/dgraph-io/dgraph/blob/fc488f920039c507e1c089691eee63c206dcf1e7/wiki/content/graphql/queries/geolocation.md#L16)):*
> ```
> since
> ```
Because
___
*[wiki/content/graphql/queries/geolocation.md, line 171 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6782#-MKHkKGQE0gp-bTuySq0:-MKHkKGQE0gp-bTuySq1:b-7dsvem) ([raw file](https://github.com/dgraph-io/dgraph/blob/fc488f920039c507e1c089691eee63c206dcf1e7/wiki/content/graphql/queries/geolocation.md#L171)):*
> ```
> the `within` query allows searching 
> ```
The `within` query lets you search

(avoids passive voice)
___
*[wiki/content/graphql/queries/geolocation.md, line 171 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6782#-MKHkcZG8DNQ4sobFknt:-MKHkcZG8DNQ4sobFknu:brmshpj) ([raw file](https://github.com/dgraph-io/dgraph/blob/fc488f920039c507e1c089691eee63c206dcf1e7/wiki/content/graphql/queries/geolocation.md#L171)):*
> ```
> hence
> ```
so

(as much as I love "hence", "so" is more modern and widely understood :) )
___
*[wiki/content/graphql/queries/geolocation.md, line 202 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6782#-MKHkp_34iUOWREmwuLB:-MKHkp_34iUOWREmwuLC:ber65x9) ([raw file](https://github.com/dgraph-io/dgraph/blob/fc488f920039c507e1c089691eee63c206dcf1e7/wiki/content/graphql/queries/geolocation.md#L202)):*
> ```
> the 
> ```
The
___
*[wiki/content/graphql/queries/geolocation.md, line 235 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6782#-MKHkshP4l9nMqI0T38E:-MKHkshP4l9nMqI0T38F:ber65x9) ([raw file](https://github.com/dgraph-io/dgraph/blob/fc488f920039c507e1c089691eee63c206dcf1e7/wiki/content/graphql/queries/geolocation.md#L235)):*
> ```
> the 
> ```
The


<!-- Sent from Reviewable.io -->

2020-10-23 00:06 UTC, aaroncarey commented
This looks good to me from the perspective of a reader, I had a few "editor-type" suggestions.

2020-10-23 14:06 UTC, bucanero reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6782)* status: all files reviewed, 5 unresolved discussions (waiting on @aaroncarey, @danielmai, and @MichaelJCompton)

___
*[wiki/content/graphql/queries/geolocation.md, line 16 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6782#-MKHjPek3CpuTAJ_nPw9:-MKKkXAD3E0S9SDgm9_p:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/fc488f920039c507e1c089691eee63c206dcf1e7/wiki/content/graphql/queries/geolocation.md#L16)):*
<details><summary><i>Previously, aaroncarey (Aaron Carey) wrote…</i></summary><blockquote>

> ```
> since
> ```
Because
</blockquote></details>

Done.
___
*[wiki/content/graphql/queries/geolocation.md, line 171 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6782#-MKHkKGQE0gp-bTuySq0:-MKKknpS2mowg0h0eHUs:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/fc488f920039c507e1c089691eee63c206dcf1e7/wiki/content/graphql/queries/geolocation.md#L171)):*
<details><summary><i>Previously, aaroncarey (Aaron Carey) wrote…</i></summary><blockquote>

> ```
> the `within` query allows searching 
> ```
The `within` query lets you search

(avoids passive voice)
</blockquote></details>

Done.
___
*[wiki/content/graphql/queries/geolocation.md, line 171 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6782#-MKHkcZG8DNQ4sobFknt:-MKKl9Pj69eB5bOc1vaD:b-f8mezq) ([raw file](https://github.com/dgraph-io/dgraph/blob/fc488f920039c507e1c089691eee63c206dcf1e7/wiki/content/graphql/queries/geolocation.md#L171)):*
<details><summary><i>Previously, aaroncarey (Aaron Carey) wrote…</i></summary><blockquote>

> ```
> hence
> ```
so

(as much as I love "hence", "so" is more modern and widely understood :) )
</blockquote></details>

Done.

Actually I felt that "so" was a bit repetitive, and couldn't decide between "thus", "therefore" and "hence". Nevertheless, I agree that "so" is probably the most simple and easiest option for the reader.
___
*[wiki/content/graphql/queries/geolocation.md, line 202 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6782#-MKHkp_34iUOWREmwuLB:-MKKl3wa65vhU82lEjyo:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/fc488f920039c507e1c089691eee63c206dcf1e7/wiki/content/graphql/queries/geolocation.md#L202)):*
<details><summary><i>Previously, aaroncarey (Aaron Carey) wrote…</i></summary><blockquote>

> ```
> the 
> ```
The
</blockquote></details>

Done.
___
*[wiki/content/graphql/queries/geolocation.md, line 235 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6782#-MKHkshP4l9nMqI0T38E:-MKKl4wP4Zq8bwN6GPnH:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/fc488f920039c507e1c089691eee63c206dcf1e7/wiki/content/graphql/queries/geolocation.md#L235)):*
<details><summary><i>Previously, aaroncarey (Aaron Carey) wrote…</i></summary><blockquote>

> ```
> the 
> ```
The
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-23 18:12 UTC, aaroncarey approved these changes
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6782)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @aaroncarey, @bucanero, @danielmai, and @MichaelJCompton)

___
*[wiki/content/graphql/queries/geolocation.md, line 171 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6782#-MKHkcZG8DNQ4sobFknt:-MKLe-xC9IYoX9teK9GX:b-azxa8b) ([raw file](https://github.com/dgraph-io/dgraph/blob/fc488f920039c507e1c089691eee63c206dcf1e7/wiki/content/graphql/queries/geolocation.md#L171)):*
<details><summary><i>Previously, bucanero (Damián Parrino) wrote…</i></summary><blockquote>

Done.

Actually I felt that "so" was a bit repetitive, and couldn't decide between "thus", "therefore" and "hence". Nevertheless, I agree that "so" is probably the most simple and easiest option for the reader.
</blockquote></details>

Gotcha! I sometimes use "therefore" to avoid too many "sos" :)


<!-- Sent from Reviewable.io -->

2020-10-26 07:18 UTC, abhimanyusinghgaur requested changes
I have put some more comments. That will be all the feedback from me. After that, we should have @michaeljcompton review it once.

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6782#-:-MKYkwPLBNRltyNLYkLt:bb2lnbq)* status: 0 of 5 files reviewed, 21 unresolved discussions (waiting on @aaroncarey, @abhimanyusinghgaur, @bucanero, @danielmai, and @MichaelJCompton)

___
*[wiki/content/graphql/queries/geolocation.md, line 1 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6782#-MKYhXL31mBsOBMTF3We:-MKYhXL31mBsOBMTF3Wf:b-2n2ggp) ([raw file](https://github.com/dgraph-io/dgraph/blob/c9c91604d0ef4658d51e68d786f8d9013a49576c/wiki/content/graphql/queries/geolocation.md#L1)):*
> ```Markdown
> +++
> ```

I think now we won't need a separate page for Geolocation in `Queries` or `Mutations` section because we are already explaining the necessary bits for it in the `Schema` section. So, this page can be removed now.
___
*[wiki/content/graphql/schema/dgraph-schema.md, line 91 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6782#-MKYSg_dEoT4__nlWf4r:-MKYSg_dEoT4__nlWf4s:b20w1rk) ([raw file](https://github.com/dgraph-io/dgraph/blob/c9c91604d0ef4658d51e68d786f8d9013a49576c/wiki/content/graphql/schema/dgraph-schema.md#L91)):*
<details><summary><i alt="summary">Quoted 84 lines of code…</i></summary>

> ```
> scalar DateTime
> enum DgraphIndex {
> 	int
> 	float
> 	bool
> 	hash
> 	exact
> 	term
> 	fulltext
> 	trigram
> 	regexp
> 	year
> 	month
> 	day
> 	hour
> }
> input AuthRule {
> 	and: [AuthRule]
> 	or: [AuthRule]
> 	not: AuthRule
> 	rule: String
> }
> enum HTTPMethod {
> 	GET
> 	POST
> 	PUT
> 	PATCH
> 	DELETE
> }
> enum Mode {
> 	BATCH
> 	SINGLE
> }
> input CustomHTTP {
> 	url: String!
> 	method: HTTPMethod!
> 	body: String
> 	graphql: String
> 	mode: Mode
> 	forwardHeaders: [String!]
> 	secretHeaders: [String!]
> 	introspectionHeaders: [String!]
> 	skipIntrospection: Boolean
> }
> input NearFilter {
>     Distance: Float!
>     Coordinate: Point!
> }
> input WithinFilter {
>     polygon: Polygon!
> }
> input ContainsFilter {
>     # The user should be giving one of these.
>     point: Point
>     polygon: Polygon
> }
> input IntersectsFilter {
>     # The user should be giving one of these.
>     polygon: Polygon
>     mulitPolygon: MultiPolygon
> }
> input PointGeoFilter {
>     near: NearFilter
>     within: WithinFilter
> }
> input PolygonGeoFilter {
>     near: NearFilter
>     within: WithinFilter
>     contains: ContainsFilter
>     intersects: IntersectsFilter
> }
> directive @hasInverse(field: String!) on FIELD_DEFINITION
> directive @search(by: [DgraphIndex!]) on FIELD_DEFINITION
> directive @dgraph(type: String, pred: String) on OBJECT | INTERFACE | FIELD_DEFINITION
> directive @id on FIELD_DEFINITION
> directive @withSubscription on OBJECT | INTERFACE
> directive @secret(field: String!, pred: String) on OBJECT | INTERFACE
> directive @auth(
> 	query: AuthRule,
> 	add: AuthRule,
> 	update: AuthRule,
> 	delete: AuthRule) on OBJECT
> directive @custom(http: CustomHTTP) on FIELD_DEFINITION
> directive @remote on OBJECT | INTERFACE
> ```
</details>

This whole thing has got outdated over time. It can now be replaced with [`schemaExtras` constant in gqlschema.go file](https://github.com/dgraph-io/dgraph/blob/master/graphql/schema/gqlschema.go#L83-L314).
___
*[wiki/content/graphql/schema/reserved.md, line 28 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6782#-MKYCG896aSi8BncREZ4:-MKYCG896aSi8BncREZ5:b8foi0y) ([raw file](https://github.com/dgraph-io/dgraph/blob/c9c91604d0ef4658d51e68d786f8d9013a49576c/wiki/content/graphql/schema/reserved.md#L28)):*
> ```
> - `AuthorFilter`
> ```
We should put a new line before this. The rendering seems incorrect at present: https://dgraph-c9c91604d0-104138.surge.sh/graphql/schema/reserved/
You can find how it is being rendered using the `Docs Preview` link generated in the PR checks section present at the bottom of the PR.
___
*[wiki/content/graphql/schema/search.md, line 307 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6782#-MKYW5Q89JNqY7eOAhWx:-MKYW5Q89JNqY7eOAhWy:btdlefp) ([raw file](https://github.com/dgraph-io/dgraph/blob/c9c91604d0ef4658d51e68d786f8d9013a49576c/wiki/content/graphql/schema/search.md#L307)):*
> ```
> Geolocation supports four filter options: `near`, `within`, `contains` and `intersects`.
> ```
Something like:

There are 3 Geolocation types - `Point`, `Polygon` and `MultiPolygon`. All of them are searchable. The following table lists the generated filters for each type if you put  `@search` on a field of that type:

| type | constructed searches |
|----------|----------------------|
| `Point` | `near`, `within` |
| `Polygon` | `near`, `within`, `contains`, `intersects` |
| `MultiPolygon` | `near`, `within`, `contains`, `intersects` |
___
*[wiki/content/graphql/schema/search.md, line 316 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6782#-MKYXgumEEf8NSbGk5Ad:-MKYXgumEEf8NSbGk5Ae:b-u7eblr) ([raw file](https://github.com/dgraph-io/dgraph/blob/c9c91604d0ef4658d51e68d786f8d9013a49576c/wiki/content/graphql/schema/search.md#L316)):*
> ```
>   location: Point
>   area: Polygon
> ```
should be:
```
   location: Point @search
   area: Polygon @search
```
___
*[wiki/content/graphql/schema/search.md, line 322 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6782#-MKYZB159vKBbwmYTbzQ:-MKYZB159vKBbwmYTbzR:b9txxw3) ([raw file](https://github.com/dgraph-io/dgraph/blob/c9c91604d0ef4658d51e68d786f8d9013a49576c/wiki/content/graphql/schema/search.md#L322)):*
> ```
> The `near` function matches all entities where the location given by `predicate` is within a distance `meters` from a geojson coordinate `[lat, long]`.
> ```
The wording in the RFC is a bit DQL specific. The corresponding wording from GraphQL perspective would be:

```
The `near` filter matches all entities where the location given by a field is within a distance `meters` from a coordinate.
```

Note that I have changed the following:
* function -> filter
* predicate  -> field
* geojson -> (removed it, it actually refers to a library being used by Dgraph)
* [lat, long] -> (removed it, it is DQL specific format, and is already conveyed by the word coordinate)

We should make similar changes for `within`, `contains` and `intersects`.
___
*[wiki/content/graphql/schema/search.md, line 344 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6782#-MKYah9q1SGOHSmb3Eif:-MKYah9q1SGOHSmb3Eig:bhck5hx) ([raw file](https://github.com/dgraph-io/dgraph/blob/c9c91604d0ef4658d51e68d786f8d9013a49576c/wiki/content/graphql/schema/search.md#L344)):*
> ```
> {{% notice "tip" %}}
> The `within` query lets you search for all geo entities (`point`, `polygon`) within a polygon, so they are generated for all types.
> {{% /notice %}}
> ```
should we remove these tips, now that we have it all tabulated at the start of this section?
___
*[wiki/content/graphql/schema/search.md, line 359 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6782#-MKYaC-o4lgKo134FMsU:-MKYaC-o4lgKo134FMsV:bmam6zv) ([raw file](https://github.com/dgraph-io/dgraph/blob/c9c91604d0ef4658d51e68d786f8d9013a49576c/wiki/content/graphql/schema/search.md#L359)):*
<details><summary><i alt="summary">Quoted 15 lines of code…</i></summary>

> ```
> 								points: [{
> 									latitude: 11.11,
> 									longitude: 22.22
> 								}, {
> 									latitude: 15.15,
> 									longitude: 16.16
> 								}, {
> 									latitude: 20.20,
> 									longitude: 21.21
> 								},
>  								{
> 									latitude: 11.11,
> 									longitude: 22.22
> 								}]
> 							}],
> ```
</details>

indentation need to be corrected.
___
*[wiki/content/graphql/schema/search.md, line 379 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6782#-MKYd5vP-pObkqLXNuZj:-MKYd5vP-pObkqLXNuZk:b-s3wocf) ([raw file](https://github.com/dgraph-io/dgraph/blob/c9c91604d0ef4658d51e68d786f8d9013a49576c/wiki/content/graphql/schema/search.md#L379)):*
> ```
> The `contains` function matches all entities where [...]

2020-10-26 20:08 UTC, bucanero reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6782)* status: 0 of 4 files reviewed, 21 unresolved discussions (waiting on @aaroncarey, @abhimanyusinghgaur, @danielmai, and @MichaelJCompton)

___
*[wiki/content/graphql/queries/geolocation.md, line 1 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6782#-MKYhXL31mBsOBMTF3We:-MKaUv5QDQcDbULb3ucV:b-j6n9dn) ([raw file](https://github.com/dgraph-io/dgraph/blob/c9c91604d0ef4658d51e68d786f8d9013a49576c/wiki/content/graphql/queries/geolocation.md#L1)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

I think now we won't need a separate page for Geolocation in `Queries` or `Mutations` section because we are already explaining the necessary bits for it in the `Schema` section. So, this page can be removed now.
</blockquote></details>

Article removed.

You're right, the information is already available in the other articles (Types, Reserved names, Schema Fragments).
___
*[wiki/content/graphql/schema/dgraph-schema.md, line 91 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6782#-MKYSg_dEoT4__nlWf4r:-MK_ComQ6P_aa73pL8Q0:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c9c91604d0ef4658d51e68d786f8d9013a49576c/wiki/content/graphql/schema/dgraph-schema.md#L91)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> scalar DateTime
> enum DgraphIndex {
> 	int
> 	float
> 	bool
> 	hash
> 	exact
> 	term
> 	fulltext
> 	trigram
> 	regexp
> 	year
> 	month
> 	day
> 	hour
> }
> input AuthRule {
> 	and: [AuthRule]
> 	or: [AuthRule]
> 	not: AuthRule
> 	rule: String
> }
> enum HTTPMethod {
> 	GET
> 	POST
> 	PUT
> 	PATCH
> 	DELETE
> }
> enum Mode {
> 	BATCH
> 	SINGLE
> }
> input CustomHTTP {
> 	url: String!
> 	method: HTTPMethod!
> 	body: String
> 	graphql: String
> 	mode: Mode
> 	forwardHeaders: [String!]
> 	secretHeaders: [String!]
> 	introspectionHeaders: [String!]
> 	skipIntrospection: Boolean
> }
> input NearFilter {
>     Distance: Float!
>     Coordinate: Point!
> }
> input WithinFilter {
>     polygon: Polygon!
> }
> input ContainsFilter {
>     # The user should be giving one of these.
>     point: Point
>     polygon: Polygon
> }
> input IntersectsFilter {
>     # The user should be giving one of these.
>     polygon: Polygon
>     mulitPolygon: MultiPolygon
> }
> input PointGeoFilter {
>     near: NearFilter
>     within: WithinFilter
> }
> input PolygonGeoFilter {
>     near: NearFilter
>     within: WithinFilter
>     contains: ContainsFilter
>     intersects: IntersectsFilter
> }
> directive @hasInverse(field: String!) on FIELD_DEFINITION
> directive @search(by: [DgraphIndex!]) on FIELD_DEFINITION
> directive @dgraph(type: String, pred: String) on OBJECT | INTERFACE | FIELD_DEFINITION
> directive @id on FIELD_DEFINITION
> directive @withSubscription on OBJECT | INTERFACE
> directive @secret(field: String!, pred: String) on OBJECT | INTERFACE
> directive @auth(
> 	query: AuthRule,
> 	add: AuthRule,
> 	update: AuthRule,
> 	delete: AuthRule) on OBJECT
> directive @custom(http: CustomHTTP) on FIELD_DEFINITION
> directive @remote on OBJECT | INTERFACE
> ```
This whole thing has got outdated over time. It can now be replaced with [`schemaExtras` constant in gqlschema.go file](https://github.com/dgraph-io/dgraph/blob/master/graphql/schema/gqlschema.go#L83-L314).
</blockquote></details>

Done.
___
*[wiki/content/graphql/schema/reserved.md, line 28 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6782#-MKYCG896aSi8BncREZ4:-MK_DOtg8eTlp08r0j4_:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c9c91604d0ef4658d51e68d786f8d9013a49576c/wiki/content/graphql/schema/reserved.md#L28)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> - `AuthorFilter`
> ```
We should put a new line before this. The rendering seems incorrect at present: https://dgraph-c9c91604d0-104138.surge.sh/graphql/schema/reserved/
You can find how it is being rendered using the `Docs Preview` link generated in the PR checks section present at the bottom of the PR.
</blockquote></details>

Done.
___
*[wiki/content/graphql/schema/search.md, line 307 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6782#-MKYW5Q89JNqY7eOAhWx:-MK_H6e3CkJ7-r2wTstw:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c9c91604d0ef4658d51e68d786f8d9013a49576c/wiki/content/graphql/schema/search.md#L307)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> Geolocation supports four filter options: `near`, `within`, `contains` and `intersects`.
> ```
Something like:

There are 3 Geolocation types - `Point`, `Polygon` and `MultiPolygon`. All of them are searchable. The following table lists the generated filters for each type if you put  `@search` on a field of that type:

| type | constructed searches |
|----------|----------------------|
| `Point` | `near`, `within` |
| `Polygon` | `near`, `within`, `contains`, `intersects` |
| `MultiPolygon` | `near`, `within`, `contains`, `intersects` |

</blockquote></details>

Done.
___
*[wiki/content/graphql/schema/search.md, line 316 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6782#-MKYXgumEEf8NSbGk5Ad:-MK_H7eAEUScj188MUSs:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c9c91604d0ef4658d51e68d786f8d9013a49576c/wiki/content/graphql/schema/search.md#L316)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
>   location: Point
>   area: Polygon
> ```
should be:
```
   location: Point @search
   area: Polygon @search
```
</blockquote></details>

Done.
___
*[wiki/content/graphql/schema/search.md, line 322 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6782#-MKYZB159vKBbwmYTbzQ:-MKaGC5n31t0_EhF2A-c:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c9c91604d0ef4658d51e68d786f8d9013a49576c/wiki/content/graphql/schema/search.md#L322)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> The `near` function matches all entities where the location given by `predicate` is within a distance `meters` from a geojson coordinate `[lat, long]`.
> ```
The wording in the RFC is a bit DQL specific. The corresponding wording from GraphQL perspective would be:

```
The `near` filter matches all entities where the location given by a field is within a distance `meters` from a coordinate.
```

Note that I have changed the following:
* function -> filter
* predicate  -> field
* geojson -> (removed it, it actually refers to a library being used by Dgraph)
* [lat, long] -> (removed it, it is DQL specific format, and is already conveyed by the word coordinate)

We should make similar changes for `within`, `contains` and `intersects`.
</blockquote></details>

Done.
___
*[wiki/content/graphql/schema/search.md, line 344 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6782#-MKYah9q1SGOHSmb3Eif:-MKaGDRx2mxTsPZ4ONGk:bvv5cxw) ([raw file](https://github.com/dgraph-io/dgraph/blob/c9c91604d0ef4658d51e68d786f8d9013a49576c/wiki/content/graphql/schema/search.md#L344)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> {{% notice "tip" %}}
> The `within` query lets you search for all geo entities (`point`, `polygon`) within a polygon, so they are generated for all types.
> {{% /notice %}}
> ```
should we remove these tips, now that we have it all tabulated at the start of this section?
</blockquote></details>

I agree, they're not needed now.
___
*[wiki/content/graphql/schema/search.md, line 359 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6782#-MKYaC-o4lgKo134FMsU:-MKaRK_r9KUtSh9headh:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c9c91604d0ef4658d51e68d786f8d9013a49576c/wiki/content/grap [...]

2020-10-27 10:08 UTC, abhimanyusinghgaur approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>
Thanks for the changes.

I have put Just one comment about removing the outdated types.

> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6782#-:-MKdWWIP38QF6UWAE3ck:b1xvrlq)* status: all files reviewed, 6 unresolved discussions (waiting on @aaroncarey, @bucanero, @danielmai, and @MichaelJCompton)

___
*[wiki/content/graphql/schema/types.md, line 232 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6782#-MKdVosQ-lgd19-5sJlg:-MKdVosQ-lgd19-5sJlh:b-ieq4vu) ([raw file](https://github.com/dgraph-io/dgraph/blob/c4f917b3d674838617e34dc8f2a20dc17cafd4c8/wiki/content/graphql/schema/types.md#L232)):*
> ```
> 
> #### Point
> 
> ```graphql
> type Point {
>   Latitude: Float!
>   Longitude: Float!
> }
> ```
> #### PointList
> ```graphql
> type PointList {
>   Points: [Point!]!
> }
> ```
> #### Polygon
> ```graphql
> type Polygon {
>   Coordinates: [PointList!]!
> }
> ```
> #### MultiPolygon
> ```graphql
> type MultiPolygon {
>   Coordinates: [Polygon!]!
> }
> ```
> ```
This part won't be required here, it is already in `Dgraph Schema Fragment` with the correct syntax.


<!-- Sent from Reviewable.io -->

2020-10-27 13:50 UTC, merged