docs: clarify exact order for trigram and term indexes when specified together
dgraph-io/dgraph pull request #6800
Opened 2020-10-26 18:02 UTC by OmarAyo

Clarified how it's the exact order for both `trigram` and `term` index when specified together in the schema.

Order has to look like:
```
<predicate>: string @index(term, trigram) . 
```

2020-10-26 18:41 UTC, danielmai requested changes
This needs to be updated in the string indices docs, not tutorial: https://dgraph.io/docs/query-language/schema/#string-indices

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6800#-:-MKaCPiXBEs4aOffdjg5:b2w5mst)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MichaelJCompton)



<!-- Sent from Reviewable.io -->

2020-10-26 18:45 UTC, danielmai requested changes
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6800)* status: all files reviewed, 1 unresolved discussion (waiting on @MichaelJCompton and @OmarAyo)

___
*[wiki/content/tutorial-3/index.md, line 291 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6800#-MKaCgmzEYsKSQbELgsa:-MKaCgmzEYsKSQbELgsb:b-alvs7j) ([raw file](https://github.com/dgraph-io/dgraph/blob/aec6b1abe5b3576384b0cfec3ddf77afc989a65a/wiki/content/tutorial-3/index.md#L291)):*
> ```
> Please note that when specifying at the same time both `trigram` and `term` indexes, in the schema, you will need to specify them in the following **exact** order: `<predicate>: string @index(term, trigram) .` no vice-versa.
> ```

Rephrase to the following:

Please note that when specifying at the same time both `term` and `trigram` indexes, in the schema, you will need to specify them in the following **exact** order: `<predicate>: string @index(term, trigram) .` not vice-versa. Doing otherwise causes queries using the index to return an error about invalid tokenizers.

* Specify the order of the indexes in the first clause to make the order more obvious.
* not* vice-versa.
* Add a blurb at the end about the error message that happens when the index is set incorrectly.


<!-- Sent from Reviewable.io -->

2020-10-27 18:50 UTC, OmarAyo commented
Done





<!-- Sent from Reviewable.io -->

2020-10-27 18:51 UTC, OmarAyo commented
___
*[wiki/content/tutorial-3/index.md, line 291 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6800#-MKaCgmzEYsKSQbELgsa:-MKfOXbgE-u9D6dUULDR:b-896fjx) ([raw file](https://github.com/dgraph-io/dgraph/blob/aec6b1abe5b3576384b0cfec3ddf77afc989a65a/wiki/content/tutorial-3/index.md#L291)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> Please note that when specifying at the same time both `trigram` and `term` indexes, in the schema, you will need to specify them in the following **exact** order: `<predicate>: string @index(term, trigram) .` no vice-versa.
> ```

Rephrase to the following:

Please note that when specifying at the same time both `term` and `trigram` indexes, in the schema, you will need to specify them in the following **exact** order: `<predicate>: string @index(term, trigram) .` not vice-versa. Doing otherwise causes queries using the index to return an error about invalid tokenizers.

* Specify the order of the indexes in the first clause to make the order more obvious.
* not* vice-versa.
* Add a blurb at the end about the error message that happens when the index is set incorrectly.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2020-10-27 18:55 UTC, danielmai approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6800#-:-MKfPdPw10rhsOvC7RSY:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @danielmai and @MichaelJCompton)



<!-- Sent from Reviewable.io -->

2020-10-27 18:57 UTC, merged