[WIP] Update search-filtering.md
dgraph-io/dgraph pull request #6813
Opened 2020-10-30 01:08 UTC by aaroncarey

Adding documentation for the `between` filter for GraphQL, also minor wording changes to the rest of this page.

Fixes DGRAPH-2607

2020-10-30 18:58 UTC, bucanero commented on wiki/content/graphql/queries/search-filtering.md
> +Fetch the title, text and `datePublished` for a post with id `0x1`.
```suggestion
Fetch the `title`, `text`, and `datePublished` for a post with id `0x1`.
```

2020-10-30 19:01 UTC, bucanero commented on wiki/content/graphql/queries/search-filtering.md
> +For example, the following query fetches the author with the `id` 0x1 and their posts about GraphQL.
```suggestion
For example, the following query fetches the `author` with the `id` `0x1` and their posts about GraphQL.
```

2020-10-30 19:02 UTC, bucanero commented on wiki/content/graphql/queries/search-filtering.md
> +For example, given the following schema, the query below fetches a user's name and age by `userID` (which has the `@id` directive):
```suggestion
For example, given the following schema, the query below fetches a user's `name` and `age` by `userID` (which has the `@id` directive):
```

2020-10-30 19:03 UTC, bucanero commented on wiki/content/graphql/queries/search-filtering.md
> +You can query a list of objects using GraphQL. For example, the following query fetches the title, text and and `datePublished` for all posts:
```suggestion
You can query a list of objects using GraphQL. For example, the following query fetches the `title`, `text`, and `datePublished` for all posts:
```

2020-10-30 19:04 UTC, bucanero commented on wiki/content/graphql/queries/search-filtering.md
> +For example, the following query fetches all of the authors whose name contains `Lee` and with their `completed` posts that have a score greater than 10:
```suggestion
For example, the following query fetches all of the authors whose name contains `Lee` and with their `completed` posts that have a score greater than `10`:
```

2020-10-30 19:11 UTC, bucanero commented on wiki/content/graphql/queries/search-filtering.md
> +DQL; to learn more, see [DQL Functions: `between`](/query-language/functions/#between).
This note could be in a green **Tip** box:
```
This keyword is also supported for DQL; to learn more, see [DQL Functions: `between`](/query-language/functions/#between).
```

2020-10-30 19:12 UTC, bucanero reviewed
Shared some formatting suggestions.

2020-10-30 22:46 UTC, aaroncarey reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6813)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @aaroncarey, @bucanero, @danielmai, @MichaelJCompton, and @minhaj-shakeel)

___
*[wiki/content/graphql/queries/search-filtering.md, line 14 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6813#-MKr28gEzAYPhB_LRVtR-r1-14:-MKvdlAM6P1cxXbho1cO:boyexb3) ([raw file](https://github.com/dgraph-io/dgraph/blob/b5951baf214318fa3d775afeaf972b1b9551685d/wiki/content/graphql/queries/search-filtering.md#L14)):*
<details><summary><i>Previously, bucanero (Damián Parrino) wrote…</i></summary><blockquote>

```suggestion
Fetch the `title`, `text`, and `datePublished` for a post with id `0x1`.
```
</blockquote></details>

Done. Thanks!
___
*[wiki/content/graphql/queries/search-filtering.md, line 47 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6813#-MKr28gEzAYPhB_LRVtR-r1-47:-MKve-8mEEjPM20mPGL2:bmni7ff) ([raw file](https://github.com/dgraph-io/dgraph/blob/b5951baf214318fa3d775afeaf972b1b9551685d/wiki/content/graphql/queries/search-filtering.md#L47)):*
<details><summary><i>Previously, bucanero (Damián Parrino) wrote…</i></summary><blockquote>

```suggestion
For example, the following query fetches the `author` with the `id` `0x1` and their posts about `GraphQL`.
```
</blockquote></details>

I applied the `GraphQL` formatting fix, but "author" doesn't appear in the example, so I didn't apply code formatting to it.
___
*[wiki/content/graphql/queries/search-filtering.md, line 68 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6813#-MKr28gEzAYPhB_LRVtR-r1-68:-MKveDk84y3loytSk0ec:b-dtkds3) ([raw file](https://github.com/dgraph-io/dgraph/blob/b5951baf214318fa3d775afeaf972b1b9551685d/wiki/content/graphql/queries/search-filtering.md#L68)):*
<details><summary><i>Previously, bucanero (Damián Parrino) wrote…</i></summary><blockquote>

```suggestion
For example, given the following schema, the query below fetches a user's `name` and `age` by `userID` (which has the `@id` directive):
```
</blockquote></details>

Done, thanks!
___
*[wiki/content/graphql/queries/search-filtering.md, line 93 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6813#-MKr28gEzAYPhB_LRVtR-r1-93:-MKveOW85DWw4iPJOgux:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b5951baf214318fa3d775afeaf972b1b9551685d/wiki/content/graphql/queries/search-filtering.md#L93)):*
<details><summary><i>Previously, bucanero (Damián Parrino) wrote…</i></summary><blockquote>

```suggestion
You can query a list of objects using GraphQL. For example, the following query fetches the `title`, `text`, and `datePublished` for all posts:
```
</blockquote></details>

Done.
___
*[wiki/content/graphql/queries/search-filtering.md, line 177 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6813#-MKr28gEzAYPhB_LRVtR-r1-177:-MKvevC4-Zh_oKUM_rSv:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b5951baf214318fa3d775afeaf972b1b9551685d/wiki/content/graphql/queries/search-filtering.md#L177)):*
<details><summary><i>Previously, bucanero (Damián Parrino) wrote…</i></summary><blockquote>

This note could be in a green **Tip** box:
```
This keyword is also supported for DQL; to learn more, see [DQL Functions: `between`](/query-language/functions/#between).
```

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-31 05:09 UTC, minhaj-shakeel requested changes
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6813)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @aaroncarey, @bucanero, @danielmai, @MichaelJCompton, and @minhaj-shakeel)

___
*[wiki/content/query-language/functions.md, line 405 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6813#-MKx2DOf6EgpdXJm_oEt:-MKx2DOg7Kl9S37Kummc:b-rrbzht) ([raw file](https://github.com/dgraph-io/dgraph/blob/be60c9c972232a8cf221c0640e2ac8b256ded983/wiki/content/query-language/functions.md#L405)):*
> ```Markdown
> Schema Types: Scalar types, including `dateTime`, `int`, `float` and `string`
> 
> Index Required: `dateTime`
> ```

Could mention indices for other scalar types also Like:
Index Required: `dateTime`, `int`, `float`, and `exact` on strings.
 
and the below example should start as:
"Here is the example usage on `dateTime` ".


<!-- Sent from Reviewable.io -->

2020-11-02 18:53 UTC, aaroncarey reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6813)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @aaroncarey, @bucanero, @danielmai, @MichaelJCompton, and @minhaj-shakeel)

___
*[wiki/content/query-language/functions.md, line 405 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6813#-MKx2DOf6EgpdXJm_oEt:-ML9IKKGDwfcRbwtdJkT:b-jsd9r5) ([raw file](https://github.com/dgraph-io/dgraph/blob/be60c9c972232a8cf221c0640e2ac8b256ded983/wiki/content/query-language/functions.md#L405)):*
<details><summary><i>Previously, minhaj-shakeel wrote…</i></summary><blockquote>

Could mention indices for other scalar types also Like:
Index Required: `dateTime`, `int`, `float`, and `exact` on strings.
 
and the below example should start as:
"Here is the example usage on `dateTime` ".
</blockquote></details>

Great feedback, thank you! I updated the "Index Required" section exactly as you suggested, and added a lead-in for the example that clarifies that the example only shows how to use `between` with a `dateTime` index, but that there are other use cases.


<!-- Sent from Reviewable.io -->

2020-11-02 21:08 UTC, merged