feat(GraphQL): types should be able to inherit mutation auth rules from interfaces
dgraph-io/dgraph pull request #6816
Opened 2020-10-30 10:39 UTC by minhaj-shakeel

Fixes GRAPHQL-740.

2020-11-03 08:15 UTC, pawanrawal requested changes
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6816)* status: 0 of 7 files reviewed, 9 unresolved discussions (waiting on @MichaelJCompton, @minhaj-shakeel, and @pawanrawal)

___
*[graphql/resolve/auth_add_test.yaml, line 1025 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLBnNP51cnhlpRX6A6H:-MLBnNP51cnhlpRX6A6I:btbsa60) ([raw file](https://github.com/dgraph-io/dgraph/blob/4d472f6ac2521e1429fc8b20aa8fe14952349835/graphql/resolve/auth_add_test.yaml#L1025)):*
> ```YAML
>   skipauth: true
> 
> - name: "Adding Type with having Auth on interfaces successfully."
> ```

Adding nodes for a type that inherits auth rules from an interface successfully.
___
*[graphql/resolve/auth_add_test.yaml, line 1072 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLBm3xY2KnAarSK0961:-MLBm3xY2KnAarSK0962:b-s6aboe) ([raw file](https://github.com/dgraph-io/dgraph/blob/4d472f6ac2521e1429fc8b20aa8fe14952349835/graphql/resolve/auth_add_test.yaml#L1072)):*
> ```YAML
>     }
>   authjson: |
>     {"Question": [ {"uid": "0x123"}], "Author": [{"uid": "0x456"}]}
> ```

There is no query for the Author above in `authquery` so the `authjson` doesn't really need an `Author` key?

What if `Author` also had auth rules? Would its auth rules also be verified using a separate query then? Can we have a test for such a case?
___
*[graphql/resolve/auth_add_test.yaml, line 1073 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLBnZzzBBqwFkescdnI:-MLBnZzzBBqwFkescdnJ:b-eseq0o) ([raw file](https://github.com/dgraph-io/dgraph/blob/4d472f6ac2521e1429fc8b20aa8fe14952349835/graphql/resolve/auth_add_test.yaml#L1073)):*
> ```YAML
>   authjson: |
>     {"Question": [ {"uid": "0x123"}], "Author": [{"uid": "0x456"}]}
> - name: "Adding Type with having Auth on interfaces failed."
> ```

Adding nodes for a type that inherits auth rules from an interface fails.
___
*[graphql/resolve/auth_add_test.yaml, line 1124 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLBnfDjEjT2oHOECWGa:-MLBnfDjEjT2oHOECWGb:b-aykeeg) ([raw file](https://github.com/dgraph-io/dgraph/blob/4d472f6ac2521e1429fc8b20aa8fe14952349835/graphql/resolve/auth_add_test.yaml#L1124)):*
> ```YAML
>     { "message": "mutation failed because authorization failed"}
> 
> - name: "Add type with Having RBAC rule on interface successfully"
> ```

with having RBAC
___
*[graphql/resolve/auth_add_test.yaml, line 1128 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLBnz3V3VcalKOzt2DT:-MLBnz3V3VcalKOzt2DU:b-13ruiu) ([raw file](https://github.com/dgraph-io/dgraph/blob/4d472f6ac2521e1429fc8b20aa8fe14952349835/graphql/resolve/auth_add_test.yaml#L1128)):*
> ```YAML
>     mutation addFbPost($post: [AddFbPostInput!]!){
>       addFbPost(input: $post){
>         fbPost{
> ```

space before {
`fbPost {`
___
*[graphql/resolve/auth_add_test.yaml, line 1166 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLC5v5z7LmfSOMSg3uW:-MLC5v5z7LmfSOMSg3uX:byyth3e) ([raw file](https://github.com/dgraph-io/dgraph/blob/4d472f6ac2521e1429fc8b20aa8fe14952349835/graphql/resolve/auth_add_test.yaml#L1166)):*
> ```YAML
>     }
>   authjson: |
>     {"FbPost": [ {"uid": "0x123"}], "Author": [{"uid": "0x456"}]}
> ```

Again, the Author is probably not required here as it would not be returned from the `authquery` result?
___
*[graphql/resolve/auth_delete_test.yaml, line 669 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLC9ewfCyC09P8KKIKD:-MLC9ewfCyC09P8KKIKE:b-mbksle) ([raw file](https://github.com/dgraph-io/dgraph/blob/4d472f6ac2521e1429fc8b20aa8fe14952349835/graphql/resolve/auth_delete_test.yaml#L669)):*
> ```YAML
>          }]
>   dgquery: |-
>     query {
> ```

I don't quite get it, where are the uids `0x1` and `0x2` used in this query? I don't see them here. It looks like we'd end up deleting all questions which pass the auth rules.
___
*[graphql/resolve/auth_delete_test.yaml, line 712 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLC9wIG1HZnBSo0Jl49:-MLC9wIG1HZnBSo0Jl4A:b-66n436) ([raw file](https://github.com/dgraph-io/dgraph/blob/4d472f6ac2521e1429fc8b20aa8fe14952349835/graphql/resolve/auth_delete_test.yaml#L712)):*
> ```YAML
>       x as deleteQuestion()
>     }
> - name: "Delete type having RBAC Auth Rules on interface and those are not satisfied."
> ```

Add a newline before starting a new test case. Makes for easier reading.
___
*[graphql/resolve/auth_delete_test.yaml, line 764 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLCA29Z2_mkqYvTY9xY:-MLCA29Z2_mkqYvTY9xZ:b-6b1nks) ([raw file](https://github.com/dgraph-io/dgraph/blob/4d472f6ac2521e1429fc8b20aa8fe14952349835/graphql/resolve/auth_delete_test.yaml#L764)):*
> ```YAML
>          }]
>   dgquery: |-
>     query {
> ```

Same comment as above. Why do we select all `FbPost`?


<!-- Sent from Reviewable.io -->

2020-11-03 08:16 UTC, pawanrawal reviewed
Haven't reviewed the e2e tests yet. I also don't see any tests for update mutation with auth. We should have some of those as well.

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-:-MLCAD9rBdRSmFoSGz60:b-gr8wp)* status: 0 of 7 files reviewed, 9 unresolved discussions (waiting on @MichaelJCompton, @minhaj-shakeel, and @pawanrawal)



<!-- Sent from Reviewable.io -->

2020-11-03 12:01 UTC, minhaj-shakeel reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6816)* status: 0 of 8 files reviewed, 9 unresolved discussions (waiting on @MichaelJCompton and @pawanrawal)

___
*[graphql/resolve/auth_add_test.yaml, line 1025 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLBnNP51cnhlpRX6A6H:-MLCyHmwDwKY5N9yGPIh:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4d472f6ac2521e1429fc8b20aa8fe14952349835/graphql/resolve/auth_add_test.yaml#L1025)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Adding nodes for a type that inherits auth rules from an interface successfully.
</blockquote></details>

Done.
___
*[graphql/resolve/auth_add_test.yaml, line 1072 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLBm3xY2KnAarSK0961:-MLCyV9u97rbVTT06mUi:b28zkpm) ([raw file](https://github.com/dgraph-io/dgraph/blob/4d472f6ac2521e1429fc8b20aa8fe14952349835/graphql/resolve/auth_add_test.yaml#L1072)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

There is no query for the Author above in `authquery` so the `authjson` doesn't really need an `Author` key?

What if `Author` also had auth rules? Would its auth rules also be verified using a separate query then? Can we have a test for such a case?
</blockquote></details>

I have removed the `Author` key from the `authjson`.
___
*[graphql/resolve/auth_add_test.yaml, line 1073 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLBnZzzBBqwFkescdnI:-MLCyIht1oiGSeLJfukp:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4d472f6ac2521e1429fc8b20aa8fe14952349835/graphql/resolve/auth_add_test.yaml#L1073)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Adding nodes for a type that inherits auth rules from an interface fails.
</blockquote></details>

Done.
___
*[graphql/resolve/auth_add_test.yaml, line 1124 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLBnfDjEjT2oHOECWGa:-MLCyJ7sB-JiYG_VURwO:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4d472f6ac2521e1429fc8b20aa8fe14952349835/graphql/resolve/auth_add_test.yaml#L1124)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

with having RBAC
</blockquote></details>

Done.
___
*[graphql/resolve/auth_add_test.yaml, line 1128 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLBnz3V3VcalKOzt2DT:-MLCyJWb4kQ7rhmEQ7xG:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4d472f6ac2521e1429fc8b20aa8fe14952349835/graphql/resolve/auth_add_test.yaml#L1128)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

space before {
`fbPost {`
</blockquote></details>

Done.
___
*[graphql/resolve/auth_add_test.yaml, line 1166 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLC5v5z7LmfSOMSg3uW:-MLCyLFM7fSnb_zQ5wom:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4d472f6ac2521e1429fc8b20aa8fe14952349835/graphql/resolve/auth_add_test.yaml#L1166)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Again, the Author is probably not required here as it would not be returned from the `authquery` result?
</blockquote></details>

Done.
___
*[graphql/resolve/auth_delete_test.yaml, line 669 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLC9ewfCyC09P8KKIKD:-MLCyMAlDr20dhFsePQv:b-ybsfuw) ([raw file](https://github.com/dgraph-io/dgraph/blob/4d472f6ac2521e1429fc8b20aa8fe14952349835/graphql/resolve/auth_delete_test.yaml#L669)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

I don't quite get it, where are the uids `0x1` and `0x2` used in this query? I don't see them here. It looks like we'd end up deleting all questions which pass the auth rules.
</blockquote></details>

Fixed that
___
*[graphql/resolve/auth_delete_test.yaml, line 712 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLC9wIG1HZnBSo0Jl49:-MLCyO2LESoxbm2p9RbW:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4d472f6ac2521e1429fc8b20aa8fe14952349835/graphql/resolve/auth_delete_test.yaml#L712)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Add a newline before starting a new test case. Makes for easier reading.
</blockquote></details>

Done.
___
*[graphql/resolve/auth_delete_test.yaml, line 764 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLCA29Z2_mkqYvTY9xY:-MLCyOsv-vaCiuwR8fR-:b1b762e) ([raw file](https://github.com/dgraph-io/dgraph/blob/4d472f6ac2521e1429fc8b20aa8fe14952349835/graphql/resolve/auth_delete_test.yaml#L764)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Same comment as above. Why do we select all `FbPost`?
</blockquote></details>

Fixed that.


<!-- Sent from Reviewable.io -->

2020-11-04 07:11 UTC, pawanrawal requested changes
All the e2e sub test cases need a description or comment field to clarify what they are testing as we have in unit tests. 

> Reviewed 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-:-MLH52zS6Fu_wjKY6hsO:br41436)* status: 2 of 8 files reviewed, 14 unresolved discussions (waiting on @MichaelJCompton and @minhaj-shakeel)

___
*[graphql/e2e/auth/add_mutation_test.go, line 156 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLH2-2v9q1Ob97pYDxm:-MLH2-2v9q1Ob97pYDxn:bfbkemk) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a73fd715e54131f536ca4ab6c51b9ba0699b617/graphql/e2e/auth/add_mutation_test.go#L156)):*
> ```Go
> }
> 
> func TestAddOnTypeWithRBACFilterOnInterface(t *testing.T) {
> ```

TestAuth_AddOnTypeWithRBACRuleOnInterface
___
*[graphql/e2e/auth/add_mutation_test.go, line 231 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLH1jyB5DxxafiedwiD:-MLH1jyB5DxxafiedwiE:bem8so7) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a73fd715e54131f536ca4ab6c51b9ba0699b617/graphql/e2e/auth/add_mutation_test.go#L231)):*
> ```Go
> 
> 		gqlResponse := getUserParams.ExecuteAsPost(t, graphqlURL)
> 		if tcase.result == "" {
> ```

Usually, there is another variable in the test case called `expectedErr` which is set to true for cases where you expect the error.  You are using the result value to check the same thing but having another variable makes it more clear and explicit.
___
*[graphql/e2e/auth/add_mutation_test.go, line 245 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLH1aCjEmXz3558BwH8:-MLH1aCjEmXz3558BwH9:b-qju3s5) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a73fd715e54131f536ca4ab6c51b9ba0699b617/graphql/e2e/auth/add_mutation_test.go#L245)):*
> ```Go
> 		require.NoError(t, err)
> 
> 		opt := cmpopts.IgnoreFields(FbPost{}, "Id")
> ```

No need to even fetch the id in the response. If you didn't fetch the id you can just compare the string JSON directly without having to unmarshal it using `testutil.CompareJSON`
___
*[graphql/e2e/auth/add_mutation_test.go, line 260 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLH25sT7sxf0jxIBvfj:-MLH25sT7sxf0jxIBvfk:bglwdim) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a73fd715e54131f536ca4ab6c51b9ba0699b617/graphql/e2e/auth/add_mutation_test.go#L260)):*
> ```Go
> }
> 
> func TestAddOnTypeWithGraphFilterOnInterface(t *testing.T) {
> ```

TestAuth_AddOnTypeWithGraphTraversalRuleOnInterface
___
*[graphql/e2e/auth/add_mutation_test.go, line 326 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLH2FUM9En9LMMzcU1e:-MLH2FUM9En9LMMzcU1f:bfiluj8) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a73fd715e54131f536ca4ab6c51b9ba0699b617/graphql/e2e/auth/add_mutation_test.go#L326)):*
> ```Go
> 
> 		gqlResponse := getUserParams.ExecuteAsPost(t, graphqlURL)
> 		if tcase.result == "" {
> ```

Same comments as above apply
___
*[graphql/e2e/auth/delete_mutation_test.go, line 208 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLH4usm75I0W632Uo6w:-MLH4usm75I0W632Uo6x:b73r8mo) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a73fd715e54131f536ca4ab6c51b9ba0699b617/graphql/e2e/auth/delete_mutation_test.go#L208)):*
> ```Go
> 
> func TestDeleteTypeWithGraphFilterOnInterface(t *testing.T) {
> 	testCases := []TestCase{{
> ```

Add a description or comment string field which talks about what each case is testing otherwise I have to go look at the schema each time to try to understand whats happening.
___
*[graphql/e2e/auth/delete_mutation_test.go, line 240 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLH3eojD4_Tp_jWeu7l:-MLH3eojD4_Tp_jWeu7m:b-fewdrz) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a73fd715e54131f536ca4ab6c51b9ba0699b617/graphql/e2e/auth/delete_mutation_test.go#L240)):*
> ```Go
> 			_, allQuestionsIds := getAllQuestions(t, []string{"user1@dgraph.io", "user2@dgraph.io"}, []bool{true, false})
> 			require.True(t, len(allQuestionsIds) == 3)
> 			deleteQuestions, _ := getAllQuestions(t, []string{tcase.user}, []bool{tcase.ans})
> ```

Instead of running this query again, the first request above could give you the questions for all possible combinations?
___
*[graphql/e2e/auth/delete_mutation_test.go, line 242 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLH3pHCAX20KWL9U6P8:-MLH3pHCAX20KWL9U6P9:b-def95h) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a73fd715e54131f536ca4ab6c51b9ba0699b617/graphql/e2e/auth/delete_mutation_test.go#L242)):*
> ```Go
> 			deleteQuestions, _ := getAllQuestions(t, []string{tcase.user}, []bool{tcase.ans})
> 
> 			getUserParams := &common.GraphQLParams{
> ```

It's not getUserParams, just call it params.
___
*[graphql/e2e/auth/delete_mutation_test.go, line 250 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLH4wS87h3McF4OZqAx:-MLH4wS87h3McF4OZqAy:b-wsvh2j) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a73fd715e54131f536ca4ab6c51b9ba0699b617/graphql/e2e/auth/delete_mutation_test.go#L250)):*
> ```Go
> 			gqlResponse := getUserParams.ExecuteAsPost(t, graphqlURL)
> 			require.Nil(t, gqlResponse.Errors)
> 			require.JSONEq(t, tcase.result, string(gqlResponse.Data))
> ```

Should we verify the state after the delete operation has gone through?
___
*[graphql/e2e/auth/delete_mutation_test.go, line 252 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLH3u-T356fm8jfZG4D:-MLH3u-T356fm8jfZG4E:b93bm1t) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a73fd715e54131f536ca4ab6c51b9ba0699b617/graphql/e2e/auth/delete_mutation_test.go#L252)):*
> ```Go
> 			require.JSONEq(t, tcase.result, string(gqlResponse.Data))
> 
> 			// Restore the deleted Questions.
> ```

... deleted Questions for other test cases.
___
*[graphql/e2e/auth/update_mutation_test.go, line 373 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLH4gB10TuKSqs9JoT4:-MLH4gB10TuKSqs9JoT5:b73r8mo) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a73fd715e54131f536ca4ab6c51b9ba0699b617/graphql/e2e/auth/update_mutation_test.go#L373)):*
> ```Go
> 
> 	testCases := []TestCase{{
> 		user:   "user1@dgraph.io",
> ```

Add a description or comment string field which talks about what each case is testing otherwise I have to go look at the schema each time to try to understand whats happening.
___
*[graphql/e2e/auth/update_mutation_test.go, line 390 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLH4MIA9oZY0wZf241m:-MLH4MIA9oZY0wZf241n:b-f92r24) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a73fd715e54131f536ca4ab6c51b9ba0699b617/graphql/e2e/auth/update_mutation_test.go#L390)):*
> ```Go
> 		mutation($ids: [ID!]){
> 			updateQuestion(input: {filter: {id: $ids}, set: {topic: "A Topic"}}){
> 			question{
> ```

formatting is messed up
___
*[graphql/e2e/auth/update_mutation_test.go, line 400 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLH4OTd70cOwYBSnFHg:-MLH4OTd70cOwYBSnFHh:b-gx1rzr) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a73fd715e54131f536ca4ab6c51b9ba0699b617/graphql/e2e/auth/update_mutation_test.go#L400)):*
> ```Go
> 	for _, tcase := range testCases {
> 		t.Run(tcase.user+strconv.FormatBool(tcase.ans), func(t *testing.T) {
> 			getUserParams := &common.GraphQLParams{
> ```

just `params`
___
*[graphql/e2e/auth/update_mutation_test.go, line 408 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLH4_7YDOH0wOGWye8n:-MLH4_7YDOH0wOGWye8o:bkqd9tu) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a73fd715e54131f536ca4ab6c51b9ba0699b617/graphql/e2e/auth/update_mutation_test.go#L408)):*
> ```Go
> 			gqlResponse := getUserParams.ExecuteAsPost(t, graphqlURL)
> 			require.Nil(t, gqlResponse.Errors)
> 			require.JSONEq(t, string(gqlResponse.Data), tcase.result)
> ```

We didn't really verify if the update actually updated the data. Should we do another query to verify the updated state?


<!-- Sent from Reviewable.io -->

2020-11-04 09:08 UTC, minhaj-shakeel reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6816)* status: 2 of 8 files reviewed, 14 unresolved discussions (waiting on @MichaelJCompton and @pawanrawal)

___
*[graphql/e2e/auth/add_mutation_test.go, line 156 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLH2-2v9q1Ob97pYDxm:-MLHU1C7DYHikkCPB0AR:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a73fd715e54131f536ca4ab6c51b9ba0699b617/graphql/e2e/auth/add_mutation_test.go#L156)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

TestAuth_AddOnTypeWithRBACRuleOnInterface
</blockquote></details>

Done.
___
*[graphql/e2e/auth/add_mutation_test.go, line 231 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLH1jyB5DxxafiedwiD:-MLHV4vh4190hpxc0Xua:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a73fd715e54131f536ca4ab6c51b9ba0699b617/graphql/e2e/auth/add_mutation_test.go#L231)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Usually, there is another variable in the test case called `expectedErr` which is set to true for cases where you expect the error.  You are using the result value to check the same thing but having another variable makes it more clear and explicit.
</blockquote></details>

Done.
___
*[graphql/e2e/auth/add_mutation_test.go, line 245 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLH1aCjEmXz3558BwH8:-MLHVDve5Dj2f4WK955J:b3vpgh7) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a73fd715e54131f536ca4ab6c51b9ba0699b617/graphql/e2e/auth/add_mutation_test.go#L245)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

No need to even fetch the id in the response. If you didn't fetch the id you can just compare the string JSON directly without having to unmarshal it using `testutil.CompareJSON`
</blockquote></details>

`Ids` are fetched to delete the nodes after the test.
___
*[graphql/e2e/auth/add_mutation_test.go, line 260 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLH25sT7sxf0jxIBvfj:-MLHVNgX7sL5i5ZA6zmE:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a73fd715e54131f536ca4ab6c51b9ba0699b617/graphql/e2e/auth/add_mutation_test.go#L260)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

TestAuth_AddOnTypeWithGraphTraversalRuleOnInterface
</blockquote></details>

Done.
___
*[graphql/e2e/auth/add_mutation_test.go, line 326 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLH2FUM9En9LMMzcU1e:-MLHVOjV6E11ud51ZsQd:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a73fd715e54131f536ca4ab6c51b9ba0699b617/graphql/e2e/auth/add_mutation_test.go#L326)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Same comments as above apply
</blockquote></details>

Done.
___
*[graphql/e2e/auth/delete_mutation_test.go, line 208 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLH4usm75I0W632Uo6w:-MLHVQ4x9hY4BdzzcZ2T:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a73fd715e54131f536ca4ab6c51b9ba0699b617/graphql/e2e/auth/delete_mutation_test.go#L208)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Add a description or comment string field which talks about what each case is testing otherwise I have to go look at the schema each time to try to understand whats happening.
</blockquote></details>

Done.
___
*[graphql/e2e/auth/delete_mutation_test.go, line 240 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLH3eojD4_Tp_jWeu7l:-MLHVRB55F50q1mgGesb:b-s66yyv) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a73fd715e54131f536ca4ab6c51b9ba0699b617/graphql/e2e/auth/delete_mutation_test.go#L240)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Instead of running this query again, the first request above could give you the questions for all possible combinations?
</blockquote></details>

We want a subset of possible combinations which is easier this way.
___
*[graphql/e2e/auth/delete_mutation_test.go, line 242 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLH3pHCAX20KWL9U6P8:-MLHVa5rA6qAColsrlAt:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a73fd715e54131f536ca4ab6c51b9ba0699b617/graphql/e2e/auth/delete_mutation_test.go#L242)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

It's not getUserParams, just call it params.
</blockquote></details>

Done.
___
*[graphql/e2e/auth/delete_mutation_test.go, line 250 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLH4wS87h3McF4OZqAx:-MLHVeP-A0nJORVcGPlS:b7czb8e) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a73fd715e54131f536ca4ab6c51b9ba0699b617/graphql/e2e/auth/delete_mutation_test.go#L250)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Should we verify the state after the delete operation has gone through?
</blockquote></details>

I think `numUids` is sufficient after adding comments.
___
*[graphql/e2e/auth/delete_mutation_test.go, line 252 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLH3u-T356fm8jfZG4D:-MLHVmX49CHXHvB6YRly:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a73fd715e54131f536ca4ab6c51b9ba0699b617/graphql/e2e/auth/delete_mutation_test.go#L252)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

... deleted Questions for other test cases.
</blockquote></details>

Done.
___
*[graphql/e2e/auth/update_mutation_test.go, line 373 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLH4gB10TuKSqs9JoT4:-MLHVnAB67L9kw9nGRSl:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a73fd715e54131f536ca4ab6c51b9ba0699b617/graphql/e2e/auth/update_mutation_test.go#L373)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Add a description or comment string field which talks about what each case is testing otherwise I have to go look at the schema each time to try to understand whats happening.
</blockquote></details>

Done.
___
*[graphql/e2e/auth/update_mutation_test.go, line 390 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLH4MIA9oZY0wZf241m:-MLHVnuK2v0c-CG5mA2U:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a73fd715e54131f536ca4ab6c51b9ba0699b617/graphql/e2e/auth/update_mutation_test.go#L390)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

formatting is messed up
</blockquote></details>

Done.
___
*[graphql/e2e/auth/update_mutation_test.go, line 400 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLH4OTd70cOwYBSnFHg:-MLHVoUZ9aAdwDJ7Qw0W:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a73fd715e54131f536ca4ab6c51b9ba0699b617/graphql/e2e/auth/update_mutation_test.go#L400)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

just `params`
</blockquote></details>

Done.
___
*[graphql/e2e/auth/update_mutation_test.go, line 408 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLH4_7YDOH0wOGWye8n:-MLHVpID8Kyem4Z_b7nZ:b9qqsgz) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a73fd715e54131f536ca4ab6c51b9ba0699b617/graphql/e2e/auth/update_mutation_test.go#L408)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

We didn't really verify if the update actually updated the data. Should we do another query to verify the updated state?
</blockquote></details>

As per my understanding, the response of update mutations does the job.


<!-- Sent from Reviewable.io -->

2020-11-04 09:47 UTC, pawanrawal approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-:-MLHdkND7ACJnWgUsTFL:bg7igkv)* status: 2 of 8 files reviewed, 4 unresolved discussions (waiting on @MichaelJCompton and @minhaj-shakeel)

___
*[graphql/e2e/auth/add_mutation_test.go, line 225 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLHd4iwCXtm_qmsdv0F:-MLHd4iwCXtm_qmsdv0G:bevmo5e) ([raw file](https://github.com/dgraph-io/dgraph/blob/4fbaf02f30fa1b5308654fbb517cded3948483f8/graphql/e2e/auth/add_mutation_test.go#L225)):*
> ```Go
> 
> 	for _, tcase := range testCases {
> 		Params := &common.GraphQLParams{
> ```

Call it `params` with a small p.
___
*[graphql/e2e/auth/delete_mutation_test.go, line 242 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLH3pHCAX20KWL9U6P8:-MLHd0fj1POyIn-EUC0Q:bevmo5e) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a73fd715e54131f536ca4ab6c51b9ba0699b617/graphql/e2e/auth/delete_mutation_test.go#L242)):*
<details><summary><i>Previously, minhaj-shakeel wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Call it `params` with a small p.
___
*[graphql/e2e/auth/update_mutation_test.go, line 400 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLH4OTd70cOwYBSnFHg:-MLHdG_E9nUcW32ixOX6:bj8aebd) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a73fd715e54131f536ca4ab6c51b9ba0699b617/graphql/e2e/auth/update_mutation_test.go#L400)):*
<details><summary><i>Previously, minhaj-shakeel wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Go convention is to start variable names with small case unless they are exported
___
*[graphql/e2e/auth/update_mutation_test.go, line 408 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLH4_7YDOH0wOGWye8n:-MLHdScf2uUJGsuds5Ye:be1dwrd) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a73fd715e54131f536ca4ab6c51b9ba0699b617/graphql/e2e/auth/update_mutation_test.go#L408)):*
<details><summary><i>Previously, minhaj-shakeel wrote…</i></summary><blockquote>

As per my understanding, the response of update mutations does the job.
</blockquote></details>

Oh right, that should be fine.


<!-- Sent from Reviewable.io -->

2020-11-04 10:46 UTC, minhaj-shakeel reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6816)* status: 2 of 8 files reviewed, 4 unresolved discussions (waiting on @MichaelJCompton and @pawanrawal)

___
*[graphql/e2e/auth/add_mutation_test.go, line 225 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLHd4iwCXtm_qmsdv0F:-MLHrJoD8FBu3fmjHHzm:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4fbaf02f30fa1b5308654fbb517cded3948483f8/graphql/e2e/auth/add_mutation_test.go#L225)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Call it `params` with a small p.
</blockquote></details>

Done.
___
*[graphql/e2e/auth/update_mutation_test.go, line 408 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6816#-MLH4_7YDOH0wOGWye8n:-MLHrHKR75J4ONaJa8Ph:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a73fd715e54131f536ca4ab6c51b9ba0699b617/graphql/e2e/auth/update_mutation_test.go#L408)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Oh right, that should be fine.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-04 10:54 UTC, minhaj-shakeel commented
Fixes GRAPHQL-740.

2020-11-04 10:55 UTC, merged