Update docs for count queries
dgraph-io/dgraph pull request #6854
Opened 2020-11-05 18:29 UTC by vmrajas

Motivation:
There were certain changes to how count queries were implemented then what was mentioned in RFC. Specifically the following:
1. Name of Aggregate Fields has been changed to `<name>Aggregate` rather than `aggregate_<name>`
This PR reflects the same. It also adds two types to Reserved Names.

2020-11-05 19:37 UTC, bucanero requested changes
Just a minor change

2020-11-05 19:37 UTC, bucanero commented on wiki/content/graphql/queries/count.md
> +Dgraph automatically generates count queries for a given GraphQL schema, enabling you to `count` on predicates, edges and to count nodes satisfying certain criteria specified using a filter. Count Qu
```suggestion
Dgraph automatically generates count queries for a given GraphQL schema, enabling you to `count` on predicates, edges, and to count nodes satisfying certain criteria specified using a filter. Count Queries are also compatible with the `@auth` directive and honor the same authorization rules as `query`.
```

2020-11-05 19:38 UTC, bucanero approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6854#-:-MLOue1OEGEvKBCjvc3w:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @danielmai, @MichaelJCompton, @pawanrawal, and @vmrajas)



<!-- Sent from Reviewable.io -->

2020-11-06 11:10 UTC, vmrajas reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6854)* status: all files reviewed, 1 unresolved discussion (waiting on @bucanero, @danielmai, @MichaelJCompton, and @pawanrawal)

___
*[wiki/content/graphql/queries/count.md, line 9 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6854#-MLOet4_16DpR8tuVhD2-r1-9:-MLSF4pP69cHCB_8UO4g:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/27f6ed7eb664afa00511c327ef67e047538dc8b1/wiki/content/graphql/queries/count.md#L9)):*
<details><summary><i>Previously, bucanero (Damián Parrino) wrote…</i></summary><blockquote>

```suggestion
Dgraph automatically generates count queries for a given GraphQL schema, enabling you to `count` on predicates, edges, and to count nodes satisfying certain criteria specified using a filter. Count Queries are also compatible with the `@auth` directive and honor the same authorization rules as `query`.
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-06 11:12 UTC, merged