Docs (metrics) Document dgraph_txn_aborts_total metric
dgraph-io/dgraph pull request #6927
Opened 2020-11-20 06:37 UTC by aaroncarey

Document the new dgraph_txn_aborts_total metric that counts transaction aborts for a Dgraph server cluster.

Fixes /DGRAPH-2606

2020-11-20 06:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dgraph-io/dgraph?pullRequest=6927) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dgraph-io/dgraph?pullRequest=6927) before we can accept your contribution.<br/><hr/>**aaroncarey** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dgraph-io/dgraph?pullRequest=6927) it.</sub>

2020-11-20 06:49 UTC, danielmai requested changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6927)* status: all files reviewed, 1 unresolved discussion (waiting on @aaroncarey, @darkn3rd, @MichaelJCompton, and @OmarAyo)

___
*[wiki/content/deploy/metrics.md, line 66 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6927#-MMZPBV75UEJWwicgIDZ:-MMZPBV842yliaMwknTl:b-4chn7p) ([raw file](https://github.com/dgraph-io/dgraph/blob/b59d4884a756420a2acae3213c542cd99d5b36fa/wiki/content/deploy/metrics.md#L66)):*
> ```
> on the cluster.
> ```
Metrics are mostly local to that one Alpha. So, it's not right to say "cluster" here.

If users want to know the total number of aborts across the cluster, they can sum up this metric across all Alphas.


<!-- Sent from Reviewable.io -->

2020-11-20 08:03 UTC, danielmai approved these changes
One comment and then <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6927#-:-MMZPcv6-2FZsStoJt5x:b-q4nvk6)* status: all files reviewed, 1 unresolved discussion (waiting on @aaroncarey, @darkn3rd, @MichaelJCompton, and @OmarAyo)



<!-- Sent from Reviewable.io -->

2020-11-20 13:04 UTC, OmarAyo commented on wiki/content/deploy/metrics.md
> +and server node health - along with built-in metrics provided by Go. Dgraph metrics follow
I would avoid using the "dash" inside a sentence, I suggest replacing it with a coma or semicolon.

`.. and server node health, along with built-in metrics...`

2020-11-20 13:08 UTC, OmarAyo approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6927)* status: all files reviewed, 2 unresolved discussions (waiting on @aaroncarey, @darkn3rd, and @MichaelJCompton)



<!-- Sent from Reviewable.io -->

2020-11-20 15:12 UTC, aaroncarey reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6927)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @danielmai, @darkn3rd, @MichaelJCompton, and @OmarAyo)

___
*[wiki/content/deploy/metrics.md, line 66 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6927#-MMZPBV75UEJWwicgIDZ:-MMZrjqj8fLNjwv3umww:b-ncjvsr) ([raw file](https://github.com/dgraph-io/dgraph/blob/b59d4884a756420a2acae3213c542cd99d5b36fa/wiki/content/deploy/metrics.md#L66)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> on the cluster.
> ```
Metrics are mostly local to that one Alpha. So, it's not right to say "cluster" here.

If users want to know the total number of aborts across the cluster, they can sum up this metric across all Alphas.
</blockquote></details>

Fixed, thanks for the clarification :)
___
*[wiki/content/deploy/metrics.md, line 11 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6927#-MMZMmjTN5uiB5SDU4pE-r3-11:-MMaBjAHCt7eX4CWKIXO:bb6un1j) ([raw file](https://github.com/dgraph-io/dgraph/blob/9d10aaa676d542f24f0acb258606e47478d1c1c3/wiki/content/deploy/metrics.md#L11)):*
<details><summary><i>Previously, OmarAyo (OmarAyo) wrote…</i></summary><blockquote>

I would avoid using the "dash" inside a sentence, I suggest replacing it with a comma or semicolon.

`.. and server node health, along with built-in metrics...`
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2020-11-20 17:08 UTC, aaroncarey reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6927#-:-MMaLryL-3VEyspnI29g:bnfp4nl)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @aaroncarey, @danielmai, @darkn3rd, @MichaelJCompton, and @OmarAyo)



<!-- Sent from Reviewable.io -->

2020-11-20 17:30 UTC, aaroncarey reviewed
> Dismissed @OmarAyo from a discussion.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6927)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @aaroncarey, @danielmai, @darkn3rd, @MichaelJCompton, and @OmarAyo)



<!-- Sent from Reviewable.io -->

2020-11-20 17:31 UTC, aaroncarey reviewed
> Dismissed @danielmai from a discussion.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6927)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @aaroncarey, @darkn3rd, @MichaelJCompton, and @OmarAyo)



<!-- Sent from Reviewable.io -->

2020-11-20 17:31 UTC, aaroncarey reviewed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6927)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @darkn3rd and @MichaelJCompton)



<!-- Sent from Reviewable.io -->

2020-11-20 21:12 UTC, darkn3rd approved these changes
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6927)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @aaroncarey and @MichaelJCompton)

*[a discussion](https://reviewable.io/reviews/dgraph-io/dgraph/6927#-MMbV6qYC3jtZWi2GUzT:-MMbV6qYC3jtZWi2GUzU:bg7igkv) (no related file):*
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

---


<!-- Sent from Reviewable.io -->

2020-11-20 23:38 UTC, aaroncarey reviewed
> Reviewed 1 of 1 files at r6.
> Dismissed @darkn3rd from a discussion.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6927)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MichaelJCompton)



<!-- Sent from Reviewable.io -->

2020-11-21 00:52 UTC, aaroncarey commented
I have fixed my local client, but this PR is still blocked by CLA Assistant.

2020-11-21 01:12 UTC, aaroncarey reviewed
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6927)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MichaelJCompton)



<!-- Sent from Reviewable.io -->

2020-11-21 01:31 UTC, merged