fix(graphql): adding support for @id with type other than strings
dgraph-io/dgraph pull request #7019
Opened 2020-11-30 16:22 UTC by aman-bansal

This PR fixes GRAPHQL-762. Earlier we only can define String! datatypes with @id directive. This enables user to define @id directive with Int, Int64, Float datatypes too.

2020-12-02 07:24 UTC, abhimanyusinghgaur requested changes
In addition to e2e, we should also add mutation rewriting test cases for these.
Some common practices in tests:
* Data added in a test should be cleaned up at the end of the test (see `DeleteGqlType` in common/mutaiton.go)
* using `RequireNoGQLErrors(t, response)` instead of `require.Nil(t, response.Errors)`
* using `testutil.CompareJSON()` for comparing the expected output of query

> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7019#-:-MNXJoNNENPGmikSJjlT:brpne9a)* status: all files reviewed, 14 unresolved discussions (waiting on @aman-bansal, @MichaelJCompton, and @pawanrawal)

___
*[graphql/e2e/common/mutation.go, line 4598 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7019#-MNXEXBq6R_S4VSxfZH9:-MNXEXBq6R_S4VSxfZHA:bvvu2lt) ([raw file](https://github.com/dgraph-io/dgraph/blob/a29f31675386ec928390adbd9074008c341f7bf8/graphql/e2e/common/mutation.go#L4598)):*
> ```
> require.Nil(t, response.Errors)
> ```
RequireNoGQLErrors(t, response)
___
*[graphql/e2e/common/mutation.go, line 4607 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7019#-MNXHLEI8KbUCHGkHm2h:-MNXHLEJDSo_1-cJkUOQ:b-ofpkoo) ([raw file](https://github.com/dgraph-io/dgraph/blob/a29f31675386ec928390adbd9074008c341f7bf8/graphql/e2e/common/mutation.go#L4607)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> 	b, _ := response.Data.MarshalJSON()
> 	expBuffer := new(bytes.Buffer)
> 	require.NoError(t, json.Compact(expBuffer, []byte(expected)))
> 	actBuffer := new(bytes.Buffer)
> 	require.NoError(t, json.Compact(actBuffer, b))
> 	require.Equal(t, expBuffer.String(), actBuffer.String())
> ```
</details>

testutil.CompareJSON(t, expected, string(response.Data))
___
*[graphql/e2e/common/mutation.go, line 4614 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7019#-MNXHrOECquoxWWZrNs5:-MNXHrOECquoxWWZrNs6:b-y9xpr) ([raw file](https://github.com/dgraph-io/dgraph/blob/a29f31675386ec928390adbd9074008c341f7bf8/graphql/e2e/common/mutation.go#L4614)):*
> ```Go
> 	response = query.ExecuteAsPost(t, GraphqlURL)
> 	require.Contains(t, response.Errors.Error(), "already exists")
> }
> ```

cleanup the added data at the end of each test, there is a generic function `deleteGqlType` for helping with that.
___
*[graphql/e2e/common/mutation.go, line 4630 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7019#-MNXIG15--NuHdgqWEDO:-MNXIG15--NuHdgqWEDP:bana9ox) ([raw file](https://github.com/dgraph-io/dgraph/blob/a29f31675386ec928390adbd9074008c341f7bf8/graphql/e2e/common/mutation.go#L4630)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 	if response.Errors != nil {
> 		log.Print("error from servce is", response.Errors.Error())
> 	}
> 	require.Nil(t, response.Errors)
> ```
</details>

RequireNoGQLErrors(t, response)
___
*[graphql/e2e/common/mutation.go, line 4643 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7019#-MNXIJQcAA9HUSakm-nF:-MNXIJQcAA9HUSakm-nG:b-tns4g4) ([raw file](https://github.com/dgraph-io/dgraph/blob/a29f31675386ec928390adbd9074008c341f7bf8/graphql/e2e/common/mutation.go#L4643)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> 	b, _ := response.Data.MarshalJSON()
> 	expBuffer := new(bytes.Buffer)
> 	require.NoError(t, json.Compact(expBuffer, []byte(expected)))
> 	actBuffer := new(bytes.Buffer)
> 	require.NoError(t, json.Compact(actBuffer, b))
> 	require.Equal(t, expBuffer.String(), actBuffer.String())
> ```
</details>

testutil.CompareJSON
___
*[graphql/e2e/common/mutation.go, line 4670 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7019#-MNXIXvzChAuWJrEsaiT:-MNXIXw-5hLTwhSnrjcN:bvvu2lt) ([raw file](https://github.com/dgraph-io/dgraph/blob/a29f31675386ec928390adbd9074008c341f7bf8/graphql/e2e/common/mutation.go#L4670)):*
> ```
> require.Nil(t, response.Errors)
> ```
RequireNoGQLErrors(t, response)
___
*[graphql/e2e/common/mutation.go, line 4678 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7019#-MNXIZbgDQBxPtNEOSer:-MNXIZbgDQBxPtNEOSes:b-tns4g4) ([raw file](https://github.com/dgraph-io/dgraph/blob/a29f31675386ec928390adbd9074008c341f7bf8/graphql/e2e/common/mutation.go#L4678)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> 	b, _ := response.Data.MarshalJSON()
> 	expBuffer := new(bytes.Buffer)
> 	require.NoError(t, json.Compact(expBuffer, []byte(expected)))
> 	actBuffer := new(bytes.Buffer)
> 	require.NoError(t, json.Compact(actBuffer, b))
> 	require.Equal(t, expBuffer.String(), actBuffer.String())
> ```
</details>

testutil.CompareJSON
___
*[graphql/e2e/common/query.go, line 3200 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7019#-MNXIpvjCvmQFj1Srmdf:-MNXIpvjCvmQFj1Srmdg:bq0q9eb) ([raw file](https://github.com/dgraph-io/dgraph/blob/a29f31675386ec928390adbd9074008c341f7bf8/graphql/e2e/common/query.go#L3200)):*
> ```
> queryBook
> ```
can we instead use `getBook` type of queries for all these query tests, because an `@id` field should be allowed from get queries.
___
*[graphql/e2e/common/query.go, line 3213 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7019#-MNXIe7D5yOx03y9-9i6:-MNXIe7D5yOx03y9-9i7:bvvu2lt) ([raw file](https://github.com/dgraph-io/dgraph/blob/a29f31675386ec928390adbd9074008c341f7bf8/graphql/e2e/common/query.go#L3213)):*
> ```
> require.Nil(t, response.Errors)
> ```
RequireNoGQLErrors(t, response)
___
*[graphql/e2e/common/query.go, line 3224 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7019#-MNXJVqv7RJSU4KHmlBn:-MNXJVqv7RJSU4KHmlBo:b-tns4g4) ([raw file](https://github.com/dgraph-io/dgraph/blob/a29f31675386ec928390adbd9074008c341f7bf8/graphql/e2e/common/query.go#L3224)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> 	b, _ := response.Data.MarshalJSON()
> 	expBuffer := new(bytes.Buffer)
> 	require.NoError(t, json.Compact(expBuffer, []byte(expected)))
> 	actBuffer := new(bytes.Buffer)
> 	require.NoError(t, json.Compact(actBuffer, b))
> 	require.Equal(t, expBuffer.String(), actBuffer.String())
> ```
</details>

testutil.CompareJSON
___
*[graphql/resolve/mutation_rewriter.go, line 998 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7019#-MNXBKsY5ABb40ewvJ51:-MNXBKsY5ABb40ewvJ52:bt1rxf5) ([raw file](https://github.com/dgraph-io/dgraph/blob/a29f31675386ec928390adbd9074008c341f7bf8/graphql/resolve/mutation_rewriter.go#L998)):*
> ```
> "Int!"
> ```
`.Name()` will only return `Int`
`.String()` would give `Int!`
So, we can skip mentioning `Int!`, `Float!`, ... cases here.
___
*[graphql/resolve/mutation_rewriter.go, line 999 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7019#-MNXBsIX1OUCO2hh8nPh:-MNXBsIX1OUCO2hh8nPi:b-sn02j4) ([raw file](https://github.com/dgraph-io/dgraph/blob/a29f31675386ec928390adbd9074008c341f7bf8/graphql/resolve/mutation_rewriter.go#L999)):*
> ```
> xidVal.(int64)
> ```
should we also do an ok check for these conversions to int or float like we are doing for `String`?
___
*[graphql/resolve/mutation_rewriter.go, line 1003 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7019#-MNXCjQk3BTAHsZ_w_7F:-MNXCjQl2ZOuhzuNDDTh:b-g1syld) ([raw file](https://github.com/dgraph-io/dgraph/blob/a29f31675386ec928390adbd9074008c341f7bf8/graphql/resolve/mutation_rewriter.go#L1003)):*
> ```
> 			case "Int64!", "Int64":
> 				fallthrough
> ```
we can skip mentioning this, it would anyways fall to default case
___
*[graphql/schema/rules.go, line 2001 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7019#-MNX69c56HaTSPUUHjXo:-MNX69c56HaTSPUUHjXp:b-jp93rc) ([raw file](https://github.com/dgraph-io/dgraph/blob/a29f31675386ec928390adbd9074008c341f7bf8/graphql/schema/rules.go#L2001)):*
> ```
> "Type %s; Field %s: with @id directive must be of type String!, not %s"
> ```
... of type String!, Int!, Int64 or Float!


<!-- Sent from Reviewable.io -->

2020-12-03 14:06 UTC, aman-bansal reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7019)* status: 12 of 18 files reviewed, 14 unresolved discussions (waiting on @abhimanyusinghgaur, @MichaelJCompton, and @pawanrawal)

___
*[graphql/e2e/common/mutation.go, line 4598 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7019#-MNXEXBq6R_S4VSxfZH9:-MNcuMJJ8XGXw3F6bzJp:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a29f31675386ec928390adbd9074008c341f7bf8/graphql/e2e/common/mutation.go#L4598)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> require.Nil(t, response.Errors)
> ```
RequireNoGQLErrors(t, response)
</blockquote></details>

Done.
___
*[graphql/e2e/common/mutation.go, line 4607 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7019#-MNXHLEI8KbUCHGkHm2h:-MNcuOg26kfI9Z6n0Tl1:bm5zpuf) ([raw file](https://github.com/dgraph-io/dgraph/blob/a29f31675386ec928390adbd9074008c341f7bf8/graphql/e2e/common/mutation.go#L4607)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 	b, _ := response.Data.MarshalJSON()
> 	expBuffer := new(bytes.Buffer)
> 	require.NoError(t, json.Compact(expBuffer, []byte(expected)))
> 	actBuffer := new(bytes.Buffer)
> 	require.NoError(t, json.Compact(actBuffer, b))
> 	require.Equal(t, expBuffer.String(), actBuffer.String())
> ```
testutil.CompareJSON(t, expected, string(response.Data))
</blockquote></details>

I guess there is no need. require.JSONEq does map based matching. Any special case I am missing here?
___
*[graphql/e2e/common/mutation.go, line 4614 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7019#-MNXHrOECquoxWWZrNs5:-MNcuZ2C8FO3JDXUztG8:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a29f31675386ec928390adbd9074008c341f7bf8/graphql/e2e/common/mutation.go#L4614)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

cleanup the added data at the end of each test, there is a generic function `deleteGqlType` for helping with that.
</blockquote></details>

Done.
___
*[graphql/e2e/common/mutation.go, line 4630 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7019#-MNXIG15--NuHdgqWEDO:-MNcuZocA_Pa02of6G9_:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a29f31675386ec928390adbd9074008c341f7bf8/graphql/e2e/common/mutation.go#L4630)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 	if response.Errors != nil {
> 		log.Print("error from servce is", response.Errors.Error())
> 	}
> 	require.Nil(t, response.Errors)
> ```
RequireNoGQLErrors(t, response)
</blockquote></details>

Done.
___
*[graphql/e2e/common/mutation.go, line 4643 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7019#-MNXIJQcAA9HUSakm-nF:-MNcuaBWD7bWoImi_bgf:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a29f31675386ec928390adbd9074008c341f7bf8/graphql/e2e/common/mutation.go#L4643)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 	b, _ := response.Data.MarshalJSON()
> 	expBuffer := new(bytes.Buffer)
> 	require.NoError(t, json.Compact(expBuffer, []byte(expected)))
> 	actBuffer := new(bytes.Buffer)
> 	require.NoError(t, json.Compact(actBuffer, b))
> 	require.Equal(t, expBuffer.String(), actBuffer.String())
> ```
testutil.CompareJSON
</blockquote></details>

Done.
___
*[graphql/e2e/common/mutation.go, line 4670 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7019#-MNXIXvzChAuWJrEsaiT:-MNcub-P3N9wJCUYlnWh:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a29f31675386ec928390adbd9074008c341f7bf8/graphql/e2e/common/mutation.go#L4670)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> require.Nil(t, response.Errors)
> ```
RequireNoGQLErrors(t, response)
</blockquote></details>

Done.
___
*[graphql/e2e/common/mutation.go, line 4678 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7019#-MNXIZbgDQBxPtNEOSer:-MNcubdi88tHXx8wtXc5:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a29f31675386ec928390adbd9074008c341f7bf8/graphql/e2e/common/mutation.go#L4678)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 	b, _ := response.Data.MarshalJSON()
> 	expBuffer := new(bytes.Buffer)
> 	require.NoError(t, json.Compact(expBuffer, []byte(expected)))
> 	actBuffer := new(bytes.Buffer)
> 	require.NoError(t, json.Compact(actBuffer, b))
> 	require.Equal(t, expBuffer.String(), actBuffer.String())
> ```
testutil.CompareJSON
</blockquote></details>

Done.
___
*[graphql/e2e/common/query.go, line 3200 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7019#-MNXIpvjCvmQFj1Srmdf:-MNcucfv6hMDLgqWbRVz:b-6ddui6) ([raw file](https://github.com/dgraph-io/dgraph/blob/a29f31675386ec928390adbd9074008c341f7bf8/graphql/e2e/common/query.go#L3200)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> queryBook
> ```
can we instead use `getBook` type of queries for all these query tests, because an `@id` field should be allowed from get queries.
</blockquote></details>

Good catch. It's Done.
___
*[graphql/e2e/common/query.go, line 3213 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7019#-MNXIe7D5yOx03y9-9i6:-MNcugLlBhFFXolng-S4:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a29f31675386ec928390adbd9074008c341f7bf8/graphql/e2e/common/query.go#L3213)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> require.Nil(t, response.Errors)
> ```
RequireNoGQLErrors(t, response)
</blockquote></details>

Done.
___
*[graphql/e2e/common/query.go, line 3224 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7019#-MNXJVqv7RJSU4KHmlBn:-MNcuguy3-qgKR37LCiU:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a29f31675386ec928390adbd9074008c341f7bf8/graphql/e2e/common/query.go#L3224)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 	b, _ := response.Data.MarshalJSON()
> 	expBuffer := new(bytes.Buffer)
> 	require.NoError(t, json.Compact(expBuffer, []byte(expected)))
> 	actBuffer := new(bytes.Buffer)
> 	require.NoError(t, json.Compact(actBuffer, b))
> 	require.Equal(t, expBuffer.String(), actBuffer.String())
> ```
testutil.CompareJSON
</blockquote></details>

Done.
___
*[graphql/resolve/mutation_rewriter.go, line 998 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7019#-MNXBKsY5ABb40ewvJ51:-MNcunD6A42k8p3Q46kt:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a29f31675386ec928390adbd9074008c341f7bf8/graphql/resolve/mutation_rewriter.go#L998)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> "Int!"
> ```
`.Name()` will only return `Int`
`.String()` would give `Int!`
So, we can skip mentioning `Int!`, `Float!`, ... cases here.
</blockquote></details>

Done.
___
*[graphql/resolve/mutation_rewriter.go, line 999 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7019#-MNXBsIX1OUCO2hh8nPh:-MNcunfOBZP3aymrYRNS:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a29f31675386ec928390adbd9074008c341f7bf8/graphql/resolve/mutation_rewriter.go#L999)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> xidVal.(int64)
> ```
should we also do an ok check for these conversions to int or float like we are doing for `String`?
</blockquote></details>

Done.
___
*[graphql/resolve/mutation_rewriter.go, line 1003 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7019#-MNXCjQk3BTAHsZ_w_7F:-MNcuos70lqpKGLOcLRQ:bpt98ww) ([raw file](https://github.com/dgraph-io/dgraph/blob/a29f3167538 [...]

2020-12-07 10:56 UTC, pawanrawal requested changes
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7019)* status: 12 of 18 files reviewed, 15 unresolved discussions (waiting on @abhimanyusinghgaur, @aman-bansal, @MichaelJCompton, and @pawanrawal)

___
*[graphql/resolve/query_test.yaml, line 871 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7019#-MNwp_kt9mkAnDd75csf:-MNwp_kt9mkAnDd75csg:bjlty3v) ([raw file](https://github.com/dgraph-io/dgraph/blob/9dfd7797a6de2b659b93a9cbf0c36bc143b58619/graphql/resolve/query_test.yaml#L871)):*
> ```YAML
>   dgquery: |-
>     query {
>       queryAuthor(func: type(Author)) @filter((le(Author.dob, "2001-01-01") AND eq(Author.name, "A. N. Author") AND gt(Author.reputation, "2.5"))) {
> ```

Can you add a unit test for the float issue that you are talking about?


<!-- Sent from Reviewable.io -->

2020-12-08 07:20 UTC, aman-bansal reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7019)* status: 11 of 18 files reviewed, 15 unresolved discussions (waiting on @abhimanyusinghgaur, @MichaelJCompton, and @pawanrawal)

___
*[graphql/resolve/query_test.yaml, line 871 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7019#-MNwp_kt9mkAnDd75csf:-MO0DKKn7UQv-Wv_Oik1:bb7f2mf) ([raw file](https://github.com/dgraph-io/dgraph/blob/9dfd7797a6de2b659b93a9cbf0c36bc143b58619/graphql/resolve/query_test.yaml#L871)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Can you add a unit test for the float issue that you are talking about?
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2020-12-08 08:16 UTC, pawanrawal requested changes
We should also add some query and mutation rewriting unit tests for the new types that now support ID.

> Reviewed 2 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7019#-:-MO0Pm1E4iYlavbfr7Cv:b-pvo0he)* status: 13 of 18 files reviewed, 16 unresolved discussions (waiting on @abhimanyusinghgaur, @aman-bansal, @MichaelJCompton, and @pawanrawal)

___
*[graphql/e2e/common/mutation.go, line 4597 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7019#-MO0NTXX1GHMHZcqLFfJ:-MO0NTXX1GHMHZcqLFfK:bfxppcd) ([raw file](https://github.com/dgraph-io/dgraph/blob/107fb6c8de2a4c00324b7e60e6f50a0939554b98/graphql/e2e/common/mutation.go#L4597)):*
> ```Go
> 	response := query.ExecuteAsPost(t, GraphqlURL)
> 	RequireNoGQLErrors(t, response)
> 	var expected = `{
> ```

A shorthand notation is more common unless you want to explicitly define the type.
```
expected := `
...
`
```
___
*[graphql/schema/wrappers.go, line 1064 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7019#-MO0PVnyAsWoyKX4TwfH:-MO0PVnzCEqJfsJmNhki:b-71amsl) ([raw file](https://github.com/dgraph-io/dgraph/blob/107fb6c8de2a4c00324b7e60e6f50a0939554b98/graphql/schema/wrappers.go#L1064)):*
> ```Go
> 		var ok bool
> 		var xidArgVal string
> 		switch f.ArgValue(xidArgName).(type) {
> ```

You can also get the typecasted value v here and then you can use that directly for int64 and float64 case.


<!-- Sent from Reviewable.io -->

2020-12-14 07:29 UTC, aman-bansal reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7019)* status: 5 of 18 files reviewed, 16 unresolved discussions (waiting on @abhimanyusinghgaur, @MichaelJCompton, and @pawanrawal)

___
*[graphql/e2e/common/mutation.go, line 4597 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7019#-MO0NTXX1GHMHZcqLFfJ:-MOV8ekn0ehZtAWTUhkG:b8qoidj) ([raw file](https://github.com/dgraph-io/dgraph/blob/107fb6c8de2a4c00324b7e60e6f50a0939554b98/graphql/e2e/common/mutation.go#L4597)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

A shorthand notation is more common unless you want to explicitly define the type.
```
expected := `
...
`
```

</blockquote></details>

oh i started with different approach. forgot to change that. thanks
___
*[graphql/schema/wrappers.go, line 1064 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7019#-MO0PVnyAsWoyKX4TwfH:-MOV8o4t9qMwBnbIWEQK:bisoqsf) ([raw file](https://github.com/dgraph-io/dgraph/blob/107fb6c8de2a4c00324b7e60e6f50a0939554b98/graphql/schema/wrappers.go#L1064)):*
>  way in my opinion. We are handling Int64 as special case. This makes it known that Int64 is handled in different way.
oh yes right! Done


<!-- Sent from Reviewable.io -->

2020-12-14 10:37 UTC, pawanrawal approved these changes
> Reviewed 5 of 16 files at r1, 13 of 13 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7019)* status: all files reviewed, 14 unresolved discussions (waiting on @abhimanyusinghgaur and @MichaelJCompton)



<!-- Sent from Reviewable.io -->

2020-12-14 12:40 UTC, merged