GraphQL(Docs): Documentation for Aggregate Queries
dgraph-io/dgraph pull request #7104
Opened 2020-12-10 08:53 UTC by aaroncarey

Fixes https://dgraph.atlassian.net/browse/GRAPHQL-890

2020-12-10 17:59 UTC, vmrajas requested changes
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7104)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @aaroncarey, @bucanero, @danielmai, @MichaelJCompton, and @vmrajas)

___
*[wiki/content/graphql/queries/aggregate.md, line 2 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOCnNFa0_bZ3Za3-GJH:-MOCnNFa0_bZ3Za3-GJI:bocc5p3) ([raw file](https://github.com/dgraph-io/dgraph/blob/4168b2d975086d82ffa919e2a00e0c9ea488c441/wiki/content/graphql/queries/aggregate.md#L2)):*
> ```Markdown
> +++
> title = "Aggregate Queries"
> ```

I believe these docs about aggregate queries and count queries docs have a lot in common. Count in a way is part of aggregate query. Can we have a single doc for aggregate queries (containing both count and other aggregate functions). Maybe, count can have a separate section in it.
___
*[wiki/content/graphql/queries/aggregate.md, line 11 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOClJgJ72XZiHETYyRF:-MOClJgJ72XZiHETYyRG:b-rkhg7m) ([raw file](https://github.com/dgraph-io/dgraph/blob/4168b2d975086d82ffa919e2a00e0c9ea488c441/wiki/content/graphql/queries/aggregate.md#L11)):*
> ```Markdown
> Dgraph automatically generates aggregate queries for GraphQL schemas,
> letting you calculate the maximum, minimum, sum and average of specified fields,
> as well as nodes that meet criteria specified using a filter.
> ```

This feels a bit off. I believe this has been taken from count query docs. It may be better if we can break this into two sentences.
___
*[wiki/content/graphql/queries/aggregate.md, line 25 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOCmvdoEQ1DqTNeOeJM:-MOCmvdoEQ1DqTNeOeJN:bjl5rk4) ([raw file](https://github.com/dgraph-io/dgraph/blob/4168b2d975086d82ffa919e2a00e0c9ea488c441/wiki/content/graphql/queries/aggregate.md#L25)):*
> ```Markdown
> field's type (`Int`, `Float`, `String` or `Datetime`), as follows:
> 
> * **`<field name>Max`** and **`<field name>Min`**: generated for fields typed as
> ```

Good to see this. 
___
*[wiki/content/graphql/queries/aggregate.md, line 32 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOCmITI3FJrmkYNVIoz:-MOCmITI3FJrmkYNVIp-:b-rv78k4) ([raw file](https://github.com/dgraph-io/dgraph/blob/4168b2d975086d82ffa919e2a00e0c9ea488c441/wiki/content/graphql/queries/aggregate.md#L32)):*
> ```Markdown
> #### Examples
> 
> Example: Fetch the minimum, maximum, and average number of `posts` per
> ```

Even this is find average number of posts for `all` authors. Maybe in this examples, you can include some filter to indicate that filters can also be used with aggregate queries. Something like min, max, avg posts for authors whose name is `John` or something similar.
___
*[wiki/content/graphql/queries/aggregate.md, line 67 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOCn2qPAOT0GwO8GVdd:-MOCn2qPAOT0GwO8GVde:b-sg2zur) ([raw file](https://github.com/dgraph-io/dgraph/blob/4168b2d975086d82ffa919e2a00e0c9ea488c441/wiki/content/graphql/queries/aggregate.md#L67)):*
> ```Markdown
> * **`<field name>Max`** and **`<field name>Min`**: generated for fields typed as
> `Int`, `Float`, `String` or `Datetime`.
> * **`<field name>Sum`** and **`<field name>Avg`**: generated for fields typed as
> ```

As this is a repetition of the above generated aggregate fields. Can we have a single one at the top.
___
*[wiki/content/graphql/queries/aggregate.md, line 89 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOCnKh4BxaiA20EG-GG:-MOCnKh4BxaiA20EG-GH:b-5vsc5r) ([raw file](https://github.com/dgraph-io/dgraph/blob/4168b2d975086d82ffa919e2a00e0c9ea488c441/wiki/content/graphql/queries/aggregate.md#L89)):*
> ```Markdown
> 
> Example: Fetch the date of the most recent post with a `score` greater than
> `10` for all authors, along with the author's `name`.
> ```

This is a good example. 


<!-- Sent from Reviewable.io -->

2020-12-10 18:52 UTC, bucanero reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7104)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @aaroncarey, @bucanero, @danielmai, @MichaelJCompton, and @vmrajas)

___
*[wiki/content/graphql/queries/aggregate.md, line 2 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOCnNFa0_bZ3Za3-GJH:-MOCzWyi8hhmBpl_ZSt_:bwu2o1g) ([raw file](https://github.com/dgraph-io/dgraph/blob/4168b2d975086d82ffa919e2a00e0c9ea488c441/wiki/content/graphql/queries/aggregate.md#L2)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

I believe these docs about aggregate queries and count queries docs have a lot in common. Count in a way is part of aggregate query. Can we have a single doc for aggregate queries (containing both count and other aggregate functions). Maybe, count can have a separate section in it.
</blockquote></details>

I agree with @vmrajas, I think that "count" could be part of the same "Aggregate" article, so merging them could help to reduce content duplication.


<!-- Sent from Reviewable.io -->

2020-12-10 19:40 UTC, aaroncarey reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7104)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @aaroncarey, @bucanero, @danielmai, @MichaelJCompton, and @vmrajas)

___
*[wiki/content/graphql/queries/aggregate.md, line 2 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOCnNFa0_bZ3Za3-GJH:-MOCuPkp1RiMQhZrsYuV:bav8pti) ([raw file](https://github.com/dgraph-io/dgraph/blob/4168b2d975086d82ffa919e2a00e0c9ea488c441/wiki/content/graphql/queries/aggregate.md#L2)):*
<details><summary><i>Previously, bucanero (Damián Parrino) wrote…</i></summary><blockquote>

I agree with @vmrajas, I think that "count" could be part of the same "Aggregate" article, so merging them could help to reduce content duplication.
</blockquote></details>

OK, sounds good; That will be in an upcoming commit before I submit this PR.
___
*[wiki/content/graphql/queries/aggregate.md, line 11 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOClJgJ72XZiHETYyRF:-MOCutAD4wLYJfv3a_Uj:bezzcft) ([raw file](https://github.com/dgraph-io/dgraph/blob/4168b2d975086d82ffa919e2a00e0c9ea488c441/wiki/content/graphql/queries/aggregate.md#L11)):*
> ```
> Dgraph automatically generates aggregate queries for GraphQL schemas,
> letting you calculate the maximum, minimum, sum, and average of specified fields.
> ```
So, should we just drop the last part of the sentence, having it read as shown above? Or, would you suggest including a second sentence? (i.e. "You can also calculate aggregates for nodes that meet criteria specified using a filter.")

I'm not 100% sure what to change based on your comment, thanks for clarifying further.
___
*[wiki/content/graphql/queries/aggregate.md, line 25 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOCmvdoEQ1DqTNeOeJM:-MOCvO5hCGidXMLnxJuH:b-unzs0k) ([raw file](https://github.com/dgraph-io/dgraph/blob/4168b2d975086d82ffa919e2a00e0c9ea488c441/wiki/content/graphql/queries/aggregate.md#L25)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

Good to see this. 
</blockquote></details>

Thanks! More thoughts about this bit of information are below.
___
*[wiki/content/graphql/queries/aggregate.md, line 32 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOCmITI3FJrmkYNVIoz:-MOCvVEz6ZiTiEGAZfza:b99p872) ([raw file](https://github.com/dgraph-io/dgraph/blob/4168b2d975086d82ffa919e2a00e0c9ea488c441/wiki/content/graphql/queries/aggregate.md#L32)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

Even this is find average number of posts for `all` authors. Maybe in this examples, you can include some filter to indicate that filters can also be used with aggregate queries. Something like min, max, avg posts for authors whose name is `John` or something similar.
</blockquote></details>

Thanks for catching this error on my part. I'll update the lead-in text to reflect that this is the average number of posts for all authors in an upcoming commit ("Fetch the average number of posts for all authors"), and adjust the syntax of the query to match.

I'm happy to change the example to "Fetch the minimum, maximum and average number of posts for authors whose names contain John", but in the interests of speed and efficiency I'd ask you to provide the query syntax for that example (I'm sure that it would occur to you more quickly :) ).
___
*[wiki/content/graphql/queries/aggregate.md, line 67 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOCn2qPAOT0GwO8GVdd:-MOCvoKL2maBLUwRAiXO:b-fq1q78) ([raw file](https://github.com/dgraph-io/dgraph/blob/4168b2d975086d82ffa919e2a00e0c9ea488c441/wiki/content/graphql/queries/aggregate.md#L67)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

As this is a repetition of the above generated aggregate fields. Can we have a single one at the top.
</blockquote></details>

I see your point. I tried the structure you are suggesting in an earlier draft (mentioning it once, at the top), and I ended up including this information without a lead-in that provides appropriate context, or adding a lead-in that was confusing and repeated information stated later in each section. I also don't want readers to miss this if they only read a portion of the file. I strive to minimize duplication, but the fact that readers generally read only portions of a page requires duplication in some cases. If it were a longer discussion, I would heartily agree about moving it to a standalone section in the doc.

But, looking at this again I think that it could be a shorter "note" present in each section, or covered in fewer words with equal clarity. I'm working on that in an upcoming commit. Thanks for encouraging me to take another look at this :)

As an aside, we'd like to implement re-usable markdown snippets at some point, so that repeated notes can be managed in a single place for easier maintenance and improved consistency :)
___
*[wiki/content/graphql/queries/aggregate.md, line 89 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOCnKh4BxaiA20EG-GG:-MOCwPUJ0shfhpxDJkMi:b-ucfknh) ([raw file](https://github.com/dgraph-io/dgraph/blob/4168b2d975086d82ffa919e2a00e0c9ea488c441/wiki/content/graphql/queries/aggregate.md#L89)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

This is a good example. 
</blockquote></details>

Thanks!


<!-- Sent from Reviewable.io -->

2020-12-11 01:23 UTC, aaroncarey reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7104)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @aaroncarey, @danielmai, @MichaelJCompton, and @vmrajas)

___
*[wiki/content/graphql/queries/aggregate.md, line 2 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOCnNFa0_bZ3Za3-GJH:-MOEJaILCtjduHJyCd1f:b-ulv84q) ([raw file](https://github.com/dgraph-io/dgraph/blob/4168b2d975086d82ffa919e2a00e0c9ea488c441/wiki/content/graphql/queries/aggregate.md#L2)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

OK, sounds good; That will be in an upcoming commit before I submit this PR.
</blockquote></details>

Holding off on this change until I have clarity on how to resolve the next comment.
___
*[wiki/content/graphql/queries/aggregate.md, line 32 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOCmITI3FJrmkYNVIoz:-MOECjB130uE_xMYWw8i:b-56e9bu) ([raw file](https://github.com/dgraph-io/dgraph/blob/4168b2d975086d82ffa919e2a00e0c9ea488c441/wiki/content/graphql/queries/aggregate.md#L32)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

Thanks for catching this error on my part. I'll update the lead-in text to reflect that this is the average number of posts for all authors in an upcoming commit ("Fetch the average number of posts for all authors"), and adjust the syntax of the query to match.

I'm happy to change the example to "Fetch the minimum, maximum and average number of posts for authors whose names contain John", but in the interests of speed and efficiency I'd ask you to provide the query syntax for that example (I'm sure that it would occur to you more quickly :) ).
</blockquote></details>

In my latest commit, I changed the examples for aggregate queries at root to:

"Fetch the average number of `posts` per `Author`"

and

"Fetch the total number of `posts` by all authors, and the maximum number of `posts` by any single `Author`:"

I'm happy to add a third example with a filter (as you suggest above), if you have the query syntax handy :)
___
*[wiki/content/graphql/queries/aggregate.md, line 67 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOCn2qPAOT0GwO8GVdd:-MOEH6e0D67y0ilHBdYy:b-svgb5q) ([raw file](https://github.com/dgraph-io/dgraph/blob/4168b2d975086d82ffa919e2a00e0c9ea488c441/wiki/content/graphql/queries/aggregate.md#L67)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

I see your point. I tried the structure you are suggesting in an earlier draft (mentioning it once, at the top), and I ended up including this information without a lead-in that provides appropriate context, or adding a lead-in that was confusing and repeated information stated later in each section. I also don't want readers to miss this if they only read a portion of the file. I strive to minimize duplication, but the fact that readers generally read only portions of a page requires duplication in some cases. If it were a longer discussion, I would heartily agree about moving it to a standalone section in the doc.

But, looking at this again I think that it could be a shorter "note" present in each section, or covered in fewer words with equal clarity. I'm working on that in an upcoming commit. Thanks for encouraging me to take another look at this :)

As an aside, we'd like to implement re-usable markdown snippets at some point, so that repeated notes can be managed in a single place for easier maintenance and improved consistency :)
</blockquote></details>

I refactored this into shorter "notes" in each section.


<!-- Sent from Reviewable.io -->

2020-12-11 02:05 UTC, aaroncarey reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7104)* status: 0 of 8 files reviewed, 6 unresolved discussions (waiting on @aaroncarey, @danielmai, @MichaelJCompton, and @vmrajas)

___
*[wiki/content/graphql/queries/aggregate.md, line 2 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOCnNFa0_bZ3Za3-GJH:-MOEWoK1-QqmZul2BAjj:b6tsdfc) ([raw file](https://github.com/dgraph-io/dgraph/blob/4168b2d975086d82ffa919e2a00e0c9ea488c441/wiki/content/graphql/queries/aggregate.md#L2)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

Holding off on this change until I have clarity on how to resolve the next comment.
</blockquote></details>

Actually, I went ahead and combined Aggregate Queries and Count Queries in the latest commit. Discussing these in a single file without confusing readers required me to use a new term ("advanced aggregate queries" - the newer capabilities that behave differently than `count`). I tried writing it without using this, and the draft became unwieldy, so we definitely need a shorthand to refer the "non-count aggregate queries" in this file.
___
*[wiki/content/graphql/queries/aggregate.md, line 11 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOClJgJ72XZiHETYyRF:-MOEWSTG3y7CuUN1Sien:bazk4o) ([raw file](https://github.com/dgraph-io/dgraph/blob/4168b2d975086d82ffa919e2a00e0c9ea488c441/wiki/content/graphql/queries/aggregate.md#L11)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

> ```
> Dgraph automatically generates aggregate queries for GraphQL schemas,
> letting you calculate the maximum, minimum, sum, and average of specified fields.
> ```
So, should we just drop the last part of the sentence, having it read as shown above? Or, would you suggest including a second sentence? (i.e. "You can also calculate aggregates for nodes that meet criteria specified using a filter.")

I'm not 100% sure what to change based on your comment, thanks for clarifying further.
</blockquote></details>

Updated using what I provided above. Let me know if this needs further clarification after my most recent commit where I made the edit shown above.


<!-- Sent from Reviewable.io -->

2020-12-11 02:06 UTC, aaroncarey reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7104)* status: 0 of 8 files reviewed, 6 unresolved discussions (waiting on @danielmai, @MichaelJCompton, and @vmrajas)

___
*[wiki/content/graphql/queries/aggregate.md, line 2 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOCnNFa0_bZ3Za3-GJH:-MOEY4Tc7am4UONYbeb8:b-eapff3) ([raw file](https://github.com/dgraph-io/dgraph/blob/4168b2d975086d82ffa919e2a00e0c9ea488c441/wiki/content/graphql/queries/aggregate.md#L2)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

Actually, I went ahead and combined Aggregate Queries and Count Queries in the latest commit. Discussing these in a single file without confusing readers required me to use a new term ("advanced aggregate queries" - the newer capabilities that behave differently than `count`). I tried writing it without using this, and the draft became unwieldy, so we definitely need a shorthand to refer the "non-count aggregate queries" in this file.
</blockquote></details>

Resolved.


<!-- Sent from Reviewable.io -->

2020-12-11 06:27 UTC, aaroncarey reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7104)* status: 0 of 8 files reviewed, 7 unresolved discussions (waiting on @bucanero, @danielmai, @MichaelJCompton, and @vmrajas)

___
*[wiki/content/graphql/queries/skip-include.md, line 3 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOFTUgeE-l3Ozm4gO4v:-MOFTUgfBkgzEZAK7rKH:bixjozi) ([raw file](https://github.com/dgraph-io/dgraph/blob/11e78b26816650b4d409fe0ac63cd286a281acc2/wiki/content/graphql/queries/skip-include.md#L3)):*
> ```
> 9
> ```
Here and elsewhere, I updated the "weight" metadata for the other files under /graphql/queries/ to avoid some build errors caused by duplicate numbers. I left the order as it was rendering on the site before, with "Aggregate Queries" taking the place of "Count Queries"


<!-- Sent from Reviewable.io -->

2020-12-11 09:21 UTC, aaroncarey reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7104)* status: 0 of 8 files reviewed, 7 unresolved discussions (waiting on @bucanero, @danielmai, @MichaelJCompton, and @vmrajas)

___
*[wiki/content/graphql/queries/aggregate.md, line 11 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOClJgJ72XZiHETYyRF:-MOG1d6p8ivjU88PkDzM:b-h4b2lk) ([raw file](https://github.com/dgraph-io/dgraph/blob/4168b2d975086d82ffa919e2a00e0c9ea488c441/wiki/content/graphql/queries/aggregate.md#L11)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

Updated using what I provided above. Let me know if this needs further clarification after my most recent commit where I made the edit shown above.
</blockquote></details>

I adjusted this a bit more - we now cover all of this at the top of the page, including the part about filters.
___
*[wiki/content/graphql/queries/aggregate.md, line 32 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOCmITI3FJrmkYNVIoz:-MOG5cPu8RJRkONcPbR8:bz4789c) ([raw file](https://github.com/dgraph-io/dgraph/blob/4168b2d975086d82ffa919e2a00e0c9ea488c441/wiki/content/graphql/queries/aggregate.md#L32)):*
> avg posts for authors whose name is John or something similar.
I went with "Fetch the average number of `posts` for authors with more than 20
`friends`" in my latest commit.


<!-- Sent from Reviewable.io -->

2020-12-11 15:02 UTC, vmrajas requested changes
Thanks for updating the PR.
I believe the aggregate queries documentation is almost there and feels good. With the comments addressed it should be good to go.

There is one more note which should be part of the documentation (maybe at the end).
It is regarding the fact that if aggregate queries are queried on empty data, it returns null. 
So, in the below example say suppose there are no nodes of type Author, the aggregateAuthor query will return null. Similarly, if an author has not written any posts, the field postsAggregate will be null for that author.

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-:-MOHIpZp6XfZEykWovuJ:b-o8prux)* status: 0 of 8 files reviewed, 7 unresolved discussions (waiting on @aaroncarey, @bucanero, @danielmai, @MichaelJCompton, and @vmrajas)

___
*[wiki/content/graphql/queries/aggregate.md, line 10 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOHGDq0DJpsPTSHbiOJ:-MOHGDq0DJpsPTSHbiOK:b7i7kb3) ([raw file](https://github.com/dgraph-io/dgraph/blob/cd007398e00973095bb0043e979291ef08584939/wiki/content/graphql/queries/aggregate.md#L10)):*
> ```Markdown
> 
> Dgraph automatically generates aggregate queries for GraphQL schemas.
> Aggregate queries fetch aggregate data, and including the following:
> ```

Is the `and` necessary ? . I may be wrong but 'Aggregate Queries fetch aggregate data, including the following:' feels more correct. Do revise it if you think this is grammatically not correct.
___
*[wiki/content/graphql/queries/aggregate.md, line 25 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOHIQ1D24LuBHeKnqS1:-MOHIQ1D24LuBHeKnqS2:b-bhvp4t) ([raw file](https://github.com/dgraph-io/dgraph/blob/cd007398e00973095bb0043e979291ef08584939/wiki/content/graphql/queries/aggregate.md#L25)):*
> ```Markdown
> For every `type` defined in a GraphQL schema, Dgraph generates an aggregate query
> `aggregate<type name>`. This query includes a `count` field, as well as
> advanced aggregate query fields, discussed below.
> ```

Also link 'below' to the aggregate queries at root section below.
___
*[wiki/content/graphql/queries/aggregate.md, line 59 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOHIE10CaniUbocdnR3:-MOHIE10CaniUbocdnR4:boe752b) ([raw file](https://github.com/dgraph-io/dgraph/blob/cd007398e00973095bb0043e979291ef08584939/wiki/content/graphql/queries/aggregate.md#L59)):*
> ```Markdown
> is of type `List[Type/Interface]` inside `query<type name>` queries, allowing
> you to do a `count` on fields, or to use the advanced aggregate queries
> discussed below.
> ```

Also, link 'below' to the aggregate queries at child section below.
___
*[wiki/content/graphql/queries/aggregate.md, line 97 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOHHwhMBA0OW-zlGpdO:-MOHHwhMBA0OW-zlGpdP:b-3ugteq) ([raw file](https://github.com/dgraph-io/dgraph/blob/cd007398e00973095bb0043e979291ef08584939/wiki/content/graphql/queries/aggregate.md#L97)):*
> ```Markdown
> 
> For every `type` defined in the GraphQL schema, Dgraph generates an aggregate
> query `aggregate<type name>`. This query includes a `count` field, and also
> ```

This feels like a complete repeat of count at Root section above. Maybe you can mention the count part at the end of this description and include a link to count at root.
___
*[wiki/content/graphql/queries/aggregate.md, line 112 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOHHQB9-zV_YIlKKy0l:-MOHHQBA7rKkfiLwWPB9:bdz9wfg) ([raw file](https://github.com/dgraph-io/dgraph/blob/cd007398e00973095bb0043e979291ef08584939/wiki/content/graphql/queries/aggregate.md#L112)):*
> ```Markdown
> #### Examples
> 
> Example: Fetch the average number of `posts` written by all authors:
> ```

This is not a valid example as posts field contains information about posts of an author and may confuse Users. I suggest you use something like `numPostsMax` and `numPostsAvg` . 
___
*[wiki/content/graphql/queries/aggregate.md, line 152 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOHIbmj9jcXMTLslAZS:-MOHIbmj9jcXMTLslAZT:b-sp4xmw) ([raw file](https://github.com/dgraph-io/dgraph/blob/cd007398e00973095bb0043e979291ef08584939/wiki/content/graphql/queries/aggregate.md#L152)):*
> ```Markdown
> ### Advanced aggregate queries for child nodes
> 
> Dgraph also defines aggregate `<field name>Aggregate` fields for child nodes
> ```

This description is well written. Maybe you can use something similar for advanced aggregate queries at root.


<!-- Sent from Reviewable.io -->

2020-12-11 18:13 UTC, bucanero commented on wiki/content/graphql/queries/aggregate.md
> +advanced aggregate query fields, discussed below.
```suggestion
[advanced aggregate query fields](#advanced-aggregate-queries-at-root).
```

2020-12-11 18:15 UTC, bucanero commented on wiki/content/graphql/queries/aggregate.md
> +discussed below.
```suggestion
you to do a `count` on fields, or to use the [advanced aggregate queries](#advanced-aggregate-queries-for-child-nodes).
```

2020-12-11 18:18 UTC, bucanero approved these changes
See my suggestion to add links to the aggregate sections (for accessibility).

2020-12-11 19:07 UTC, aaroncarey reviewed
Thanks to both of you for your feedback! I added a section on how null data is handled, directly based on the comment that vmrajas provided above, and the PR that he linked me to. I also addressed the other feedback (in one case, by cutting an example that wasn't required because we already have a filter and non-filter example in that section).

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-:-MOIBHVPAWUdPVwF6U4y:b-okye9m)* status: 0 of 8 files reviewed, 8 unresolved discussions (waiting on @bucanero, @danielmai, @MichaelJCompton, and @vmrajas)

___
*[wiki/content/graphql/queries/aggregate.md, line 10 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOHGDq0DJpsPTSHbiOJ:-MOI48NdDd9QHeAplsWW:b-u7rd0e) ([raw file](https://github.com/dgraph-io/dgraph/blob/cd007398e00973095bb0043e979291ef08584939/wiki/content/graphql/queries/aggregate.md#L10)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

Is the `and` necessary ? . I may be wrong but 'Aggregate Queries fetch aggregate data, including the following:' feels more correct. Do revise it if you think this is grammatically not correct.
</blockquote></details>

Good catch; this occurred as part of last night's edit and I missed it in my read-through. Fixed.
___
*[wiki/content/graphql/queries/aggregate.md, line 25 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOHIQ1D24LuBHeKnqS1:-MOI4HdJ3-mAo5tdlpLp:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/cd007398e00973095bb0043e979291ef08584939/wiki/content/graphql/queries/aggregate.md#L25)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

Also link 'below' to the aggregate queries at root section below.
</blockquote></details>

Done.
___
*[wiki/content/graphql/queries/aggregate.md, line 25 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOAqojTLLTAvNb1e2Va-r4-25:-MOI4IrH7hdiHrws3jVG:b-gj45t5) ([raw file](https://github.com/dgraph-io/dgraph/blob/cd007398e00973095bb0043e979291ef08584939/wiki/content/graphql/queries/aggregate.md#L25)):*
<details><summary><i>Previously, bucanero (Damián Parrino) wrote…</i></summary><blockquote>

```suggestion
[advanced aggregate query fields](#advanced-aggregate-queries-at-root).
```
</blockquote></details>

Done - thanks for the suggested edit :)
___
*[wiki/content/graphql/queries/aggregate.md, line 59 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOHIE10CaniUbocdnR3:-MOI4Lq45P1IFZn3o8oa:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/cd007398e00973095bb0043e979291ef08584939/wiki/content/graphql/queries/aggregate.md#L59)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

Also, link 'below' to the aggregate queries at child section below.
</blockquote></details>

Done.
___
*[wiki/content/graphql/queries/aggregate.md, line 59 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOAqojTLLTAvNb1e2Va-r4-59:-MOI4MXXE5Wgx_IXQQ65:bbzwh4o) ([raw file](https://github.com/dgraph-io/dgraph/blob/cd007398e00973095bb0043e979291ef08584939/wiki/content/graphql/queries/aggregate.md#L59)):*
<details><summary><i>Previously, bucanero (Damián Parrino) wrote…</i></summary><blockquote>

```suggestion
you to do a `count` on fields, or to use the [advanced aggregate queries](#advanced-aggregate-queries-for-child-nodes).
```
</blockquote></details>

Done - thanks for the suggested edit
___
*[wiki/content/graphql/queries/aggregate.md, line 97 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOHHwhMBA0OW-zlGpdO:-MOI54il8eBFXLAJWkZz:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/cd007398e00973095bb0043e979291ef08584939/wiki/content/graphql/queries/aggregate.md#L97)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

This feels like a complete repeat of count at Root section above. Maybe you can mention the count part at the end of this description and include a link to count at root.
</blockquote></details>

Done.
___
*[wiki/content/graphql/queries/aggregate.md, line 112 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOHHQB9-zV_YIlKKy0l:-MOHlSO139aSrI5K1AbV:b7z2ebv) ([raw file](https://github.com/dgraph-io/dgraph/blob/cd007398e00973095bb0043e979291ef08584939/wiki/content/graphql/queries/aggregate.md#L112)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

This is not a valid example as posts field contains information about posts of an author and may confuse Users. I suggest you use something like `numPostsMax` and `numPostsAvg` . 
</blockquote></details>

Thanks for flagging that there is an issue with this example. I'm not certain how best to alter the syntax and description here. But, we have two examples in this section already - with and without filters. So, in the interest of completing this PR by today's deadline (per our TPM), I removed this example. We can enhance this page with additional examples in a follow-up PR.
___
*[wiki/content/graphql/queries/aggregate.md, line 152 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOHIbmj9jcXMTLslAZS:-MOI7GMg5f_RNhjh1V2Y:b-xfsz6i) ([raw file](https://github.com/dgraph-io/dgraph/blob/cd007398e00973095bb0043e979291ef08584939/wiki/content/graphql/queries/aggregate.md#L152)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

This description is well written. Maybe you can use something similar for advanced aggregate queries at root.
</blockquote></details>

Thanks! I revised the description of "Advanced aggregate queries at root" to make it clearer.


<!-- Sent from Reviewable.io -->

2020-12-11 19:17 UTC, vmrajas approved these changes
LGTM . Just added a minor comment regarding the replacements for postsAvg, postsMax, postsSum. 

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-:-MOIE1WS1T-ejpxjz8_E:b-51ig56)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @aaroncarey, @bucanero, @danielmai, and @MichaelJCompton)

___
*[wiki/content/graphql/queries/aggregate.md, line 112 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOHHQB9-zV_YIlKKy0l:-MOIDeGG0DyMqW5J3uJ2:b-w8sibo) ([raw file](https://github.com/dgraph-io/dgraph/blob/cd007398e00973095bb0043e979291ef08584939/wiki/content/graphql/queries/aggregate.md#L112)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

Thanks for flagging that there is an issue with this example. I'm not certain how best to alter the syntax and description here. But, we have two examples in this section already - with and without filters. So, in the interest of completing this PR by today's deadline (per our TPM), I removed this example. We can enhance this page with additional examples in a follow-up PR.
</blockquote></details>

I don't see the example being removed. There is no need to replace the example. Just replace the following things and it will be good enough.
postsSum by numPostsSum
postsMax by numPostsMax
postsAvg by numPostsAvg 
___
*[wiki/content/graphql/queries/aggregate.md, line 193 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOIDzul5nm1cnF6jLlx:-MOIDzul5nm1cnF6jLly:bff5zk8) ([raw file](https://github.com/dgraph-io/dgraph/blob/34adb9298984f56215935fa968d8ae4dc16cfce5/wiki/content/graphql/queries/aggregate.md#L193)):*
> ```Markdown
> ### Aggregate queries on null data
> 
> Aggregate queries against empty data return `null`. This is true for both the
> ```

This looks good.


<!-- Sent from Reviewable.io -->

2020-12-11 20:08 UTC, aaroncarey reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7104)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @bucanero, @danielmai, @MichaelJCompton, and @vmrajas)

___
*[wiki/content/graphql/queries/aggregate.md, line 112 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOHHQB9-zV_YIlKKy0l:-MOIP4m19LHZInPGRuMt:belyvtx) ([raw file](https://github.com/dgraph-io/dgraph/blob/cd007398e00973095bb0043e979291ef08584939/wiki/content/graphql/queries/aggregate.md#L112)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

I don't see the example being removed. There is no need to replace the example. Just replace the following things and it will be good enough.
postsSum by numPostsSum
postsMax by numPostsMax
postsAvg by numPostsAvg 
</blockquote></details>

Great, thanks for clarifying :) I updated the examples in this section as you suggested. I'll re-add a corrected version of the first example in a final commit before submitting :)
___
*[wiki/content/graphql/queries/aggregate.md, line 193 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOIDzul5nm1cnF6jLlx:-MOIPCLHC6p94I5aKpSW:bsg732z) ([raw file](https://github.com/dgraph-io/dgraph/blob/34adb9298984f56215935fa968d8ae4dc16cfce5/wiki/content/graphql/queries/aggregate.md#L193)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

This looks good.
</blockquote></details>

Thanks! Your feedback made this easy :)


<!-- Sent from Reviewable.io -->

2020-12-11 20:50 UTC, aaroncarey reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7104)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @bucanero, @danielmai, @MichaelJCompton, and @vmrajas)

___
*[wiki/content/graphql/queries/aggregate.md, line 112 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7104#-MOHHQB9-zV_YIlKKy0l:-MOIZCC305eYWNrTs8ME:blebho2) ([raw file](https://github.com/dgraph-io/dgraph/blob/cd007398e00973095bb0043e979291ef08584939/wiki/content/graphql/queries/aggregate.md#L112)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

Great, thanks for clarifying :) I updated the examples in this section as you suggested. I'll re-add a corrected version of the first example in a final commit before submitting :)
</blockquote></details>

Re-added a corrected example in the final commit for this PR:

Example: Fetch the average number of `posts` written by authors:

```graphql
   query {
     aggregateAuthor {
       numPostsAvg
     }
   }
```


<!-- Sent from Reviewable.io -->

2020-12-11 20:53 UTC, merged