docs: Update GraphQL interface implementation reference
dgraph-io/dgraph pull request #7142
Opened 2020-12-15 15:18 UTC by bucanero

Fixes GRAPHQL-893

2020-12-16 08:57 UTC, JatinDevDG requested changes
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7142)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @bucanero, @danielmai, @JatinDevDG, and @MichaelJCompton)

___
*[wiki/content/graphql/schema/types.md, line 106 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7142#-MOecCzs9HBDunylX25A:-MOecCztAFZS1I2fBd_n:b-ucz9xg) ([raw file](https://github.com/dgraph-io/dgraph/blob/b8072452315414f6153432e59b928fbbbfe176e5/wiki/content/graphql/schema/types.md#L106)):*
> ```Markdown
> GraphQL interfaces allow you to define a generic pattern that multiple types follow.  When a type implements an interface, that means it has all fields of the interface and some extras.  
> 
> When a type implements an interface, GraphQL requires that the type repeats all the fields from the interface. For example:
> ```

it is not required but optional thing.we added this feature to be compliment with graphql specs. Because previously we were throwing error for this case. you can just add something like this  "According to specs we can have same fields in implementing types  as the interface but that is not compulsory requirement. And the generated dgraph schema will have correct schema ithut repetition of fields." Also mention that "if we repeat field name in a type then it should be of same type(also include list or scalar type),should have same nullable condition as a field in interface otherwise we return error. And apart fro it if field in interface have a directory like @search then that is inherited by field in implementing type ."
___
*[wiki/content/graphql/schema/types.md, line 127 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7142#-MOedKMwDUY0XM0DWaTW:-MOedKMwDUY0XM0DWaTX:bgan8rm) ([raw file](https://github.com/dgraph-io/dgraph/blob/b8072452315414f6153432e59b928fbbbfe176e5/wiki/content/graphql/schema/types.md#L127)):*
> ```Markdown
> 
> {{% notice "tip" %}}
> Dgraph doesn't need that repetition in the input schema and will generate the correct GraphQL for you.
> ```

change to something like "GraphQL will generate the correct dgraph schema where fields occur only once."
___
*[wiki/content/graphql/schema/types.md, line 169 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7142#-MOejILM97bhILRuPXzH:-MOejILNAhauGXElGDmB:b-htlbm2) ([raw file](https://github.com/dgraph-io/dgraph/blob/b8072452315414f6153432e59b928fbbbfe176e5/wiki/content/graphql/schema/types.md#L169)):*
> ```Markdown
> {{% /notice %}}
> 
> Dgraph currently allows this behavior for `ID` type fields, since the `ID` type field is not actually a predicate. For example:
> ```

same rule also apply here. In both the interfaces and in implementing type,nullable condition and type(list or scalar) 'ID' should be same. 


<!-- Sent from Reviewable.io -->

2020-12-16 13:02 UTC, bucanero reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7142)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @danielmai, @JatinDevDG, and @MichaelJCompton)

___
*[wiki/content/graphql/schema/types.md, line 106 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7142#-MOecCzs9HBDunylX25A:-MOfcy5Q8RLvchL-wiNC:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b8072452315414f6153432e59b928fbbbfe176e5/wiki/content/graphql/schema/types.md#L106)):*
<details><summary><i>Previously, JatinDevDG (Jatin Dev) wrote…</i></summary><blockquote>

it is not required but optional thing.we added this feature to be compliment with graphql specs. Because previously we were throwing error for this case. you can just add something like this  "According to specs we can have same fields in implementing types  as the interface but that is not compulsory requirement. And the generated dgraph schema will have correct schema ithut repetition of fields." Also mention that "if we repeat field name in a type then it should be of same type(also include list or scalar type),should have same nullable condition as a field in interface otherwise we return error. And apart fro it if field in interface have a directory like @search then that is inherited by field in implementing type ."
</blockquote></details>

Done.
___
*[wiki/content/graphql/schema/types.md, line 127 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7142#-MOedKMwDUY0XM0DWaTW:-MOfcxZ_49f3OvwkHi8K:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b8072452315414f6153432e59b928fbbbfe176e5/wiki/content/graphql/schema/types.md#L127)):*
<details><summary><i>Previously, JatinDevDG (Jatin Dev) wrote…</i></summary><blockquote>

change to something like "GraphQL will generate the correct dgraph schema where fields occur only once."
</blockquote></details>

Done.
___
*[wiki/content/graphql/schema/types.md, line 169 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7142#-MOejILM97bhILRuPXzH:-MOfcwjkBtl6rX0wICS7:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b8072452315414f6153432e59b928fbbbfe176e5/wiki/content/graphql/schema/types.md#L169)):*
<details><summary><i>Previously, JatinDevDG (Jatin Dev) wrote…</i></summary><blockquote>

same rule also apply here. In both the interfaces and in implementing type,nullable condition and type(list or scalar) 'ID' should be same. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-16 15:02 UTC, JatinDevDG approved these changes
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7142)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @bucanero, @danielmai, @JatinDevDG, and @MichaelJCompton)

___
*[wiki/content/graphql/schema/types.md, line 106 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7142#-MOg2Vl8Ee8FHBoIaKjY:-MOg2Vl8Ee8FHBoIaKjZ:b-ebwl9m) ([raw file](https://github.com/dgraph-io/dgraph/blob/3f3ce8df2c5598ca6da5964125b368ab9ab05efc/wiki/content/graphql/schema/types.md#L106)):*
> ```Markdown
> GraphQL interfaces allow you to define a generic pattern that multiple types follow.  When a type implements an interface, that means it has all fields of the interface and some extras.  
> 
> According to GraphQL specifications, you can have the same fields in implementing types as the interface. In such cases, the generated Dgraph schema will have the correct schema without field duplications.
> ```

In such cases, the GraphQL layer will generate the correct  Dgraph schema and that won't be having these duplicate fields.
___
*[wiki/content/graphql/schema/types.md, line 151 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7142#-MOg236g9s6DskEFtQvP:-MOg236g9s6DskEFtQvQ:b-abjqxi) ([raw file](https://github.com/dgraph-io/dgraph/blob/3f3ce8df2c5598ca6da5964125b368ab9ab05efc/wiki/content/graphql/schema/types.md#L151)):*
> ```Markdown
> ```
> 
> The generated GraphQL will contain the full types, for example, `Question` and `Comment` get expanded as:
> ```

The generated  Schema .....


<!-- Sent from Reviewable.io -->

2020-12-17 01:32 UTC, bucanero reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7142)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @danielmai, @JatinDevDG, and @MichaelJCompton)

___
*[wiki/content/graphql/schema/types.md, line 106 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7142#-MOg2Vl8Ee8FHBoIaKjY:-MOiJTH50XJfJEMxdtiL:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/3f3ce8df2c5598ca6da5964125b368ab9ab05efc/wiki/content/graphql/schema/types.md#L106)):*
<details><summary><i>Previously, JatinDevDG (Jatin Dev) wrote…</i></summary><blockquote>

In such cases, the GraphQL layer will generate the correct  Dgraph schema and that won't be having these duplicate fields.
</blockquote></details>

Done.
___
*[wiki/content/graphql/schema/types.md, line 151 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7142#-MOg236g9s6DskEFtQvP:-MOiJmeGALwxY-ghBemd:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/3f3ce8df2c5598ca6da5964125b368ab9ab05efc/wiki/content/graphql/schema/types.md#L151)):*
<details><summary><i>Previously, JatinDevDG (Jatin Dev) wrote…</i></summary><blockquote>

The generated  Schema .....
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-17 01:33 UTC, merged