Feat(GraphQL): This PR adds allow multiple @id fields in a type.
dgraph-io/dgraph pull request #7235
Opened 2020-12-31 05:21 UTC by JatinDevDG

2021-01-05 05:10 UTC, abhimanyusinghgaur requested changes
Looking good.
We also need to add some e2e tests for mutations and queries using multiple XID fields.

For mutations, we should also write tests for error cases where we first add one object with multiple XIDs, then try to add another object keeping only one of the XIDs same, then another with some other XID same, then another with all the XIDs same. All the trials apart from the first one should result in errors.

> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-:-MQFw7Wy4H9C3kpQaiNW:b7s4usf)* status: 6 of 9 files reviewed, 7 unresolved discussions (waiting on @JatinDevDG, @MichaelJCompton, and @pawanrawal)

___
*[graphql/resolve/query_rewriter.go, line 476 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MQFvdlbEz6L_56dc3NS:-MQFvdlbEz6L_56dc3NT:biyehn1) ([raw file](https://github.com/dgraph-io/dgraph/blob/0f3a107b3e6ef25e8517c4f1500d55f77b3ecaec/graphql/resolve/query_rewriter.go#L476)):*
> ```
> xidArgName := query.XIDArg()
> ```
xidArgNameToDgPredMap := query.XIDArgs()
___
*[graphql/resolve/query_test.yaml, line 3167 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MQFv6r3Cs9pXUshnyrn:-MQFv6r3Cs9pXUshnyro:bn7ipu5) ([raw file](https://github.com/dgraph-io/dgraph/blob/0f3a107b3e6ef25e8517c4f1500d55f77b3ecaec/graphql/resolve/query_test.yaml#L3167)):*
> ```YAML
>         Author : Book.Author
>       }
>     }
> ```

we should also add a case where there are multiple `@id` fields in args but no `ID` field.
___
*[graphql/schema/rules.go, line 684 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MQFt6Vl1va-veGhSfMY:-MQFt6Vl1va-veGhSfMZ:b-4uww3c) ([raw file](https://github.com/dgraph-io/dgraph/blob/0f3a107b3e6ef25e8517c4f1500d55f77b3ecaec/graphql/schema/rules.go#L684)):*
> ```
> var idDirectiveFields []*ast.FieldDefinition
> ```
should be removed now
___
*[graphql/schema/rules.go, line 690 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MQFt9zh1N0lgrcM07jt:-MQFt9zh1N0lgrcM07ju:bmpuwz1) ([raw file](https://github.com/dgraph-io/dgraph/blob/0f3a107b3e6ef25e8517c4f1500d55f77b3ecaec/graphql/schema/rules.go#L690)):*
> ```
> 		if d := field.Directives.ForName(idDirective); d != nil {
> 			idDirectiveFields = append(idDirectiveFields, field)
> 		}
> ```
should be removed now
___
*[graphql/schema/wrappers.go, line 124 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MQFvrhZCrpmSDHGur3L:-MQFvrhZCrpmSDHGur3M:buxor3e) ([raw file](https://github.com/dgraph-io/dgraph/blob/0f3a107b3e6ef25e8517c4f1500d55f77b3ecaec/graphql/schema/wrappers.go#L124)):*
> ```
> XIDArg()
> ```
We should name it `XIDArgs()` now that there are multiple XIDs.
___
*[graphql/schema/wrappers.go, line 1028 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MQFrecg4_Q-NRUdath3:-MQFrecg4_Q-NRUdath4:b-eirjji) ([raw file](https://github.com/dgraph-io/dgraph/blob/0f3a107b3e6ef25e8517c4f1500d55f77b3ecaec/graphql/schema/wrappers.go#L1028)):*
> ```
>  0
> ```
this can be skipped
___
*[graphql/schema/wrappers.go, line 1052 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MQFrypx-qKPaklrsQhm:-MQFrypx-qKPaklrsQhn:b-yl7uro) ([raw file](https://github.com/dgraph-io/dgraph/blob/0f3a107b3e6ef25e8517c4f1500d55f77b3ecaec/graphql/schema/wrappers.go#L1052)):*
> ```
> 0
> ```
can be skipped


<!-- Sent from Reviewable.io -->

2021-01-05 06:47 UTC, pawanrawal requested changes
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7235)* status: 6 of 9 files reviewed, 12 unresolved discussions (waiting on @abhimanyusinghgaur, @JatinDevDG, @MichaelJCompton, and @pawanrawal)

___
*[graphql/resolve/query_test.yaml, line 3152 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MQGEmio38Dhnsn3TMQy:-MQGEmio38Dhnsn3TMQz:bnagkt0) ([raw file](https://github.com/dgraph-io/dgraph/blob/0f3a107b3e6ef25e8517c4f1500d55f77b3ecaec/graphql/resolve/query_test.yaml#L3152)):*
> ```YAML
>   gqlquery: |
>     query {
>       getBook(id: "0x1",title:"GraphQL",ISBN:"001HB") {
> ```

If all of these are nullable, then what happens if I don't give any of them? That is

```
getBook {
  id
  title
}
```
___
*[graphql/resolve/query_test.yaml, line 3167 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MQFv6r3Cs9pXUshnyrn:-MQGEZ-OEDI8QPhgEfQE:b2nih0v) ([raw file](https://github.com/dgraph-io/dgraph/blob/0f3a107b3e6ef25e8517c4f1500d55f77b3ecaec/graphql/resolve/query_test.yaml#L3167)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

we should also add a case where there are multiple `@id` fields in args but no `ID` field.
</blockquote></details>

yup
___
*[graphql/schema/gqlschema.go, line 1472 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MQGF7QD8qNEiHp-ROnI:-MQGF7QD8qNEiHp-ROnJ:b-kz3e4c) ([raw file](https://github.com/dgraph-io/dgraph/blob/0f3a107b3e6ef25e8517c4f1500d55f77b3ecaec/graphql/schema/gqlschema.go#L1472)):*
> ```Go
> 
> // fieldMulti returns true if multiple field in fields satisfies pred
> func fieldMulti(fields ast.FieldList, pred func(*ast.FieldDefinition) bool) bool {
> ```

What is pred, should be `cond` or `condition`? Do we even need this function if its just being used at one place?
___
*[graphql/schema/gqlschema.go, line 1749 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MQGFblS0EEURHAP6Bwe:-MQGFblS0EEURHAP6Bwf:bo1ploe) ([raw file](https://github.com/dgraph-io/dgraph/blob/0f3a107b3e6ef25e8517c4f1500d55f77b3ecaec/graphql/schema/gqlschema.go#L1749)):*
> ```Go
> func addGetQuery(schema *ast.Schema, defn *ast.Definition, generateSubscription bool) {
> 	hasIDField := hasID(defn)
> 	hasXIDField := hasXID(defn)
> ```

this and the below function are both checking for xids, would have been better if there was just function which returned number of xid fields and then the result could have been used to do whatever you are doing below
___
*[graphql/schema/wrappers.go, line 1048 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MQGGOBwEWwd5JGCzxRo:-MQGGOBwEWwd5JGCzxRp:bghglqc) ([raw file](https://github.com/dgraph-io/dgraph/blob/0f3a107b3e6ef25e8517c4f1500d55f77b3ecaec/graphql/schema/wrappers.go#L1048)):*
> ```Go
> }
> 
> func (f *field) IDArgValue() (xids map[string]*string, uid uint64, err error) {
> ```

Why are we returning a pointer to the string, we can just return `map[string]string`
___
*[graphql/schema/wrappers.go, line 1052 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MQGGioZ9-ZTBLGFIl-a:-MQGGioZ9-ZTBLGFIl-b:bqsa3m2) ([raw file](https://github.com/dgraph-io/dgraph/blob/0f3a107b3e6ef25e8517c4f1500d55f77b3ecaec/graphql/schema/wrappers.go#L1052)):*
> ```Go
> 	passwordField := f.Type().PasswordField()
> 	xidArgName := ""
> 	xidArgToVal := make(map[string]*string, 0)
> ```

Do you need this? Why not just assign directly to `xids`?


<!-- Sent from Reviewable.io -->

2021-02-12 06:10 UTC, JatinDevDG reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7235)* status: 0 of 15 files reviewed, 12 unresolved discussions (waiting on @abhimanyusinghgaur, @filter, @MichaelJCompton, and @pawanrawal)

___
*[graphql/resolve/query_rewriter.go, line 476 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MQFvdlbEz6L_56dc3NS:-MTH_u1XCOMpGt23td1e:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/0f3a107b3e6ef25e8517c4f1500d55f77b3ecaec/graphql/resolve/query_rewriter.go#L476)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> xidArgName := query.XIDArg()
> ```
xidArgNameToDgPredMap := query.XIDArgs()
</blockquote></details>

done.
___
*[graphql/resolve/query_test.yaml, line 3152 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MQGEmio38Dhnsn3TMQy:-MTHb5yeDF_10hy1vN4i:b-rn5zb1) ([raw file](https://github.com/dgraph-io/dgraph/blob/0f3a107b3e6ef25e8517c4f1500d55f77b3ecaec/graphql/resolve/query_test.yaml#L3152)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

If all of these are nullable, then what happens if I don't give any of them? That is

```
getBook {
  id
  title
}
```
</blockquote></details>

That will be an empty query.
Corresponding Dgraph query will be 
query {
  getBook(func: uid(0x0)) @filter(type(Book)) {
    Book.id : uid
  }
}
___
*[graphql/resolve/query_test.yaml, line 3167 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MQFv6r3Cs9pXUshnyrn:-MTHbPt-5dmMC6yF42P6:b-rnraql) ([raw file](https://github.com/dgraph-io/dgraph/blob/0f3a107b3e6ef25e8517c4f1500d55f77b3ecaec/graphql/resolve/query_test.yaml#L3167)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

yup
</blockquote></details>

done.
___
*[graphql/schema/gqlschema.go, line 1472 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MQGF7QD8qNEiHp-ROnI:-MTHe-DY0m_SjlI2hOv_:brpmqc3) ([raw file](https://github.com/dgraph-io/dgraph/blob/0f3a107b3e6ef25e8517c4f1500d55f77b3ecaec/graphql/schema/gqlschema.go#L1472)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

What is pred, should be `cond` or `condition`? Do we even need this function if its just being used at one place?
</blockquote></details>

removed.
___
*[graphql/schema/gqlschema.go, line 1749 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MQGFblS0EEURHAP6Bwe:-MTHlzF73ALJCbk95hFs:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/0f3a107b3e6ef25e8517c4f1500d55f77b3ecaec/graphql/schema/gqlschema.go#L1749)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

this and the below function are both checking for xids, would have been better if there was just function which returned number of xid fields and then the result could have been used to do whatever you are doing below
</blockquote></details>

done.
___
*[graphql/schema/rules.go, line 684 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MQFt6Vl1va-veGhSfMY:-MTHfnNh5KyikFjEpouM:brpmqc3) ([raw file](https://github.com/dgraph-io/dgraph/blob/0f3a107b3e6ef25e8517c4f1500d55f77b3ecaec/graphql/schema/rules.go#L684)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> var idDirectiveFields []*ast.FieldDefinition
> ```
should be removed now
</blockquote></details>

removed.
___
*[graphql/schema/rules.go, line 690 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MQFt9zh1N0lgrcM07jt:-MTHfoxKD4-jwcGK-auC:brpmqc3) ([raw file](https://github.com/dgraph-io/dgraph/blob/0f3a107b3e6ef25e8517c4f1500d55f77b3ecaec/graphql/schema/rules.go#L690)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 		if d := field.Directives.ForName(idDirective); d != nil {
> 			idDirectiveFields = append(idDirectiveFields, field)
> 		}
> ```
should be removed now
</blockquote></details>

removed.
___
*[graphql/schema/wrappers.go, line 124 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MQFvrhZCrpmSDHGur3L:-MTHgCz1DFgRnNg98zDe:b-b5c35t) ([raw file](https://github.com/dgraph-io/dgraph/blob/0f3a107b3e6ef25e8517c4f1500d55f77b3ecaec/graphql/schema/wrappers.go#L124)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> XIDArg()
> ```
We should name it `XIDArgs()` now that there are multiple XIDs.
</blockquote></details>

changed.
___
*[graphql/schema/wrappers.go, line 1028 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MQFrecg4_Q-NRUdath3:-MTHgXMg83WOUU-v4KkK:bno9vn) ([raw file](https://github.com/dgraph-io/dgraph/blob/0f3a107b3e6ef25e8517c4f1500d55f77b3ecaec/graphql/schema/wrappers.go#L1028)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
>  0
> ```
this can be skipped
</blockquote></details>

skipped.
___
*[graphql/schema/wrappers.go, line 1048 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MQGGOBwEWwd5JGCzxRo:-MTHiqLP3IvWKXWNedKS:bet439q) ([raw file](https://github.com/dgraph-io/dgraph/blob/0f3a107b3e6ef25e8517c4f1500d55f77b3ecaec/graphql/schema/wrappers.go#L1048)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Why are we returning a pointer to the string, we can just return `map[string]string`
</blockquote></details>

yeah, changed.
Previously also we are returning address of it, so thought of using the same.
___
*[graphql/schema/wrappers.go, line 1052 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MQFrypx-qKPaklrsQhm:-MTHgheK4YsRDd2w9PAU:bno9vn) ([raw file](https://github.com/dgraph-io/dgraph/blob/0f3a107b3e6ef25e8517c4f1500d55f77b3ecaec/graphql/schema/wrappers.go#L1052)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 0
> ```
can be skipped
</blockquote></details>

skipped.
___
*[graphql/schema/wrappers.go, line 1052 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MQGGioZ9-ZTBLGFIl-a:-MTHhHpb9Z6vWXdhKQUV:b-b5c35t) ([raw file](https://github.com/dgraph-io/dgraph/blob/0f3a107b3e6ef25e8517c4f1500d55f77b3ecaec/graphql/schema/wrappers.go#L1052)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Do you need this? Why not just assign directly to `xids`?
</blockquote></details>

changed.


<!-- Sent from Reviewable.io -->

2021-02-12 18:49 UTC, vmrajas requested changes
> Reviewed 1 of 2 files at r2, 13 of 18 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7235)* status: 14 of 19 files reviewed, 18 unresolved discussions (waiting on @abhimanyusinghgaur, @filter, @JatinDevDG, @manishrjain, @MichaelJCompton, and @pawanrawal)

___
*[ee/acl/acl_test.go, line 234 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MTMV28r6y-Z_pZ96jo1:-MTMV28r6y-Z_pZ96jo2:b-ql77ks) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7466ede5b8135aa0a2f222e6b391c10ce9b5305/ee/acl/acl_test.go#L234)):*
> ```Go
> 	require.Equal(t, 1, len(resp.Errors))
> 	require.Equal(t, "couldn't rewrite mutation addUser because failed to rewrite mutation payload because id"+
> 		" alice already exists: field name, type User", resp.Errors[0].Message)
> ```

Instead of using ":", I feel the following feels more intuitive and conveys the message,
"id alice already exists for field name inside type User".
___
*[graphql/e2e/common/common.go, line 779 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MTMVJoK7LptT6jR2o4H:-MTMVJoK7LptT6jR2o4I:b-6b0dnh) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7466ede5b8135aa0a2f222e6b391c10ce9b5305/graphql/e2e/common/common.go#L779)):*
> ```Go
> 	t.Run("parallel mutations", parallelMutations)
> 	t.Run("input coercion to list", inputCoerciontoList)
> 	t.Run("mutation with multiple external Ids", mutationWithMultipleXids)
> ```

Can we add more tests testing following scenarios.
1. Update mutation tests with multiple IDs.
2. Add mutation test in which the type with multiple IDs is not at root level (but at second or third level).
3. Update mutation test in which the type with multiple IDs is not at root level(but at second or third level).
4. Delete mutation tests with multiple IDs. I believe the code related to delete has not been touched and this may fail.
5. Query tests with multiple IDs. Querying by different IDs should give the same node.
6. Query tests. Querying with more than ! IDs using AND/ OR filter should give the same node. Querying with conflicting IDs should give no nodes.
7. get Query tests. Querying with get using different IDs. 
___
*[graphql/e2e/directives/schema.graphql, line 368 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MTMWZ74CQ_gAFsSzHND:-MTMWZ74CQ_gAFsSzHNE:bl3sq5n) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7466ede5b8135aa0a2f222e6b391c10ce9b5305/graphql/e2e/directives/schema.graphql#L368)):*
> ```GraphQL
>     name: String!
>     reg_No: String! @id
>     emp_Id: String! @id
> ```

To bring more diversity in tests. It will be better if one of reg_No or emp_Id is of type Int! . IDs can now also be integers. 
___
*[graphql/resolve/add_mutation_test.yaml, line 3332 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MTMX01j9sK7TvWlNoji:-MTMX01j9sK7TvWlNojj:brssns1) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7466ede5b8135aa0a2f222e6b391c10ce9b5305/graphql/resolve/add_mutation_test.yaml#L3332)):*
> ```YAML
>       failed to rewrite mutation payload because value for field `members` in type `Home` index `0` must have exactly one child, found 2 children
> 
> -
> ```

Add test with the following scenarios:
1. Tests in which the type with multple IDs is at a deeper level. The deeper level linked to first level by reverse edges. This will also let us see if the deletejson works as expected.
2. Tests in which one of Book1 or Book2 exists and need not be created.
3. Deeper level tests with more variability, in which some of the queried variables in dgquery exist.
___
*[graphql/resolve/mutation_rewriter.go, line 1309 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MTMY-sP8jknP0W2DZ6M:-MTMY-sP8jknP0W2DZ6N:bemnoqx) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7466ede5b8135aa0a2f222e6b391c10ce9b5305/graphql/resolve/mutation_rewriter.go#L1309)):*
> ```Go
> 				} else {
> 					// Node with XID does not exist. It means this is a new node.
> 					// This node will be created later.
> ```

This logic may not work with Multiple IDs. I can see at least one scenario in which this won't work.
Consider the following scenario
type Employee {
    empId : String! @id
    id: String! @id
    name: String!
}
type Company{
    employees : [Employee]
}

Suppose an employee exists with name, "Name" and id, "ID", empID, "EmpID"
and a new mutation adds a company with the same employee but with mistakenly different id, say something like this,
input: [ {employees: [ {id: "Wrong ID", empID: "EmpID"} ] } ].

The code would think that this is a new employee and will throw an error that required name not provided. But, in reality this is an exisitng employee with valid empID reference.
___
*[graphql/schema/wrappers.go, line 2357 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MTMZmit9yL8ge-HkND0:-MTMZmit9yL8ge-HkND1:b-m2r9hs) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7466ede5b8135aa0a2f222e6b391c10ce9b5305/graphql/schema/wrappers.go#L2357)):*
> ```Go
> }
> 
> func (t *astType) XIDField() []FieldDefinition {
> ```

Can this be renamed to XIDFields ?


<!-- Sent from Reviewable.io -->

2021-02-12 18:55 UTC, vmrajas reviewed
Can you also add more tests for update_mutation_test.yaml, delete_mutation_test.yaml .
It will also be good to have a one test each for auth .yaml files and auth e2e tests (if possible). It will ensure robustness of code.

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-:-MTM_Med099VRyZhMhXS:b-h6m94r)* status: 14 of 19 files reviewed, 18 unresolved discussions (waiting on @abhimanyusinghgaur, @filter, @JatinDevDG, @manishrjain, @MichaelJCompton, and @pawanrawal)



<!-- Sent from Reviewable.io -->

2021-02-18 13:44 UTC, JatinDevDG reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7235)* status: 4 of 21 files reviewed, 18 unresolved discussions (waiting on @abhimanyusinghgaur, @filter, @id, @JatinDevDG, @manishrjain, @MichaelJCompton, @pawanrawal, and @vmrajas)

___
*[ee/acl/acl_test.go, line 234 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MTMV28r6y-Z_pZ96jo1:-MTpMkMG6OYpeVD1AjF_:b-b5c35t) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7466ede5b8135aa0a2f222e6b391c10ce9b5305/ee/acl/acl_test.go#L234)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

Instead of using ":", I feel the following feels more intuitive and conveys the message,
"id alice already exists for field name inside type User".
</blockquote></details>

changed.
___
*[graphql/e2e/common/common.go, line 779 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MTMVJoK7LptT6jR2o4H:-MTpMmBAEg4qr04k14Eh:brponno) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7466ede5b8135aa0a2f222e6b391c10ce9b5305/graphql/e2e/common/common.go#L779)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

Can we add more tests testing following scenarios.
1. Update mutation tests with multiple IDs.
2. Add mutation test in which the type with multiple IDs is not at root level (but at second or third level).
3. Update mutation test in which the type with multiple IDs is not at root level(but at second or third level).
4. Delete mutation tests with multiple IDs. I believe the code related to delete has not been touched and this may fail.
5. Query tests with multiple IDs. Querying by different IDs should give the same node.
6. Query tests. Querying with more than ! IDs using AND/ OR filter should give the same node. Querying with conflicting IDs should give no nodes.
7. get Query tests. Querying with get using different IDs. 
</blockquote></details>

added tests 
___
*[graphql/resolve/add_mutation_test.yaml, line 3332 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MTMX01j9sK7TvWlNoji:-MTpNPeH7JBiQ_dyFH-N:bq3jnj0) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7466ede5b8135aa0a2f222e6b391c10ce9b5305/graphql/resolve/add_mutation_test.yaml#L3332)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

Add test with the following scenarios:
1. Tests in which the type with multple IDs is at a deeper level. The deeper level linked to first level by reverse edges. This will also let us see if the deletejson works as expected.
2. Tests in which one of Book1 or Book2 exists and need not be created.
3. Deeper level tests with more variability, in which some of the queried variables in dgquery exist.
</blockquote></details>

added tests
___
*[graphql/resolve/mutation_rewriter.go, line 1309 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MTMY-sP8jknP0W2DZ6M:-MTpNSb07cwhl7wEjqpT:b-qssebl) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7466ede5b8135aa0a2f222e6b391c10ce9b5305/graphql/resolve/mutation_rewriter.go#L1309)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

This logic may not work with Multiple IDs. I can see at least one scenario in which this won't work.
Consider the following scenario
type Employee {
    empId : String! @id
    id: String! @id
    name: String!
}
type Company{
    employees : [Employee]
}

Suppose an employee exists with name, "Name" and id, "ID", empID, "EmpID"
and a new mutation adds a company with the same employee but with mistakenly different id, say something like this,
input: [ {employees: [ {id: "Wrong ID", empID: "EmpID"} ] } ].

The code would think that this is a new employee and will throw an error that required name not provided. But, in reality this is an exisitng employee with valid empID reference.
</blockquote></details>

fixed.
___
*[graphql/schema/wrappers.go, line 2357 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MTMZmit9yL8ge-HkND0:-MTpNVoE7EoJITYkP0PY:brythjh) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7466ede5b8135aa0a2f222e6b391c10ce9b5305/graphql/schema/wrappers.go#L2357)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

Can this be renamed to XIDFields ?
</blockquote></details>

renamed.


<!-- Sent from Reviewable.io -->

2021-02-18 13:46 UTC, JatinDevDG commented
> Can you also add more tests for update_mutation_test.yaml, delete_mutation_test.yaml .
> It will also be good to have a one test each for auth .yaml files and auth e2e tests (if possible). It will ensure robustness of code.
> 
> > _[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-:-MTM_Med099VRyZhMhXS:b-h6m94r)_ status: 14 of 19 files reviewed, 18 unresolved discussions (waiting on @abhimanyusinghgaur, @filter, @JatinDevDG, @manishrjain, @MichaelJCompton, and @pawanrawal)

added update and delete mutation tests. Auth tests not required.

2021-02-19 05:28 UTC, vmrajas requested changes
> Reviewed 3 of 18 files at r3, 5 of 15 files at r4, 11 of 11 files at r5.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7235)* status: all files reviewed, 21 unresolved discussions (waiting on @abhimanyusinghgaur, @filter, @JatinDevDG, @manishrjain, @MichaelJCompton, and @pawanrawal)

___
*[graphql/e2e/common/mutation.go, line 5825 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MTshO78Dc8dZtp4uiHY:-MTshO78Dc8dZtp4uiHZ:bcg4kov) ([raw file](https://github.com/dgraph-io/dgraph/blob/719da938c8f7781dcd40e4fea2314820e7f32df8/graphql/e2e/common/mutation.go#L5825)):*
> ```Go
>                      }`,
> 			error: `couldn't rewrite mutation updateEmployer because failed to rewrite mutation payload because field reg_No cannot be empty`,
> 		},
> ```

Good job with fixing indentation.
___
*[graphql/e2e/directives/schema.graphql, line 368 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MTMWZ74CQ_gAFsSzHND:-MTshDEx7HB7HrKroiCC:b-ty74oh) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7466ede5b8135aa0a2f222e6b391c10ce9b5305/graphql/e2e/directives/schema.graphql#L368)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

To bring more diversity in tests. It will be better if one of reg_No or emp_Id is of type Int! . IDs can now also be integers. 
</blockquote></details>

I believe this is also done.
___
*[graphql/e2e/directives/schema.graphql, line 374 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MTshFQIAbCS_eUhM2wn:-MTshFQIAbCS_eUhM2wo:b40fqyw) ([raw file](https://github.com/dgraph-io/dgraph/blob/719da938c8f7781dcd40e4fea2314820e7f32df8/graphql/e2e/directives/schema.graphql#L374)):*
> ```GraphQL
>     company: String! @id
>     worker: [Worker]
> }
> ```

nit: Add new line at end of file.
___
*[graphql/resolve/add_mutation_test.yaml, line 3332 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MTMX01j9sK7TvWlNoji:-MTsgPm4Ey4k56GRZtuN:bjrrzt2) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7466ede5b8135aa0a2f222e6b391c10ce9b5305/graphql/resolve/add_mutation_test.yaml#L3332)):*
<details><summary><i>Previously, JatinDevDG (Jatin Dev) wrote…</i></summary><blockquote>

added tests
</blockquote></details>

Add two more tests similar to "Add type with multiple XID fields at deep level".
1.: Book1 exists. The author should be linked to existing book and deletejson should be formed.
2. Book1 and Book2 both exist and point to two different books. the mutation should link it to one of the existing book.
___
*[graphql/resolve/mutation_rewriter.go, line 1268 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MTshieyC3tEzMXMjtvL:-MTshieyC3tEzMXMjtvM:b10p9az) ([raw file](https://github.com/dgraph-io/dgraph/blob/719da938c8f7781dcd40e4fea2314820e7f32df8/graphql/resolve/mutation_rewriter.go#L1268)):*
> ```Go
> 	xids := typ.XIDFields()
> 	if len(xids) != 0 {
> 		var xidsWithoutNodes int
> ```

Can this be renamed to nonExistingXIDs . Also can you add a comment over here over what these variables store.
___
*[graphql/resolve/mutation_rewriter.go, line 1317 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MTsi9woEayIz0T2t0M0:-MTsi9woEayIz0T2t0M1:b-nefrzi) ([raw file](https://github.com/dgraph-io/dgraph/blob/719da938c8f7781dcd40e4fea2314820e7f32df8/graphql/resolve/mutation_rewriter.go#L1317)):*
> ```Go
> 					// Node with XIDs does not exist. It means this is a new node.
> 					// This node will be created later.
> 					if xidsWithoutNodes == len(xids)-1 {
> ```

Add a comment here explaining why only in this case we do this processing.
___
*[graphql/resolve/mutation_rewriter.go, line 1336 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MTsiOxd0-BEfjSbViOt:-MTsiOxd0-BEfjSbViOu:b-3fr8my) ([raw file](https://github.com/dgraph-io/dgraph/blob/719da938c8f7781dcd40e4fea2314820e7f32df8/graphql/resolve/mutation_rewriter.go#L1336)):*
> ```Go
> 						// Set existenceQueryResult to _:variable. This is to make referencing to
> 						// this node later easier.
> 						idExistence[variable] = fmt.Sprintf("_:%s", variable)
> ```

We need to consider a test case in which the node is created and referenced by a different XID (other than last). The following test case may fail if this is not handled.
I know a way to handle this. Lets discuss this offline.
Consider this schema and mutation:

type Person {
    id: String! @id
    name: String! @id
    friends: [Person]
    closeFriends: [Person]
}

addPerson( input: [ { id: "1", name: "Person1", closeFriends: [ { add a new friend}]friends: [ { reference by id } ] } ]) {
    person {
        id
    }
}
___
*[graphql/resolve/mutation_rewriter.go, line 1352 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MTsiHNX7r0B3eKzc61x:-MTsiHNX7r0B3eKzc61y:b9fhujq) ([raw file](https://github.com/dgraph-io/dgraph/blob/719da938c8f7781dcd40e4fea2314820e7f32df8/graphql/resolve/mutation_rewriter.go#L1352)):*
> ```Go
> 				err := errors.Errorf("field %s cannot be empty", xid.Name())
> 				retErrors = append(retErrors, err)
> 				missingXid = true
> ```

Add a comment here on why this is done and error thrown after the for loop.
___
*[graphql/schema/wrappers.go, line 2409 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MTskT052iMGiOYqy0wH:-MTskT052iMGiOYqy0wI:b-3nnzzp) ([raw file](https://github.com/dgraph-io/dgraph/blob/719da938c8f7781dcd40e4fea2314820e7f32df8/graphql/schema/wrappers.go#L2409)):*
> ```Go
> 		}
> 	}
> 	sort.Slice(xids, func(i, j int) bool { return xids[i].Name() < xids[j].Name() })
> ```

Add a comment that XIDs are sorted by name to ensure consistency.


<!-- Sent from Reviewable.io -->

2021-02-19 10:37 UTC, JatinDevDG reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7235)* status: 16 of 21 files reviewed, 20 unresolved discussions (waiting on @abhimanyusinghgaur, @filter, @JatinDevDG, @manishrjain, @MichaelJCompton, @pawanrawal, and @vmrajas)

___
*[graphql/e2e/common/mutation.go, line 5825 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MTshO78Dc8dZtp4uiHY:-MTtqtUgBemCpbPYNGHz:bd5l6n4) ([raw file](https://github.com/dgraph-io/dgraph/blob/719da938c8f7781dcd40e4fea2314820e7f32df8/graphql/e2e/common/mutation.go#L5825)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

Good job with fixing indentation.
</blockquote></details>

thanks.
___
*[graphql/e2e/directives/schema.graphql, line 368 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MTMWZ74CQ_gAFsSzHND:-MTtqvJp1Dwoi0cus42T:b-7g7zii) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7466ede5b8135aa0a2f222e6b391c10ce9b5305/graphql/e2e/directives/schema.graphql#L368)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

I believe this is also done.
</blockquote></details>

yeah.
___
*[graphql/e2e/directives/schema.graphql, line 374 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MTshFQIAbCS_eUhM2wn:-MTtqwTr0KSq-uzkEF_k:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/719da938c8f7781dcd40e4fea2314820e7f32df8/graphql/e2e/directives/schema.graphql#L374)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

nit: Add new line at end of file.
</blockquote></details>

done.
___
*[graphql/resolve/add_mutation_test.yaml, line 3332 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MTMX01j9sK7TvWlNoji:-MTtqyWHAJTLK3IrZS50:b-t948zx) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7466ede5b8135aa0a2f222e6b391c10ce9b5305/graphql/resolve/add_mutation_test.yaml#L3332)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

Add two more tests similar to "Add type with multiple XID fields at deep level".
1.: Book1 exists. The author should be linked to existing book and deletejson should be formed.
2. Book1 and Book2 both exist and point to two different books. the mutation should link it to one of the existing book.
</blockquote></details>

added.
___
*[graphql/resolve/mutation_rewriter.go, line 1268 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MTshieyC3tEzMXMjtvL:-MTtqzr95Td-0LNYTgiv:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/719da938c8f7781dcd40e4fea2314820e7f32df8/graphql/resolve/mutation_rewriter.go#L1268)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

Can this be renamed to nonExistingXIDs . Also can you add a comment over here over what these variables store.
</blockquote></details>

done.
___
*[graphql/resolve/mutation_rewriter.go, line 1317 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MTsi9woEayIz0T2t0M0:-MTtr0x7EpbhJtX9Tuk7:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/719da938c8f7781dcd40e4fea2314820e7f32df8/graphql/resolve/mutation_rewriter.go#L1317)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

Add a comment here explaining why only in this case we do this processing.
</blockquote></details>

done.
___
*[graphql/resolve/mutation_rewriter.go, line 1352 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MTsiHNX7r0B3eKzc61x:-MTtrEL_BMGQcAMUbSrF:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/719da938c8f7781dcd40e4fea2314820e7f32df8/graphql/resolve/mutation_rewriter.go#L1352)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

Add a comment here on why this is done and error thrown after the for loop.
</blockquote></details>

done.
___
*[graphql/schema/wrappers.go, line 2409 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MTskT052iMGiOYqy0wH:-MTtrHBO7OGUQ0WcLcKU:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/719da938c8f7781dcd40e4fea2314820e7f32df8/graphql/schema/wrappers.go#L2409)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

Add a comment that XIDs are sorted by name to ensure consistency.
</blockquote></details>

done.


<!-- Sent from Reviewable.io -->

2021-02-19 14:47 UTC, JatinDevDG reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7235)* status: 6 of 21 files reviewed, 20 unresolved discussions (waiting on @abhimanyusinghgaur, @filter, @id, @manishrjain, @MichaelJCompton, @pawanrawal, and @vmrajas)

___
*[graphql/resolve/mutation_rewriter.go, line 1336 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MTsiOxd0-BEfjSbViOt:-MTuk_8A9h70yyCd9dXY:bb7f2mf) ([raw file](https://github.com/dgraph-io/dgraph/blob/719da938c8f7781dcd40e4fea2314820e7f32df8/graphql/resolve/mutation_rewriter.go#L1336)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

We need to consider a test case in which the node is created and referenced by a different XID (other than last). The following test case may fail if this is not handled.
I know a way to handle this. Lets discuss this offline.
Consider this schema and mutation:

type Person {
    id: String! @id
    name: String! @id
    friends: [Person]
    closeFriends: [Person]
}

addPerson( input: [ { id: "1", name: "Person1", closeFriends: [ { add a new friend}]friends: [ { reference by id } ] } ]) {
    person {
        id
    }
}



</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2021-02-22 04:50 UTC, vmrajas approved these changes
Thanks for the update and adding a test case for upsert with multiple XIDs.
Can you add one more test case, a test case in which only one of the variable for XID existence query exists and the other does not. It may fail this test case. The failure has more to do with upsert, I can take the fix for this if needed.

> Reviewed 2 of 5 files at r7, 9 of 12 files at r8, 6 of 6 files at r9.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-:-MU71f0c7DZTEDZgQ3ld:b-2mi7ie)* status: all files reviewed, 17 unresolved discussions (waiting on @abhimanyusinghgaur, @filter, @id, @manishrjain, @MichaelJCompton, @pawanrawal, and @vmrajas)



<!-- Sent from Reviewable.io -->

2021-02-22 05:38 UTC, JatinDevDG commented
> Thanks for the update and adding a test case for upsert with multiple XIDs.
> Can you add one more test case, a test case in which only one of the variable for XID existence query exists and the other does not. It may fail this test case. The failure has more to do with upsert, I can take the fix for this if needed.
> 
> > Reviewed 2 of 5 files at r7, 9 of 12 files at r8, 6 of 6 files at r9.
> > _[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-:-MU71f0c7DZTEDZgQ3ld:b-2mi7ie)_ status: all files reviewed, 17 unresolved discussions (waiting on @abhimanyusinghgaur, @filter, @id, @manishrjain, @MichaelJCompton, @pawanrawal, and @vmrajas)

added test case for upsert mutation.

2021-02-22 05:40 UTC, pawanrawal approved these changes
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7235)* status: 21 of 22 files reviewed, 13 unresolved discussions (waiting on @abhimanyusinghgaur, @id, @JatinDevDG, @manishrjain, @MichaelJCompton, and @vmrajas)

___
*[graphql/resolve/query_test.yaml, line 3266 at r9](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MU7EwkjAYtMHmqItuhH:-MU7EwkjAYtMHmqItuhI:b8asjux) ([raw file](https://github.com/dgraph-io/dgraph/blob/6dade877ae651891cb41196b99c334022157838c/graphql/resolve/query_test.yaml#L3266)):*
> ```YAML
>   gqlquery: |
>     query {
>     	getBook(id: "0x1", title: "GraphQL", ISBN: "001HB") {
> ```

What's up with the indentation here?


<!-- Sent from Reviewable.io -->

2021-02-22 06:16 UTC, JatinDevDG reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7235)* status: 20 of 22 files reviewed, 13 unresolved discussions (waiting on @abhimanyusinghgaur, @id, @manishrjain, @MichaelJCompton, @pawanrawal, and @vmrajas)

___
*[graphql/resolve/query_test.yaml, line 3266 at r9](https://reviewable.io/reviews/dgraph-io/dgraph/7235#-MU7EwkjAYtMHmqItuhH:-MU7NO2ODhxslSCZpp0X:b-qssebl) ([raw file](https://github.com/dgraph-io/dgraph/blob/6dade877ae651891cb41196b99c334022157838c/graphql/resolve/query_test.yaml#L3266)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

What's up with the indentation here?
</blockquote></details>

fixed.


<!-- Sent from Reviewable.io -->

2021-02-22 07:01 UTC, merged