Docs (update to v20.07) - Port encryption and use of mTLS for all internal GRPC comms
dgraph-io/dgraph pull request #7243
Opened 2021-01-04 23:33 UTC by aaroncarey

2021-01-05 09:26 UTC, aman-bansal commented on wiki/content/deploy/tls-configuration.md
> +curl --silent https://localhost:8080/admin/export
--cacert is flag for curl client. we needed this whenever tls is enabled

2021-01-05 09:26 UTC, aman-bansal commented on wiki/content/deploy/tls-configuration.md
> +  connections from external ports. To learn more, see
tls_internal_port_enabled flag is available in 20.07. This specify whether to connect with internal ports with tls config or not

2021-01-05 09:26 UTC, aman-bansal commented on wiki/content/deploy/tls-configuration.md
>  $ dgraph alpha --tls_dir tls --tls_client_auth="REQUIREANDVERIFY"
tls_internal_port_enabled=true flag is required to enable internal ports encryption

2021-01-05 17:59 UTC, aaroncarey reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7243)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @aman-bansal and @OmarAyo)

___
*[wiki/content/deploy/tls-configuration.md, line 161 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7243#-MQEoR_W0Z8rwCUuSUr2-r2-161:-MQIelyb1d-iqw9rXVTF:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/2f622fa4e54805312befef8d36631b12f4b08097/wiki/content/deploy/tls-configuration.md#L161)):*
<details><summary><i>Previously, aman-bansal (aman bansal) wrote…</i></summary><blockquote>

tls_internal_port_enabled flag is available in 20.07. This specify whether to connect with internal ports with tls config or not
</blockquote></details>

Done.
___
*[wiki/content/deploy/tls-configuration.md, line 206 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7243#-MQEoR_W0Z8rwCUuSUr2-r2-206:-MQIf7KTCOEOtscttPLj:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/2f622fa4e54805312befef8d36631b12f4b08097/wiki/content/deploy/tls-configuration.md#L206)):*
<details><summary><i>Previously, aman-bansal (aman bansal) wrote…</i></summary><blockquote>

tls_internal_port_enabled=true flag is required to enable internal ports encryption
</blockquote></details>

Done.
___
*[wiki/content/deploy/tls-configuration.md, line 327 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7243#-MQEoR_W0Z8rwCUuSUr2-r2-327:-MQIfoAZ5d5ON4uyCl7B:brnmdx6) ([raw file](https://github.com/dgraph-io/dgraph/blob/2f622fa4e54805312befef8d36631b12f4b08097/wiki/content/deploy/tls-configuration.md#L327)):*
<details><summary><i>Previously, aman-bansal (aman bansal) wrote…</i></summary><blockquote>

--cacert is flag for curl client. we needed this whenever tls is enabled
</blockquote></details>

Done. I removed the example that showed using `curl` without providing the `-cacert` flag.


<!-- Sent from Reviewable.io -->

2021-01-06 00:11 UTC, aaroncarey reviewed
> Reviewed 1 of 1 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7243)* status: all files reviewed, 3 unresolved discussions (waiting on @aman-bansal and @OmarAyo)



<!-- Sent from Reviewable.io -->

2021-01-08 15:04 UTC, aman-bansal approved these changes

2021-01-09 00:53 UTC, danielmai requested changes
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7243)* status: all files reviewed, 5 unresolved discussions (waiting on @aaroncarey, @aman-bansal, and @OmarAyo)

___
*[wiki/content/deploy/tls-configuration.md, line 12 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7243#-MQZcOZf7UaoXhg49ZHM:-MQZcOZf7UaoXhg49ZHN:b-mcbcob) ([raw file](https://github.com/dgraph-io/dgraph/blob/504ed1ad28b2b1530419680bd7ba2224a8d25ab6/wiki/content/deploy/tls-configuration.md#L12)):*
> ```
> `gRPC-external-private` 
> ```
1. This shouldn't be a `code-formatted`. It should be **in bold**, like the list in Ports Usage.
2. This needs a link to Ports Usage where "gRPC-external-private" is defined.
___
*[wiki/content/deploy/tls-configuration.md, line 269 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7243#-MQZbO_P-VQ4ac9yL6Ay:-MQZbO_Q20Pn6YFAUM06:b-km8rpf) ([raw file](https://github.com/dgraph-io/dgraph/blob/504ed1ad28b2b1530419680bd7ba2224a8d25ab6/wiki/content/deploy/tls-configuration.md#L269)):*
> ```
> Mac OS X
> ```
macOS


<!-- Sent from Reviewable.io -->

2021-01-09 01:33 UTC, aaroncarey reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7243)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @aaroncarey, @aman-bansal, @danielmai, and @OmarAyo)

___
*[wiki/content/deploy/tls-configuration.md, line 12 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7243#-MQZcOZf7UaoXhg49ZHM:-MQZl8lh8lQuQ20GVbFl:b8ukx9b) ([raw file](https://github.com/dgraph-io/dgraph/blob/504ed1ad28b2b1530419680bd7ba2224a8d25ab6/wiki/content/deploy/tls-configuration.md#L12)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> `gRPC-external-private` 
> ```
1. This shouldn't be a `code-formatted`. It should be **in bold**, like the list in Ports Usage.
2. This needs a link to Ports Usage where "gRPC-external-private" is defined.
</blockquote></details>

Done (formatting fixed here and elsewhere). The link to Ports Usage is in the following sentence.
___
*[wiki/content/deploy/tls-configuration.md, line 269 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7243#-MQZbO_P-VQ4ac9yL6Ay:-MQZlP1eBAL-3RUCYNsA:b-376vyo) ([raw file](https://github.com/dgraph-io/dgraph/blob/504ed1ad28b2b1530419680bd7ba2224a8d25ab6/wiki/content/deploy/tls-configuration.md#L269)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> Mac OS X
> ```
macOS
</blockquote></details>

Done. Good catch!


<!-- Sent from Reviewable.io -->

2021-01-09 01:48 UTC, danielmai commented
___
*[wiki/content/deploy/tls-configuration.md, line 269 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7243#-MQZbO_P-VQ4ac9yL6Ay:-MQZnnU7CoIe_r4Xdq07:b-mury0o) ([raw file](https://github.com/dgraph-io/dgraph/blob/504ed1ad28b2b1530419680bd7ba2224a8d25ab6/wiki/content/deploy/tls-configuration.md#L269)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

Done. Good catch!
</blockquote></details>

The name is just "macOS", not "macOS X".


<!-- Sent from Reviewable.io -->

2021-01-09 01:49 UTC, danielmai requested changes
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7243)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @aaroncarey, @aman-bansal, and @OmarAyo)

___
*[wiki/content/deploy/tls-configuration.md, line 106 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7243#-MQZoAhTEpCIzAI-bFxU:-MQZoAhTEpCIzAI-bFxV:b9lfvpt) ([raw file](https://github.com/dgraph-io/dgraph/blob/ecf95153ee075f887426784406e0c58df9f98c81/wiki/content/deploy/tls-configuration.md#L106)):*
> ```Markdown
> ### Certificate inspection
> 
> The command **dgraph cert ls** lists all certificates and keys in the **--dir**
> ```

CLI commands and flags can stay in `code-formatted`.


<!-- Sent from Reviewable.io -->

2021-01-09 01:54 UTC, danielmai approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7243#-:-MQZqccP5D2MI_3RAEEq:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @aaroncarey, @aman-bansal, and @OmarAyo)



<!-- Sent from Reviewable.io -->

2021-01-09 01:59 UTC, merged