docs(How-To-Guide): update and correct "Simple Login System"
dgraph-io/dgraph pull request #7246
Opened 2021-01-05 15:59 UTC by dhax

Using v20.11.0 the how-to guide seems outdated as the returned json does not match with the defined struct and leads to index out of range panics when accessing the not existing "Pass" field.

2021-01-05 15:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dgraph-io/dgraph?pullRequest=7246) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dgraph-io/dgraph?pullRequest=7246) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dgraph-io/dgraph?pullRequest=7246) it.</sub>

2021-01-20 14:49 UTC, bucanero commented
hello @dhax 

we have recently moved our docs to a new repository: https://github.com/dgraph-io/dgraph-docs/

would you mind creating a new PR in the new repo so we can include your contribution?

2021-01-20 14:56 UTC, bucanero requested changes
https://github.com/dgraph-io/dgraph-docs/

2021-01-20 15:01 UTC, dhax commented
thanks for the info, submitted in https://github.com/dgraph-io/dgraph-docs/pull/4

2021-01-20 15:02 UTC, closed without merging