docs: nginx lb for Dgraph Cluster that are not started with docker-compose
dgraph-io/dgraph pull request #7291
Opened 2021-01-13 20:24 UTC by OmarAyo

Our documentation is focused on showing how to set up nginx lb with docker-compose. This documentation will be useful for users that start their Dgraph Cluster using a different deployment method (like systemd)

2021-01-13 21:25 UTC, danielmai requested changes
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7291)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @aaroncarey, @bucanero, and @OmarAyo)

___
*[wiki/content/howto/load-balancing-nginx.md, line 35 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQxbeuZ5OUDDXC4k1dD:-MQxbeuZ5OUDDXC4k1dE:b-2znqt6) ([raw file](https://github.com/dgraph-io/dgraph/blob/14bb6309bc7db241935b8e5c1ffcc03e81c92e37/wiki/content/howto/load-balancing-nginx.md#L35)):*
> ```
>  Dgraph Cluster
> ```
Dgraph cluster (lowercase c)
___
*[wiki/content/howto/load-balancing-nginx.md, line 39 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQxbcqa7zJpmtB_moR2:-MQxbcqa7zJpmtB_moR3:b-be6uxa) ([raw file](https://github.com/dgraph-io/dgraph/blob/14bb6309bc7db241935b8e5c1ffcc03e81c92e37/wiki/content/howto/load-balancing-nginx.md#L39)):*
> ```
> Dgraph Clusteer
> ```
Dgraph cluster
___
*[wiki/content/howto/load-balancing-nginx.md, line 41 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQxblxd0dX1cXDRCSeN:-MQxblxd0dX1cXDRCSeO:b-jz2ags) ([raw file](https://github.com/dgraph-io/dgraph/blob/14bb6309bc7db241935b8e5c1ffcc03e81c92e37/wiki/content/howto/load-balancing-nginx.md#L41)):*
> ```
> apt-get install nginx
> ```

Make this a `sh` block so the syntax highlighting is correct.

Also, `apt-get` commands only works on Debian/Ubuntu. Mention that in this doc.
___
*[wiki/content/howto/load-balancing-nginx.md, line 140 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQxcgDc0-xnAtv48raH:-MQxcgDc0-xnAtv48raI:b-gs3tv0) ([raw file](https://github.com/dgraph-io/dgraph/blob/14bb6309bc7db241935b8e5c1ffcc03e81c92e37/wiki/content/howto/load-balancing-nginx.md#L140)):*
> ```
> Load Balancing methods
> ```
Load balancing methods (sentence-case).
___
*[wiki/content/howto/load-balancing-nginx.md, line 142 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQxcn3pAhzB_P-kxg_3:-MQxcn3q33hZQw_VUrPR:b-hum1mz) ([raw file](https://github.com/dgraph-io/dgraph/blob/14bb6309bc7db241935b8e5c1ffcc03e81c92e37/wiki/content/howto/load-balancing-nginx.md#L142)):*
> ```Markdown
> ## Load Balancing methods
> 
> By default, Nginx load balancing is done round-robin. By the way there are other load balancing methods availalbe like least connections, IP hashing. In case you want to use a diffrent menthod than round-robin you can do that by specifying the method you desire in the upsteram section. 
> ```

Remove trailing space.
___
*[wiki/content/howto/load-balancing-nginx.md, line 142 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQxcrM39NX-puvGO3q3:-MQxcrM41ob_xE8WpkOG:bmbxsig) ([raw file](https://github.com/dgraph-io/dgraph/blob/14bb6309bc7db241935b8e5c1ffcc03e81c92e37/wiki/content/howto/load-balancing-nginx.md#L142)):*
> ```
> By the way there are other load balancing methods availalbe like least connections, IP hashing.
> ```
There are other load-balancing methods available such as least connections or IP hashing.
___
*[wiki/content/howto/load-balancing-nginx.md, line 142 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQxcwxG4At_yOXn9UvY:-MQxcwxG4At_yOXn9UvZ:b-9gw5jr) ([raw file](https://github.com/dgraph-io/dgraph/blob/14bb6309bc7db241935b8e5c1ffcc03e81c92e37/wiki/content/howto/load-balancing-nginx.md#L142)):*
> ```
> upsteram
> ```
upstream
___
*[wiki/content/howto/load-balancing-nginx.md, line 147 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQxckHE7E4jfwCAwPfo:-MQxckHE7E4jfwCAwPfp:b-hum1mz) ([raw file](https://github.com/dgraph-io/dgraph/blob/14bb6309bc7db241935b8e5c1ffcc03e81c92e37/wiki/content/howto/load-balancing-nginx.md#L147)):*
> ```Markdown
> # use least connection method
> upstream alpha_grpc {
>   least_conn; 
> ```

Remove trailing space.


<!-- Sent from Reviewable.io -->

2021-01-13 23:29 UTC, OmarAyo commented
___
*[wiki/content/howto/load-balancing-nginx.md, line 35 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQxbeuZ5OUDDXC4k1dD:-MQy4A9h5S4mNOpnHTGZ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/14bb6309bc7db241935b8e5c1ffcc03e81c92e37/wiki/content/howto/load-balancing-nginx.md#L35)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
>  Dgraph Cluster
> ```
Dgraph cluster (lowercase c)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-13 23:29 UTC, OmarAyo commented
___
*[wiki/content/howto/load-balancing-nginx.md, line 39 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQxbcqa7zJpmtB_moR2:-MQy4H2L6jvd1NwvQH2P:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/14bb6309bc7db241935b8e5c1ffcc03e81c92e37/wiki/content/howto/load-balancing-nginx.md#L39)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> Dgraph Clusteer
> ```
Dgraph cluster
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-13 23:29 UTC, OmarAyo commented
___
*[wiki/content/howto/load-balancing-nginx.md, line 41 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQxblxd0dX1cXDRCSeN:-MQy4HfQ7d9bmNr3CBF8:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/14bb6309bc7db241935b8e5c1ffcc03e81c92e37/wiki/content/howto/load-balancing-nginx.md#L41)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> apt-get install nginx
> ```

Make this a `sh` block so the syntax highlighting is correct.

Also, `apt-get` commands only works on Debian/Ubuntu. Mention that in this doc.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-13 23:29 UTC, OmarAyo commented
___
*[wiki/content/howto/load-balancing-nginx.md, line 140 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQxcgDc0-xnAtv48raH:-MQy4Ir77Gr1QDBQUoIW:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/14bb6309bc7db241935b8e5c1ffcc03e81c92e37/wiki/content/howto/load-balancing-nginx.md#L140)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> Load Balancing methods
> ```
Load balancing methods (sentence-case).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-13 23:29 UTC, OmarAyo commented
___
*[wiki/content/howto/load-balancing-nginx.md, line 142 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQxcn3pAhzB_P-kxg_3:-MQy4KJI2zZ5EwDqFacr:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/14bb6309bc7db241935b8e5c1ffcc03e81c92e37/wiki/content/howto/load-balancing-nginx.md#L142)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

Remove trailing space.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-13 23:29 UTC, OmarAyo commented
___
*[wiki/content/howto/load-balancing-nginx.md, line 142 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQxcrM39NX-puvGO3q3:-MQy4L4OAYcgs97p27S8:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/14bb6309bc7db241935b8e5c1ffcc03e81c92e37/wiki/content/howto/load-balancing-nginx.md#L142)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> By the way there are other load balancing methods availalbe like least connections, IP hashing.
> ```
There are other load-balancing methods available such as least connections or IP hashing.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-13 23:29 UTC, OmarAyo commented
___
*[wiki/content/howto/load-balancing-nginx.md, line 142 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQxcwxG4At_yOXn9UvY:-MQy4LhvAqnJhwz5n40q:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/14bb6309bc7db241935b8e5c1ffcc03e81c92e37/wiki/content/howto/load-balancing-nginx.md#L142)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> upsteram
> ```
upstream
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-13 23:29 UTC, OmarAyo commented
___
*[wiki/content/howto/load-balancing-nginx.md, line 147 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQxckHE7E4jfwCAwPfo:-MQy4MMY0DYzcVGXC5JA:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/14bb6309bc7db241935b8e5c1ffcc03e81c92e37/wiki/content/howto/load-balancing-nginx.md#L147)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

Remove trailing space.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-14 01:37 UTC, aaroncarey requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7291)* status: all files reviewed, 26 unresolved discussions (waiting on @bucanero, @danielmai, and @OmarAyo)

___
*[wiki/content/howto/load-balancing-nginx.md, line 11 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQyPVfP6VndkRCO6qPa:-MQyPVfQ1vFVnaXCWraJ:b-khh4lg) ([raw file](https://github.com/dgraph-io/dgraph/blob/0cac8d54322caafc5ff75eb8d6cf03a627891d27/wiki/content/howto/load-balancing-nginx.md#L11)):*
> ```
> docker-compose
> ```
Suggestion: We should probably write this as "Docker Compose" in this heading, since their docs treat this as a proper noun, per https://docs.docker.com/get-started/08_using_compose/. I'd prefer to only refer to this as `docker-compose` if we are referring to the command.
___
*[wiki/content/howto/load-balancing-nginx.md, line 15 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQyQ3PeAeiTp817RXHH:-MQyQ3Pf3LU-yxjoRPSL:bks15v) ([raw file](https://github.com/dgraph-io/dgraph/blob/0cac8d54322caafc5ff75eb8d6cf03a627891d27/wiki/content/howto/load-balancing-nginx.md#L15)):*
> ```
> Download the contents of this gist's ZIP file and extract it to a directory called `graph-nginx`
> ```

I'd suggest the following edit to this sentence:

Download the contents of this gist's ZIP file and extract it to a directory called `graph-nginx`, as follows:
___
*[wiki/content/howto/load-balancing-nginx.md, line 35 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQyQuy22hhaX8q_zkJD:-MQyQuy22hhaX8q_zkJE:b5othkj) ([raw file](https://github.com/dgraph-io/dgraph/blob/0cac8d54322caafc5ff75eb8d6cf03a627891d27/wiki/content/howto/load-balancing-nginx.md#L35)):*
> ```
> When you start your Dgraph cluster directly on the host machine (e.g. with systemd) the procedure is the following:
> ```
Suggested edit:

You can start your Dgraph cluster directly on the host machine (for example, with systemd) as follows:
___
*[wiki/content/howto/load-balancing-nginx.md, line 37 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQySp0RCXptEAuu6O08:-MQySp0UCVm57_bm7HhZ:b-5rm3n0) ([raw file](https://github.com/dgraph-io/dgraph/blob/0cac8d54322caafc5ff75eb8d6cf03a627891d27/wiki/content/howto/load-balancing-nginx.md#L37)):*
> ```
>  nginx 
> ```
Should be NGINX here and anywhere else we aren't referring to the `nginx` command, usage per https://docs.nginx.com/nginx-controller/admin-guides/
___
*[wiki/content/howto/load-balancing-nginx.md, line 39 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQyT7V0CavNqDuk0cI1:-MQyT7V0CavNqDuk0cI2:bla8siz) ([raw file](https://github.com/dgraph-io/dgraph/blob/0cac8d54322caafc5ff75eb8d6cf03a627891d27/wiki/content/howto/load-balancing-nginx.md#L39)):*
> ```
> nginx
> ```
NGINX
___
*[wiki/content/howto/load-balancing-nginx.md, line 43 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQyTCtxAe_bgLAGp5_y:-MQyTCtxAe_bgLAGp5_z:bla8siz) ([raw file](https://github.com/dgraph-io/dgraph/blob/0cac8d54322caafc5ff75eb8d6cf03a627891d27/wiki/content/howto/load-balancing-nginx.md#L43)):*
> ```
> nginx
> ```
NGINX
___
*[wiki/content/howto/load-balancing-nginx.md, line 45 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQyTK3c1hAIV0hY3Tok:-MQyTK3c1hAIV0hY3Tol:bluszvw) ([raw file](https://github.com/dgraph-io/dgraph/blob/0cac8d54322caafc5ff75eb8d6cf03a627891d27/wiki/content/howto/load-balancing-nginx.md#L45)):*
> ```
> Once nginx is installed, you can start to configure it for load balancing. In essence, all you need to do is set up nginx with instructions for which type of connections to listen to and where to redirect them.
> ```
Suggested edit:

"After installing NGINX, you can configure it for load balancing. You do this by specifying which types of connections to listen to, and where to redirect them."
___
*[wiki/content/howto/load-balancing-nginx.md, line 51 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQyTi0ZBx7Z2AOgR9ZZ:-MQyTi0ZBx7Z2AOgR9Z_:b-ybhowo) ([raw file](https://github.com/dgraph-io/dgraph/blob/0cac8d54322caafc5ff75eb8d6cf03a627891d27/wiki/content/howto/load-balancing-nginx.md#L51)):*
> ```
> In the load-balancer.conf you’ll need to define the following configuration file:
> ```
Suggested edit:

"Create a configuration file, **load-balancer.conf**, and edit it to read as follows:"
___
*[wiki/content/howto/load-balancing-nginx.md, line 69 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQyUzBs--WuFTr3Wfp-:-MQyUzBs--WuFTr3Wfp0:b-osxuc2) ([raw file](https://github.com/dgraph-io/dgraph/blob/0cac8d54322caafc5ff75eb8d6cf03a627891d27/wiki/content/howto/load-balancing-nginx.md#L69)):*
> ```
> By default, Nginx load balancing is round robin.
> ```
Suggested edit (usage per https://www.nginx.com/resources/glossary/round-robin-load-balancing/):

By default, NGINX load balancing is round-robin.
___
*[wiki/content/howto/load-balancing-nginx.md, line 90 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQyVAsn7slnWmgg4wIo:-MQyVAsp6l4PDG4mQzO0:bk1xwxr) ([raw file](https://github.com/dgraph-io/dgraph/blob/0cac8d54322caafc5ff75eb8d6cf03a627891d27/wiki/content/howto/load-balancing-nginx.md#L90)):*
> ```
> ,
> ```
semicolon preferred after "configuration"
___
*[wiki/content/howto/load-balancing-nginx.md, line 90 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQyVLq95nNpjdsAoYpV:-MQyVLq95nNpjdsAoYpW:b-lc6arp) ([raw file](https://github.com/dgraph-io/dgraph/blob/0cac8d54322caafc5ff75eb8d6cf03a627891d27/wiki/content/howto/load-balancing-nginx.md#L90)):*
> ```
> **sites-enabled**
> ```
Bold formatting preferred for folder/directory names.
___
*[wiki/content/howto/load-balancing-nginx.md, line 96 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQyVXUeB2NPHCumEXyI:-MQyVXUf4D7Pdv5Fgqez:be777yv) ([raw file](https://github.com/dgraph-io/dgraph/blob/0cac8d54322caafc5ff75eb8d6cf03a627891d27/wiki/content/howto/load-balancing-nginx.md#L96)):*
> ```
> Now you can restart nginx service:
> ```
Either "Now you can restart the NGINX service:" or "Now you can restart `nginx`:" (The second one is probably better, but both are fine)
___
*[wiki/content/howto/load-balancing-nginx.md, line 104 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQyVnpo0WUwg09BABbk:-MQyVnpp4apgTRvFkrFI:bfe5e17) ([raw file](https://github.com/dgraph-io/dgraph/blob/0cac8d54322caafc5ff75eb8d6cf03a627891d27/wiki/content/howto/load-balancing-nginx.md#L104)):*
> ```
> Nginx
> ```
NGINX
___
*[wiki/content/howto/load-balancing-nginx.md, line 110 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQyVrBd678FZmT05N4c:-MQyVrBd678FZmT05N4d:b-zacdul) ([raw file](https://github.com/dgraph-io/dgraph/blob/0cac8d54322caafc5ff75eb8d6cf03a627891d27/wiki/content/howto/load-balancing-nginx.md#L110)):*
> ```
> dgraph
> ```
Dgraph
___
*[wiki/content/howto/load-balancing-nginx.md, line 120 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQyVyvu1aeqQHVyRL--:-MQyVyvu1aeqQHVyRL-0:b1hg6op) ([raw file](https://github.com/dgraph-io/dgraph/blob/0cac8d54322caafc5ff75eb8d6cf03a627891d27/wiki/content/howto/load-balancing-nginx.md#L120)):*
> ```
> docker-compose
> ```
I suggest "Docker Compose" or, if referring to the command,  `docker-compose`.
___
*[wiki/content/howto/load-balancing-nginx.md, line 123 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQyWKV-E1dslX3uQ35m:-MQyWKV-E1dslX3uQ35n:b-l3tdrj) ([raw file](https://github.com/dgraph-io/dgraph/blob/0cac8d54322caafc5ff75eb8d6cf03a627891d27/wiki/content/howto/load-balancing-nginx.md#L123)):*
> ```
> It is important to take into account with gRPC load balancing that every request hits a different Alpha, potentially increasing read throughput.
> ```
Suggested edit:

"With gRPC load balancing, each request can hit a different Alpha node. This can potentially increase read throughput."
___
*[wiki/content/howto/load-balancing-nginx.md, line 142 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQyWrrv [...]

2021-01-14 13:16 UTC, OmarAyo commented
Addressed @aaroncarey comments

2021-01-14 19:35 UTC, aaroncarey approved these changes
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7291)* status: 0 of 1 files reviewed, 27 unresolved discussions (waiting on @aaroncarey, @bucanero, @danielmai, and @OmarAyo)

___
*[wiki/content/howto/load-balancing-nginx.md, line 3 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MR1OHhe6fmHlOF2-MKL:-MR1OHhhBxcQJM-URPdt:bfe5e17) ([raw file](https://github.com/dgraph-io/dgraph/blob/5d65d71965c65432557c0050fecfd3738fe6ba7f/wiki/content/howto/load-balancing-nginx.md#L3)):*
> ```
> Nginx
> ```
NGINX


<!-- Sent from Reviewable.io -->

2021-01-14 20:51 UTC, danielmai approved these changes
A few more comments and then <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-:-MR1eZd80pqAQxVjlv4m:b-2w7zh5)* status: 0 of 1 files reviewed, 22 unresolved discussions (waiting on @aaroncarey, @bucanero, @danielmai, and @OmarAyo)

___
*[wiki/content/howto/load-balancing-nginx.md, line 120 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQyVyvu1aeqQHVyRL--:-MR1e4KE-DM6bqevJUIp:bm81tc0) ([raw file](https://github.com/dgraph-io/dgraph/blob/0cac8d54322caafc5ff75eb8d6cf03a627891d27/wiki/content/howto/load-balancing-nginx.md#L120)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

> ```
> docker-compose
> ```
I suggest "Docker Compose" or, if referring to the command,  `docker-compose`.
</blockquote></details>

As Aaron said, if it's the command, use `docker-compose`. Otherwise, use Docker Compose.

So, in this specific sentence, use "`docker-compose` up shell window" and then "If you are not using Docker Compose".
___
*[wiki/content/howto/load-balancing-nginx.md, line 123 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQyWKV-E1dslX3uQ35m:-MR1eKTY4WQ8ub57a5bS:byfewfk) ([raw file](https://github.com/dgraph-io/dgraph/blob/0cac8d54322caafc5ff75eb8d6cf03a627891d27/wiki/content/howto/load-balancing-nginx.md#L123)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

> ```
> It is important to take into account with gRPC load balancing that every request hits a different Alpha, potentially increasing read throughput.
> ```
Suggested edit:

"With gRPC load balancing, each request can hit a different Alpha node. This can potentially increase read throughput."
</blockquote></details>

You can remove the word "potentially". "can" is sufficient.
___
*[wiki/content/howto/load-balancing-nginx.md, line 104 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MR1doBr8mXLtOSL2f_7:-MR1doBr8mXLtOSL2f_8:bupjcke) ([raw file](https://github.com/dgraph-io/dgraph/blob/5d65d71965c65432557c0050fecfd3738fe6ba7f/wiki/content/howto/load-balancing-nginx.md#L104)):*
> ```Markdown
> ## Use the increment tool to start a gRPC LB
> 
> In a different shell, run the `dgraph increment` [docs](https://dgraph.io/docs/howto/#using-the-increment-tool) tool against the NGINX gRPC load balancer (`nginx:9080`):
> ```

There should be parentheses around (docs). Otherwise, it reads as "run the dgraph increment docs tool".


<!-- Sent from Reviewable.io -->

2021-01-15 17:53 UTC, OmarAyo commented
___
*[wiki/content/howto/load-balancing-nginx.md, line 120 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQyVyvu1aeqQHVyRL--:-MR6AaGuEV3b9mOBk8l5:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0cac8d54322caafc5ff75eb8d6cf03a627891d27/wiki/content/howto/load-balancing-nginx.md#L120)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

As Aaron said, if it's the command, use `docker-compose`. Otherwise, use Docker Compose.

So, in this specific sentence, use "`docker-compose` up shell window" and then "If you are not using Docker Compose".
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-15 17:57 UTC, OmarAyo commented
___
*[wiki/content/howto/load-balancing-nginx.md, line 69 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQyUzBs--WuFTr3Wfp-:-MR6BMZlEF5_B0qmUQhE:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0cac8d54322caafc5ff75eb8d6cf03a627891d27/wiki/content/howto/load-balancing-nginx.md#L69)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

> ```
> By default, Nginx load balancing is round robin.
> ```
Suggested edit (usage per https://www.nginx.com/resources/glossary/round-robin-load-balancing/):

By default, NGINX load balancing is round-robin.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-15 17:57 UTC, OmarAyo commented
___
*[wiki/content/howto/load-balancing-nginx.md, line 51 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQyTi0ZBx7Z2AOgR9ZZ:-MR6BOepCLEtTk4XiOnC:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0cac8d54322caafc5ff75eb8d6cf03a627891d27/wiki/content/howto/load-balancing-nginx.md#L51)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

> ```
> In the load-balancer.conf you’ll need to define the following configuration file:
> ```
Suggested edit:

"Create a configuration file, **load-balancer.conf**, and edit it to read as follows:"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-15 17:57 UTC, OmarAyo commented
___
*[wiki/content/howto/load-balancing-nginx.md, line 45 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQyTK3c1hAIV0hY3Tok:-MR6BPF_3gJBPjCZaz7w:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0cac8d54322caafc5ff75eb8d6cf03a627891d27/wiki/content/howto/load-balancing-nginx.md#L45)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

> ```
> Once nginx is installed, you can start to configure it for load balancing. In essence, all you need to do is set up nginx with instructions for which type of connections to listen to and where to redirect them.
> ```
Suggested edit:

"After installing NGINX, you can configure it for load balancing. You do this by specifying which types of connections to listen to, and where to redirect them."
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-15 17:57 UTC, OmarAyo commented
___
*[wiki/content/howto/load-balancing-nginx.md, line 43 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQyTCtxAe_bgLAGp5_y:-MR6BPwGCOMO_4C9v3lg:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0cac8d54322caafc5ff75eb8d6cf03a627891d27/wiki/content/howto/load-balancing-nginx.md#L43)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

> ```
> nginx
> ```
NGINX
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-15 17:57 UTC, OmarAyo commented
___
*[wiki/content/howto/load-balancing-nginx.md, line 39 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQyT7V0CavNqDuk0cI1:-MR6BQTg6sTFjyZPs4P4:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0cac8d54322caafc5ff75eb8d6cf03a627891d27/wiki/content/howto/load-balancing-nginx.md#L39)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

> ```
> nginx
> ```
NGINX
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-15 17:57 UTC, OmarAyo commented
___
*[wiki/content/howto/load-balancing-nginx.md, line 37 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQySp0RCXptEAuu6O08:-MR6BRR1E3dLAW52Gs3v:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0cac8d54322caafc5ff75eb8d6cf03a627891d27/wiki/content/howto/load-balancing-nginx.md#L37)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

> ```
>  nginx 
> ```
Should be NGINX here and anywhere else we aren't referring to the `nginx` command, usage per https://docs.nginx.com/nginx-controller/admin-guides/
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-15 17:57 UTC, OmarAyo commented
___
*[wiki/content/howto/load-balancing-nginx.md, line 35 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQyQuy22hhaX8q_zkJD:-MR6BS13-EoFyLAPJOBI:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0cac8d54322caafc5ff75eb8d6cf03a627891d27/wiki/content/howto/load-balancing-nginx.md#L35)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

> ```
> When you start your Dgraph cluster directly on the host machine (e.g. with systemd) the procedure is the following:
> ```
Suggested edit:

You can start your Dgraph cluster directly on the host machine (for example, with systemd) as follows:
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-15 17:57 UTC, OmarAyo commented
___
*[wiki/content/howto/load-balancing-nginx.md, line 15 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQyQ3PeAeiTp817RXHH:-MR6BT3K5d3glbPaOAIn:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0cac8d54322caafc5ff75eb8d6cf03a627891d27/wiki/content/howto/load-balancing-nginx.md#L15)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

> ```
> Download the contents of this gist's ZIP file and extract it to a directory called `graph-nginx`
> ```

I'd suggest the following edit to this sentence:

Download the contents of this gist's ZIP file and extract it to a directory called `graph-nginx`, as follows:
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-15 17:57 UTC, OmarAyo commented
___
*[wiki/content/howto/load-balancing-nginx.md, line 11 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQyPVfP6VndkRCO6qPa:-MR6BT_uASBcYH53B8-J:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0cac8d54322caafc5ff75eb8d6cf03a627891d27/wiki/content/howto/load-balancing-nginx.md#L11)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

> ```
> docker-compose
> ```
Suggestion: We should probably write this as "Docker Compose" in this heading, since their docs treat this as a proper noun, per https://docs.docker.com/get-started/08_using_compose/. I'd prefer to only refer to this as `docker-compose` if we are referring to the command.


</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-15 17:57 UTC, OmarAyo commented
___
*[wiki/content/howto/load-balancing-nginx.md, line 3 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MR1OHhe6fmHlOF2-MKL:-MR6BUCoC1UTouR3TP4u:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/5d65d71965c65432557c0050fecfd3738fe6ba7f/wiki/content/howto/load-balancing-nginx.md#L3)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

> ```
> Nginx
> ```
NGINX
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-15 17:57 UTC, OmarAyo commented
___
*[wiki/content/howto/load-balancing-nginx.md, line 110 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQyVrBd678FZmT05N4c:-MR6BWu0483zRf5Asn2-:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0cac8d54322caafc5ff75eb8d6cf03a627891d27/wiki/content/howto/load-balancing-nginx.md#L110)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

> ```
> dgraph
> ```
Dgraph
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-15 17:57 UTC, OmarAyo commented
___
*[wiki/content/howto/load-balancing-nginx.md, line 142 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7291#-MQyWrrv435FazEHFWCT:-MR6BXzjDsbZU3D0PsxB:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0cac8d54322caafc5ff75eb8d6cf03a627891d27/wiki/content/howto/load-balancing-nginx.md#L142)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

> ```
> Nginx
> ```
NGINX
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-15 17:58 UTC, merged