chore(dgraph): updating badger to v3
dgraph-io/dgraph pull request #7292
Opened 2021-01-14 04:30 UTC by aman-bansal

2021-01-14 06:58 UTC, danielmai approved these changes
> Reviewed 66 of 66 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7292)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @manishrjain, @martinmr, @pawanrawal, and @vvbalaji-dgraph)



<!-- Sent from Reviewable.io -->

2021-01-14 06:59 UTC, danielmai approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7292#-:-MQzgBCE3n3sbGHUroU0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @manishrjain, @martinmr, @pawanrawal, and @vvbalaji-dgraph)



<!-- Sent from Reviewable.io -->

2021-01-14 07:04 UTC, danielmai requested changes
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7292)* status: all files reviewed, 1 unresolved discussion (waiting on @aman-bansal, @manishrjain, @martinmr, @pawanrawal, and @vvbalaji-dgraph)

___
*[go.mod, line 71 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7292#-MQzhQKBC-skFNKwjSRK:-MQzhQKBC-skFNKwjSRL:b-jlnbs4) ([raw file](https://github.com/dgraph-io/dgraph/blob/20fd984bd489202cf10462e124ffc154932f4b93/go.mod#L71)):*
> ```
> 	google.golang.org/grpc v1.27.0
> 	google.golang.org/protobuf v1.25.0 // indirect
> ```
Why are these dependencies upgraded or added?


<!-- Sent from Reviewable.io -->

2021-01-15 11:44 UTC, jarifibrahim commented on x/metrics.go
>  			"badger_v2_disk_reads_total",
Add a comment about why this is v2

2021-01-15 11:45 UTC, jarifibrahim approved these changes

2021-01-15 17:16 UTC, danielmai approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 13 of 13 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7292#-:-MR61z83BBlKQNPVAKpI:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @aman-bansal, @manishrjain, @martinmr, @pawanrawal, and @vvbalaji-dgraph)



<!-- Sent from Reviewable.io -->

2021-01-15 18:16 UTC, merged