feat(Apollo): Add "_entities" resolver.
dgraph-io/dgraph pull request #7334
Opened 2021-01-19 11:28 UTC by minhaj-shakeel

Fixes GRAPHQL-922.

2021-01-20 08:33 UTC, abhimanyusinghgaur requested changes
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7334)* status: 0 of 2 files reviewed, 12 unresolved discussions (waiting on @minhaj-shakeel and @pawanrawal)

___
*[graphql/resolve/resolver.go, line 301 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRTivr-6FolgsSg2LPA:-MRTivr07GaO9IrDJ4FT:bbz7qpa) ([raw file](https://github.com/dgraph-io/dgraph/blob/c72852e2665a4e020693819d38a1846330729a2a/graphql/resolve/resolver.go#L301)):*
> ```
> 					return &Resolved{
> 						Err: fmt.Errorf("Got Error in Unmarshalling Input Argument"),
> 					}
> ```
```
return EmptyResult(q, fmt.Errorf("Error unmarshalling `_representations` argument"))
```
___
*[graphql/resolve/resolver.go, line 307 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRTltrs6ouKGE-vVpD0:-MRTltrs6ouKGE-vVpD1:b-t47ieg) ([raw file](https://github.com/dgraph-io/dgraph/blob/c72852e2665a4e020693819d38a1846330729a2a/graphql/resolve/resolver.go#L307)):*
> ```
> 					return &Resolved{
> 						Err: fmt.Errorf("Unable to extract __typename from input"),
> 					}
> ```
use `EmptyResult()` here

```
Unable to extract __typename from `_representations` argument
```
___
*[graphql/resolve/resolver.go, line 316 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRTmS693mLCQ-ASJNCR:-MRTmS693mLCQ-ASJNCS:bfw1dvm) ([raw file](https://github.com/dgraph-io/dgraph/blob/c72852e2665a4e020693819d38a1846330729a2a/graphql/resolve/resolver.go#L316)):*
> ```
> 					return &Resolved{
> 						Err: err,
> 					}
> ```
`EmptyResult()`
___
*[graphql/resolve/resolver.go, line 324 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRTo9_ZCyJSow_rFbur:-MRTo9_ZCyJSow_rFbus:b-6g5fay) ([raw file](https://github.com/dgraph-io/dgraph/blob/c72852e2665a4e020693819d38a1846330729a2a/graphql/resolve/resolver.go#L324)):*
> ```
> 					return &Resolved{
> 						Err: fmt.Errorf("Unable to Extract value for %s", keyFieldValue),
> 					}
> ```
`Emptyresult()`
error message could be a bit more verbose:
```
Unable to extract value for key field `%s` from `_representations` argument
```
___
*[graphql/resolve/resolver.go, line 335 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRToulI1E4vBhKQmToD:-MRToulI1E4vBhKQmToE:b-y5d19l) ([raw file](https://github.com/dgraph-io/dgraph/blob/c72852e2665a4e020693819d38a1846330729a2a/graphql/resolve/resolver.go#L335)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> 			for _, typ := range typeNames {
> 				if typ != typeNames[0] {
> 					return &Resolved{
> 						Err: fmt.Errorf("Expecting All the representations of the type %s, Got %s", typeNames[0], typ),
> 					}
> 				}
> 			}
> ```
</details>

we could just use a `map[string]bool` to store typenames, and check here that if the len(map)>1, we report error with all the keys in the map.
Error message could say:
```
Expected only one unique typename in `_representations` argument, got: %v
```
where %v is the list containing all the keys from the map.
___
*[graphql/resolve/resolver.go, line 344 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRTq6KTEN4ecs6Jal1-:-MRTq6KTEN4ecs6Jal10:bqy2wnc) ([raw file](https://github.com/dgraph-io/dgraph/blob/c72852e2665a4e020693819d38a1846330729a2a/graphql/resolve/resolver.go#L344)):*
> ```
> // 2. We are using filter Query to resolve the Fields so filter queries must not be turned off in the Schema
> ```
Once we get it all working, then later we should do it by adding a new rewriter, that way we won't have to depend on `@generate` directive turning off the filter query.
___
*[graphql/resolve/resolver.go, line 347 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRTq11D8wuuxe5lW8C-:-MRTq11D8wuuxe5lW8C0:b-nrxh3p) ([raw file](https://github.com/dgraph-io/dgraph/blob/c72852e2665a4e020693819d38a1846330729a2a/graphql/resolve/resolver.go#L347)):*
> ```
> 				return &Resolved{
> 					Err: err,
> 				}
> ```
`EmptyResult()`
___
*[graphql/schema/wrappers.go, line 2642 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRTtxYvC1PHt5YKf1Sg:-MRTtxYvC1PHt5YKf1Sh:bw3h1ao) ([raw file](https://github.com/dgraph-io/dgraph/blob/c72852e2665a4e020693819d38a1846330729a2a/graphql/schema/wrappers.go#L2642)):*
> ```
> Alias string, op Operation, selection []Field
> ```
instead of passing these 3 args separately, we could just pass one argument `q Query` and then figure out these from that.
Alias would then be q.Alias(), better than hardcoding `_entities`.
___
*[graphql/schema/wrappers.go, line 2642 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRTvEIsEe6fQr2COAw3:-MRTvEIsEe6fQr2COAw4:b-ilf2b9) ([raw file](https://github.com/dgraph-io/dgraph/blob/c72852e2665a4e020693819d38a1846330729a2a/graphql/schema/wrappers.go#L2642)):*
> ```
> ConstructFilterQueryFromKeyField
> ```
maybe rename it to:
```
ConstructEntitiesQuery
```
___
*[graphql/schema/wrappers.go, line 2649 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRTrLqA6bpAKuk2G4Pr:-MRTrLqA6bpAKuk2G4Ps:b-bwmgyo) ([raw file](https://github.com/dgraph-io/dgraph/blob/c72852e2665a4e020693819d38a1846330729a2a/graphql/schema/wrappers.go#L2649)):*
> ```
> oprn.inSchema.schema.Types[typeName]
> ```
`typeDefn`
___
*[graphql/schema/wrappers.go, line 2653 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRTrfk58CuNUXvyFuxD:-MRTrfk58CuNUXvyFuxE:b-1264do) ([raw file](https://github.com/dgraph-io/dgraph/blob/c72852e2665a4e020693819d38a1846330729a2a/graphql/schema/wrappers.go#L2653)):*
> ```
> "ID"
> ```
use the `IDType` const
___
*[graphql/schema/wrappers.go, line 2674 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRTuPAk5cNqqmyadDLV:-MRTuPAk5cNqqmyadDLW:b-4qoug8) ([raw file](https://github.com/dgraph-io/dgraph/blob/c72852e2665a4e020693819d38a1846330729a2a/graphql/schema/wrappers.go#L2674)):*
<details><summary><i alt="summary">Quoted 21 lines of code…</i></summary>

> ```
> 	filterValue := &ast.Value{
> 		Children: idChildren,
> 		Kind:     ast.ListValue,
> 	}
> 	// If the key field is not of "ID" type, then it must having
> 	// @id directive on it. Construct filter with using `in` filter
> 	// in that case. For eg:-
> 	// 		queryProduct(filter: { keyfldName: {in: [val1, ...]}}){
> 	// 			...
> 	// 			...
> 	// 		}
> 	if keyFldTypeName != "ID" {
> 		filterValue = &ast.Value{
> 			Kind: ast.ObjectValue,
> 			Children: ast.ChildValueList{
> 				&ast.ChildValue{
> 					Name:  "in",
> 					Value: filterValue,
> 				}},
> 		}
> 	}
> ```
</details>

```
var filterValue *ast.Value
if keyFldTypeName == IDType {
...
} else {
...
}
```
and maybe name `filterValue` as `fieldFilterValue`, because this value is for filtering a particular field and not the value of the whole filter argument.
___
*[graphql/schema/wrappers.go, line 2722 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRTsuPiC8yDH_zIkPKw:-MRTsuPiC8yDH_zIkPKx:b9zjj90) ([raw file](https://github.com/dgraph-io/dgraph/blob/c72852e2665a4e020693819d38a1846330729a2a/graphql/schema/wrappers.go#L2722)):*
> ```
> sel: nil
> ```
`sel: fld`


<!-- Sent from Reviewable.io -->

2021-01-20 09:25 UTC, minhaj-shakeel reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7334)* status: 0 of 2 files reviewed, 12 unresolved discussions (waiting on @abhimanyusinghgaur, @minhaj-shakeel, and @pawanrawal)

___
*[graphql/resolve/resolver.go, line 301 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRTivr-6FolgsSg2LPA:-MRU69g52kmFAytdI4CS:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c72852e2665a4e020693819d38a1846330729a2a/graphql/resolve/resolver.go#L301)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 					return &Resolved{
> 						Err: fmt.Errorf("Got Error in Unmarshalling Input Argument"),
> 					}
> ```
```
return EmptyResult(q, fmt.Errorf("Error unmarshalling `_representations` argument"))
```
</blockquote></details>

Done.
___
*[graphql/resolve/resolver.go, line 307 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRTltrs6ouKGE-vVpD0:-MRU6A318aSIIWiVj9F7:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c72852e2665a4e020693819d38a1846330729a2a/graphql/resolve/resolver.go#L307)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 					return &Resolved{
> 						Err: fmt.Errorf("Unable to extract __typename from input"),
> 					}
> ```
use `EmptyResult()` here

```
Unable to extract __typename from `_representations` argument
```
</blockquote></details>

Done.
___
*[graphql/resolve/resolver.go, line 316 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRTmS693mLCQ-ASJNCR:-MRU6AO17PNlohd5-WJn:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c72852e2665a4e020693819d38a1846330729a2a/graphql/resolve/resolver.go#L316)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 					return &Resolved{
> 						Err: err,
> 					}
> ```
`EmptyResult()`
</blockquote></details>

Done.
___
*[graphql/resolve/resolver.go, line 324 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRTo9_ZCyJSow_rFbur:-MRU6AfGAQ7_ow_-IZOh:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c72852e2665a4e020693819d38a1846330729a2a/graphql/resolve/resolver.go#L324)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 					return &Resolved{
> 						Err: fmt.Errorf("Unable to Extract value for %s", keyFieldValue),
> 					}
> ```
`Emptyresult()`
error message could be a bit more verbose:
```
Unable to extract value for key field `%s` from `_representations` argument
```
</blockquote></details>

Done.
___
*[graphql/resolve/resolver.go, line 347 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRTq11D8wuuxe5lW8C-:-MRU6B-B3t4PaYPV0-q_:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c72852e2665a4e020693819d38a1846330729a2a/graphql/resolve/resolver.go#L347)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 				return &Resolved{
> 					Err: err,
> 				}
> ```
`EmptyResult()`
</blockquote></details>

Done.
___
*[graphql/schema/wrappers.go, line 2642 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRTtxYvC1PHt5YKf1Sg:-MRU6CXWCVzpE5NYdkTD:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c72852e2665a4e020693819d38a1846330729a2a/graphql/schema/wrappers.go#L2642)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> Alias string, op Operation, selection []Field
> ```
instead of passing these 3 args separately, we could just pass one argument `q Query` and then figure out these from that.
Alias would then be q.Alias(), better than hardcoding `_entities`.
</blockquote></details>

Done.
___
*[graphql/schema/wrappers.go, line 2642 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRTvEIsEe6fQr2COAw3:-MRU6CyO1W1cdgQk5IBz:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c72852e2665a4e020693819d38a1846330729a2a/graphql/schema/wrappers.go#L2642)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> ConstructFilterQueryFromKeyField
> ```
maybe rename it to:
```
ConstructEntitiesQuery
```
</blockquote></details>

Done.
___
*[graphql/schema/wrappers.go, line 2649 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRTrLqA6bpAKuk2G4Pr:-MRU6DJQAcYQRJNZy3rE:b-3qz3f1) ([raw file](https://github.com/dgraph-io/dgraph/blob/c72852e2665a4e020693819d38a1846330729a2a/graphql/schema/wrappers.go#L2649)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> oprn.inSchema.schema.Types[typeName]
> ```
`typeDefn`
</blockquote></details>

Don't understand what this means.
___
*[graphql/schema/wrappers.go, line 2653 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRTrfk58CuNUXvyFuxD:-MRU6HXK8CzotleDZDi5:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c72852e2665a4e020693819d38a1846330729a2a/graphql/schema/wrappers.go#L2653)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> "ID"
> ```
use the `IDType` const
</blockquote></details>

Done.
___
*[graphql/schema/wrappers.go, line 2674 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRTuPAk5cNqqmyadDLV:-MRU6I049KLR2gI2119X:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c72852e2665a4e020693819d38a1846330729a2a/graphql/schema/wrappers.go#L2674)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 	filterValue := &ast.Value{
> 		Children: idChildren,
> 		Kind:     ast.ListValue,
> 	}
> 	// If the key field is not of "ID" type, then it must having
> 	// @id directive on it. Construct filter with using `in` filter
> 	// in that case. For eg:-
> 	// 		queryProduct(filter: { keyfldName: {in: [val1, ...]}}){
> 	// 			...
> 	// 			...
> 	// 		}
> 	if keyFldTypeName != "ID" {
> 		filterValue = &ast.Value{
> 			Kind: ast.ObjectValue,
> 			Children: ast.ChildValueList{
> 				&ast.ChildValue{
> 					Name:  "in",
> 					Value: filterValue,
> 				}},
> 		}
> 	}
> ```
```
var filterValue *ast.Value
if keyFldTypeName == IDType {
...
} else {
...
}
```
and maybe name `filterValue` as `fieldFilterValue`, because this value is for filtering a particular field and not the value of the whole filter argument.
</blockquote></details>

Done.
___
*[graphql/schema/wrappers.go, line 2722 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRTsuPiC8yDH_zIkPKw:-MRU6ITz2mp1pGt3ExOE:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c72852e2665a4e020693819d38a1846330729a2a/graphql/schema/wrappers.go#L2722)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> sel: nil
> ```
`sel: fld`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-21 08:53 UTC, abhimanyusinghgaur requested changes
looking good, just got some nitpicks and good to merge after that.

> Reviewed 10 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-:-MRZ8JOBDb6o1HkNk9g4:b-zc2pls)* status: all files reviewed, 15 unresolved discussions (waiting on @minhaj-shakeel and @pawanrawal)

___
*[graphql/resolve/query_rewriter.go, line 166 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRZ-cdLBrJKl-zoTbny:-MRZ-cdLBrJKl-zoTbnz:b-1kgr4b) ([raw file](https://github.com/dgraph-io/dgraph/blob/54fd5389f687926194dcbaa390eb8b740335585e/graphql/resolve/query_rewriter.go#L166)):*
> ```
> to resolve `extended` types.
> ```
not only the types extended by this service, but also the ones defined in this service
___
*[graphql/resolve/query_rewriter.go, line 184 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRZ0K79DVdxTrcPyBUd:-MRZ0K79DVdxTrcPyBUe:bfhhed2) ([raw file](https://github.com/dgraph-io/dgraph/blob/54fd5389f687926194dcbaa390eb8b740335585e/graphql/resolve/query_rewriter.go#L184)):*
> ```
> representations := field.ArgValue("representations").([]interface{})
> ```
```
representations, ok := field.ArgValue("representations").([]interface{})
if !ok {
  return nil, fmt.Errorf("Error parsing `_representations` argument")
}
```
___
*[graphql/resolve/query_rewriter.go, line 193 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRZ10XlASyd87e037Gg:-MRZ10XlASyd87e037Gh:bl0dkv2) ([raw file](https://github.com/dgraph-io/dgraph/blob/54fd5389f687926194dcbaa390eb8b740335585e/graphql/resolve/query_rewriter.go#L193)):*
> ```
> unmarshelling
> ```
parsing
___
*[graphql/resolve/query_rewriter.go, line 201 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRZ1CY20-iP6ELRFXkm:-MRZ1CY20-iP6ELRFXkn:b10ejnk) ([raw file](https://github.com/dgraph-io/dgraph/blob/54fd5389f687926194dcbaa390eb8b740335585e/graphql/resolve/query_rewriter.go#L201)):*
> ```
> an Array
> ```
a map
___
*[graphql/resolve/query_rewriter.go, line 204 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRZ1tG7-kqtdjnusz2_:-MRZ1tG7-kqtdjnusz2a:b-4om77e) ([raw file](https://github.com/dgraph-io/dgraph/blob/54fd5389f687926194dcbaa390eb8b740335585e/graphql/resolve/query_rewriter.go#L204)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> 		keyFieldname, isIDType, err := field.KeyField(typename)
> 		if err != nil {
> 			return nil, err
> 		}
> 		keyFieldIsID = isIDType
> 		keyFieldName = keyFieldname
> ```
</details>

we should just declare `var err error` outside of this for loop, so that we don't have to use `:=` here. That would remove the need for last two statements. 
___
*[graphql/resolve/query_rewriter.go, line 218 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRZ6cLB5Z_W86oW-ndV:-MRZ6cLB5Z_W86oW-ndW:bugc58a) ([raw file](https://github.com/dgraph-io/dgraph/blob/54fd5389f687926194dcbaa390eb8b740335585e/graphql/resolve/query_rewriter.go#L218)):*
> ```Go
> 	// representation List should be same, we need to validate it and throw error
> 	// if represenation of more than one type exists.
> 	if len(typeNames) > 1 {
> ```

lets also add a check above this  that `if len(typeNames) == 0` we return an error, because we always want only one typeName, neither less nor more.
___
*[graphql/resolve/query_rewriter.go, line 251 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRZ3TcL-10MQJ81a_EN:-MRZ3TcL-10MQJ81a_EO:bobed3n) ([raw file](https://github.com/dgraph-io/dgraph/blob/54fd5389f687926194dcbaa390eb8b740335585e/graphql/resolve/query_rewriter.go#L251)):*
> ```
> keyFieldsValue
> ```
keyFieldsIsID
___
*[graphql/resolve/query_rewriter.go, line 258 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRZ40DaCpOAciqewpMO:-MRZ40DaCpOAciqewpMP:b4qch2g) ([raw file](https://github.com/dgraph-io/dgraph/blob/54fd5389f687926194dcbaa390eb8b740335585e/graphql/resolve/query_rewriter.go#L258)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> 		ids := convertIDs(keyFieldValueList)
> 		dgQuery.Func = &gql.Function{
> 			Name: "uid",
> 			UID:  ids,
> 		}
> ```
</details>

addUIDFunc(dgquery, convertIDs(keyFieldValueList))
___
*[graphql/resolve/query_rewriter.go, line 264 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRZ54HB6X8QXFZqZ3PE:-MRZ54HB6X8QXFZqZ3PF:blnwoaf) ([raw file](https://github.com/dgraph-io/dgraph/blob/54fd5389f687926194dcbaa390eb8b740335585e/graphql/resolve/query_rewriter.go#L264)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
> 		args := []gql.Arg{{Value: typeDefn.DgraphPredicate(keyFieldName)}}
> 		for _, v := range keyFieldValueList {
> 			args = append(args, gql.Arg{Value: maybeQuoteArg("eq", v)})
> 		}
> 		dgQuery.Func = &gql.Function{
> 			Name: "eq",
> 			Args: args,
> 		}
> ```
</details>

lets add a function `addEqFunc(q *gql.GraphQuery, dgPred string, values []interface{})` which encapsulates this piece of code.
___
*[graphql/resolve/query_rewriter.go, line 281 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRZ5auABA6LnmH37Zab:-MRZ5auABA6LnmH37Zac:b-nunwah) ([raw file](https://github.com/dgraph-io/dgraph/blob/54fd5389f687926194dcbaa390eb8b740335585e/graphql/resolve/query_rewriter.go#L281)):*
> ```
> 	// we don't need to query uid for auth queries, as they always have at least one field in their
> 	// selection set.
> ```
stale comment
___
*[graphql/resolve/query_rewriter.go, line 285 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRZ5fIv7r7PlfAZeYjy:-MRZ5fIv7r7PlfAZeYjz:blc5jix) ([raw file](https://github.com/dgraph-io/dgraph/blob/54fd5389f687926194dcbaa390eb8b740335585e/graphql/resolve/query_rewriter.go#L285)):*
> ```
> field.BuildType(typeName)
> ```
we already saved this in `typeDefn`, lets reuse that here
___
*[graphql/schema/wrappers.go, line 167 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRZ--mQ32OeOcibEVBS:-MRZ--mQ32OeOcibEVBT:by68r6i) ([raw file](https://github.com/dgraph-io/dgraph/blob/54fd5389f687926194dcbaa390eb8b740335585e/graphql/schema/wrappers.go#L167)):*
> ```
> 	KeyField(typeName string) (string, bool, error)
> 	BuildType(typeName string) Type
> ```
let's add comments here about what each of these functions does and what is the meaning of the returned values.
___
*[graphql/schema/wrappers.go, line 1143 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRYxajy2uLRk8T6lfMA:-MRYxajy2uLRk8T6lfMB:b-72cpe0) ([raw file](https://github.com/dgraph-io/dgraph/blob/54fd5389f687926194dcbaa390eb8b740335585e/graphql/schema/wrappers.go#L1143)):*
> ```
> t.NamedType = q.op.inSchema.schema.Types[typeName].Name
> ```
won't this be same as:
```
t.NamedType = typeName
```
___
*[graphql/schema/wrappers.go, line 1145 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRYy6w2AErMZkDRDNir:-MRYy6w2AErMZkDRDNis:b-7h9hae) ([raw file](https://github.com/dgraph-io/dgraph/blob/54fd5389f687926194dcbaa390eb8b740335585e/graphql/schema/wrappers.go#L1145)):*
> ```
> 		typ: &ast.Type{
> 			Elem: t,
> 		},
> ```
If typeName were `Astronaut`, this would mean: `[Astronaut]` (i.e. a list of Astronaut).
I think we just want it to be `Astronaut`, as we just want to refer to a type defined in the schema and not the return type of a field.
So, we should keep it like:
```
typ: t
```
So, overall this function would just be one return statement:
```
return &astType{
  typ: &ast.Type{NamedType: typeName},
  ...
  ...
}
```
___
*[graphql/schema/wrappers.go, line 1500 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRYzw7c1vUaqCa0gVi3:-MRYzw7c1vUaqCa0gVi4:byrzf5) ([raw file](https://github.com/dgraph-io/dgraph/blob/54fd5389f687926194dcbaa390eb8b740335585e/graphql/schema/wrappers.go#L1500)):*
> ```
> // Todo , modify to return isIDType
> ```
stale comment


<!-- Sent from Reviewable.io -->

2021-01-21 09:43 UTC, minhaj-shakeel reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7334)* status: 8 of 10 files reviewed, 15 unresolved discussions (waiting on @abhimanyusinghgaur, @minhaj-shakeel, and @pawanrawal)

___
*[graphql/resolve/query_rewriter.go, line 166 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRZ-cdLBrJKl-zoTbny:-MRZJdBl9fz-R5jPQ2OP:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/54fd5389f687926194dcbaa390eb8b740335585e/graphql/resolve/query_rewriter.go#L166)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> to resolve `extended` types.
> ```
not only the types extended by this service, but also the ones defined in this service
</blockquote></details>

Done.
___
*[graphql/resolve/query_rewriter.go, line 184 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRZ0K79DVdxTrcPyBUd:-MRZJdr3B6Qz9FUc7Iym:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/54fd5389f687926194dcbaa390eb8b740335585e/graphql/resolve/query_rewriter.go#L184)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> representations := field.ArgValue("representations").([]interface{})
> ```
```
representations, ok := field.ArgValue("representations").([]interface{})
if !ok {
  return nil, fmt.Errorf("Error parsing `_representations` argument")
}
```
</blockquote></details>

Done.
___
*[graphql/resolve/query_rewriter.go, line 193 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRZ10XlASyd87e037Gg:-MRZJeIDAnI8xx-f8DEH:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/54fd5389f687926194dcbaa390eb8b740335585e/graphql/resolve/query_rewriter.go#L193)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> unmarshelling
> ```
parsing
</blockquote></details>

Done.
___
*[graphql/resolve/query_rewriter.go, line 204 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRZ1tG7-kqtdjnusz2_:-MRZJek79PQnUPy00wm6:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/54fd5389f687926194dcbaa390eb8b740335585e/graphql/resolve/query_rewriter.go#L204)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 		keyFieldname, isIDType, err := field.KeyField(typename)
> 		if err != nil {
> 			return nil, err
> 		}
> 		keyFieldIsID = isIDType
> 		keyFieldName = keyFieldname
> ```
we should just declare `var err error` outside of this for loop, so that we don't have to use `:=` here. That would remove the need for last two statements. 
</blockquote></details>

Done.
___
*[graphql/resolve/query_rewriter.go, line 218 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRZ6cLB5Z_W86oW-ndV:-MRZJfAG0GFd4atF3raL:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/54fd5389f687926194dcbaa390eb8b740335585e/graphql/resolve/query_rewriter.go#L218)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

lets also add a check above this  that `if len(typeNames) == 0` we return an error, because we always want only one typeName, neither less nor more.
</blockquote></details>

Done.
___
*[graphql/resolve/query_rewriter.go, line 251 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRZ3TcL-10MQJ81a_EN:-MRZJfc61r4oexlSe2or:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/54fd5389f687926194dcbaa390eb8b740335585e/graphql/resolve/query_rewriter.go#L251)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> keyFieldsValue
> ```
keyFieldsIsID
</blockquote></details>

Done.
___
*[graphql/resolve/query_rewriter.go, line 258 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRZ40DaCpOAciqewpMO:-MRZJgGZ1Jv57xV_mNtS:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/54fd5389f687926194dcbaa390eb8b740335585e/graphql/resolve/query_rewriter.go#L258)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 		ids := convertIDs(keyFieldValueList)
> 		dgQuery.Func = &gql.Function{
> 			Name: "uid",
> 			UID:  ids,
> 		}
> ```
addUIDFunc(dgquery, convertIDs(keyFieldValueList))
</blockquote></details>

Done.
___
*[graphql/resolve/query_rewriter.go, line 264 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRZ54HB6X8QXFZqZ3PE:-MRZJgeu2KS30DvNte47:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/54fd5389f687926194dcbaa390eb8b740335585e/graphql/resolve/query_rewriter.go#L264)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 		args := []gql.Arg{{Value: typeDefn.DgraphPredicate(keyFieldName)}}
> 		for _, v := range keyFieldValueList {
> 			args = append(args, gql.Arg{Value: maybeQuoteArg("eq", v)})
> 		}
> 		dgQuery.Func = &gql.Function{
> 			Name: "eq",
> 			Args: args,
> 		}
> ```
lets add a function `addEqFunc(q *gql.GraphQuery, dgPred string, values []interface{})` which encapsulates this piece of code.
</blockquote></details>

Done.
___
*[graphql/resolve/query_rewriter.go, line 281 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRZ5auABA6LnmH37Zab:-MRZJhXP0t1d1aJ2FbvT:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/54fd5389f687926194dcbaa390eb8b740335585e/graphql/resolve/query_rewriter.go#L281)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 	// we don't need to query uid for auth queries, as they always have at least one field in their
> 	// selection set.
> ```
stale comment
</blockquote></details>

Done.
___
*[graphql/resolve/query_rewriter.go, line 285 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRZ5fIv7r7PlfAZeYjy:-MRZJiIi3m85nu_L82_G:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/54fd5389f687926194dcbaa390eb8b740335585e/graphql/resolve/query_rewriter.go#L285)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> field.BuildType(typeName)
> ```
we already saved this in `typeDefn`, lets reuse that here
</blockquote></details>

Done.
___
*[graphql/schema/wrappers.go, line 167 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRZ--mQ32OeOcibEVBS:-MRZJkGu7n6uvh-LdOnh:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/54fd5389f687926194dcbaa390eb8b740335585e/graphql/schema/wrappers.go#L167)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 	KeyField(typeName string) (string, bool, error)
> 	BuildType(typeName string) Type
> ```
let's add comments here about what each of these functions does and what is the meaning of the returned values.
</blockquote></details>

Done.
___
*[graphql/schema/wrappers.go, line 1143 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRYxajy2uLRk8T6lfMA:-MRZJkiu37NjmJeT2YUQ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/54fd5389f687926194dcbaa390eb8b740335585e/graphql/schema/wrappers.go#L1143)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> t.NamedType = q.op.inSchema.schema.Types[typeName].Name
> ```
won't this be same as:
```
t.NamedType = typeName
```
</blockquote></details>

Done.
___
*[graphql/schema/wrappers.go, line 1145 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRYy6w2AErMZkDRDNir:-MRZJlHV9EC25bnS2FRs:b-wpjwgb) ([raw file](https://github.com/dgraph-io/dgraph/blob/54fd5389f687926194dcbaa390eb8b740335585e/graphql/schema/wrappers.go#L1145)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 		typ: &ast.Type{
> 			Elem: t,
> 		},
> ```
If typeName were `Astronaut`, thi [...]

2021-01-21 13:14 UTC, pawanrawal approved these changes
> Reviewed 8 of 10 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7334)* status: all files reviewed, 24 unresolved discussions (waiting on @abhimanyusinghgaur and @minhaj-shakeel)

___
*[graphql/e2e/directives/schema.graphql, line 317 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MR_0Q2cEwcp4kOAE8_i:-MR_0Q2d9HvL-jOlHqO_:b-jpuwxv) ([raw file](https://github.com/dgraph-io/dgraph/blob/869acfb52df30c4822670aa14ebe87de5139271d/graphql/e2e/directives/schema.graphql#L317)):*
> ```GraphQL
> }
> 
> type Astronaut @key(fields: "id") @extends {
> ```

Add a comment here that why is this not used yet 
___
*[graphql/resolve/query_rewriter.go, line 165 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MR_0bfj4neulCone7TP:-MR_0bfj4neulCone7TQ:blh3ues) ([raw file](https://github.com/dgraph-io/dgraph/blob/869acfb52df30c4822670aa14ebe87de5139271d/graphql/resolve/query_rewriter.go#L165)):*
> ```Go
> }
> 
> // entitiesQuery rewrites The DQL Query from the Apollo `_entities` Query which is sent
> ```

rewrites the Apollo `_entities` Query which is sent from the Apollo gateway to a DQL query.  This query is sent to the Dgraph service to ....
___
*[graphql/resolve/query_rewriter.go, line 196 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MR_1Drm1-ZI5zAaifw2:-MR_1Drm1-ZI5zAaifw3:bm5ibar) ([raw file](https://github.com/dgraph-io/dgraph/blob/869acfb52df30c4822670aa14ebe87de5139271d/graphql/resolve/query_rewriter.go#L196)):*
> ```Go
> 		representation, ok := rep.(map[string]interface{})
> 		if !ok {
> 			return nil, fmt.Errorf("Error parsing `_representations` argument")
> ```

parsing 5th item in the `_representations` argument.
___
*[graphql/resolve/query_rewriter.go, line 204 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MR_1WOTDd3MHzSAup7K:-MR_1WOU-wL1M3Qsndbp:buxqrz9) ([raw file](https://github.com/dgraph-io/dgraph/blob/869acfb52df30c4822670aa14ebe87de5139271d/graphql/resolve/query_rewriter.go#L204)):*
> ```Go
> 		}
> 
> 		// Store all the typeNames into an Map to perfrom Validation at last.
> ```

validation with v small
___
*[graphql/resolve/query_rewriter.go, line 212 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MR_1fLR2dtSZ7rHeYXe:-MR_1fLS-U8AjIhUHlsc:bdyo34) ([raw file](https://github.com/dgraph-io/dgraph/blob/869acfb52df30c4822670aa14ebe87de5139271d/graphql/resolve/query_rewriter.go#L212)):*
> ```Go
> 		keyFieldValue, ok := representation[keyFieldName]
> 		if !ok {
> 			return nil, fmt.Errorf("Unable to extract value for key field `%s` from `_representations` argument", keyFieldName)
> ```

can return the index of the item in the array here as well
___
*[graphql/resolve/query_rewriter.go, line 222 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MR_1noo0a_l2lprusYz:-MR_1nopDIXiDaRP7vF2:bngi8yj) ([raw file](https://github.com/dgraph-io/dgraph/blob/869acfb52df30c4822670aa14ebe87de5139271d/graphql/resolve/query_rewriter.go#L222)):*
> ```Go
> 	}
> 
> 	// Since We have Restricted that All the typeNames for the inputs in the
> ```

Since we have restricted that all the typeNames
___
*[graphql/resolve/query_rewriter.go, line 281 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MR_2dHPAONgNS8b5y23:-MR_2dHPAONgNS8b5y24:b-jtwy6q) ([raw file](https://github.com/dgraph-io/dgraph/blob/869acfb52df30c4822670aa14ebe87de5139271d/graphql/resolve/query_rewriter.go#L281)):*
> ```Go
> 	dgQueries := authRw.addAuthQueries(typeDefn, []*gql.GraphQuery{dgQuery}, rbac)
> 
> 	if len(selectionAuth) > 0 {
> ```

```
return append(dgQueries, selectionAuth...), nil
```
___
*[graphql/resolve/query_test.yaml, line 3150 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MR_2xTh2aU8LxmUP8BC:-MR_2xTh2aU8LxmUP8BD:b-382y4y) ([raw file](https://github.com/dgraph-io/dgraph/blob/869acfb52df30c4822670aa14ebe87de5139271d/graphql/resolve/query_test.yaml#L3150)):*
> ```YAML
> 
> - 
>   name: "entities query for extended type having @key field of ID type"
> ```

Add a couple of unit tests with auth also, positive and negative scenarios.
___
*[graphql/schema/wrappers.go, line 1499 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MR_3kzsBHGS76ctfE_w:-MR_3kzsBHGS76ctfE_x:b6m7pta) ([raw file](https://github.com/dgraph-io/dgraph/blob/869acfb52df30c4822670aa14ebe87de5139271d/graphql/schema/wrappers.go#L1499)):*
> ```Go
> 
> func (q *query) KeyField(typeName string) (string, bool, error) {
> 	typ := q.op.inSchema.schema.Types[typeName]
> ```

if `typ == nil` return error.


<!-- Sent from Reviewable.io -->

2021-01-22 06:37 UTC, minhaj-shakeel reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7334)* status: 6 of 12 files reviewed, 24 unresolved discussions (waiting on @abhimanyusinghgaur and @pawanrawal)

___
*[graphql/e2e/directives/schema.graphql, line 317 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MR_0Q2cEwcp4kOAE8_i:-MRcns9D-8_CjC_r2W3Q:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/869acfb52df30c4822670aa14ebe87de5139271d/graphql/e2e/directives/schema.graphql#L317)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Add a comment here that why is this not used yet 
</blockquote></details>

Done.
___
*[graphql/resolve/query_rewriter.go, line 201 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MRZ1CY20-iP6ELRFXkm:-MRcnpsw5EYAj3C7inWd:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/54fd5389f687926194dcbaa390eb8b740335585e/graphql/resolve/query_rewriter.go#L201)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> an Array
> ```
a map
</blockquote></details>

Done.
___
*[graphql/resolve/query_rewriter.go, line 165 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MR_0bfj4neulCone7TP:-MRcnrgV3pMrZf5yrojL:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/869acfb52df30c4822670aa14ebe87de5139271d/graphql/resolve/query_rewriter.go#L165)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

rewrites the Apollo `_entities` Query which is sent from the Apollo gateway to a DQL query.  This query is sent to the Dgraph service to ....
</blockquote></details>

Done.
___
*[graphql/resolve/query_rewriter.go, line 196 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MR_1Drm1-ZI5zAaifw2:-MRcnqKaBbbbLWUsxwv9:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/869acfb52df30c4822670aa14ebe87de5139271d/graphql/resolve/query_rewriter.go#L196)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

parsing 5th item in the `_representations` argument.
</blockquote></details>

Done.
___
*[graphql/resolve/query_rewriter.go, line 204 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MR_1WOTDd3MHzSAup7K:-MRcnpYqDxvgiU12fcVk:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/869acfb52df30c4822670aa14ebe87de5139271d/graphql/resolve/query_rewriter.go#L204)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

validation with v small
</blockquote></details>

Done.
___
*[graphql/resolve/query_rewriter.go, line 212 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MR_1fLR2dtSZ7rHeYXe:-MRcnoOm64Y6cg88nRov:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/869acfb52df30c4822670aa14ebe87de5139271d/graphql/resolve/query_rewriter.go#L212)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

can return the index of the item in the array here as well
</blockquote></details>

Done.
___
*[graphql/resolve/query_rewriter.go, line 222 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MR_1noo0a_l2lprusYz:-MRcnnZx5eQt0JLoO6nn:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/869acfb52df30c4822670aa14ebe87de5139271d/graphql/resolve/query_rewriter.go#L222)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Since we have restricted that all the typeNames
</blockquote></details>

Done.
___
*[graphql/resolve/query_rewriter.go, line 281 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MR_2dHPAONgNS8b5y23:-MRcnljF41iHl5XTZnX7:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/869acfb52df30c4822670aa14ebe87de5139271d/graphql/resolve/query_rewriter.go#L281)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

```
return append(dgQueries, selectionAuth...), nil
```
</blockquote></details>

Done.
___
*[graphql/resolve/query_test.yaml, line 3150 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MR_2xTh2aU8LxmUP8BC:-MRcnkjsE1oxXVlDFDuU:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/869acfb52df30c4822670aa14ebe87de5139271d/graphql/resolve/query_test.yaml#L3150)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Add a couple of unit tests with auth also, positive and negative scenarios.
</blockquote></details>

Done.
___
*[graphql/schema/wrappers.go, line 1499 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7334#-MR_3kzsBHGS76ctfE_w:-MRcni0m1SGG4t1S3ZKv:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/869acfb52df30c4822670aa14ebe87de5139271d/graphql/schema/wrappers.go#L1499)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

if `typ == nil` return error.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-22 06:40 UTC, pawanrawal approved these changes
> Reviewed 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7334)* status: all files reviewed, 15 unresolved discussions (waiting on @abhimanyusinghgaur)



<!-- Sent from Reviewable.io -->

2021-01-22 06:42 UTC, merged