fix(Backups): new badger SuperFlag, NumGoroutines option solves OOM crashes
dgraph-io/dgraph pull request #7387
Opened 2021-02-02 15:15 UTC by karlmcguire

(This PR is paired with dgraph-io/badger#1656 which adds the Badger options.)

On master, Alpha nodes would crash during a backup on a machine with low memory (<6gb in my tests). This was because the default number of goroutines was [hardcoded as 16](https://github.com/dgraph-io/dgraph/blob/master/worker/backup_processor.go#L42) which is used to create [local threads](https://github.com/dgraph-io/dgraph/blob/master/worker/backup_processor.go#L68) and used to [overwrite `Stream.numGo`](https://github.com/dgraph-io/dgraph/blob/master/worker/backup_processor.go#L131). 

The solution is to add a `--badger "goroutines=8; ..."` SuperFlag to Alpha and anything else that might want to set Badger options. So far I've also added it to `bulk/run.go`, but that might be too much for this PR. The command line flags for Badger should be the same across each tool, for consistency.

2021-02-03 16:06 UTC, jarifibrahim commented on dgraph/cmd/alpha/run.go
> +	cache_mb=N total size of cache (in MB) per shard in the reducer.
We also have the posting list cache. We can move both the badger caches inside the `--badger` flag and keep the posting list size flag outside.

Something like `dgraph --badger="cache_mb=100; cache_percentage=50,50" --posting-cache-mb=50`

2021-02-03 16:06 UTC, jarifibrahim commented on worker/backup_processor.go
> +	BadgerDefaults = "goroutines=8; compression=snappy; cache_mb=64; cache_percentage=70,30;"
You can keep this in the `worker/server_state.go` file.

2021-02-03 16:06 UTC, jarifibrahim commented on worker/backup_processor.go
> +	BadgerDefaults = "goroutines=8; compression=snappy; cache_mb=64; cache_percentage=70,30;"
Keep the cache size to 1024. 64 mb might be too small.

2021-02-03 19:54 UTC, karlmcguire commented on dgraph/cmd/alpha/run.go
> +	goroutines=N provides the number of goroutines to use in badger.Stream.
We need this `goroutines` flag in Alpha for [creating local threads during backups](https://github.com/dgraph-io/dgraph/pull/7387/files#diff-e64b7a1608a78718294f5229733bcdfc7a383ecb5a359dd82ab35883874a94cbR63), and Badger uses the `goroutines` value as the default `Stream.numGo`.

2021-02-03 19:54 UTC, karlmcguire commented on dgraph/cmd/alpha/run.go
> +	compression=[none, zstd:level, snappy] specifies the compression algorithm and the compression
We need this `compression` flag in Alpha for [setting the compression type](https://github.com/dgraph-io/dgraph/pull/7387/files#diff-a72445362e52218163e2d2f572b946ff3aea61f8675aa235a5dab3227ac6168eR610) of Badger.

2021-02-03 19:54 UTC, karlmcguire commented on dgraph/cmd/bulk/run.go
> +	compression=[none, zstd:level, snappy] specifies the compression algorithm and the compression
We need this `compression` flag in Bulk for [setting the compression type](https://github.com/dgraph-io/dgraph/pull/7387/files#diff-76237e26c3354ceb21e16c8c34877ddb485e468d4eb711ba35477f35f9018e96R133) of Badger (similar to how Alpha uses it).

2021-02-03 19:54 UTC, karlmcguire commented on dgraph/cmd/bulk/run.go
> +	cache_mb=N total size of cache (in MB) per shard in the reducer.
We need this `cache_mb` flag in Bulk for [setting the Badger cache size](https://github.com/dgraph-io/dgraph/pull/7387/files#diff-76237e26c3354ceb21e16c8c34877ddb485e468d4eb711ba35477f35f9018e96R170). The default value is set in [`worker/server_state.go`](https://github.com/dgraph-io/dgraph/pull/7387/files#diff-02ceb0db5e4dd0958bdba03c2fdee17011b75a2fc34cdaec7d232a828d7bfda8R34).

2021-02-03 19:54 UTC, karlmcguire commented on dgraph/cmd/bulk/run.go
> +	cache_percentage=N cache percentages summing up to 100 for various caches.
We need this `cache_percentage` flag in Bulk for [setting the BlockCacheSize and IndexCacheSize](https://github.com/dgraph-io/dgraph/pull/7387/files#diff-76237e26c3354ceb21e16c8c34877ddb485e468d4eb711ba35477f35f9018e96R172).

2021-02-03 19:54 UTC, karlmcguire commented on worker/backup_processor.go
> +		threads: make([]*threadLocal, x.WorkerConfig.Badger.GetUint64("goroutines")),
TODO: Figure out how to calculate this at runtime so we never have OOM errors with default flags?

2021-02-03 19:54 UTC, karlmcguire commented on worker/server_state.go
> +	BadgerDefaults = "goroutines=8; compression=snappy; cache_mb=64; cache_percentage=70,30"
Some of these defaults aren't used by Alpha, which is kind of confusing...

We use [`goroutines`](https://github.com/dgraph-io/dgraph/pull/7387/files#diff-a72445362e52218163e2d2f572b946ff3aea61f8675aa235a5dab3227ac6168eR113) and [`compression`](https://github.com/dgraph-io/dgraph/pull/7387/files#diff-a72445362e52218163e2d2f572b946ff3aea61f8675aa235a5dab3227ac6168eR114) in Alpha.

We use [`compression`](https://github.com/dgraph-io/dgraph/pull/7387/files#diff-76237e26c3354ceb21e16c8c34877ddb485e468d4eb711ba35477f35f9018e96R120), [`cache_mb`](https://github.com/dgraph-io/dgraph/pull/7387/files#diff-76237e26c3354ceb21e16c8c34877ddb485e468d4eb711ba35477f35f9018e96R123), and [`cache_percentage`](https://github.com/dgraph-io/dgraph/pull/7387/files#diff-76237e26c3354ceb21e16c8c34877ddb485e468d4eb711ba35477f35f9018e96R124) in Bulk.

2021-02-09 14:31 UTC, manishrjain requested changes
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7387)* status: 0 of 5 files reviewed, 14 unresolved discussions (waiting on @karlmcguire and @vvbalaji-dgraph)

___
*[dgraph/cmd/alpha/run.go, line 609 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7387#-MSddWd60nJPxI374FZS:-MSddWd8BLu7Z4w7gzJP:b-1ex4r) ([raw file](https://github.com/dgraph-io/dgraph/blob/1d65d59695b55405d4e53002a8f0a02a03a01134/dgraph/cmd/alpha/run.go#L609)):*
> ```Go
> 	walCache := (cachePercent[3] * (totalCache << 20)) / 100
> 
> 	badger := x.NewSuperFlag(Alpha.Conf.GetString("badger")).MergeAndCheckDefault(worker.BadgerDefaults)
> ```

100 chars.
___
*[dgraph/cmd/bulk/run.go, line 120 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7387#-MT6Bek37Boz2J1yy1qS:-MT6Bek37Boz2J1yy1qT:b-d3zjqa) ([raw file](https://github.com/dgraph-io/dgraph/blob/1d65d59695b55405d4e53002a8f0a02a03a01134/dgraph/cmd/bulk/run.go#L120)):*
> ```Go
> 	flag.String("badger", worker.BadgerDefaults,
> 		`Various badger options.
> 	compression=[none, zstd:level, snappy] specifies the compression algorithm and the compression
> ```

This string can be in one place. Also, we should be using Badger options directly. Whatever options Badger already has, should do directly to Badger.
___
*[dgraph/cmd/bulk/run.go, line 132 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7387#-MT6BrnJABme4z4SnDGR:-MT6BrnJABme4z4SnDGS:b-1ex4r) ([raw file](https://github.com/dgraph-io/dgraph/blob/1d65d59695b55405d4e53002a8f0a02a03a01134/dgraph/cmd/bulk/run.go#L132)):*
> ```Go
> 
> func run() {
> 	badger := x.NewSuperFlag(Bulk.Conf.GetString("badger")).MergeAndCheckDefault(worker.BadgerDefaults)
> ```

100 chars.
___
*[worker/server_state.go, line 34 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7387#-MSYJ34KNekuFqMrO4qh-r2-34:-MT6C-NL4Unah-ZCpyqA:b-jcolot) ([raw file](https://github.com/dgraph-io/dgraph/blob/1d65d59695b55405d4e53002a8f0a02a03a01134/worker/server_state.go#L34)):*
<details><summary><i>Previously, karlmcguire (Karl McGuire) wrote…</i></summary><blockquote>

Some of these defaults aren't used by Alpha, which is kind of confusing...

We use [`goroutines`](https://github.com/dgraph-io/dgraph/pull/7387/files#diff-a72445362e52218163e2d2f572b946ff3aea61f8675aa235a5dab3227ac6168eR113) and [`compression`](https://github.com/dgraph-io/dgraph/pull/7387/files#diff-a72445362e52218163e2d2f572b946ff3aea61f8675aa235a5dab3227ac6168eR114) in Alpha.

We use [`compression`](https://github.com/dgraph-io/dgraph/pull/7387/files#diff-76237e26c3354ceb21e16c8c34877ddb485e468d4eb711ba35477f35f9018e96R120), [`cache_mb`](https://github.com/dgraph-io/dgraph/pull/7387/files#diff-76237e26c3354ceb21e16c8c34877ddb485e468d4eb711ba35477f35f9018e96R123), and [`cache_percentage`](https://github.com/dgraph-io/dgraph/pull/7387/files#diff-76237e26c3354ceb21e16c8c34877ddb485e468d4eb711ba35477f35f9018e96R124) in Bulk. 

It doesn't make sense to split up the `BadgerDefaults` across packages, but it might be worth adding a comment explaining which packages use which options.
</blockquote></details>

Let's not change the default value of cache.


<!-- Sent from Reviewable.io -->

2021-02-16 14:36 UTC, karlmcguire commented
> This string can be in one place.

Where? We have Badger flags for Alpha and Bulk, both using different flags. Alpha used to expose `compression` and `goroutine`, Bulk used to expose `compression`, `cache_mb`, and `cache_percentage`. If we get rid of `cache_mb` and `cache_percentage` then we could probably just use the same `compression` and `goroutine` flag string for Alpha and Bulk.

> Also, we should be using Badger options directly. Whatever options Badger already has, should do directly to Badger.

I'm not sure what this means.           

> Let's not change the default value of cache.

We're currently using `cache_mb` and `cache_percentage` in Bulk [here](https://github.com/dgraph-io/dgraph/blob/master/dgraph/cmd/bulk/run.go#L124-L127) for the [block and index caches](https://github.com/dgraph-io/dgraph/blob/master/dgraph/cmd/bulk/run.go#L173-L179). Should we not expose these flags?

2021-02-22 20:45 UTC, merged