feat(cmd/debug): Add decode_key to debug tool.
dgraph-io/dgraph pull request #7640
Opened 2021-03-24 06:23 UTC by danielmai

This adds a `dgraph debug --decode_key` flag that can return the ParsedKey
struct of a hex key. This is useful if there's a lone key that you want parse
without having to have a p directory around---this flag does not need a p
directory, just the hex key string.

Example:

    $ dgraph debug --decode_key 00000375726c000000000000000001
    Key: {ByteType:0 Attr:url Uid:1 HasStartUid:false StartUid:0 Term: Count:0 bytePrefix:0}

  This tells you that the key 00000375726c000000000000000001 is for the
  predicate `url` and the UID `0x1`.

2021-05-20 06:09 UTC, jarifibrahim approved these changes

2023-08-21 10:44 UTC, harshil-goel approved these changes

2023-08-21 20:03 UTC, all-seeing-code requested changes
This is a valuable update. o ensure users are fully aware, could we also update the documentation here: https://dgraph.io/docs/howto/using-debug-tool/? Including this doc update in the PR would be beneficial, and I believe it might be a minor adjustment. Thank you!

2023-08-24 07:30 UTC, all-seeing-code approved these changes
Thanks!

2023-08-24 07:55 UTC, kevinmingtarja approved these changes

2023-08-24 08:21 UTC, merged