feat(cloud): add cloud mode flag in alpha to disable ACL for non-GoG
dgraph-io/dgraph pull request #7770
Opened 2021-04-30 19:23 UTC by NamanJain8

This PR adds a `--cloud` super flag. It contains a flag `disable-non-galaxy`, when set to true (false by default), will restrict access to any of the ACL operations like `Login`, add/remove/update user from non-galaxy namespaces.

2021-05-03 11:15 UTC, NamanJain8 commented on edgraph/access_ee.go
> +	aclOp *acl.Operation) *authPredResult {
This is just some clean up.

2021-05-03 13:08 UTC, jarifibrahim reviewed
The PR looks good to me but we need tests. @NamanJain8 create a docker compose file with the cloud flag and then try to run login/create user, etc on that dgraph cluster.

2021-05-04 19:15 UTC, manishrjain requested changes
some early comments. Haven't looked at the rest of the PR yet.

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7770#-:-MZsndlrDdeQWJ7Y3s4o:bq9t1ev)* status: 0 of 13 files reviewed, 4 unresolved discussions (waiting on @NamanJain8 and @vvbalaji-dgraph)

___
*[dgraph/cmd/alpha/run.go, line 262 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7770#-MZsmn8rCg9wEF_tDWtO:-MZsmn8rCg9wEF_tDWtP:buzvtnf) ([raw file](https://github.com/dgraph-io/dgraph/blob/0772daef8fd304376277233aafca21e15dde8fa3/dgraph/cmd/alpha/run.go#L262)):*
> ```Go
> 		String())
> 
> 	flag.String("cloud", worker.CloudDefaults, z.NewSuperFlagHelp(worker.CloudDefaults).
> ```

how about put this in the "limit" flag?
___
*[dgraph/cmd/alpha/run.go, line 264 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7770#-MZsn3On4U7yzFSyryp8:-MZsn3On4U7yzFSyryp9:btq0fz2) ([raw file](https://github.com/dgraph-io/dgraph/blob/0772daef8fd304376277233aafca21e15dde8fa3/dgraph/cmd/alpha/run.go#L264)):*
> ```Go
> 	flag.String("cloud", worker.CloudDefaults, z.NewSuperFlagHelp(worker.CloudDefaults).
> 		Head("Dgraph cloud options").
> 		Flag("disable-non-galaxy",
> ```

probably don't need this. Unless you think the cloud flag would grow to many options. I reckon it's just for "shared-instance" users of the cloud.

So, perhaps `limit=shared-instance=true`, which would then automatically disable a bunch of things.
___
*[testutil/multi_tenancy.go, line 347 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7770#-MZsnPZA329NVz3AxD0x:-MZsnPZA329NVz3AxD0y:b-1ex4r) ([raw file](https://github.com/dgraph-io/dgraph/blob/0772daef8fd304376277233aafca21e15dde8fa3/testutil/multi_tenancy.go#L347)):*
> ```Go
> 
> func Export(t *testing.T, token *HttpToken, dest, accessKey, secretKey string) *GraphQLResponse {
> 	exportRequest := `mutation export($dst: String!, $f: String!, $access: String!, $secret: String!){
> ```

100 chars.


<!-- Sent from Reviewable.io -->

2021-05-05 06:43 UTC, jarifibrahim approved these changes
Get @ahsanbarkati's review as well.

2021-05-05 07:35 UTC, NamanJain8 reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7770)* status: 0 of 14 files reviewed, 3 unresolved discussions (waiting on @manishrjain and @vvbalaji-dgraph)

___
*[dgraph/cmd/alpha/run.go, line 262 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7770#-MZsmn8rCg9wEF_tDWtO:-MZvRbxBATirjY0KVq7C:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0772daef8fd304376277233aafca21e15dde8fa3/dgraph/cmd/alpha/run.go#L262)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

how about put this in the "limit" flag?
</blockquote></details>

Done.
___
*[dgraph/cmd/alpha/run.go, line 264 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7770#-MZsn3On4U7yzFSyryp8:-MZvRdc8AK53U5hMlOuQ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0772daef8fd304376277233aafca21e15dde8fa3/dgraph/cmd/alpha/run.go#L264)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

probably don't need this. Unless you think the cloud flag would grow to many options. I reckon it's just for "shared-instance" users of the cloud.

So, perhaps `limit=shared-instance=true`, which would then automatically disable a bunch of things.
</blockquote></details>

Done.
___
*[testutil/multi_tenancy.go, line 347 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7770#-MZsnPZA329NVz3AxD0x:-MZvRgZT3yTDGCS6dI6d:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0772daef8fd304376277233aafca21e15dde8fa3/testutil/multi_tenancy.go#L347)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

100 chars.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-05 08:00 UTC, ahsanbarkati approved these changes

2021-05-05 08:00 UTC, merged