feat(GraphQL): Support auth with custom DQL
dgraph-io/dgraph pull request #7775
Opened 2021-05-03 14:54 UTC by minhaj-shakeel

Fixes GRAPHQL-1171.

2021-05-12 14:26 UTC, abhimanyusinghgaur requested changes
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7775)* status: 1 of 9 files reviewed, 8 unresolved discussions (waiting on @minhaj-shakeel and @pawanrawal)

___
*[graphql/dgraph/graphquery.go, line 217 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7775#-M_VnUdj8qebxsQ7UrXH:-M_VnUdk-n4K4NENu2Xr:bn33a3s) ([raw file](https://github.com/dgraph-io/dgraph/blob/b54cc0cef8a9d9af158a1d47b085c7e13e0a4bae/graphql/dgraph/graphquery.go#L217)):*
> ```
> writeFilterArguments(b, q.Func.Args, q.Func.Attr, q.Func.Name)
> ```
maybe just pass `q.Func` and use that in the function
___
*[graphql/dgraph/graphquery.go, line 223 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7775#-M_VnlEm71WOOQP7avLS:-M_VnlEm71WOOQP7avLT:b-4acqhk) ([raw file](https://github.com/dgraph-io/dgraph/blob/b54cc0cef8a9d9af158a1d47b085c7e13e0a4bae/graphql/dgraph/graphquery.go#L223)):*
> ```Go
> }
> 
> func maybeQuoteArg(fn string, arg interface{}) string {
> ```

I think we have a similar function in `resolve` pkg. Can't we reuse that here?
If it's a package dependency issue, we can move that function to a higher level package in the dependency tree (`schema` pkg), or in the package`x`.
___
*[graphql/e2e/auth/schema.graphql, line 991 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7775#-M_VpYbyDCXXS8-lAnrN:-M_VpYbyDCXXS8-lAnrO:b-lsqfyl) ([raw file](https://github.com/dgraph-io/dgraph/blob/b54cc0cef8a9d9af158a1d47b085c7e13e0a4bae/graphql/e2e/auth/schema.graphql#L991)):*
> ```
> $search: string
> ```
stale
___
*[graphql/e2e/auth/schema.graphql, line 997 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7775#-M_VqMgBBdAwvwG96z22:-M_VqMgBBdAwvwG96z23:buoa8hw) ([raw file](https://github.com/dgraph-io/dgraph/blob/b54cc0cef8a9d9af158a1d47b085c7e13e0a4bae/graphql/e2e/auth/schema.graphql#L997)):*
> ```
> orderdesc: val(age)
> ```
can this directly work here? as the map `age` is a map from owner uid to age value, while the root func here is iterating over the Issue uids. So, I think this might not produce the intended results after all.
This var query might be needed:
```
		iss as var(func: type(Issue)) @filter(has(Issue.owner)) {
			Issue.owner {
				age as User.age
			}
			ownerAge as max(val(age))
		}
```
Then use `val(ownerAge)` in the `orderdesc`.
___
*[graphql/resolve/custom_auth_query_test.yaml, line 26 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7775#-M_VxwAh7nt1wuNKK3Hi:-M_VxwAh7nt1wuNKK3Hj:b-lxoeh3) ([raw file](https://github.com/dgraph-io/dgraph/blob/b54cc0cef8a9d9af158a1d47b085c7e13e0a4bae/graphql/resolve/custom_auth_query_test.yaml#L26)):*
> ```YAML
>     }
> 
> - name : "custom DQL query with var block RBAC rules true"
> ```

can we also add another test where there are multiple var blocks in the DQL, and all of them are used in the user's query?
___
*[graphql/resolve/custom_auth_query_test.yaml, line 75 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7775#-M_VsRs92Kr6tlC7-1L3:-M_VsRs92Kr6tlC7-1L4:bng6oc1) ([raw file](https://github.com/dgraph-io/dgraph/blob/b54cc0cef8a9d9af158a1d47b085c7e13e0a4bae/graphql/resolve/custom_auth_query_test.yaml#L75)):*
> ```
> iss as var(func: uid(0x1)) @filter((uid(0x2) AND has(Issue.owner)))
> ```
:+1: 
why is the `AND has(Issue.owner)` here?
___
*[graphql/resolve/query_rewriter.go, line 641 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7775#-M_VvEPDC9M1YXwxuQD5:-M_VvEPE9nuQi7-BxMsx:boyhmlf) ([raw file](https://github.com/dgraph-io/dgraph/blob/b54cc0cef8a9d9af158a1d47b085c7e13e0a4bae/graphql/resolve/query_rewriter.go#L641)):*
<details><summary><i alt="summary">Quoted 12 lines of code…</i></summary>

> ```
> 	args := query.Arguments()
> 	vars := make(map[string]string)
> 	for k, v := range args {
> 		// dgoapi.Request{}.Vars accepts only string values for variables,
> 		// so need to convert all variable values to string
> 		vStr, err := convertScalarToString(v)
> 		if err != nil {
> 			return nil, err
> 		}
> 		// the keys in dgoapi.Request{}.Vars are assumed to be prefixed with $
> 		vars["$"+k] = vStr
> 	}
> ```
</details>

we should put this in a function, this piece of code is being used at two places
___
*[graphql/resolve/query_rewriter.go, line 680 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7775#-M_VvZ_PBh_5jwaz-M6E:-M_VvZ_PBh_5jwaz-M6F:b-ksc1xm) ([raw file](https://github.com/dgraph-io/dgraph/blob/b54cc0cef8a9d9af158a1d47b085c7e13e0a4bae/graphql/resolve/query_rewriter.go#L680)):*
> ```
> 	typeName = extractTypeFromFilter(dgQuery.Filter)
> 	return typeName
> ```
`return extractTypeFromFilter(dgQuery.Filter)`

also, should we try to extract type from `order`?


<!-- Sent from Reviewable.io -->

2021-05-18 04:27 UTC, minhaj-shakeel reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7775)* status: 0 of 10 files reviewed, 8 unresolved discussions (waiting on @abhimanyusinghgaur and @pawanrawal)

___
*[graphql/dgraph/graphquery.go, line 217 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7775#-M_VnUdj8qebxsQ7UrXH:-M_xiMenE4NQv4DYNG5_:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b54cc0cef8a9d9af158a1d47b085c7e13e0a4bae/graphql/dgraph/graphquery.go#L217)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> writeFilterArguments(b, q.Func.Args, q.Func.Attr, q.Func.Name)
> ```
maybe just pass `q.Func` and use that in the function
</blockquote></details>

Done.
___
*[graphql/dgraph/graphquery.go, line 223 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7775#-M_VnlEm71WOOQP7avLS:-M_xiOcy9BFx2CYNUyh1:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b54cc0cef8a9d9af158a1d47b085c7e13e0a4bae/graphql/dgraph/graphquery.go#L223)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

I think we have a similar function in `resolve` pkg. Can't we reuse that here?
If it's a package dependency issue, we can move that function to a higher level package in the dependency tree (`schema` pkg), or in the package`x`.
</blockquote></details>

Done.
___
*[graphql/e2e/auth/schema.graphql, line 991 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7775#-M_VpYbyDCXXS8-lAnrN:-M_xiQGz7gdsfqS_HWwr:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b54cc0cef8a9d9af158a1d47b085c7e13e0a4bae/graphql/e2e/auth/schema.graphql#L991)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> $search: string
> ```
stale
</blockquote></details>

Done.
___
*[graphql/e2e/auth/schema.graphql, line 997 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7775#-M_VqMgBBdAwvwG96z22:-M_xiRRN6qd6-Jcpqiy0:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b54cc0cef8a9d9af158a1d47b085c7e13e0a4bae/graphql/e2e/auth/schema.graphql#L997)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> orderdesc: val(age)
> ```
can this directly work here? as the map `age` is a map from owner uid to age value, while the root func here is iterating over the Issue uids. So, I think this might not produce the intended results after all.
This var query might be needed:
```
		iss as var(func: type(Issue)) @filter(has(Issue.owner)) {
			Issue.owner {
				age as User.age
			}
			ownerAge as max(val(age))
		}
```
Then use `val(ownerAge)` in the `orderdesc`.
</blockquote></details>

Done.
___
*[graphql/resolve/custom_auth_query_test.yaml, line 26 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7775#-M_VxwAh7nt1wuNKK3Hi:-M_xiU2Q6F_r0TDfwtQQ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b54cc0cef8a9d9af158a1d47b085c7e13e0a4bae/graphql/resolve/custom_auth_query_test.yaml#L26)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

can we also add another test where there are multiple var blocks in the DQL, and all of them are used in the user's query?
</blockquote></details>

Done.
___
*[graphql/resolve/custom_auth_query_test.yaml, line 75 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7775#-M_VsRs92Kr6tlC7-1L3:-M_xiV340cYwNq2-Aonm:bzb3qs) ([raw file](https://github.com/dgraph-io/dgraph/blob/b54cc0cef8a9d9af158a1d47b085c7e13e0a4bae/graphql/resolve/custom_auth_query_test.yaml#L75)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> iss as var(func: uid(0x1)) @filter((uid(0x2) AND has(Issue.owner)))
> ```
:+1: 
why is the `AND has(Issue.owner)` here?
</blockquote></details>

because it is attached in the query.
___
*[graphql/resolve/query_rewriter.go, line 641 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7775#-M_VvEPDC9M1YXwxuQD5:-M_xibeZ3qKgAYpDb5UP:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b54cc0cef8a9d9af158a1d47b085c7e13e0a4bae/graphql/resolve/query_rewriter.go#L641)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 	args := query.Arguments()
> 	vars := make(map[string]string)
> 	for k, v := range args {
> 		// dgoapi.Request{}.Vars accepts only string values for variables,
> 		// so need to convert all variable values to string
> 		vStr, err := convertScalarToString(v)
> 		if err != nil {
> 			return nil, err
> 		}
> 		// the keys in dgoapi.Request{}.Vars are assumed to be prefixed with $
> 		vars["$"+k] = vStr
> 	}
> ```
we should put this in a function, this piece of code is being used at two places
</blockquote></details>

Done.
___
*[graphql/resolve/query_rewriter.go, line 680 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7775#-M_VvZ_PBh_5jwaz-M6E:-M_xidSJChwUBjZVZ0Pd:b-gr4804) ([raw file](https://github.com/dgraph-io/dgraph/blob/b54cc0cef8a9d9af158a1d47b085c7e13e0a4bae/graphql/resolve/query_rewriter.go#L680)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 	typeName = extractTypeFromFilter(dgQuery.Filter)
> 	return typeName
> ```
`return extractTypeFromFilter(dgQuery.Filter)`

also, should we try to extract type from `order`?
</blockquote></details>

Done. Added an example of order also.


<!-- Sent from Reviewable.io -->

2021-05-21 04:50 UTC, vmrajas approved these changes
LGTM

2021-05-21 04:50 UTC, vmrajas commented on graphql/dgraph/graphquery.go
> +func writeNeedVar(b *strings.Builder, query *gql.GraphQuery) {
add a comment

2021-05-21 04:50 UTC, vmrajas commented on graphql/dgraph/graphquery.go
> +func writeFilterArguments(b *strings.Builder, q *gql.Function) {
Add a comment. check if the condition needs to be updated.

2021-05-21 04:50 UTC, vmrajas commented on graphql/e2e/auth/schema.graphql
> +    queryIssueSortedByOwnerAge: [Issue] @custom(dql: """
Fix indentation if possible.

2021-05-21 04:50 UTC, vmrajas commented on graphql/e2e/auth/auth_test.go
> +			name: "RBAC OR filter query; RBAC fail",
nit: RBAC false or user1 projects.

2021-05-21 04:50 UTC, vmrajas commented on graphql/e2e/auth/auth_test.go
> +		query{
nit: indent

2021-05-21 04:50 UTC, vmrajas commented on graphql/resolve/custom_auth_query_test.yaml
> +- name : "Auth rules with deep filter missing JWT"
add an explanation field for easier understanding.

2021-05-21 04:50 UTC, vmrajas commented on graphql/resolve/query_rewriter.go
> +	for _, qry := range parsedResult.Query {
Add a comment

2021-05-21 04:50 UTC, vmrajas commented on graphql/resolve/query_rewriter.go
> +		if typ.IsInterface() && !implementingTypesHasAuthRules {
:+1:

2021-05-21 04:50 UTC, vmrajas commented on graphql/resolve/query_rewriter.go
> +func getFieldName(attr string) string {
May be add a TODO here or in query rewriter that dgraph directive with custom DQL auth won't work and is to be added.

2021-05-24 10:41 UTC, minhaj-shakeel reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7775)* status: 0 of 10 files reviewed, 15 unresolved discussions (waiting on @abhimanyusinghgaur, @minhaj-shakeel, @pawanrawal, and @vmrajas)

___
*[graphql/e2e/auth/schema.graphql, line 990 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7775#-MZmiFhxCIObd98LcGLw-r2-990:-MaSwm0G2Vv3IJxl0p3I:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/434cdcd6085462fb759f3171bcb787b5ce175fbb/graphql/e2e/auth/schema.graphql#L990)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

Fix indentation if possible.
</blockquote></details>

Done.
___
*[graphql/resolve/custom_auth_query_test.yaml, line 154 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7775#-MZpZG4YRayolWeD0itY-r2-154:-MaSwnsE2pUTNeqZip7a:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/434cdcd6085462fb759f3171bcb787b5ce175fbb/graphql/resolve/custom_auth_query_test.yaml#L154)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

add an explanation field for easier understanding.
</blockquote></details>

Done.
___
*[graphql/resolve/query_rewriter.go, line 648 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7775#-MZmiFhxCIObd98LcGLy-r2-648:-MaSwt0O19Mdj2akcxdV:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/434cdcd6085462fb759f3171bcb787b5ce175fbb/graphql/resolve/query_rewriter.go#L648)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

Add a comment
</blockquote></details>

Done.
___
*[graphql/resolve/query_rewriter.go, line 998 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7775#-MZmiFhxCIObd98LcGLy-r2-998:-MaSwuLsD0xVQ-U_hjov:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/434cdcd6085462fb759f3171bcb787b5ce175fbb/graphql/resolve/query_rewriter.go#L998)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

Done.
___
*[graphql/resolve/query_rewriter.go, line 1728 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7775#-MZmiFhxCIObd98LcGLy-r2-1728:-MaSxckH9ZrNskgwUHTb:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/434cdcd6085462fb759f3171bcb787b5ce175fbb/graphql/resolve/query_rewriter.go#L1728)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

May be add a TODO here or in query rewriter that dgraph directive with custom DQL auth won't work and is to be added.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-25 07:14 UTC, abhimanyusinghgaur approved these changes
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7775)* status: 0 of 10 files reviewed, 7 unresolved discussions (waiting on @abhimanyusinghgaur, @minhaj-shakeel, @pawanrawal, and @vmrajas)



<!-- Sent from Reviewable.io -->

2021-05-26 05:22 UTC, minhaj-shakeel commented
Fixes GRAPHQL-1171.
This PR adds support for @auth on custom DQL queries.
This PR also adds the parsing step to the DQL query.
The Algorithm tries to figure out the `queried type` at the root of the query either from the `root func` or `filters`.
Suppose if the root func is `func: type(Person)` or `func: has(Person.name)` or `func: eq(Person.age, 10)` then 
it infers that the queried type is `Person`. 
However, there are certain DQL queries on which @auth rules are not added currently since the queried type is not clear. 
for eg: 
```
me(func: uid(0x1, 0x2)) {
 ...
}
```
or the query:
```
me(func: has(name@en) {
 ...
}
```

2021-05-26 05:23 UTC, merged

2022-01-26 01:44 UTC, benwoodward commented
Would be great if there was some example syntax. If I'm creating a `@custom` query, then I put it inside `type Query {}`. So presumably I add `@auth` directive rules to `type Query {}` as I would do if it were not a `@custom` query? Assuming this is the case, then if I have multiple `@custom` queries, can I create multiple `type Query {}` blocks, one for each `@custom` query, each block with its own `@auth` rules? How would you solve this problem?