WIP: Add GCS backup support
dgraph-io/dgraph pull request #7829
Opened 2021-05-18 17:38 UTC by rohanprasad

Currently, we use MinIO to write backup files to CGP storage. To do this we need to start a minio server (with GCP credentials) and trigger a backup with the destination as the minio server. This requires the user to run the minio server every time (or always) when a backup needs to be triggered. Using native  SDK will help get rid of the extra service.

Fixes DGRAPH-3340

2021-05-19 14:53 UTC, ahsanbarkati requested changes
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7829)* status: 0 of 3 files reviewed, 16 unresolved discussions (waiting on @manishrjain, @rohanprasad, and @vvbalaji-dgraph)

___
*[x/handlers.go, line 364 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma4117Q41g0RrXkQfS2:-Ma4117Q41g0RrXkQfS3:bhnxze4) ([raw file](https://github.com/dgraph-io/dgraph/blob/21f96cd7a069613597fdaa264c436335b8b62858/x/handlers.go#L364)):*
> ```Go
> }
> 
> func NewGCSHandler(uri *url.URL, creds *MinioCredentials) (gcs *GCS, err error) {
> ```

`creds` is not being used anywhere in the function. If it is unused, we should remove it.

Rather, we should pass the creds instead of reading from the `env` variables.
___
*[x/handlers.go, line 399 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma42PfV03h2GIDZdAy9:-Ma42PfV03h2GIDZdAyA:b-lnc78a) ([raw file](https://github.com/dgraph-io/dgraph/blob/21f96cd7a069613597fdaa264c436335b8b62858/x/handlers.go#L399)):*
> ```Go
> 
> 	gcs.bucket = gcs.client.Bucket(uri.Host)
> 	if _, err := gcs.bucket.Attrs(ctx); err != nil {
> ```

Is this the idiomatic way to check for the existence of the bucket?
___
*[x/handlers.go, line 401 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma42ZtWASdHu-RTar54:-Ma42ZtWASdHu-RTar55:b-bnyrfe) ([raw file](https://github.com/dgraph-io/dgraph/blob/21f96cd7a069613597fdaa264c436335b8b62858/x/handlers.go#L401)):*
> ```Go
> 	if _, err := gcs.bucket.Attrs(ctx); err != nil {
> 		gcs.client.Close()
> 		return nil, errors.Wrapf(err, "while accessing bucket: %s", err)
> ```

No need to have err twice, 
`errors.Wrap(err, "while accessing bucket")`
___
*[x/handlers.go, line 413 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma437dQ3JUsiaWGe9Rw:-Ma437dR3i975U5jziHO:bzddlha) ([raw file](https://github.com/dgraph-io/dgraph/blob/21f96cd7a069613597fdaa264c436335b8b62858/x/handlers.go#L413)):*
> ```Go
> 	// GCS used a flat storage and provides an illusion of directories. To create a directory, file
> 	// name must be followed by '/'.
> 	dir := filepath.Join(gcs.pathName, path, "") + "/"
> ```

Use `filepath.Separator` instead of  '/'.
___
*[x/handlers.go, line 414 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma43nju8vwR2GYo4R0R:-Ma43nju8vwR2GYo4R0S:bunlagr) ([raw file](https://github.com/dgraph-io/dgraph/blob/21f96cd7a069613597fdaa264c436335b8b62858/x/handlers.go#L414)):*
> ```Go
> 	// name must be followed by '/'.
> 	dir := filepath.Join(gcs.pathName, path, "") + "/"
> 	glog.V(2).Infof("Creating dir: %s", dir)
> ```

use `%q` for paths. 
___
*[x/handlers.go, line 418 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma443Fd1pYSZUcNEvIB:-Ma443Fd1pYSZUcNEvIC:bmb1b2i) ([raw file](https://github.com/dgraph-io/dgraph/blob/21f96cd7a069613597fdaa264c436335b8b62858/x/handlers.go#L418)):*
> ```Go
> 	writer := gcs.bucket.Object(dir).NewWriter(ctx)
> 	if err := writer.Close(); err != nil {
> 		return errors.Wrapf(err, "while creating directory: %s", err)
> ```

No need or err again in wrap message.
___
*[x/handlers.go, line 446 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma44H5q88tFzFCa94Mi:-Ma44H5q88tFzFCa94Mj:b-qpc6mw) ([raw file](https://github.com/dgraph-io/dgraph/blob/21f96cd7a069613597fdaa264c436335b8b62858/x/handlers.go#L446)):*
> ```Go
> 	// GCS doesn't has the concept of directories, it emulated the folder behaviour if the path is
> 	// suffixed with '/'.
> 	absPath += "/"
> ```

use `filepath.Separator` instead
___
*[x/handlers.go, line 455 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma44MZw4aKdhGdpWC9s:-Ma44MZw4aKdhGdpWC9t:b-ftprw) ([raw file](https://github.com/dgraph-io/dgraph/blob/21f96cd7a069613597fdaa264c436335b8b62858/x/handlers.go#L455)):*
> ```Go
> 		return true
> 	} else if err != nil {
> 		glog.Error(errors.Wrapf(err, "while checking if directory exists: %s", err))
> ```

No need to wrap when you are just logging the error. Use `glog.Errorf()` and format the error.
___
*[x/handlers.go, line 469 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma44bCcDcfKsD2j6GMy:-Ma44bCcDcfKsD2j6GMz:brhumzt) ([raw file](https://github.com/dgraph-io/dgraph/blob/21f96cd7a069613597fdaa264c436335b8b62858/x/handlers.go#L469)):*
> ```Go
> 		return false
> 	} else if err != nil {
> 		glog.Error(errors.Wrapf(err, "while checking if file exists: %s", err))
> ```

Same here.
___
*[x/handlers.go, line 488 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma44dfl32sDlwQbDMmo:-Ma44dfl32sDlwQbDMmp:b50dxhp) ([raw file](https://github.com/dgraph-io/dgraph/blob/21f96cd7a069613597fdaa264c436335b8b62858/x/handlers.go#L488)):*
> ```Go
> 	absPath := gcs.JoinPath(path)
> 	if len(absPath) != 0 {
> 		absPath += "/"
> ```

`filepath.Separator`
___
*[x/handlers.go, line 503 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma453On30Ov2C6TMrJn:-Ma453On30Ov2C6TMrJo:brhumzt) ([raw file](https://github.com/dgraph-io/dgraph/blob/21f96cd7a069613597fdaa264c436335b8b62858/x/handlers.go#L503)):*
> ```Go
> 		}
> 		if err != nil {
> 			glog.Error(errors.Wrapf(err, "while listing paths: %s", err))
> ```

Same here.
___
*[x/handlers.go, line 521 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma45YWgBIPHwVIUHrQo:-Ma45YWgBIPHwVIUHrQp:brhumzt) ([raw file](https://github.com/dgraph-io/dgraph/blob/21f96cd7a069613597fdaa264c436335b8b62858/x/handlers.go#L521)):*
> ```Go
> 	reader, err := gcs.bucket.Object(gcs.JoinPath(path)).NewReader(ctx)
> 	if err != nil {
> 		return nil, errors.Wrapf(err, "while reading file: %s", err)
> ```

Same here.
___
*[x/handlers.go, line 527 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma45_0a6NAjrPbgMAyo:-Ma45_0a6NAjrPbgMAyp:brhumzt) ([raw file](https://github.com/dgraph-io/dgraph/blob/21f96cd7a069613597fdaa264c436335b8b62858/x/handlers.go#L527)):*
> ```Go
> 	data, err := ioutil.ReadAll(reader)
> 	if err != nil {
> 		return nil, errors.Wrapf(err, "while reading file: %s", err)
> ```

Same here.
___
*[x/handlers.go, line 534 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma45yQm6Hw5J9gUSclp:-Ma45yQm6Hw5J9gUSclq:bx8unet) ([raw file](https://github.com/dgraph-io/dgraph/blob/21f96cd7a069613597fdaa264c436335b8b62858/x/handlers.go#L534)):*
> ```Go
> 
> // Rename renames the src file to the destination file.
> func (gcs *GCS) Rename(src, dst string) error {
> ```

Did we check that GCP doesn't provide atomic rename operation? If it does, then we won't need copy + delete.
___
*[x/handlers.go, line 541 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma46Hel3YMpjQIUhS9f:-Ma46Hem6XMlmEiIA8xO:brhumzt) ([raw file](https://github.com/dgraph-io/dgraph/blob/21f96cd7a069613597fdaa264c436335b8b62858/x/handlers.go#L541)):*
> ```Go
> 
> 	if _, err := dstObj.CopierFrom(srcObj).Run(ctx); err != nil {
> 		return errors.Wrapf(err, "while renaming file: %s", err)
> ```

Same here.
___
*[x/handlers.go, line 557 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma46J5D2b1rKkX0dYqO:-Ma46J5D2b1rKkX0dYqP:buo9nmt) ([raw file](https://github.com/dgraph-io/dgraph/blob/21f96cd7a069613597fdaa264c436335b8b62858/x/handlers.go#L557)):*
> ```Go
> 	reader, err := gcs.bucket.Object(gcs.JoinPath(path)).NewReader(ctx)
> 	if err != nil {
> 		return nil, errors.Wrapf(err, "while reading file: %s", err)
> ```

Same here


<!-- Sent from Reviewable.io -->

2021-05-19 15:03 UTC, rohanprasad commented
___
*[x/handlers.go, line 364 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma4117Q41g0RrXkQfS2:-Ma48LSJ-UKf4qM4uMX6:bla0afj) ([raw file](https://github.com/dgraph-io/dgraph/blob/21f96cd7a069613597fdaa264c436335b8b62858/x/handlers.go#L364)):*
<details><summary><i>Previously, ahsanbarkati (Ahsan Barkati) wrote…</i></summary><blockquote>

`creds` is not being used anywhere in the function. If it is unused, we should remove it.

Rather, we should pass the creds instead of reading from the `env` variables.
</blockquote></details>

For GCP, a credentials.json file is provided which is used for authentication. The file contains keys, project_ids, etc. Are we suggesting getting all the values from creds (via GQL vals) or just the file path?


<!-- Sent from Reviewable.io -->

2021-05-19 15:06 UTC, rohanprasad commented
___
*[x/handlers.go, line 399 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma42PfV03h2GIDZdAy9:-Ma48tVm06VFT7xNnQbG:b-466yd5) ([raw file](https://github.com/dgraph-io/dgraph/blob/21f96cd7a069613597fdaa264c436335b8b62858/x/handlers.go#L399)):*
<details><summary><i>Previously, ahsanbarkati (Ahsan Barkati) wrote…</i></summary><blockquote>

Is this the idiomatic way to check for the existence of the bucket?
</blockquote></details>

No, this is one of the ways. The other is to iterate over all buckets and check if the name matches.


<!-- Sent from Reviewable.io -->

2021-05-19 15:12 UTC, rohanprasad commented
___
*[x/handlers.go, line 413 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma437dQ3JUsiaWGe9Rw:-Ma4AI1F-OQ4DYpKAvM2:bv8c3gn) ([raw file](https://github.com/dgraph-io/dgraph/blob/21f96cd7a069613597fdaa264c436335b8b62858/x/handlers.go#L413)):*
<details><summary><i>Previously, ahsanbarkati (Ahsan Barkati) wrote…</i></summary><blockquote>

Use `filepath.Separator` instead of  '/'.
</blockquote></details>

works fine as long as we are on a system with '/' as file separator. For GCS, we need to use '/', as we only officially only support linux we can use filepath.Separator. But anyone building and running this on windows will face issues.


<!-- Sent from Reviewable.io -->

2021-05-19 15:15 UTC, rohanprasad commented
___
*[x/handlers.go, line 534 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma45yQm6Hw5J9gUSclp:-Ma4BPYlAXqbAn-1wwcJ:b-5ewydf) ([raw file](https://github.com/dgraph-io/dgraph/blob/21f96cd7a069613597fdaa264c436335b8b62858/x/handlers.go#L534)):*
<details><summary><i>Previously, ahsanbarkati (Ahsan Barkati) wrote…</i></summary><blockquote>

Did we check that GCP doesn't provide atomic rename operation? If it does, then we won't need copy + delete.
</blockquote></details>

Yup, this is straight from the docs.


<!-- Sent from Reviewable.io -->

2021-05-19 15:33 UTC, rohanprasad commented
___
*[x/handlers.go, line 364 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma4117Q41g0RrXkQfS2:-Ma4FafU-xP-i5d6Zlid:b-hpm88) ([raw file](https://github.com/dgraph-io/dgraph/blob/21f96cd7a069613597fdaa264c436335b8b62858/x/handlers.go#L364)):*
<details><summary><i>Previously, rohanprasad (Rohan Prasad) wrote…</i></summary><blockquote>

For GCP, a credentials.json file is provided which is used for authentication. The file contains keys, project_ids, etc. Are we suggesting getting all the values from creds (via GQL vals) or just the file path?
</blockquote></details>

Maybe take both env and from query (if specified, will override the value)?


<!-- Sent from Reviewable.io -->

2021-05-19 15:33 UTC, rohanprasad reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7829)* status: 0 of 3 files reviewed, 16 unresolved discussions (waiting on @ahsanbarkati, @manishrjain, and @vvbalaji-dgraph)

___
*[x/handlers.go, line 401 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma42ZtWASdHu-RTar54:-Ma49wvV2-p_66TRjqAp:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/21f96cd7a069613597fdaa264c436335b8b62858/x/handlers.go#L401)):*
<details><summary><i>Previously, ahsanbarkati (Ahsan Barkati) wrote…</i></summary><blockquote>

No need to have err twice, 
`errors.Wrap(err, "while accessing bucket")`
</blockquote></details>

Done.
___
*[x/handlers.go, line 414 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma43nju8vwR2GYo4R0R:-Ma4As8c6Kah_btgEZuv:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/21f96cd7a069613597fdaa264c436335b8b62858/x/handlers.go#L414)):*
<details><summary><i>Previously, ahsanbarkati (Ahsan Barkati) wrote…</i></summary><blockquote>

use `%q` for paths. 
</blockquote></details>

Done.
___
*[x/handlers.go, line 418 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma443Fd1pYSZUcNEvIB:-Ma4AztQ7uuVVhUQuqvI:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/21f96cd7a069613597fdaa264c436335b8b62858/x/handlers.go#L418)):*
<details><summary><i>Previously, ahsanbarkati (Ahsan Barkati) wrote…</i></summary><blockquote>

No need or err again in wrap message.
</blockquote></details>

Done.
___
*[x/handlers.go, line 446 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma44H5q88tFzFCa94Mi:-Ma4B17V9nHC9xzVr61f:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/21f96cd7a069613597fdaa264c436335b8b62858/x/handlers.go#L446)):*
<details><summary><i>Previously, ahsanbarkati (Ahsan Barkati) wrote…</i></summary><blockquote>

use `filepath.Separator` instead
</blockquote></details>

Done.
___
*[x/handlers.go, line 455 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma44MZw4aKdhGdpWC9s:-Ma49txhChY_StCtL23w:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/21f96cd7a069613597fdaa264c436335b8b62858/x/handlers.go#L455)):*
<details><summary><i>Previously, ahsanbarkati (Ahsan Barkati) wrote…</i></summary><blockquote>

No need to wrap when you are just logging the error. Use `glog.Errorf()` and format the error.
</blockquote></details>

Done.
___
*[x/handlers.go, line 469 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma44bCcDcfKsD2j6GMy:-Ma4BDGl1N_xnmHOOE7U:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/21f96cd7a069613597fdaa264c436335b8b62858/x/handlers.go#L469)):*
<details><summary><i>Previously, ahsanbarkati (Ahsan Barkati) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[x/handlers.go, line 488 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma44dfl32sDlwQbDMmo:-Ma4BECt7ag3JReu_Fbp:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/21f96cd7a069613597fdaa264c436335b8b62858/x/handlers.go#L488)):*
<details><summary><i>Previously, ahsanbarkati (Ahsan Barkati) wrote…</i></summary><blockquote>

`filepath.Separator`
</blockquote></details>

Done.
___
*[x/handlers.go, line 503 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma453On30Ov2C6TMrJn:-Ma4BJWy-TqRBOXqtFTF:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/21f96cd7a069613597fdaa264c436335b8b62858/x/handlers.go#L503)):*
<details><summary><i>Previously, ahsanbarkati (Ahsan Barkati) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[x/handlers.go, line 521 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma45YWgBIPHwVIUHrQo:-Ma4BKzF8EbKGyPdE2UW:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/21f96cd7a069613597fdaa264c436335b8b62858/x/handlers.go#L521)):*
<details><summary><i>Previously, ahsanbarkati (Ahsan Barkati) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[x/handlers.go, line 527 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma45_0a6NAjrPbgMAyo:-Ma4BOkdB8UGYdJNP07_:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/21f96cd7a069613597fdaa264c436335b8b62858/x/handlers.go#L527)):*
<details><summary><i>Previously, ahsanbarkati (Ahsan Barkati) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[x/handlers.go, line 541 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma46Hel3YMpjQIUhS9f:-Ma4BXHJ5V70Keu7-90O:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/21f96cd7a069613597fdaa264c436335b8b62858/x/handlers.go#L541)):*
<details><summary><i>Previously, ahsanbarkati (Ahsan Barkati) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[x/handlers.go, line 557 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma46J5D2b1rKkX0dYqO:-Ma4BWWe02cEUpCYYeWz:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/21f96cd7a069613597fdaa264c436335b8b62858/x/handlers.go#L557)):*
<details><summary><i>Previously, ahsanbarkati (Ahsan Barkati) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-20 06:48 UTC, NamanJain8 requested changes
Have some comments. Is it possible to add an integration test for this as we have for minio?

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-:-Ma7WqjS3y__rDzwkxLD:bl11dhl)* status: 0 of 3 files reviewed, 19 unresolved discussions (waiting on @ahsanbarkati, @manishrjain, @rohanprasad, and @vvbalaji-dgraph)

___
*[go.sum, line 9 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma7RVXd7SRZ_EC-0wFA:-Ma7RVXd7SRZ_EC-0wFB:b-nd1w9o) ([raw file](https://github.com/dgraph-io/dgraph/blob/36cb1c577a0bac852cc69e1ce96f650afc86e06b/go.sum#L9)):*
> ```
> cloud.google.com/go v0.46.3/go.mod h1:a6bKKbmY7er1mI7TEI4lsAkts/mkhTSZK8w33B4RAg0=
> cloud.google.com/go v0.50.0/go.mod h1:r9sluTvynVuxRIOHXQEHMFffphuXHOMZMycpNR5e6To=
> cloud.google.com/go v0.52.0/go.mod h1:pXajvRH/6o3+F9jDHZWQ5PbGhn+o8w9qiu/CffaVdO4=
> ```

go mod tidy?
___
*[x/handlers.go, line 364 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma4117Q41g0RrXkQfS2:-Ma7SSVb0sWJneZh_AMZ:btuepnw) ([raw file](https://github.com/dgraph-io/dgraph/blob/21f96cd7a069613597fdaa264c436335b8b62858/x/handlers.go#L364)):*
<details><summary><i>Previously, rohanprasad (Rohan Prasad) wrote…</i></summary><blockquote>

Maybe take both env and from query (if specified, will override the value)?
</blockquote></details>

We should support taking the values from ENV/file and override it with the passed credentials. Check `MinioCredentialsProvider()`. Also, support not using environment variables if `shared-cluster` is set to true. 
___
*[x/handlers.go, line 413 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma437dQ3JUsiaWGe9Rw:-Ma7Vnut5WrRoQT2_gQx:bkfzup6) ([raw file](https://github.com/dgraph-io/dgraph/blob/21f96cd7a069613597fdaa264c436335b8b62858/x/handlers.go#L413)):*
<details><summary><i>Previously, rohanprasad (Rohan Prasad) wrote…</i></summary><blockquote>

works fine as long as we are on a system with '/' as file separator. For GCS, we need to use '/', as we only officially only support linux we can use filepath.Separator. But anyone building and running this on windows will face issues.
</blockquote></details>

`/` is the requirement of GCP? Do we have this separator defined in gcp library? if yes, then lets use that, else I would suggest using `/` and adding comment there.
___
*[x/handlers.go, line 90 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma7R_NRDDPH4YIoIAE6:-Ma7R_NRDDPH4YIoIAE7:bnsz24n) ([raw file](https://github.com/dgraph-io/dgraph/blob/36cb1c577a0bac852cc69e1ce96f650afc86e06b/x/handlers.go#L90)):*
> ```Go
> //   s3://dgraph.s3.amazonaws.com/dgraph/backups?secure=true
> //   minio://localhost:9000/dgraph?secure=true
> //   file:///tmp/dgraph/backups
> ```

Add an example uri
___
*[x/handlers.go, line 478 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma7WWuJDM3na5DtBwQi:-Ma7WWuJDM3na5DtBwQj:bb3snqs) ([raw file](https://github.com/dgraph-io/dgraph/blob/36cb1c577a0bac852cc69e1ce96f650afc86e06b/x/handlers.go#L478)):*
> ```Go
> // JoinPath appends the given path to the root path of the handler.
> func (gcs *GCS) JoinPath(path string) string {
> 	return filepath.Join(gcs.pathName, path)
> ```

filepath.Join will use the separator of the system that we are running dgraph on? 


<!-- Sent from Reviewable.io -->

2021-05-21 06:43 UTC, rohanprasad commented
___
*[go.sum, line 9 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma7RVXd7SRZ_EC-0wFA:-MaCePbg3YmOJICpktVM:b9lyf6d) ([raw file](https://github.com/dgraph-io/dgraph/blob/36cb1c577a0bac852cc69e1ce96f650afc86e06b/go.sum#L9)):*
<details><summary><i>Previously, NamanJain8 (Naman Jain) wrote…</i></summary><blockquote>

go mod tidy?
</blockquote></details>

This is after go mod tidy. 


<!-- Sent from Reviewable.io -->

2021-05-21 06:45 UTC, rohanprasad commented
___
*[x/handlers.go, line 364 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma4117Q41g0RrXkQfS2:-MaCeWBZ90GRtPsAUlsg:bpq9xlq) ([raw file](https://github.com/dgraph-io/dgraph/blob/21f96cd7a069613597fdaa264c436335b8b62858/x/handlers.go#L364)):*
<details><summary><i>Previously, NamanJain8 (Naman Jain) wrote…</i></summary><blockquote>

We should support taking the values from ENV/file and override it with the passed credentials. Check `MinioCredentialsProvider()`. Also, support not using environment variables if `shared-cluster` is set to true. 
</blockquote></details>

+1 for overriding values. Why would we want to disable it in shared-cluster mode? We are overriding it anyway.


<!-- Sent from Reviewable.io -->

2021-05-21 06:45 UTC, rohanprasad commented
___
*[x/handlers.go, line 413 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma437dQ3JUsiaWGe9Rw:-MaCeycm-4nH1M9PWk3q:b-gbwg3v) ([raw file](https://github.com/dgraph-io/dgraph/blob/21f96cd7a069613597fdaa264c436335b8b62858/x/handlers.go#L413)):*
<details><summary><i>Previously, NamanJain8 (Naman Jain) wrote…</i></summary><blockquote>

`/` is the requirement of GCP? Do we have this separator defined in gcp library? if yes, then lets use that, else I would suggest using `/` and adding comment there.
</blockquote></details>

Didn't find any, using a constant instead.


<!-- Sent from Reviewable.io -->

2021-05-21 06:47 UTC, rohanprasad commented
___
*[x/handlers.go, line 478 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma7WWuJDM3na5DtBwQi:-MaCf5CfCnp1Miem5-om:b-jpu720) ([raw file](https://github.com/dgraph-io/dgraph/blob/36cb1c577a0bac852cc69e1ce96f650afc86e06b/x/handlers.go#L478)):*
<details><summary><i>Previously, NamanJain8 (Naman Jain) wrote…</i></summary><blockquote>

filepath.Join will use the separator of the system that we are running dgraph on? 
</blockquote></details>

Yes, (depends on the system we build dgraph) it will use "\" for Windows system.


<!-- Sent from Reviewable.io -->

2021-05-21 06:47 UTC, rohanprasad reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7829)* status: 0 of 3 files reviewed, 19 unresolved discussions (waiting on @ahsanbarkati, @manishrjain, @NamanJain8, and @vvbalaji-dgraph)

___
*[x/handlers.go, line 90 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-Ma7R_NRDDPH4YIoIAE6:-MaCeTbJ9dDe_H5-mt-V:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/36cb1c577a0bac852cc69e1ce96f650afc86e06b/x/handlers.go#L90)):*
<details><summary><i>Previously, NamanJain8 (Naman Jain) wrote…</i></summary><blockquote>

Add an example uri
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-24 06:57 UTC, rohanprasad commented
There's no provision to add an integration test as of now. Mocking the GCP connection won't give us much benefit because all we are doing is calling those APIs here. Leaving this as a TODO for now.





<!-- Sent from Reviewable.io -->

2021-05-25 16:15 UTC, ahsanbarkati approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Please test these APIs manually. Few comments, otherwise looks good to me. 

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-:-MaZIYPFEGvC78JPRoPX:b-mgoxac)* status: 0 of 3 files reviewed, 23 unresolved discussions (waiting on @ahsanbarkati, @manishrjain, @NamanJain8, @rohanprasad, and @vvbalaji-dgraph)

___
*[x/handlers.go, line 364 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-MaZGrhsE_GMto56ET8N:-MaZGrhsE_GMto56ET8O:b-wg2ph2) ([raw file](https://github.com/dgraph-io/dgraph/blob/f686d9f1d9e7df153f66bfef3f3cd68f9f2f2d53/x/handlers.go#L364)):*
> ```Go
> 	client   *storage.Client
> 	bucket   *storage.BucketHandle
> 	pathName string
> ```

Isn't `pathName` more like a `pathPrefix`. Should we call it `pathPrefix`?
___
*[x/handlers.go, line 371 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-MaZF3zC5gzDVZLkb1zL:-MaZF3zD76ERAkfisG7Z:b-404z7k) ([raw file](https://github.com/dgraph-io/dgraph/blob/f686d9f1d9e7df153f66bfef3f3cd68f9f2f2d53/x/handlers.go#L371)):*
> ```Go
> 
> 	var c *storage.Client
> 	if creds.SecretKey != "" || os.Getenv("GOOGLE_APPLICATION_CREDENTIALS") != "" {
> ```

I see only the secretKey is being used. Any reason to pass `*MinioCredentials` struct? We can just pass the key. 
___
*[x/handlers.go, line 417 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-MaZGK98D4SJJz86CM56:-MaZGK98D4SJJz86CM57:b-h1kbh8) ([raw file](https://github.com/dgraph-io/dgraph/blob/f686d9f1d9e7df153f66bfef3f3cd68f9f2f2d53/x/handlers.go#L417)):*
> ```Go
> 	ctx := context.Background()
> 
> 	// GCS used a flat storage and provides an illusion of directories. To create a directory, file
> ```

Minor typo: GCS used -> GCS uses
___
*[x/handlers.go, line 458 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-MaZHUFZ9Y1DhbKbHr4w:-MaZHUFZ9Y1DhbKbHr4x:b-ewleab) ([raw file](https://github.com/dgraph-io/dgraph/blob/f686d9f1d9e7df153f66bfef3f3cd68f9f2f2d53/x/handlers.go#L458)):*
> ```Go
> 	})
> 
> 	if _, err := it.Next(); err != iterator.Done {
> ```

`err == iterator.Done`? If there is some other error then also it will return true. 


<!-- Sent from Reviewable.io -->

2021-05-25 17:46 UTC, rohanprasad commented
___
*[x/handlers.go, line 458 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-MaZHUFZ9Y1DhbKbHr4w:-MaZcJZW26yA1yonYSDH:b5twh6j) ([raw file](https://github.com/dgraph-io/dgraph/blob/f686d9f1d9e7df153f66bfef3f3cd68f9f2f2d53/x/handlers.go#L458)):*
<details><summary><i>Previously, ahsanbarkati (Ahsan Barkati) wrote…</i></summary><blockquote>

`err == iterator.Done`? If there is some other error then also it will return true. 
</blockquote></details>

if err != iterator.Done, then we can surely say that there are items in the buffer and hence directory exists.


<!-- Sent from Reviewable.io -->

2021-05-25 17:46 UTC, rohanprasad reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7829)* status: 0 of 3 files reviewed, 22 unresolved discussions (waiting on @ahsanbarkati, @manishrjain, @NamanJain8, and @vvbalaji-dgraph)

___
*[x/handlers.go, line 364 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-MaZGrhsE_GMto56ET8N:-MaZcB7cCMcN6u1hqX_H:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f686d9f1d9e7df153f66bfef3f3cd68f9f2f2d53/x/handlers.go#L364)):*
<details><summary><i>Previously, ahsanbarkati (Ahsan Barkati) wrote…</i></summary><blockquote>

Isn't `pathName` more like a `pathPrefix`. Should we call it `pathPrefix`?
</blockquote></details>

Done.
___
*[x/handlers.go, line 371 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7829#-MaZF3zC5gzDVZLkb1zL:-MaZcEku8H5gWlbcHCyl:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f686d9f1d9e7df153f66bfef3f3cd68f9f2f2d53/x/handlers.go#L371)):*
<details><summary><i>Previously, ahsanbarkati (Ahsan Barkati) wrote…</i></summary><blockquote>

I see only the secretKey is being used. Any reason to pass `*MinioCredentials` struct? We can just pass the key. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-25 22:09 UTC, iluminae reviewed
Sorry to intrude on your PR - but I believe the handling of `GOOGLE_APPLICATION_CREDENTIALS` is already done by [by the google bindings](https://cloud.google.com/docs/authentication/production#automatically) automatically with different semantics than you have written here.

There is a case as written where credentials are used if the environment variable is set, and the other case _explicitly disables_ authenticated access. However, this does not allow the case where the default service account of the GCE/GKE node you are running on can be automatically loaded and used:

> If the environment variable GOOGLE_APPLICATION_CREDENTIALS isn't set, ADC uses the service account that is attached to the resource that is running your code.


This would be useful for automatically deploying dgraph alphas capable of secure GCS upload, instead of pushing out explicit service account json files, mounting them via helm chart and setting the variable accordingly.

2021-05-26 19:57 UTC, merged

2022-01-01 23:43 UTC, JLaferri commented
I'm trying to follow how to properly use this as per the comments in this PR but am somewhat struggling.

1. Do I need to use an env variable or can I pass in the path to my creds file?
2. Where does the creds file have to be? In each of my alpha instances I imagine?
3. Which graphql args do I use other than settings my destination to `gs://<bucket_name>`

Any help is greatly appreciated and thank you for adding this functionality!

2022-01-02 15:43 UTC, iluminae commented
You cannot pass your creds in via the GraphQL mutation - you can only pass in the path on the alpha where the service account file is located.

This is a bit unfortunate in my view as the helm chart does not allow attaching arbitrary secrets from k8s into the pods, which means the only way to use the chart is to use the machine service account or workload identity.

The destination is the only argument you need but forceFull will work as normal to control type.

2022-01-06 03:27 UTC, JLaferri commented
> You cannot pass your creds in via the GraphQL mutation - you can only pass in the path on the alpha where the service account file is located.
> 
> This is a bit unfortunate in my view as the helm chart does not allow attaching arbitrary secrets from k8s into the pods, which means the only way to use the chart is to use the machine service account or workload identity.
> 
> The destination is the only argument you need but forceFull will work as normal to control type.

Thanks for the response.

What I ended up doing is ssh'ing into my `dgraph-alpha` pods and writing the perms file in there. I then just passed the path to that file as the "secretKey" arg for the backup mutation.

https://github.com/dgraph-io/dgraph/pull/7829/files#diff-1bdc3fb6f68f83cb902639f7f23ac781753b96d3c19ea8f078d0cb3934424759R625

After fixing some permissions issues, I got it working. Thanks again to all the contributors 👍