add CIFuzz github action
dgraph-io/dgraph pull request #8443
Opened 2022-11-20 17:25 UTC by DavidKorczynski

Signed-off-by: David Korczynski <david@adalogics.com>

## Problem
 
 Fuzzers are integrated into OSS-Fuzz but does not run as part of the CI to prevent issues and regressions being merged.

## Solution
 
 Add [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) workflow action to have fuzzers build and run on each PR. This is a service offered by OSS-Fuzz where Dgraph already runs. In the current PR the fuzzers gets build on a pull request and will run for 300 seconds.

2022-11-20 17:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dgraph-io/dgraph?pullRequest=8443) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dgraph-io/dgraph?pullRequest=8443) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dgraph-io/dgraph?pullRequest=8443) it.</sub>

2022-11-22 22:05 UTC, MichelDiz commented
Please clean the hidden lines in the PR comment block e.g
```
<!--
 Change Github PR Title 
(...)
(...)
```

2022-11-22 22:06 UTC, DavidKorczynski commented
> Please clean the hidden lines in the PR comment block e.g

done

2023-03-18 16:05 UTC, mangalaman93 commented
@joshua-goldstein @skrdgraph could you take a look at this. Thanks

2023-04-20 11:31 UTC, mangalaman93 commented
@DavidKorczynski is it possible for you to rebase the PR on latest main?

2023-04-20 11:35 UTC, mangalaman93 requested changes
Thanks for the PR, a few comments.

2023-04-20 11:35 UTC, mangalaman93 commented on .github/workflows/ci-cifuzz.yml
> +on: [pull_request]
Please add the following similar to our other CI jobs, e.g. https://github.com/dgraph-io/dgraph/blob/main/.github/workflows/ci-dgraph-load-tests.yml

```
on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main
      - 'release/**'
  schedule:
    - cron: "0 0,6,12,18 * * *"
```

2023-04-20 11:35 UTC, mangalaman93 commented on .github/workflows/ci-cifuzz.yml
> +  Fuzzing:
could we call it `dgraph-fuzzing` instead?

2023-04-20 11:35 UTC, mangalaman93 commented on .github/workflows/ci-cifuzz.yml
> +    runs-on: ubuntu-latest
we should have this clause too similar to other CI jobs:

```
if: github.event.pull_request.draft == false
```

2023-06-14 02:42 UTC, mangalaman93 commented
closing this in lieu of https://github.com/dgraph-io/dgraph/pull/8874

2023-06-14 02:42 UTC, closed without merging