fix(proposals): Incremental proposal key for zero proposals (#8005)
dgraph-io/dgraph pull request #8567
Opened 2023-01-04 13:01 UTC by anurags92

Change the proposal's unique key to an atomic counter instead of using a randomly generated key.

(cherry picked from commit a515d0dede9014955f571f96525b49fc8c9913f4) (cherry picked from commit 2aa3d3e5c8f38bfb8c83c4123cdcc86aed58136e)

2023-01-05 04:49 UTC, mangalaman93 commented
What's the benefit of this change? Could it cause problems when old Zero's key and new Zero's keys after upgrade collide?

2023-01-24 18:28 UTC, matthewmcneely approved these changes

2023-02-05 14:32 UTC, mangalaman93 approved these changes

2023-02-06 09:32 UTC, mangalaman93 submitted a review, later dismissed

2023-02-06 18:30 UTC, matthewmcneely approved these changes

2023-02-07 14:19 UTC, mangalaman93 approved these changes

2023-02-07 15:11 UTC, mangalaman93 requested changes

2023-02-07 15:11 UTC, mangalaman93 commented on worker/proposal.go
> -	"github.com/pkg/errors"
I think the order is opposite. first external and then dgraph imports.

2023-02-07 15:11 UTC, mangalaman93 commented on dgraph/cmd/zero/zero_test.go
> -	"github.com/stretchr/testify/require"
same

2023-02-07 19:33 UTC, mangalaman93 approved these changes

2023-02-07 20:24 UTC, matthewmcneely submitted a review, later dismissed

2023-02-08 09:26 UTC, mangalaman93 approved these changes

2023-02-08 12:15 UTC, anurags92 commented on dgraph/cmd/zero/raft.go
> +	proposalKey, err = x.ProposalKey(n.Id)
We do need for initialization otherwise we are obscuring that?

2023-02-08 12:25 UTC, harshil-goel approved these changes

2023-02-08 12:29 UTC, merged