Harshil/manifest bug fix
dgraph-io/dgraph pull request #8601
Opened 2023-01-10 19:45 UTC by harshil-goel

## Problem
 

## Solution

2023-01-10 19:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dgraph-io/dgraph?pullRequest=8601) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/dgraph-io/dgraph?pullRequest=8601) before we can accept your contribution.<br/>**0** out of **3** committers have signed the CLA.<br/><br/>:x: NamanJain8<br/>:x: ajeetdsouza<br/>:x: ahsanbarkati<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dgraph-io/dgraph?pullRequest=8601) it.</sub>

2023-01-19 10:38 UTC, mangalaman93 requested changes

2023-01-23 19:36 UTC, matthewmcneely requested changes

2023-01-23 19:36 UTC, matthewmcneely commented on worker/backup_ee.go
>  		return errors.Wrap(err, "Complete backup failed")
Realize this is not your doing, but error text should not be capitalized

2023-01-23 19:36 UTC, matthewmcneely commented on worker/restore_map.go
> +					return nil, errors.Wrap(err, "Map phase failed to parse namespace")
Error text should not be capitalized

2023-02-01 10:44 UTC, mangalaman93 commented on ee/updatemanifest/run.go
> + * Copyright 2021 Dgraph Labs, Inc. and Contributors
fix the license

2023-02-02 04:54 UTC, mangalaman93 requested changes

2023-02-02 04:54 UTC, mangalaman93 commented on x/keys.go
> +func AttrFrom2103(attr string) (string, error) {
is this function defined again here?

2023-02-02 04:54 UTC, mangalaman93 commented on x/keys.go
> +func AttrFrom2103(attr string) (string, error) {
And can we explain what is going on here? maybe an example in the comments.

2023-02-03 10:03 UTC, mangalaman93 submitted a review, later dismissed

2023-02-03 10:13 UTC, mangalaman93 approved these changes

2023-02-03 18:52 UTC, matthewmcneely approved these changes

2023-02-03 18:58 UTC, merged