Change intersect heuristic from 500 to 100
dgraph-io/dgraph pull request #8615
Opened 2023-01-18 16:26 UTC by harshil-goel

Currently for intersecting two different arrays, we either use linear or binary jump. This is decided on the basis of the ratio of the two arrays being intersected. Currently, the ratio is set to be 500. We have had certain customer issues where queries too long. After debugging, the issue seems to be the ratio. Changing the ratio back to 100 fixes the customer issues. Query time went from 9 sec to 0.3sec.

2023-01-18 16:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dgraph-io/dgraph?pullRequest=8615) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dgraph-io/dgraph?pullRequest=8615) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dgraph-io/dgraph?pullRequest=8615) it.</sub>

2023-01-18 16:43 UTC, anurags92 approved these changes

2023-01-18 18:11 UTC, mangalaman93 requested changes
Can we write a benchmark for it showing that it does what you are saying and later on we can track if it goes the other way round due to a change?

2023-09-29 09:29 UTC, closed without merging

2023-09-29 09:29 UTC, harshil-goel commented
We have better algorithm now