fix(ci): Uncomment draft PR logic
dgraph-io/dgraph pull request #8644
Opened 2023-02-01 18:54 UTC by adityasadalage

Uncommenting this logic post-release to run the workflow on non-draft PRs only

2023-02-01 19:13 UTC, matthewmcneely submitted a review, later dismissed

2023-02-03 05:06 UTC, skrdgraph approved these changes

2023-02-09 07:56 UTC, mangalaman93 submitted a review, later dismissed

2023-02-09 18:57 UTC, skrdgraph requested changes
@adityasadalage could you make this consistent across all `ci-*.yamls` please?

specifically these:  
- https://github.com/dgraph-io/dgraph/blob/main/.github/workflows/ci-dgraph-ldbc-tests.yml#L18
- https://github.com/dgraph-io/dgraph/blob/main/.github/workflows/ci-aqua-security-trivy-tests.yml#L19-L20

2023-02-09 20:36 UTC, skrdgraph approved these changes

2023-02-09 20:37 UTC, joshua-goldstein approved these changes
👍

2023-02-09 20:38 UTC, merged