chore(linter): enable errcheck and ineffassign linters
dgraph-io/dgraph pull request #8647
Opened 2023-02-03 04:18 UTC by mangalaman93

2023-02-03 05:02 UTC, skrdgraph approved these changes

2023-02-03 05:14 UTC, skrdgraph commented
On the CI run .. this seems to have no issues.

I am checking locally to make sure this doesn't break after merge (like last time).

<img width="936" alt="Screen Shot 2023-02-03 at 05 13 12" src="https://user-images.githubusercontent.com/108091997/216518064-72e23061-1f4e-484c-baaf-d16fbb1fcde1.png">

2023-02-03 05:17 UTC, skrdgraph commented
We should not merge this, there is something wrong with this when run locally: 

```
Sudhishs-MacBook-Pro-Work:dgraph sudhishkr$ golangci-lint run


xidmap/trie.go:76:15: Error return value of `t.buf.Release` is not checked (errcheck)
        t.buf.Release()
                     ^
dgraph/cmd/live/run.go:191:19: Error return value of `txn.Discard` is not checked (errcheck)
        defer txn.Discard(ctx)
                         ^
dgraph/cmd/live/run.go:667:19: Error return value of `txn.Discard` is not checked (errcheck)
        defer txn.Discard(ctx)
                         ^
worker/backup_ee.go:327:17: Error return value of `th.buf.Release` is not checked (errcheck)
                th.buf.Release()
                              ^
worker/predicate_move.go:169:19: Error return value of `buf.SliceIterate` is not checked (errcheck)
                buf.SliceIterate(func(_ []byte) error {
                                ^
worker/predicate_move.go:289:20: Error return value of `buf.Release` is not checked (errcheck)
                defer buf.Release()
                                 ^
worker/restore_map.go:166:19: Error return value of `buf.Release` is not checked (errcheck)
        defer buf.Release()
                         ^
worker/restore_map.go:180:18: Error return value of `buf.SliceIterate` is not checked (errcheck)
        buf.SliceIterate(func(slice []byte) error {
                        ^
worker/restore_map.go:281:19: Error return value of `buf.Release` is not checked (errcheck)
        defer buf.Release()
                         ^
worker/restore_map.go:437:25: Error return value of `req.lbuf.Release` is not checked (errcheck)
                defer req.lbuf.Release()
                                      ^
worker/restore_reduce.go:255:17: Error return value of `cbuf.Release` is not checked (errcheck)
                                cbuf.Release()
                                            ^
worker/restore_reduce.go:270:15: Error return value of `cbuf.Release` is not checked (errcheck)
                cbuf.Release()
                            ^
worker/restore_reduce.go:284:16: Error return value of `kvBuf.Release` is not checked (errcheck)
                kvBuf.Release()
                             ^
worker/restore_reduce.go:311:15: Error return value of `cbuf.Release` is not checked (errcheck)
                cbuf.Release()
                            ^
dgraph/cmd/bulk/count_index.go:142:22: Error return value of `outBuf.Release` is not checked (errcheck)
        defer outBuf.Release()
                            ^
dgraph/cmd/bulk/count_index.go:166:18: Error return value of `buf.SliceIterate` is not checked (errcheck)
        buf.SliceIterate(func(slice []byte) error {
                        ^
dgraph/cmd/bulk/count_index.go:184:21: Error return value of `c.countBuf.Release` is not checked (errcheck)
                c.countBuf.Release()
                                  ^
dgraph/cmd/bulk/mapper.go:186:19: Error return value of `cbuf.SliceIterate` is not checked (errcheck)
        cbuf.SliceIterate(func(slice []byte) error {
                         ^
dgraph/cmd/bulk/mapper.go:284:19: Error return value of `sh.cbuf.Release` is not checked (errcheck)
                        sh.cbuf.Release()
                                       ^
dgraph/cmd/bulk/reduce.go:323:29: Error return value of `req.countBuf.Release` is not checked (errcheck)
                defer req.countBuf.Release()
                                          ^
dgraph/cmd/bulk/reduce.go:332:28: Error return value of `req.countBuf.SliceIterate` is not checked (errcheck)
                req.countBuf.SliceIterate(func(slice []byte) error {
                                         ^
dgraph/cmd/bulk/reduce.go:362:21: Error return value of `ci.writer.Write` is not checked (errcheck)
                                        ci.writer.Write(buf)
                                                       ^
dgraph/cmd/bulk/reduce.go:369:17: Error return value of `kvBuf.Release` is not checked (errcheck)
                        kvBuf.Release()
                                     ^
dgraph/cmd/bulk/reduce.go:423:19: Error return value of `cbuf.SliceIterate` is not checked (errcheck)
        cbuf.SliceIterate(func(slice []byte) error {
                         ^
dgraph/cmd/bulk/reduce.go:713:16: Error return value of `kvBuf.Release` is not checked (errcheck)
                kvBuf.Release()
                             ^
edgraph/server.go:1376:17: Error return value of `grpc.SendHeader` is not checked (errcheck)
        grpc.SendHeader(ctx, md)
                       ^
query/outputnode.go:961:6: ineffectual assignment to slice (ineffassign)
                                        slice = cur
                                        ^
query/outputnode.go:972:4: ineffectual assignment to slice (ineffassign)
                        slice = nil
                        ^
dgraph/cmd/bulk/reduce.go:604:3: ineffectual assignment to slice (ineffassign)
                slice, next := []byte{}, start
                ^
dgraph/cmd/live/run.go:614:6: ineffectual assignment to tlsConfig (ineffassign)
        var tlsConfig *tls.Config = nil
            ^
```

2023-02-10 00:58 UTC, skrdgraph commented
convert to draft

2023-02-10 00:59 UTC, skrdgraph commented
converting this to draft* (its still a WIP)

2023-02-13 16:36 UTC, mangalaman93 commented on graphql/admin/http.go
> +	if gh == nil {
same here

2023-02-13 16:55 UTC, skrdgraph commented
Just validated a local run - this looks good. Looks like the `golangci` ran fine. This should hold.

2023-02-13 17:17 UTC, skrdgraph approved these changes
👍

2023-02-13 17:42 UTC, harshil-goel approved these changes

2023-02-13 17:43 UTC, merged

2023-02-13 17:52 UTC, matthewmcneely requested changes
Nit: There are dozens of places in this PR where the first word of log output is not capitalized. The Go conventions we follow require the opposite. I realize this isn't super-consistent across the code-base, but... (note: I gave up commenting on each occurrence after 9 or so)

2023-02-13 17:52 UTC, matthewmcneely commented on contrib/integration/acctupsert/main.go
> +			glog.Warningf("error in discarding txn: %v", err)
Nit: Log entries should be capitalized

2023-02-13 17:52 UTC, matthewmcneely commented on dgraph/cmd/bulk/count_index.go
> +			glog.Warningf("error in releasing buffer: %v", err)
Nit: First word of log output should be capitalized

2023-02-13 17:52 UTC, matthewmcneely commented on dgraph/cmd/bulk/count_index.go
> +			glog.Warningf("error in releasing buffer: %v", err)
Nit: First word of log output should be capitalized

2023-02-13 17:52 UTC, matthewmcneely commented on dgraph/cmd/bulk/count_index.go
> +		glog.Errorf("error while counting in buf: %v\n", err)
Nit: First word of log output should be capitalized

2023-02-13 17:52 UTC, matthewmcneely commented on dgraph/cmd/bulk/count_index.go
> +			glog.Warningf("error in releasing buffer: %v", err)
Nit: First word of log output should be capitalized

2023-02-13 17:52 UTC, matthewmcneely commented on dgraph/cmd/bulk/mapper.go
> +			glog.Warningf("error in releasing buffer: %v", err)
Nit: First word of log output should be capitalized

2023-02-13 17:52 UTC, matthewmcneely commented on dgraph/cmd/bulk/mapper.go
> +				glog.Warningf("error in releasing buffer: %v", err)
Nit: First word of log output should be capitalized

2023-02-13 17:52 UTC, matthewmcneely commented on dgraph/cmd/bulk/reduce.go
> +				glog.Warningf("error in releasing buffer: %v", err)
Nit: First word of log output should be capitalized

2023-02-13 17:52 UTC, matthewmcneely commented on dgraph/cmd/bulk/reduce.go
> +			glog.Errorf("error while iterating over buf: %v", err)
Nit: First word of log output should be capitalized

2023-02-13 17:52 UTC, matthewmcneely commented on graphql/admin/namespace.go
> +		return resolve.EmptyResult(m, errors.New("Cannot delete default namespace")), false
Error messages should not be capitalized

2023-02-13 18:36 UTC, mangalaman93 commented
@matthewmcneely I think it is the opposite. Everything should start from small letters, nothing should be capitalized.

2023-02-13 20:04 UTC, matthewmcneely commented
@mangalaman93 Well it's definitely inconsistent throughout. But IIRC, the convention is that the first word in output to logs *should* be capitalized. Error messages should NEVER be capitalized or punctutated, because they are likely to be chained together.

I guess we just need to declare which way is "the way" for Dgraph.