chore(template):
dgraph-io/dgraph pull request #8757
Opened 2023-03-15 21:45 UTC by joshua-goldstein

- Make Jira ticket field more prominent (all PR's should reference Jira ticket to keep track of error messages associated with issue, customer logs, etc.)
- Community PR's can disregard this field
- Combine Problem/Solution into Description

2023-03-15 21:46 UTC, joshua-goldstein commented
@mangalaman93

2023-03-16 20:39 UTC, mangalaman93 commented on .github/PULL_REQUEST_TEMPLATE.md
> -## Problem
I think we can make the whole template a bit smaller. We probably just need JIRA Ticket, GitHub issue, [Breaking], description.

2023-03-16 20:39 UTC, mangalaman93 requested changes
I think we can make the whole template a bit smaller. We probably just need JIRA Ticket, GitHub issue, [Breaking], description.

2023-05-02 08:50 UTC, mangalaman93 requested changes
Two questions:
1. we wanted to add a list of areas, what happened to that?
2. what do you think about something like below?

```
Description: <add description>
Fixes <GitHub Issue>
Closes <JIRA Issue>

* Add [BREAKING] if it is a breaking change
* Ensure title begins with <type<(<area>)
```

2023-05-14 09:00 UTC, mangalaman93 commented
add a comment saying that, add [BREAKING] if the change is breaking something @joshua-goldstein

2023-06-12 17:20 UTC, mangalaman93 requested changes
PR looks good, just one comment.

2023-06-12 17:20 UTC, mangalaman93 commented on .github/PULL_REQUEST_TEMPLATE.md
>   Sample Titles:
we don't need samples now I think. These are the areas that I am thinking:
acl|audit|backup|badger|cdc|dql|export|graphql|indexing|multi-tenancy|raft|restore|upgrade

2023-06-13 17:35 UTC, harshil-goel approved these changes

2023-06-13 17:36 UTC, merged