chore(test): fix frequently failing NFS-backup tests
dgraph-io/dgraph pull request #8807
Opened 2023-04-24 07:24 UTC by shivaji-dgraph

NFS backup tests fail frequently in CI. The test installs the NFS client before starting the alpha service because of this the Alpha container takes more time to reach a healthy state and may not pass the health check. To solve this, created new Docker file which is a combination of NFS-client and Dgraph, This has been added under the build key of docker-compose file. https://github.com/dgraph-io/dgraph/actions/runs/4744244095/jobs/8424889366

2023-04-24 11:01 UTC, mangalaman93 requested changes
Looks pretty good, two suggestions/questions:
1. why aren't we using dgraph image as the base image
2. dgraphxnfsclient -> dgraph-xnfs-client

2023-04-25 13:47 UTC, mangalaman93 requested changes
Looks good, just one comment.

2023-04-25 13:47 UTC, mangalaman93 commented on systest/backup/nfs-backup/docker-compose.yml
> +    image: itsthenetwork/nfs-server-alpine:${NFS_SERVER_IMAGE_ARCH:-latest}
we should use a fixed reference here, not a moving reference.

2023-04-26 20:34 UTC, skrdgraph approved these changes

2023-04-26 20:34 UTC, merged