Feat(GraphQL): This PR allows @id field in interface to be unique acr…
dgraph-io/dgraph pull request #8876
Opened 2023-06-14 21:38 UTC by harshil-goel

…oss all the implementing types. (#7710)

Currently, @id fields in the interface are unique only in one implementing type. But there are several use cases that require @id field to be unique across all the implementation types. Also currently. get a query on the interface can result in unexpected errors as we can have multiple implementing types have the same value for that @id field.

Now we are allowing the @id field in the interface to be unique across all the implementing types. In order to do this, we have added a new argument interface of boolean type in the @id field.

Whenever a @id field in interface type has an interface argument set then its value will be unique across all the implementing types. Users will get errors if they try to add a node with such a field and there is already a node with the same value of that field even in some other implementing types. This is true for other scenarios like adding nested value or while using upserts.

If the interface argument is not present or its value is false then that field will be unique only for one implementing type. But such fields won't be allowed in argument to get query on interface in the future, see this PR also #7602

Example Schema,

 interface LibraryItem {
    refID: String! @id                   //  This field is unique only for one implementing type
    itemID: String! @id(interface:true)    // This field will be unique over all the implementing types inheriting this interface
}

type Book implements LibraryItem {
    title: String
    author: String
}
Related discuss Post: https://discuss.dgraph.io/t/uniqueness-for-id-fields-on-interface/13294

2023-06-14 21:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dgraph-io/dgraph?pullRequest=8876) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dgraph-io/dgraph?pullRequest=8876) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dgraph-io/dgraph?pullRequest=8876) it.</sub>

2023-07-05 12:42 UTC, mangalaman93 requested changes

2023-07-06 09:52 UTC, harshil-goel commented on graphql/e2e/auth/debug_off/debugoff_test.go
> +	require.Equal(t, 0, resultSportsMember.AddSportsMember.NumUids)
It's an error in debug mode. Due to security reasons, we don't show an error in non debug mode.

2023-07-10 07:29 UTC, mangalaman93 requested changes

2023-07-10 07:29 UTC, mangalaman93 commented on graphql/e2e/directives/schema.graphql
> +}
add a newline here

2023-07-10 07:29 UTC, mangalaman93 commented on graphql/e2e/normal/schema.graphql
> +}
add a newline here

2023-07-10 07:29 UTC, mangalaman93 commented on graphql/resolve/add_mutation_test.yaml
> +      LibraryMember_2(func: eq(Member.refID, "101")) {
We should file a JIRA for this

2023-07-10 07:29 UTC, mangalaman93 commented on graphql/resolve/mutation_rewriter.go
> +	// We pass the xidName as "Int.xidName" to generate variable for existence query
pending

2023-07-10 07:29 UTC, mangalaman93 commented on graphql/resolve/mutation_rewriter.go
> +	// TODO(GRAPHQL): currently we are checking typ of the mutated field for auth rules,
q?

2023-07-10 07:29 UTC, mangalaman93 commented on graphql/resolve/mutation_rewriter.go
>  					if atTopLevel {
q?

2023-07-10 07:29 UTC, mangalaman93 commented on graphql/resolve/mutation_rewriter.go
> +	xidString string) (schema.Type, string) {
nit: add a new line after multi line signature

2023-07-10 07:29 UTC, mangalaman93 commented on graphql/resolve/mutation_rewriter.go
> +	interfaceName string) error {
nit: add a newline after multiline signature

2023-07-10 07:29 UTC, mangalaman93 commented on graphql/schema/gqlschema.go
> -		if defn.Kind == "INTERFACE" {
q?

2023-07-13 17:30 UTC, mangalaman93 approved these changes
Please don't forget to file JIRA ticket for the pending work. LGTM

2023-07-17 06:25 UTC, all-seeing-code commented
> . Also currently. get a query on the interface can result in unexpected errors as we can have multiple implementing types have the same value for that @id field.

Unclear

2023-07-17 12:01 UTC, all-seeing-code approved these changes

2023-07-17 12:04 UTC, merged