First commit
dgraph-io/dgraph pull request #8877
Opened 2023-06-15 04:45 UTC by harshil-goel

2023-06-17 01:10 UTC, mangalaman93 requested changes
What are our plans for this PR? Do we want to add a separate option in Dgraph for in memory badger?

2023-06-17 01:10 UTC, mangalaman93 commented on dgraph/cmd/alpha/run.go
> +		TmpDir:              "./t",
do we need this?

2023-06-17 01:10 UTC, mangalaman93 commented on dgraph/cmd/alpha/run.go
> +	fmt.Println("WORKER CONFIG ============", x.WorkerConfig)
will this print correctly? Could you copy an example here?

2023-06-17 01:10 UTC, mangalaman93 commented on dgraph/cmd/alpha/run.go
> +	worker.SetConfiguration(&opts)
can you add a comment to why this needs to be moved down here?

2023-06-17 01:10 UTC, mangalaman93 commented on raftwal/log.go
> +			InMemory:                      true,
we are doing this permanent?

2023-06-17 01:10 UTC, mangalaman93 commented on worker/config.go
> -	x.AssertTruef(pd != wd,
we should add a special condition for in memory.

2023-06-17 01:10 UTC, mangalaman93 commented on worker/server_state.go
> +		fmt.Println("Here", Config.PostingDir)
remove this

2023-06-28 17:13 UTC, harshil-goel commented on dgraph/cmd/alpha/run.go
> -	worker.SetConfiguration(&opts)
Why?

2023-07-06 04:21 UTC, mangalaman93 requested changes
We should add a test to ensure that we don't break it in future.

2023-07-06 12:54 UTC, sanjayk-github-dev commented on worker/server_state.go
> +		if Config.WALDir != "" {
@harshil-goel just trying to understand the changes. 

Is it the case that when badger is run in-memory, WALDir and PostingDir will be empty? And raftwal.InitEncrypted() handles this case properly?

2024-07-24 14:02 UTC, closed without merging