fix: compilation on 32bit
dgraph-io/dgraph pull request #8895
Opened 2023-07-05 08:19 UTC by wmillers

Fix compilation on 32bit machine

2023-07-05 08:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dgraph-io/dgraph?pullRequest=8895) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dgraph-io/dgraph?pullRequest=8895) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dgraph-io/dgraph?pullRequest=8895) it.</sub>

2023-07-05 12:43 UTC, mangalaman93 commented
@wmillers Thanks for the PR. Two questions: 1. why are you using a 32 bit machine still? 2. Why does this create problems on a 32 bit machine?

2023-07-06 03:31 UTC, wmillers commented
@mangalaman93

1. I need to run dgraph on a 32-bit system as part of my program.
2. When passing constants that exceed the range of int on a 32-bit system during compilation, the following error occurs:

```console
# github.com/dgraph-io/dgraph/xidmap
..\xidmap\trie.go:38:49: cannot use math.MaxUint32 (untyped int constant 4294967295) as int value in argument to z.NewBuffer(32 << 20, "Trie").WithMaxSize (overflows)
# github.com/dgraph-io/dgraph/worker
..\worker\restore_reduce.go:39:23: cannot use 2 << 30 (untyped int constant 2147483648) as int value in constant declaration (overflows)
..\worker\queue.go:305:42: cannot use math.MaxUint32 (untyped int constant 4294967295) as int value in argument to t.rng.Intn (overflows)
```

The `WithMaxSize` function (so as `Intn`) expects an argument of type int, and on a 32-bit system, the maximum allowed value is 2 << 30 - 1, which is math.MaxInt32.

2023-07-06 08:17 UTC, mangalaman93 commented
> @mangalaman93
> 
>     1. I need to run dgraph on a 32-bit system as part of my program.
> 
>     2. When passing constants that exceed the range of int on a 32-bit system during compilation, the following error occurs:
> 
> 
> ```
> # github.com/dgraph-io/dgraph/xidmap
> ..\xidmap\trie.go:38:49: cannot use math.MaxUint32 (untyped int constant 4294967295) as int value in argument to z.NewBuffer(32 << 20, "Trie").WithMaxSize (overflows)
> # github.com/dgraph-io/dgraph/worker
> ..\worker\restore_reduce.go:39:23: cannot use 2 << 30 (untyped int constant 2147483648) as int value in constant declaration (overflows)
> ..\worker\queue.go:305:42: cannot use math.MaxUint32 (untyped int constant 4294967295) as int value in argument to t.rng.Intn (overflows)
> ```
> 
> The `WithMaxSize` function (so as `Intn`) expects an argument of type int, and on a 32-bit system, the maximum allowed value is 2 << 30 - 1, which is math.MaxInt32.

Make sense. I am still wondering what machine you are planning to run that is still 32 bit. In any case, just one suggestion to this PR and we would be happy to merge it. Thanks for answering the questions.

2023-07-06 08:17 UTC, mangalaman93 requested changes

2023-07-07 01:28 UTC, wmillers commented on worker/queue.go
> +		id := myRaftId<<32 | uint64(t.rng.Intn(math.MaxInt32))
Thanks for the suggestion, I have changed it to `Uint32()`.

2023-07-07 02:50 UTC, mangalaman93 approved these changes

2023-07-13 00:57 UTC, sanjayk-github-dev approved these changes
LGTM

2023-07-13 01:04 UTC, merged