added namespace aware restore functionality
dgraph-io/dgraph pull request #8968
Opened 2023-08-23 13:03 UTC by shivaji-dgraph

2023-08-28 17:42 UTC, mangalaman93 requested changes
I don't see any code for moveTablet. How is this working?

2023-08-28 17:42 UTC, mangalaman93 commented on dgraphtest/cluster.go
> +	backupId string, incrFrom, backupNum int, encKey string, namespace uint64) error {
let's call it `fromNamespace` instead, same everywhere below

2023-08-28 17:42 UTC, mangalaman93 commented on graphql/admin/endpoints_ee.go
> +		"""
this needs more explanation

2023-08-28 17:42 UTC, mangalaman93 commented on systest/online-restore/namespace-aware/restore_test.go
> +
nit: remove the newline

2023-08-28 17:42 UTC, mangalaman93 commented on systest/online-restore/namespace-aware/restore_test.go
> +
nit: remove the newline

2023-08-28 17:42 UTC, mangalaman93 commented on systest/online-restore/namespace-aware/restore_test.go
> +	require.NoError(t, dgraphtest.CompareJSON(`{"allMails":[{"count":0}]}`, string(resp.Json)))
can we also have emails in ns2 in the test?

2023-08-28 17:42 UTC, mangalaman93 commented on systest/online-restore/namespace-aware/restore_test.go
> +		allMails(func: has(name)) {
change this to allNames and you could say `const query = ""`

2023-08-28 17:42 UTC, mangalaman93 commented on systest/online-restore/namespace-aware/restore_test.go
> +func TestNamespaceAwareRestoreOnMultipleGroup(t *testing.T) {
nit: MultipleGroup*s*

2023-08-28 17:42 UTC, mangalaman93 commented on systest/online-restore/namespace-aware/restore_test.go
> +		c.Cleanup(true)
fix this too

2023-08-28 17:42 UTC, mangalaman93 commented on systest/online-restore/namespace-aware/restore_test.go
> +	// so email predicte distributed into both groups
can you write down in comments what is the distribution of predicates in the groups at this point?

2023-08-28 17:42 UTC, mangalaman93 commented on systest/online-restore/namespace-aware/restore_test.go
> +	fmt.Println("Restoring only namespace ", ns1)
t.Logf please

2023-08-28 17:42 UTC, mangalaman93 commented on systest/online-restore/namespace-aware/restore_test.go
> +func TestNamespaceAwareRestoreOnMultipleGroup(t *testing.T) {
we should also add a test with incremental restore as well

2023-08-28 17:42 UTC, mangalaman93 commented on worker/online_restore.go
> +	// Make sure to assign the correct alpha group when restoring predicates
mention "namespace aware restore" here

2023-08-28 17:42 UTC, mangalaman93 commented on worker/online_restore.go
> +	if req.Namespace != -1 {
check for < 0

2023-08-28 17:42 UTC, mangalaman93 commented on worker/online_restore.go
> +		restorePreds = addPredIntoRestorePreds(restorePreds, req.Namespace)
we should also add test for namespace 0 -> namespace 0 restore

2023-08-28 17:42 UTC, mangalaman93 commented on worker/online_restore.go
> +func addPredIntoRestorePreds(restorePreds []string, namespace int64) []string {
we should add unit tests for this function

2023-08-28 17:42 UTC, mangalaman93 commented on worker/online_restore.go
> +func addPredIntoRestorePreds(restorePreds []string, namespace int64) []string {
namespace -> fromNamespace and make the type same as `ns`

2023-08-28 17:42 UTC, mangalaman93 commented on worker/online_restore.go
> +	var newRestorePreds []string
you could the the trick for filter in slice

## Filtering without allocating

This trick uses the fact that a slice shares the same backing array and capacity as the original, so the storage is reused for the filtered slice. Of course, the original contents are modified.

b := a[:0]
for _, x := range a {
	if f(x) {
		b = append(b, x)
	}
}

2023-08-28 17:42 UTC, mangalaman93 commented on worker/restore_map.go
> +		isNameSpaceAwareRestore := in.namespace > 0
what if it is equal to zero

2023-08-28 17:42 UTC, mangalaman93 commented on worker/restore_map.go
> +		maxNs = x.Max(maxNs, 0)
this doesn't look right for the normal case

2023-08-28 17:42 UTC, mangalaman93 commented on worker/restore_map.go
> +			parsedKey.Attr = strings.Replace(parsedKey.Attr, strconv.FormatUint(ns, 16), "0", 1)
we should not use strings.Replace. Predicates could have a the namespace number too. See if we could add a test with such a predicate.

2023-08-30 13:47 UTC, mangalaman93 requested changes
More todos:
1. I do not like the API, oneNamespaceOnly flag. we need to think more.
2. Uprgade tests will fail because of the change in cluster.go restore function. It should support both old and new API
3. We should test against a fresh cluster when zero doesn't have any tablets

2023-08-30 13:47 UTC, mangalaman93 commented on dgraphtest/cluster.go
> +func (hc *HTTPClient) GetState() (*pb.MembershipState, error) {
we probably don't need this any more

2023-08-30 13:47 UTC, mangalaman93 commented on worker/online_restore.go
> +// addPredIntoRestorePreds
explain what this function is doing and why.

2023-08-30 13:47 UTC, mangalaman93 commented on worker/restore_map.go
> +		if in.oneNamespaceOnly && ns != in.fromNamespace {
add a comment

2023-08-30 13:47 UTC, mangalaman93 commented on worker/restore_map.go
> +		if in.oneNamespaceOnly {
add a comment here, and I think this is not right. Try performing a namespace aware restore and then create an existing namesapce. It should not work.

2023-08-30 13:47 UTC, mangalaman93 commented on worker/restore_map.go
> +			changeNameSpaceToDefault := func(parsedKey x.ParsedKey) error {
changeNameSpaceToDefault is not self explanatory

2023-08-30 14:38 UTC, sanjayk-github-dev commented on graphql/admin/endpoints_ee.go
> +		oneNamespaceOnly: Boolean
Do we need `oneNamespaceOnly`? Can we use `fromNamespace > 0` to imply the same?

2023-09-01 16:24 UTC, mangalaman93 requested changes
We should consider having a completely new API for this.

2023-09-01 16:24 UTC, mangalaman93 commented on dgraphtest/cluster.go
> +	isNamespaceAwareRestorSupported, err := IsHigherVersion(c.GetVersion(), "ba727644664138d3ddba96a21348612b2bec2d88")
isNamespaceAwareRestor*e*Supported

2023-09-01 16:24 UTC, mangalaman93 commented on dgraphtest/cluster.go
> +		"encKey": encKey, "oneNamespaceOnly": oneNamespaceOnly, "fromNamespace": fromNamespace}
we don't need to have the keys here "oneNamespaceOnly" & "fromNamespace"

2023-09-13 14:02 UTC, mangalaman93 commented on systest/online-restore/namespace-aware/restore_test.go
> +			const query = `{
nit: format query

2023-09-14 07:25 UTC, mangalaman93 approved these changes

2023-09-14 14:02 UTC, harshil-goel approved these changes

2023-09-14 14:40 UTC, merged