Update sorting function to improve performance
dgraph-io/dgraph pull request #8995
Opened 2023-09-07 11:16 UTC by harshil-goel

Title format:

 - `Topic(Area): Feature`
 - `Topic` must be one of `build|ci|docs|feat|fix|perf|refactor|chore|test`
 - `Area` must be one of `acl|audit|backup|badger|cdc|dql|export|graphql|indexing|multi-tenancy|raft|restore|upgrade|zero`
 - * Add [BREAKING] if it is a breaking change

------------------
Body Format:

Description: <add description>
Fixes: <GitHub Issue>
Closes: <JIRA Issue>
Docs: <docs PR>

2023-09-08 04:53 UTC, mangalaman93 requested changes
1. we don't need to compare start == 0
2. what if end is close to len(ul.Uids)

2023-09-10 07:30 UTC, mangalaman93 requested changes

2023-09-10 07:30 UTC, mangalaman93 commented on types/sort.go
> +			return errors.Errorf("Value of type: %s isn't sortable", val.Tid.Name())
errors.Wrapf?

2023-09-10 07:30 UTC, mangalaman93 commented on types/sort.go
> +			return errors.Errorf("Value of type: %s isn't sortable", val.Tid.Name())
and %s --> %v

2023-09-10 07:30 UTC, mangalaman93 commented on types/sort.go
> +func SortTopN(v [][]Val, ul *[]uint64, desc []bool, lang string, n int) error {
does ul have to be a pointer?

2023-09-10 07:30 UTC, mangalaman93 commented on types/sort.go
> +	sort.Sort(tbs)
add a note as to why we are sorting here

2023-09-10 07:30 UTC, mangalaman93 commented on worker/sort.go
> +		if end < len(ul.Uids)/2 {
why half?

2023-09-10 07:30 UTC, mangalaman93 commented on worker/sort.go
> +		fmt.Println("Time taken", t2)
we still want this?

2023-09-14 14:29 UTC, mangalaman93 requested changes
1. move the quick select code to another files in the types package
2. Fix the benchmarks
3. Add a TODO in line 458 of worker/sort.go
4. Update the description with the new benchmarks
5. Add a reference to the place where we copied the quicksort code

2023-09-14 15:12 UTC, mangalaman93 requested changes
LG, minor comments

2023-09-14 15:12 UTC, mangalaman93 commented on types/sort_test.go
> +	var seededRand *rand.Rand = rand.New(
this too

2023-09-14 15:13 UTC, jairad26 approved these changes
lgtm

2023-09-14 15:50 UTC, mangalaman93 approved these changes

2023-09-14 17:45 UTC, mangalaman93 commented on types/select.go
> +func quickSelect(data byValue, low, high, k int) {
nit: add a comment here.

2023-09-14 19:46 UTC, jairad26 approved these changes
lgtm

2023-09-14 20:40 UTC, mangalaman93 approved these changes

2023-09-14 20:58 UTC, merged