Add vector type to Dgraph
dgraph-io/dgraph pull request #9050
Opened 2024-03-13 16:56 UTC by harshil-goel

Title format:

 - `Topic(Area): Feature`
 - `Topic` must be one of `build|ci|docs|feat|fix|perf|refactor|chore|test`
 - `Area` must be one of `acl|audit|backup|badger|cdc|dql|export|graphql|indexing|multi-tenancy|raft|restore|upgrade|zero`
 - * Add [BREAKING] if it is a breaking change

------------------
Body Format:

Description: <add description>
Fixes: <GitHub Issue>
Closes: <JIRA Issue>
Docs: <docs PR>

2024-03-13 16:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dgraph-io/dgraph?pullRequest=9050) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dgraph-io/dgraph?pullRequest=9050) before we can accept your contribution.<br/><hr/>**Harshil Goel** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dgraph-io/dgraph?pullRequest=9050) it.</sub>

2024-03-14 10:58 UTC, mangalaman93 requested changes
We should check for coverage for the new changes using unit tests

2024-03-14 10:58 UTC, mangalaman93 commented on types/value.go
> +	retVal := "["
we should strings.Builder here

2024-03-14 13:29 UTC, harshil-goel commented on types/conversion.go
> +func ParseVFloat(s string) ([]float32, error) {
We don't have lexer for an array.

2024-03-14 15:02 UTC, mangalaman93 commented on query/outputnode.go
> +					encodeAsList := (pc.List && lang == "")
we don't need this change

2024-03-14 15:20 UTC, mangalaman93 commented on go.mod
> +	github.com/dgraph-io/dgo/v230 v230.0.2-0.20230929195431-42a4d4ef28da
we need to merge dgo PR first

2024-03-14 15:26 UTC, mangalaman93 commented on types/value.go
> +
nit: extra newline

2024-03-18 06:03 UTC, mangalaman93 requested changes

2024-03-18 06:03 UTC, mangalaman93 commented on query/query0_test.go
> +	k := `{
can we format the query better so it is readable.

2024-03-18 06:03 UTC, mangalaman93 commented on query/query0_test.go
> +        "vectorNonIndex": [
nit: you could put these in one line

2024-03-18 06:03 UTC, mangalaman93 commented on types/conversion.go
> +func ParseVFloat(s string) ([]float32, error) {
Let's put a todo here for now

2024-03-18 06:03 UTC, mangalaman93 commented on types/scalar_types.go
> +	"float32vector": VFloatID,
check for the name once with the leadership

2024-03-18 11:39 UTC, mangalaman93 submitted a review, later dismissed

2024-03-19 06:31 UTC, mangalaman93 approved these changes

2024-03-19 13:11 UTC, merged