feat(core): Update caching mechanism of posting lists
dgraph-io/dgraph pull request #9068
Opened 2024-04-08 15:54 UTC by harshil-goel

Title format:

 - `Topic(Area): Feature`
 - `Topic` must be one of `build|ci|docs|feat|fix|perf|refactor|chore|test`
 - `Area` must be one of `acl|audit|backup|badger|cdc|dql|export|graphql|indexing|multi-tenancy|raft|restore|upgrade|zero`
 - * Add [BREAKING] if it is a breaking change

------------------
Body Format:

Description: <add description>
Fixes: <GitHub Issue>
Closes: <JIRA Issue>
Docs: <docs PR>

2024-04-26 17:13 UTC, harshil-goel commented on posting/mvcc.go
> +		if l != nil && l.maxTs < readTs {
l.minTs > readTs

2024-05-19 09:14 UTC, mangalaman93 requested changes
See whether we want to put this behind a feature flag just in case!

2024-05-19 09:14 UTC, mangalaman93 commented on posting/list.go
> +func (l *List) getPostingAndLengthNoSort(readTs, afterUid, uid uint64) (int, bool, *pb.Posting) {
we should create a separate PR for this

2024-05-19 09:14 UTC, mangalaman93 commented on posting/mvcc.go
>  /*
undo this change

2024-05-19 09:14 UTC, mangalaman93 commented on posting/mvcc.go
> +	count      map[string]int
use a struct instead! More maps => more memory unpredictability

2024-05-23 02:56 UTC, mangalaman93 approved these changes

2024-05-23 06:53 UTC, merged