chore: Upgrade go.mod dependencies, fix jose v2 vulnerability, upgrade jemalloc
dgraph-io/dgraph pull request #9158
Opened 2024-09-07 10:10 UTC by RJKeevil

Description: A general upgrade to latest (compatible) versions of multiple dependencies. Jose v2 also triggers vulnerability issues in our containers, so replaced that with v4 everywhere.

2024-09-07 10:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dgraph-io/dgraph?pullRequest=9158) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dgraph-io/dgraph?pullRequest=9158) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dgraph-io/dgraph?pullRequest=9158) it.</sub>

2024-09-07 10:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dgraph-io/dgraph?pullRequest=9158) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dgraph-io/dgraph?pullRequest=9158) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dgraph-io/dgraph?pullRequest=9158) it.</sub>

2024-09-09 07:17 UTC, mangalaman93 commented
Thank you for the PR. Seems like one test is failing. I am gonna look into it.

2024-09-09 07:30 UTC, mangalaman93 requested changes

2024-09-09 07:30 UTC, mangalaman93 commented on go.mod
> +	github.com/spf13/cast v1.7.0
please do not update these deps. There is a bug in cast library causing our tests to fail. More details here https://github.com/dgraph-io/dgraph/pull/9141

2024-09-09 13:12 UTC, RJKeevil commented
@mangalaman93 chnages made, hopefully tests pass now, lets see

2024-09-09 13:59 UTC, mangalaman93 approved these changes

2024-09-10 07:42 UTC, RJKeevil commented
@mangalaman93 missing TLS cert, do you think this is also caused by an incompatible module upgrade?

2024-09-10 13:19 UTC, merged