chore(repo): close response bodies to prevent resource leaks
dgraph-io/dgraph pull request #9193
Opened 2024-10-08 10:08 UTC by xqqp

- close response bodies to prevent resource leaks ("The caller must close the response body when finished with it", see https://pkg.go.dev/net/http)
- add `bodyclose` linter to linter config

2024-10-08 10:14 UTC, mangalaman93 requested changes
Could you log the error instead of ignoring it in the `defer`?

2024-10-08 10:43 UTC, xqqp commented
@mangalaman93 The errors are now logged outside of test files.

2024-10-08 16:32 UTC, xqqp commented
> Thank you for the update. Could you also update to use `%v` instead of `%s` in the glog so that it gets logged correctly. While you do that, you could also keep the structure like this (this is a nit):
> 
> ```
> 		if err := resp.Body.Close(); err != nil {
> 			glog.Errorf("Error while closing response body: %v", err)
> 		}
> ```

Done

2024-10-14 11:35 UTC, mangalaman93 approved these changes

2024-10-14 11:36 UTC, merged