perf(core): Introduce mutable map struct to update mutation map in Li…
dgraph-io/dgraph pull request #9199
Opened 2024-10-16 13:56 UTC by harshil-goel

…st object

Title format:

 - `Topic(Area): Feature`
 - `Topic` must be one of `build|ci|docs|feat|fix|perf|refactor|chore|test`
 - `Area` must be one of `acl|audit|backup|badger|cdc|dql|export|graphql|indexing|multi-tenancy|raft|restore|upgrade|zero`
 - * Add [BREAKING] if it is a breaking change

------------------
Body Format:

Description: <add description>
Fixes: <GitHub Issue>
Closes: <JIRA Issue>
Docs: <docs PR>

2024-10-24 07:56 UTC, mangalaman93 requested changes

2024-10-24 07:56 UTC, mangalaman93 commented on posting/list.go
> +	mutationMap *MutableMap
maybe use mutableLayer? and define our mutable and immutable layer.

2024-10-24 07:56 UTC, mangalaman93 commented on posting/list.go
> +// MutableMap is the structure that will store the mutable layer in the list. It used to be just a map, hence the name.
improve this description

2024-10-24 07:56 UTC, mangalaman93 commented on posting/list.go
> +	uidMap       map[uint64]int
use better names

2024-10-24 07:56 UTC, mangalaman93 commented on posting/list.go
> +func (mm *MutableMap) clone() *MutableMap {
explain clone as what is getting copied and what is not, and why not!

2024-10-24 07:56 UTC, mangalaman93 commented on posting/list.go
> +	mm.uidMap = nil
mm.uidMap.clear()?

2024-10-24 07:56 UTC, mangalaman93 commented on posting/list.go
> +	if pl, ok := mm.oldList[startTs]; ok {
can do `return mm.oldList[startTs]`

2024-10-24 07:56 UTC, mangalaman93 commented on posting/list.go
> +	if mm.curList != nil {
can do something like 
```
toInt(mm.curList != nil) + len(mm.oldList)
```

2024-10-24 07:56 UTC, mangalaman93 commented on posting/list.go
> +func (mm *MutableMap) listLen(readTs uint64) int {
add a comment here that readTs affects the returned length value

2024-10-24 07:56 UTC, mangalaman93 commented on posting/list.go
> +			for _, mpost := range pl.Postings {
nit: can extract this function out

2024-10-24 07:56 UTC, mangalaman93 commented on posting/list.go
> +	if mm.length == math.MaxInt {
check for `readTs` as well here

2024-10-24 07:56 UTC, mangalaman93 commented on posting/list.go
> +func (mm *MutableMap) populateDeleteAll(readTs uint64) uint64 {
add a comment what function does

2024-10-24 07:56 UTC, mangalaman93 commented on posting/list.go
> +	deleteMarkerUnderTs := uint64(0)
under ==> below

2024-10-24 07:56 UTC, mangalaman93 commented on posting/list.go
> +			break
continue

2024-10-24 07:56 UTC, mangalaman93 commented on posting/list.go
> +func (mm *MutableMap) _iterate(f func(ts uint64, pl *pb.PostingList)) {
func(ts uint64, pl *pb.PostingList) ===>  func(uint64, *pb.PostingList)

2024-10-24 07:56 UTC, mangalaman93 commented on posting/list.go
> +	oldList map[uint64]*pb.PostingList
oldList ==> committedData
curList ==> uncommittedData

2024-10-24 07:56 UTC, mangalaman93 commented on posting/list.go
> +		mm.iterate(func(ts uint64, pl *pb.PostingList) {
ts => `_`

2024-10-24 07:56 UTC, mangalaman93 commented on posting/list.go
> +func (mm *MutableMap) _iterate(f func(ts uint64, pl *pb.PostingList)) {
_iterate => iterateBeforeCurTime

2024-10-24 07:56 UTC, mangalaman93 commented on posting/list.go
> +		if mm.curTime != 0 && ts > mm.curTime {
I don't think we need this. We should just merge with the below if

2024-10-24 07:56 UTC, mangalaman93 commented on posting/list.go
> +			if mpost.CommitTs > mm.deleteMarker {
deleteMarker ==> deleteAllMarker

2024-10-24 07:56 UTC, mangalaman93 commented on posting/list.go
> +			mm.length -= 1
what if there is only deleteAll and nothing else? Can the length be -1 then?

2024-10-24 07:56 UTC, mangalaman93 commented on posting/list.go
> +	getPos := func() *pb.Posting {
getPos ==> getPosting

2024-10-24 07:56 UTC, mangalaman93 commented on posting/list.go
> +		pos, ok := mm.uidsH[uid]
return `mm.uidsH[uid]`

2024-10-26 02:48 UTC, hYuang commented on posting/list_test.go
> +	l.Unlock()
remove defer .  Is th function  Concurrency safety?

2024-11-05 05:31 UTC, shivaji-kharse approved these changes

2024-11-11 18:59 UTC, mangalaman93 commented on posting/list.go
> +// MutableLayer is the structure that will store mutable layer of the posting list. Every posting list has an immutable
nit: can connect it better to the fields of the structs in `List` and `MutableLayer`

2024-11-11 18:59 UTC, mangalaman93 commented on posting/list.go
> +	// Since we are storing the commitedEntries and currentEntries separetly. We can cache things things that are
nit: `things things`

2024-11-11 18:59 UTC, mangalaman93 commented on posting/list.go
> +	deleteAllMarker  uint64                 // Stores the lastest deleteAllMarker found in the posting list
lastest --> latest

2024-11-11 18:59 UTC, mangalaman93 commented on posting/list.go
> +	commitedEntries map[uint64]*pb.PostingList
nit: commited --> committed

2024-11-11 18:59 UTC, mangalaman93 commented on posting/list.go
> +	// We also cache some thigns requried for us to update currentEntries faster
requried -> required

2024-11-11 18:59 UTC, mangalaman93 commented on posting/list.go
> +	// We also cache some thigns requried for us to update currentEntries faster
thigns -> things

2024-11-11 18:59 UTC, mangalaman93 commented on posting/list.go
> +	if refresh {
nit: can consider removing this

2024-11-11 18:59 UTC, mangalaman93 commented on posting/list.go
> +// we will return the currentEntries, otherwise it should be th commitTs of old postings.
th --> the

2024-11-11 18:59 UTC, mangalaman93 commented on posting/list.go
> +		if pl.CommitTs == ts || ts == mm.readTs {
add a note here saying that this may not be required

2024-11-11 18:59 UTC, mangalaman93 commented on posting/list.go
> +		// I need to calculate deleteAllMarker again. I can't use the one from cache
move this after the if

2024-11-11 18:59 UTC, mangalaman93 commented on posting/list.go
> +func (mm *MutableLayer) insertOldPosting(pl *pb.PostingList) {
add a note here that this should only be called after acquiring lock on list

2024-11-13 15:36 UTC, mangalaman93 requested changes

2024-11-13 15:36 UTC, mangalaman93 commented on posting/list.go
> +		if l.mutationMap.commitedUids != nil {
what if `l.mutationMap.commitedUids` is nil

2024-11-13 15:36 UTC, mangalaman93 commented on posting/list.go
> +		// ts will be plist.CommitTs for commited transactions
committed

2024-11-13 15:36 UTC, mangalaman93 commented on posting/list_test.go
> +	// TODO
do we need it?

2024-11-29 00:58 UTC, mangalaman93 requested changes

2024-11-29 00:58 UTC, mangalaman93 commented on posting/list.go
> +	committedUids     map[uint64]*pb.Posting // Stores the uid to posting mapping in committedEntreis.
committedEntreis --> committedEntries

2024-11-29 00:58 UTC, mangalaman93 commented on posting/list.go
> +// know that we have committedEntries will not get changed and this can be copied by reference without any issues.
something is off in this line

2024-11-29 00:58 UTC, mangalaman93 commented on posting/list.go
> +	// Since we are storing the committedEntries and currentEntries separetly. We can cache things that are
separetly --> separately

2024-11-29 00:58 UTC, mangalaman93 commented on posting/list.go
> +	if mm == nil {
we should assert here that `mm` is not nil

2024-11-29 00:58 UTC, mangalaman93 commented on posting/list.go
> +func (mm *MutableLayer) insertOldPosting(pl *pb.PostingList) {
insertOldPosting --> insertCommittedPosting

2024-11-29 00:58 UTC, mangalaman93 commented on posting/list.go
> +	return fmt.Sprintf("OLDLIST: %+v CURLIST: %+v DELETEBELOWTS: %d  \n",
OLDLIST --> Committed List
CURLIST --> proposed List
DELETEBELOWTS --> Latest DeleteAll TS

2024-12-06 04:55 UTC, mangalaman93 approved these changes

2024-12-06 04:55 UTC, mangalaman93 commented on posting/index.go
> +			if len(kv.Value) == 0 {
we should just update the UserMeta in the if condition for clarity

2024-12-06 04:55 UTC, mangalaman93 commented on posting/index.go
> -			if len(kv.Value) == 0 {
just make sure that we do not get into this case frequently for index keys

2024-12-06 04:59 UTC, merged